### ISSUE TITLE
Which version of tensorflow_addons to use?

### ISSUE THREAD

**Issue by KaqiKaqi** [google/automl#10]
I can only us pip to install tensorflow_addons of vesion greater than 0.5.0. But those versions of tensorflow_addons needs TF2.X.

Which version of tensorflow_addons is compatible with TF1.13?

Thanks.

**Comment by mingxingtan** [comment]
Hello, since addons is only used for autoaugment, i have just made it optional in https://github.com/google/automl/commit/8981a503f1f47056bc52b4c731399948973f9470. Our code doesn't need autogument in default,  so you don't need addons unless you specifically need autoaugment.
