### ISSUE TITLE
can you show the graphs?

### ISSUE THREAD

**Issue by bitwangdan** [google/automl#100]
hi, can you show the graphs, i want to use the tensorboard
@mingxingtan

**Comment by mingxingtan** [comment]
You can run 

```
python model_inspect.py --model_name={MODEL} --logdir=logs
tensorboard --logdir=logs
```

Or you can also directly use our updated [tutorial.ipynb](https://colab.sandbox.google.com/github/google/automl/blob/master/efficientdet/tutorial.ipynb)
