### ISSUE TITLE
Loading Pretrained Weights

### ISSUE THREAD

**Issue by MarkWijkhuizen** [google/automl#1002]
Loading the model as demonstrated in the README works perfectly, however there does not seem to be any option to load pretrained weights.

How do you load the pretrained weights? Ideally you there would be a `pretrained` parameter where you could either pass "1K" or "21K".

```
# build keras model
model = effnetv2_model.EffNetV2Model('efficientnetv2-s')
# How do you load the pretrained weights?
...
```

**Comment by darien-schettler** [comment]
Hey Mark. I know you've already seen this on Kaggle probably. But for others who might be struggling. Please see this notebook for an example of how to load the weights into an EfficientNetV2 model (w/ Keras API).

https://www.kaggle.com/dschettler8845/load-efficientnetv2-pretrained-weights

**Comment by jeongyoonlee** [comment]
Hi @darien-schettler, I just forked and ran your Kaggle notebook as is, and it raised an `AssertionError` as follows:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-3e805358c80a> in <module>
      9 
     10 # Load the weights
---> 11 ev2_b0.load_weights(ckpt)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name, skip_mismatch, options)
   2214         # streaming restore for any variables created in the future.
   2215         trackable_utils.streaming_restore(status=status, session=session)
-> 2216       status.assert_nontrivial_match()
   2217       return status
   2218     if h5py is None:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py in assert_nontrivial_match(self)
   1021     # assert_nontrivial_match and assert_consumed (and both are less
   1022     # useful since we don't touch Python objects or Python state).
-> 1023     return self.assert_consumed()
   1024 
   1025   def _gather_saveable_objects(self):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py in assert_consumed(self)
    998       raise AssertionError(
    999           "Some objects had attributes which were not restored:{}".format(
-> 1000               "".join(unused_attribute_strings)))
   1001     for trackable in self._graph_view.list_objects():
   1002       # pylint: disable=protected-access

AssertionError: Some objects had attributes which were not restored:
    <tf.Variable 'eff_net_v2_model/stem/conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
```

**Comment by AnthonyChanMarvel** [comment]
> Hi @darien-schettler, I just forked and ran your Kaggle notebook as is, and it raised an `AssertionError` as follows:
> 
> ```
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-4-3e805358c80a> in <module>
>       9 
>      10 # Load the weights
> ---> 11 ev2_b0.load_weights(ckpt)
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name, skip_mismatch, options)
>    2214         # streaming restore for any variables created in the future.
>    2215         trackable_utils.streaming_restore(status=status, session=session)
> -> 2216       status.assert_nontrivial_match()
>    2217       return status
>    2218     if h5py is None:
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py in assert_nontrivial_match(self)
>    1021     # assert_nontrivial_match and assert_consumed (and both are less
>    1022     # useful since we don't touch Python objects or Python state).
> -> 1023     return self.assert_consumed()
>    1024 
>    1025   def _gather_saveable_objects(self):
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py in assert_consumed(self)
>     998       raise AssertionError(
>     999           "Some objects had attributes which were not restored:{}".format(
> -> 1000               "".join(unused_attribute_strings)))
>    1001     for trackable in self._graph_view.list_objects():
>    1002       # pylint: disable=protected-access
> 
> AssertionError: Some objects had attributes which were not restored:
>     <tf.Variable 'eff_net_v2_model/stem/conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
> ```

I got same error loading pretrained weights when used TPU as backend in Google Colab.

**Comment by darien-schettler** [comment]
Reply to @AnthonyChanMarvel & @jeongyoonlee :

For some reason this issue is resolved by putting a **`tf.keras.backend.clear_session()`** prior to model instantiation and weight loading.

I've updated the Kaggle example accordingly.

**Comment by mingxingtan** [comment]
Yes, this is a common issue of keras models. If you don't have tf.keras.backend.clear_session(), then every time you create a new model, it would have different variable names.

BTW, I also added the tutorial. With  tf.keras.backend.clear_session, it worked well.
