### ISSUE TITLE
Fine-Tuning with custom dataset

### ISSUE THREAD

**Issue by sasakits** [google/automl#1023]
I am trying Fine-Tuning with custom dataset like below, and then I have met error message like below.
I don't see why it's a mistake. Please enlighten me on the specifics. 

Code:
```
        inputs = keras.Input(shape=(480, 480, 3))
        model = effnetv2_model.EffNetV2Model('efficientnetv2-l')
        x = tf.keras.layers.Dense(4, activation='softmax')(model.layers[-2].output) # want to pop last layer
        model = tf.keras.Model(inputs=inputs, outputs=x)
```

Error:
`        AttributeError: Layer eff_net_v2_model_1 has no inbound nodes.`

**Comment by mingxingtan** [comment]
Hi @sasakits , I added a simple utility for finetuning, see here: https://github.com/google/automl/tree/master/efficientnetv2#4-build-a-pretrained-model-and-finetuning

Basically, you just need this:

```
mode = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=[224, 224, 3]),
    effnetv2_model.get_model('efficientnetv2-l', include_top=False, pretrained=True),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(4, activation='softmax'),
])
```

**Comment by sasakits** [comment]
Thank you so much for quick response and make a solution!
