### ISSUE TITLE
Gray scale  images are unable to inference but training is done

### ISSUE THREAD

**Issue by vijaysamula** [google/automl#1027]
Hi,
I am Samula Vijay Reddy, working on training with my custom thermal dataset. I have followed all the instructions to train the model and it worked well. But the problem comes when trying to infer the image. 
The error is following way 
_**Cannot feed value of shape (1, 120, 160) for Tensor 'image_arrays:0', which has shape '(None, None, None, None)'**_

![efficientdet_thermal_error](https://user-images.githubusercontent.com/50096409/122022982-69ac0800-cdc7-11eb-9c96-76a4f116d5d8.png)

**Comment by vijaysamula** [comment]
I think the model is not able to infer the grayscale image. But I trained on the same dataset.

**Comment by Steve-2040** [comment]
I have seen similar problems with grayscale images. Try to save the images for inference as grayscale but with 3 layers (RGB) as jpg. I think the training script (or training graph) automatically expand 1 grayscale layer to 3 layers. This does not happen in the inference script. E.g., open the image in GIMP and make sure from the menu (Image - Mode) is set to RGB. You can also do this with a Python script:
```Python
def get_image_array(file_name):
    im = Image.open(file_name).convert('L') # L: 8-bit pixels, black and white

    im = im.convert("RGB")
    im_arr = np.frombuffer(im.tobytes(), dtype=np.uint8)
    im_arr = im_arr.reshape((1, im.size[1], im.size[0], 3)) # 1, H, W, ch=1 or 3
    return im_arr, im
```

You can also have a look at this https://github.com/google/automl/issues/753#issuecomment-689353891
Hope this helps.

**Comment by vijaysamula** [comment]
Hi Steve,
The problem is solved as of now. 
Thanks for your help.
