### ISSUE TITLE
Non maximum suppresion unsupported on TPU

### ISSUE THREAD

**Issue by yaochenglouis** [google/automl#1034]
Was trying to perform python keras/eval.py on tpu with EfficientDet Lite3
  
(4) Invalid argument: {{function_node __inference_tpu_function_54677}} Detected unsupported operations when trying to compile graph cluster_tpu_function_16597854584464753108[] on XLA_TPU_JIT: NonMaxSuppressionV5 (No registered 'NonMaxSuppressionV5' OpKernel for XLA_TPU_JIT devices compatible with node {{node NonMaxSuppressionV5}}){{node NonMaxSuppressionV5}}

TF 2.5.0 for TPUv2-8 and my env

**Comment by fsx950223** [comment]
Fixed in tf2.6

**Comment by yaochenglouis** [comment]
(1) INVALID_ARGUMENT: {{function_node __inference_tpu_function_80207}} D
etected unsupported operations when trying to compile graph cluster_tpu_function_1831760275624533677[] on XLA_TPU_JIT: NonMaxSuppressionV5 (No regis
tered 'NonMaxSuppressionV5' OpKernel for XLA_TPU_JIT devices compatible wi
th node {{function_node __inference_model_fn_802050}}{{node NonMaxSuppressionV5.NonMaxSuppressionV5}}){{function_node __inference_model_fn_802050}}{
{node NonMaxSuppressionV5.NonMaxSuppressionV5}}                           
One approach is to outside compile the unsupported ops to run on CPUs by enabling soft placement `tf.config.set_soft_device_placement(True)`. This h
as a potential performance penalty.                                       
                                          
It seems that this problem still persists

**Comment by yaochenglouis** [comment]
after setting tf.config.set_soft_device_placement(True) in tf2/train.py in def main():  function, there comes new error like:
`         [[{{node outside_compilation_automatic_outside_compilation_cluste
r_40_host_compute}}]]                                                     
         [[TPUReplicate/_compile/_2281684753240953749/_18]]               
         [[TPUReplicate/_compile/_2281684753240953749/_18/_58]]          
  (2) Invalid argument: {{function_node __inference_tpu_function_80207}} S
hape inference for HostCompute StatefulPartitionedCall/outside_compilation
_automatic_outside_compilation_cluster_40_host_compute failed: send from h
ost node outside_compilation_cluster_tpu_function___inference_model_fn_802
050_oc_automatic_outside_compilation_cluster_40_send has non-fully defined
 shape of input index 0  `      


env: python 3.7, tf 2.6.2,
tpu: v3-8, tf 2.6.0/2.7.0 both not supporting NMSV5
