### ISSUE TITLE
Only 4000 data sets have been trained. How can the default parameters not stop？

### ISSUE THREAD

**Issue by honghande** [google/automl#105]
Run the command as follows: 4000 datasets in three categories
python main.py --training_file_pattern=tfrecrod_gstrain/train* \
    --model_name=efficientdet-d0 \
    --model_dir=ckpt/gs \
    --ckpt=efficientdet-d0 \
    --num_epochs=15 \
    --hparams="use_bfloat16=false,num_classes=3" --use_tpu=False

**Comment by WonTaeYeon** [comment]
I don't know the point of the question.
Has an error occurred?
Show me the log. please

**Comment by honghande** [comment]
Num_examples_per_epoch because this parameter setting is very large, now it has been modified, and the training can be finished soon
