### ISSUE TITLE
Effdet custom DS with images without box

### ISSUE THREAD

**Issue by Jogima-cyber** [google/automl#1059]
I have a custom dataset with one third of the images without objects to detect. I am able to train good OD model with this repo on the 2/3 of my dataset with objects to detect, but I was wondering if there is a way to integrate the third part without objects in order to reduce false positive? Does automl effdet support dataset with images without box? Or should I add a box of one pixel and an artificial class for when there is no class?

**Comment by fitoule** [comment]
set classnumber=0 and boundingbox all imge for them

**Comment by Jogima-cyber** [comment]
Thank you, I'll give it a try !
