### ISSUE TITLE
CocoAPI Install Issue

### ISSUE THREAD

**Issue by mohana-13** [google/automl#107]
When i do the command:
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

I receive this issue:
ERROR: Invalid requirement: "'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'"
Hint: = is not a valid operator. Did you mean == ?

I tried the '==' but this did not solve it.

**Comment by Sean0123456789** [comment]
hoe to install cocoapi for python?  any updates?

**Comment by Sean0123456789** [comment]
how to install cocoapi for python3?

**Comment by Sean0123456789** [comment]
any updates?

**Comment by wangtianlong1994** [comment]
You can install in this order：
1.pip install Cython
2.sudo apt install gcc
3.pip install pycocotools

**Comment by WonTaeYeon** [comment]
What is your OS?

**Comment by mohana-13** [comment]
> What is your OS?

Windows 10

**Comment by WonTaeYeon** [comment]
@mohana-13 
Have you installed 'C ++ build'?

**Comment by mohana-13** [comment]
> @mohana-13
> Have you installed 'C ++ build'?
> And you also need to install 'git'.

i have installed git. how do i install c++ build?
thanks

**Comment by mohana-13** [comment]
> You can install in this order：
> 1.pip install Cython
> 2.sudo apt install gcc
> 3.pip install pycocotools

how would i do this on windows 10? thanks

**Comment by WonTaeYeon** [comment]
@mohana-13 
https://www.kaggle.com/c/tgs-salt-identification-challenge/discussion/62381
