### ISSUE TITLE
EfficientDet for EdgeTPU

### ISSUE THREAD

**Issue by alexanderfrey** [google/automl#11]
HI, I wonder if there is a tutorial to follow to adapt this to edge tpu ? Thanks to any advice or information whether this runs on coral.

Thanks,
Alexander

**Comment by alexanderfrey** [comment]
Great, thanks for the info !

**Comment by Aspirinkb** [comment]
@mingxingtan Hi Tan, any progress?

**Comment by jbfuzier** [comment]
Hi,
I would also love to see efficientDet on edge TPU :)

**Comment by joepalermo** [comment]
Likewise!

**Comment by itsmasabdi** [comment]
Any update on this?

**Comment by Ekta246** [comment]
Would love to see too

**Comment by keesschollaart81** [comment]
I see some work has been done to support quantization 58545438f542190925a5d5f6c4cfed8047ef599b, great! When I run
``` 
python -m keras.inspector --mode=export --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir --tflite=INT81
```
I get an error: RuntimeError: Quantization not yet supported for op: `. An issue with an unsupported op (without a name?). After updating the keras/inference.py file with this:
```py
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.TFLITE_BUILTINS_INT8, 
            tf.lite.OpsSet.SELECT_TF_OPS
        ]
        converter.allow_custom_ops = True
```
I was able to export d0 to a int8.tflite. However, when I try to ceonvert this model to EdgeTPU, it fails:
```
edgetpu_compiler -s int8.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting!
```
Any clue on the unsupported op or edgetpu_compiler error?

**Comment by mingxingtan** [comment]
Yeah, somehow edgetpu compiler has a bug for the latest resize, you can manually change:

https://github.com/google/automl/blob/96e1feef7a39bd343ce19326b134d62fb640a356/efficientdet/keras/efficientdet_keras.py#L293

to the old version:

    return tf.cast(
        tf.compat.v1.image.resize_nearest_neighbor(
            tf.cast(inputs, tf.float32), [target_height, target_width]),
        inputs.dtype)

Could you tell me whether this fix works? Thanks!

**Comment by keesschollaart81** [comment]
To be clear, I used the pretrained `EfficientDet-D0` checkpoint, I did not train myself. 

I applied the change as suggested. I still get the `Quantization not yet supported for op: ` error when trying to convert to tflite. When I add the `tf.lite.OpsSet.SELECT_TF_OPS`, the quantized tflite model still builds but the edgetpu_compiler still gives the same error. 

Do you want me to train the model with the proposed change? Were you already able to somehow convert one of the pretrained models to quantized tflite and then compile using the edgetpu compiler?

**Comment by mingxingtan** [comment]
Oh, EdgetTPU only supports lite version such as efficientdet-lite0 or lite1.

**Comment by keesschollaart81** [comment]
I trained a efficientdet-lite0 model using:
```
python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/{file_pattern} \
    --validation_file_pattern=tfrecord/{file_pattern} \
    --model_name=efficientdet-lite0 \
    --model_dir=efficientdet-lite0  \
    --backbone_ckpt=efficientnet-lite0 \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples=56  \
    --num_examples_per_epoch=56  --num_epochs=1  \
    --run_epoch_in_child_process=False \
    --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true"
```

Then I tried to export to TF Lite INT8 with:

```
python -m keras.inspector --mode=export --model_name=efficientdet-lite0 --export_ckpt=efficientdet-lite0 --saved_model_dir=savedmodeldir --tflite=INT8
```

Then the conversion to TFLite INT8 fails with error: `ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: images`. This makes sense because the calibration dataset is fed with FLOAT32 data [here](https://github.com/google/automl/blob/ce28a37820c6754eaabd676f968b1c2f397e8f8e/efficientdet/keras/inference.py#L323). When I change this to np.unit8 I'm back at the `RuntimeError: Quantization not yet supported for op: ` error. Adding this `SELECT_TF_OPS` still allows me to build an int8.tflite. Trying to convert this model with new 15.x edgetpu_compiler tells me: `Invalid model: Model int8.tflite - Model not quantized`.

Any clue?

**Comment by SukyoungCho** [comment]
@mingxingtan 
hi, could you tell where I can find an Efficientdet-lite models and maybe a guideline or repo explaining how to quantize it into uint8 and EdgeTPU compile it, and deploy it on a board? Thank you!

**Comment by DanKlarman** [comment]
@keesschollaart81

Thanks for sharing. Two Questions:
1. Where did you find pretrained checkpoint of efficinetdet-lite0
2. Did you mange to solve the conversion issue?

> I succesfully trained a efficientdet-lite0 model using:
> 
> ```
> python main.py --mode=train_and_eval \
>     --training_file_pattern="tfrecord/pascal-00000-of-00100.tfrecord"  \
>     --validation_file_pattern="tfrecord/pascal-00000-of-00100.tfrecord"  \
>     --model_name=efficientdet-lite0 \
>     --model_dir=efficientdet-lite0  \
>     --backbone_ckpt=efficientnet-lite0 \
>     --train_batch_size=4 \
>     --eval_batch_size=4 --eval_samples=56  \
>     --num_examples_per_epoch=56  --num_epochs=1  \
>     --run_epoch_in_child_process=False \
>     --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true"
> ```
> 
> Then I tried to export to TF Lite INT8 with:
> 
> ```
> python -m keras.inspector --mode=export --model_name=efficientdet-lite0 --export_ckpt=efficientdet-lite0 --saved_model_dir=savedmodeldir --tflite=INT8
> ```
> 
> Then the conversion to TFLite INT8 fails with error: `ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: images`. This makes sense because the calibration dataset is fed with FLOAT32 data [here](https://github.com/google/automl/blob/ce28a37820c6754eaabd676f968b1c2f397e8f8e/efficientdet/keras/inference.py#L323). When I change this to np.unit8 I'm back at the `RuntimeError: Quantization not yet supported for op: ` error. Adding this `SELECT_TF_OPS` still allows me to build an int8.tflite. Trying to convert this model with new 15.x edgetpu_compiler tells me: `Invalid model: Model int8.tflite - Model not quantized`.
> 
> Looking at the generated saved_model.pb:
> 
> ```
> The given SavedModel SignatureDef contains the following input(s):
>   inputs['images'] tensor_info:
>       dtype: DT_UINT8
>       shape: (1, -1, -1, 3)
>       name: serving_default_images:0
> The given SavedModel SignatureDef contains the following output(s):
>   outputs['output_0'] tensor_info:
>       dtype: DT_FLOAT
>       shape: (1, 100, 4)
>       name: StatefulPartitionedCall:0
>   outputs['output_1'] tensor_info:
>       dtype: DT_FLOAT
>       shape: (1, 100)
>       name: StatefulPartitionedCall:1
>   outputs['output_2'] tensor_info:
>       dtype: DT_FLOAT
>       shape: (1, 100)
>       name: StatefulPartitionedCall:2
>   outputs['output_3'] tensor_info:
>       dtype: DT_INT32
>       shape: (1)
>       name: StatefulPartitionedCall:3
> Method name is: tensorflow/serving/predict
> ```
> 
> Any clue?

**Comment by mingxingtan** [comment]
EdgeTPU model checkpoints are added to README page (also available in tfhub).

**Comment by jbfuzier** [comment]
Hi,
On ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite I have ~10FPS
With lite-model_efficientdet_lite0_detection_default_1.tflite I only have ~0.2FPS with an usb edgetpu on a box with an old atom CPU. It seems to be cpu bound, 99% of the time is spent in tflite interpreter.py on the invoke method.

I am the only one having this beahavior / is it expected ?

```
        156463 function calls (151389 primitive calls) in 329.967 seconds
        3  324.918  108.306  324.918  108.306 interpreter.py:527(invoke)
```

Thanks
