### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.

### ISSUE THREAD

**Issue by mad-fogs** [google/automl#110]
Hi dear authers,

i have got this error with input :
python main.py --training_file_pattern=automl/efficientdet/data/tfdata/coco_train.record-00000-of-00001 \
--validation_file_pattern=automl/efficientdet/data/tfdata/coco_val.record-00000-of-00001 \
    --val_json_file=/data/coco/annotations/instances_val2017.json \
    --model_name=efficientdet-d0 \
    --model_dir=saved_model/ \
    --ckpt=automl/efficientdet-d0 \
    --hparams="use_bfloat16=false,num_classes=4,var_exclude_expr=r'.*/class-predict/.*'" \
    --use_tpu=False

tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
	 [[{{node parser/GatherNd}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
	 [[{{node parser/GatherNd}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_15307]]
0 successful operations.
0 derived errors ignored.

**Comment by WonTaeYeon** [comment]
Try:
--mode = eval
default: --mode = train

**Comment by mad-fogs** [comment]
> Try:
> --mode = eval
> default: --mode = train

Hi @WonTaeYeon ,

Thanks very much for your reply.
I made the tfdate by tensorflow/models/object_detection/... scripts, there might be some differences here.

Close this issue.

**Comment by wadewangpower** [comment]
@mad-fogs Hello，bro，today i met very similar problem，it said `tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
         [[{{node parser/GatherNd}}]]
         [[IteratorGetNext]]
  (1) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
         [[{{node parser/GatherNd}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_14336]]
0 successful operations.
0 derived errors ignored.`
I don't quite understand your comment above, can you explain it with another simple way ? Thanks !
