### ISSUE TITLE
What will happen when inferring with Efficientdet-d0 using a image smaller than 512 in size?

### ISSUE THREAD

**Issue by xiaohangshi** [google/automl#1142]
When we infer on a image smaller than 512 in size with Efficientdet-d0, what will happen?
1) will the image be resized to 512? 
2) or filled up to 512 with padding and infer with the original size?

**Comment by mingxingtan** [comment]
It will be resize to 512 in default, but you can set the image size with hparams.image_size=xx

**Comment by xiaohangshi** [comment]
Thanks for your comment! @mingxingtan 
I have another question: when we set set the image size to a small value(e.g. 80, 160 or 320) in Efficientdet-d0 with default size of 520, will the inference time be decreased due to this setting? or just keep the similar inference time compared to that of the default size? Because In yolov5, I also changed the imgsz in yolov5s,m,l(some pretrained models), but it seems that decreasing the imgsz(modified to 320) won't decrease the inference time compared to that of the default size(640).
