### ISSUE TITLE
How to define the weight in feature fusion?

### ISSUE THREAD

**Issue by Hwang64** [google/automl#115]
I wonder how to define the weight in feature fusion, however, in efficientdet_arch.py, Line479~Line498, it is strange that the weights are initialized by 1 but not the feature (note in the code), so how to define the weight?

**Comment by mingxingtan** [comment]
The weight is initialized as 1 (same as simply sum them up).   I don't understand the point why we need to initialize the weight with feature?  The output should be:  weight * feature.

**Comment by Hwang64** [comment]
The weight is a scalar, but how to update the weight during training?

**Comment by mingxingtan** [comment]
Yes, it is a scalar, but it is also a trainable variable and will automatically updated by optimizer automatically.
