### ISSUE TITLE
Eval based on tfrecord

### ISSUE THREAD

**Issue by LucasSloan** [google/automl#117]
I'm trying to finetune the model on a custom dataset.  I have a script to convert the dataset to the proper tfrecord format, and it seems to train just fine.  However, it refuses to do the eval step.  Looking at the code, it seems like it wants me to duplicate the labels in a separate json file.  Is it possible to just pull the labels out of the validation tfrecord?

**Comment by cyx6666** [comment]
Same here

**Comment by mingxingtan** [comment]
Good suggestion. the coco dataset doesn't have groudtruth section. I probably don't have bandwidth to add that, but if anyone want to contribute, I would be happy to review and merge the PR.

For now, maybe you could take a look at this script to construct a json file:  https://github.com/google/automl/blob/3ba603c413d7156f919b20102893aed500366513/efficientdet/dataset/create_pascal_tfrecord.py#L219

**Comment by LucasSloan** [comment]
Thanks for the hint, I was able to to update my converter to output the .json file.
