### ISSUE TITLE
How to load the backbone weights when training?

### ISSUE THREAD

**Issue by itsliupeng** [google/automl#118]
> python main.py --tpu=TPU_NAME --training_file_pattern=DATA_DIR/*.tfrecord --model_dir=MODEL_DIR

In this command, I don't find how to load the backbone weights. 
Does it train from scratch?

> flags.DEFINE_string('backbone_ckpt', '',
                    'Location of the ResNet50 checkpoint to use for model '
                    'initialization.')

This flag works only when training retinanet.

**Comment by mingxingtan** [comment]
please specify --backbone_ckpt=xxxx. For example:

```
wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz
tar zxf efficientnet-b0.tar.gz
python main.py --training_file_pattern=DATA_DIR/*.tfrecord --model_dir=MODEL_DIR --model_name=efficientdet-d0 --backbone_ckpt=efficientnet-b0 --hparams="use_bfloat16=false" --use_tpu=False 
```

I will update the README and tutorial to show that.
