### ISSUE TITLE
ERROR : 'ImageFont' object has no attribute 'getbbox'

### ISSUE THREAD

**Issue by ashish-2005** [google/automl#1187]
HI i am trying to do object detection with efficientdet-d0 model using following commands and getting an error
```python
SAVED_MODEL_DIR = 'savedmodel'
!mkdir {SAVED_MODEL_DIR}

#export saved model.
!python model_inspect.py --runmode=saved_model \
  --model_name={MODEL} --ckpt_path={CKPT_PATH} \
  --hparams="image_size=1200x650" \
  --saved_model_dir={SAVED_MODEL_DIR}

!mkdir output
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --saved_model_dir=/content/automl/efficientdet/savedmodel  \
  --input_image=/content/test.jpg --output_image_dir=/content/automl/efficientdet/output
```

#ERROR
```

File "/content/automl/efficientdet/visualize/vis_utils.py", line 215, in <listcomp>
    display_str_heights = [font.getbbox(ds)[3] - font.getbbox(ds)[1] for ds in display_str_list]
AttributeError: 'ImageFont' object has no attribute 'getbbox'
```

**Comment by andrecosta9** [comment]
Hi, I encountered the same error and after looking for the source of it I found that an upgrade of the Pillow library to version 9.5.0 fixes it. According to this [link ](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html) I think version 9.2.0 may also be enough. In my case, I was running the tutorial in Colab so I managed to do it by using the `!pip install pillow --upgrade` command.
