### ISSUE TITLE
the TPU kind of error

### ISSUE THREAD

**Issue by b03505036** [google/automl#119]
![image](https://user-images.githubusercontent.com/49306620/78060570-5aa58980-73be-11ea-8e04-4575e0d4eca5.png)

loading annotations into memory...
INFO:tensorflow:evaluation_loop marked as finished
I0331 18:06:22.252192 140584744810304 error_handling.py:108] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0331 18:06:22.252330 140584744810304 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3053, in evaluate
    rendezvous.record_error('evaluation_loop', sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 81, in record_error
    if value and value.op and value.op.type == _CHECK_NUMERIC_OP_NAME:
AttributeError: 'FileNotFoundError' object has no attribute 'op'

Help , Im using TPU fist time. could anyone give me some advice?
Thanks all

**Comment by Ely-S** [comment]
hm... It's having trouble finding one of the input files.

1. Try quoting "all the file arguments to avoid shell expansion.
2.  You can also test each path using `gsutil ls`

Make sure each one of these returns at least  one file
 - `gsutil ls gs://kennygs/coco/image_val*`
 - `gsutil ls gs://kennygs/models/$Model_dir`
- `gsutil ls gs://kennygs/coco/annotations/image_val.json `

**Comment by b03505036** [comment]
![image](https://user-images.githubusercontent.com/49306620/78093668-48027300-7405-11ea-8fa8-f83c779501f6.png)
but it did exist on gs.

**Comment by b03505036** [comment]
I found that if I change the json file path to local rather than gs. It can work.
Is it the "access problem" of my gs or my tpu?
