### ISSUE TITLE
Is efficientdet suitable for running in real time?

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#121]
Thx for your code.

Your 'Efficientdet' effectively reduced computation.

Therefore, I think it will be effective even in real-time video. So I only wanted to get good performance from the Only CPU computer, but it wasn't.(About 2-3FPS at D0;; my cpu : 3000G)

Can i solve these problems by grafting existing code with Efficientdet or tuning Efficientdet?

**Comment by MustafaUysal160207077** [comment]
Have you solved those problems?

**Comment by mingxingtan** [comment]
Please checkout the latest code. We have made the postprocessing much faster than before, and you should be able to get higher throughput now.

**Comment by MustafaUysal160207077** [comment]
> Please checkout the latest code. We have made the postprocessing much faster than before, and you should be able to get higher throughput now.

Thanks. It is a great work.

**Comment by WonTaeYeon** [comment]
@mingxingtan 
Stay slow.....
CPU : AMD 3000G 
RAM : 16G(8G X 2ea)
OS : Windows 10 (64bit)
In Realtime-video (1280x720 30Fps);
Pretrained EfficientDet Checkpoints Efficientdet-D0 
saved_model : 2.64 FPS
onnx : 2.90 FPS
Custom Model (Trian Only people Class in VOC + COCO with AA)
saved_model : 2.65 FPS
onnx : 3.84 FPS

Is this a parameter value problem? Or is it a specific CPU issue like AMD?

**Comment by mingxingtan** [comment]
@WonTaeYeon  Is it that slow? Could you share your command line?

**Comment by WonTaeYeon** [comment]
@mingxingtan 
saved_model command :
--num_class 1
--input_image_size None
--line_thickness 1
--max_boxes_to_draw 50
--min_score_thresh 0.2
in hparmas_config :
h.use_bfloat16 = False
h.use_tpu = False
The others values are default
When it is 'Saved_model_Video', the command line is the same.
Thx you.

**Comment by mingxingtan** [comment]
I ran the latest code on my Mac CPU, and it seems to work reasonably  good.
