### ISSUE TITLE
training error   ValueError: ['batch_size', 'context'] are reserved keys but existed in params 

### ISSUE THREAD

**Issue by xiaopojizu123** [google/automl#123]
hi,I use the following for training,but I got the following error,it seems that tpu is still called ,how  can i solve it,thanks a lot!
python main.py --training_file_pattern=C:/Users/dell/Desktop/data/BrokenEnd \
    --model_name=efficientdet-d0 \
    --model_dir=C:/Users/dell/Desktop/data/weight \
    --hparams="use_bfloat16=false" --use_tpu=False

Traceback (most recent call last):
  File "C:/Users/dell/Desktop/automl-master-new/efficientdet/main.py", line 384, in <module>
    tf.app.run(main)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:/Users/dell/Desktop/automl-master-new/efficientdet/main.py", line 241, in main
    params=params)
  File "C:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2555, in __init__
    _RESERVED_PARAMS_KEYS, params))
ValueError: ['batch_size', 'context'] are reserved keys but existed in params {'name': 'efficientdet-d0', 'image_size': 512, 'input_rand_hflip': True, 'train_scale_min': 0.1, 'train_scale_max': 2.0, 'autoaugment_policy': None, 'batch_size': 1, 'num_classes': 1, 'skip_crowd_during_training': True, 'min_level': 3, 'max_level': 7, 'num_scales': 3, 'aspect_ratios': [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)], 'anchor_scale': 4.0, 'is_training_bn': True, 'momentum': 0.9, 'learning_rate': 0.08, 'lr_warmup_init': 0.008, 'lr_warmup_epoch': 1.0, 'first_lr_drop_epoch': 200.0, 'second_lr_drop_epoch': 250.0, 'clip_gradients_norm': 10.0, 'num_epochs': 20, 'alpha': 0.25, 'gamma': 1.5, 'delta': 0.1, 'box_loss_weight': 50.0, 'weight_decay': 4e-05, 'use_bfloat16': False, 'box_class_repeats': 3, 'fpn_cell_repeats': 3, 'fpn_num_filters': 64, 'separable_conv': True, 'apply_bn_for_resampling': True, 'conv_after_downsample': False, 'conv_bn_relu_pattern': False, 'use_native_resize_op': False, 'pooling_type': None, 'fpn_name': None, 'fpn_config': None, 'survival_prob': None, 'lr_decay_method': 'cosine', 'moving_average_decay': 0.9998, 'ckpt_var_scope': None, 'backbone_name': 'efficientnet-b0', 'backbone_config': None, 'resnet_depth': 50, 'model_name': 'efficientdet-d0', 'iterations_per_loop': 100, 'model_dir': 'C:/Users/dell/Desktop/data/weight', 'num_shards': 8, 'num_examples_per_epoch': 31, 'use_tpu': False, 'backbone_ckpt': '', 'val_json_file': None, 'mode': 'train'}.

**Comment by mingxingtan** [comment]
Could you do "git pull"? There were  a period of time where I mistakenlly put batch_size in hparams, but that had been fixed in https://github.com/google/automl/commit/89f2e50e7bdf3a6539dcbb0b80bbb6658913eb0c

**Comment by xiaopojizu123** [comment]
> Could you do "git pull"? There were a period of time where I mistakenlly put batch_size in hparams, but that had been fixed in [89f2e50](https://github.com/google/automl/commit/89f2e50e7bdf3a6539dcbb0b80bbb6658913eb0c)

thanks a lot！This problem has been solved ^ ^
