### ISSUE TITLE
Could you share the hyper paramters of reproduce precision in  checkpoint you provide?

### ISSUE THREAD

**Issue by itsliupeng** [google/automl#126]
I trained Efficientdet-d0 and d1 using the default hyperparameters.
The train num_epochs are 15 by default, But I find that mAP cannot reach the numbers in your checkpoints.
I want to know how many epochs should be set to get the precision of the checkpoints you provide.
Thanks.

**Comment by itsliupeng** [comment]
I trained effiicientdet-d0  100 epochs with batch size 16 * 8 = 128, total max learning rate = 128 / 64 * 0.08 = 0.16 , but only get the following precision. I want to know how to tune the hyperparameters to reproduce the results in the paper.
Thanks.

>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.396
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.251
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.281
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.381
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.373
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.395
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.467
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.610

**Comment by mingxingtan** [comment]
Hi @itsliupeng 

All hyperparameters are in hparams_config.py, which has the value of num_epochs = 300.  There could be multiple reasons for the low accuracy:

- Do you load the backbone checkpoints? For B0, you should use this [checkpoint](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz):, and then specify --backbone_ckpt=xxx
- Do you use synchronized batch normal? Or do you change any other settings?

It is sad to see the accuracy is low (100 epochs is less than my default 300 epochs, but the accuracy difference should be <1 mAP). 

However, I am also excited to see you are able to train on multiple GPUs.  Could you share your instructions and paste your full command line to help others to train on multiple GPUs? Thank you!

**Comment by qtw1998** [comment]
> I trained effiicientdet-d0 100 epochs with batch size 16 * 8 = 128, total max learning rate = 128 / 64 * 0.08 = 0.16 , but only get the following precision. I want to know how to tune the hyperparameters to reproduce the results in the paper.
> Thanks.
> 
> > Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
> > Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.396
> > Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.251
> > Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
> > Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.281
> > Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.381
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.373
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.395
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.467
> > Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.610
> 
> This is the tensorboard of training in 100 epochs.
> ![image](https://user-images.githubusercontent.com/680843/78320265-a8c3b400-759b-11ea-829e-4572e15f2491.png)

老哥是怎么改的分布式训练？ 谢谢指教！！

**Comment by fsx950223** [comment]
I train the model on multi GPUs too, I will open-source it later.

**Comment by itsliupeng** [comment]
> Hi @itsliupeng
> 
> All hyperparameters are in hparams_config.py, which has the value of num_epochs = 300. There could be multiple reasons for the low accuracy:
> 
> * Do you load the backbone checkpoints? For B0, you should use this [checkpoint](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz):, and then specify --backbone_ckpt=xxx
> * Do you use synchronized batch normal? Or do you change any other settings?
> 
> It is sad to see the accuracy is low (100 epochs is less than my default 300 epochs, but the accuracy difference should be <1 mAP).
> 
> However, I am also excited to see you are able to train on multiple GPUs. Could you share your instructions and paste your full command line to help others to train on multiple GPUs? Thank you!

Thanks for your reply.

- I have  used  --backbone_ckpt=xxx
- I use SyncBatchNorm implemented by horovod allreduce, just like tf.keras.layers.experimental.SyncBatchNormalization in tensorflow version 2.2

I will share more details of our instructions using horovod after Qingming holidays.

**Comment by fsx950223** [comment]
> > Hi @itsliupeng
> > All hyperparameters are in hparams_config.py, which has the value of num_epochs = 300. There could be multiple reasons for the low accuracy:
> > 
> > * Do you load the backbone checkpoints? For B0, you should use this [checkpoint](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz):, and then specify --backbone_ckpt=xxx
> > * Do you use synchronized batch normal? Or do you change any other settings?
> > 
> > It is sad to see the accuracy is low (100 epochs is less than my default 300 epochs, but the accuracy difference should be <1 mAP).
> > However, I am also excited to see you are able to train on multiple GPUs. Could you share your instructions and paste your full command line to help others to train on multiple GPUs? Thank you!
> 
> Thanks for your reply.
> 
> * I have  used  --backbone_ckpt=xxx
> * I use SyncBatchNorm implemented by horovod allreduce, just like tf.keras.layers.experimental.SyncBatchNormalization in tensorflow version 2.2
> 
> I will share more details of our instructions using horovod after Qingming holidays.

Advance user.

**Comment by itsliupeng** [comment]
> Hi @itsliupeng
> 
> All hyperparameters are in hparams_config.py, which has the value of num_epochs = 300. There could be multiple reasons for the low accuracy:
> 
> * Do you load the backbone checkpoints? For B0, you should use this [checkpoint](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz):, and then specify --backbone_ckpt=xxx
> * Do you use synchronized batch normal? Or do you change any other settings?
> 
> It is sad to see the accuracy is low (100 epochs is less than my default 300 epochs, but the accuracy difference should be <1 mAP).
> 
> However, I am also excited to see you are able to train on multiple GPUs. Could you share your instructions and paste your full command line to help others to train on multiple GPUs? Thank you!

https://github.com/itsliupeng/automl/tree/master/efficientdet

**Comment by itsliupeng** [comment]
> > I trained effiicientdet-d0 100 epochs with batch size 16 * 8 = 128, total max learning rate = 128 / 64 * 0.08 = 0.16 , but only get the following precision. I want to know how to tune the hyperparameters to reproduce the results in the paper.
> > Thanks.
> > > Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
> > > Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.396
> > > Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.251
> > > Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
> > > Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.281
> > > Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.381
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.373
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.395
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.467
> > > Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.610
> > 
> > 
> > This is the tensorboard of training in 100 epochs.
> > ![image](https://user-images.githubusercontent.com/680843/78320265-a8c3b400-759b-11ea-829e-4572e15f2491.png)
> 
> 老哥是怎么改的分布式训练？ 谢谢指教！！

我上传了训练代码，你可以试试 https://github.com/itsliupeng/automl/tree/master/efficientdet

**Comment by itsliupeng** [comment]
@mingxingtan 
I trained d0 in 100 epochs and only got mAP 0.32462898.
I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint. 
I want to find why I can't achieve your precision.
I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.

I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from  https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
I would appreciate that if you can help me analyze the reasons.

![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)

![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)

**Comment by mingxingtan** [comment]
Hi @itsliupeng , excited to see you have 32.46 mAP for d0!

My previous d0 checkpoint has 32.9mAP for val with batch norm 0.997 and epsilon 1e-4 (borrowed from RetinaNet), but later on I found I should use the same batch norm parameter as backbones, so I changed batch norm to use 0.99 and epsilon 1e-3 as shown in the latest code (same as [EfficientNet](https://github.com/tensorflow/tpu/blob/f04e13e20a11d22514d55d1b7d188a55fc851f63/models/official/efficientnet/efficientnet_builder.py#L185)).

After changing BN and fixing some small bugs, I retrained all models. The latest d0 checkpoint has 33.4mAP for val and 33.8mAP for test-dev. Arxiv paper was also updated a few days ago to be aligned with the public repo: https://arxiv.org/pdf/1911.09070.pdf.

If you use the old parameters, then your results are aligned to my old results: 32.9mAP for 300 epochs and about 32.4mAP for 100 epochs. Could you retrain it with the latest code?  (I will also train d0 for 100 epochs to provide you a better comparison).

**Comment by qtw1998** [comment]
> Hi @itsliupeng , excited to see you have 32.46 mAP for d0!
> 
> My previous d0 checkpoint has 32.9mAP for val with batch norm 0.997 and epsilon 1e-4 (borrowed from RetinaNet), but later on I found I should use the same batch norm parameter as backbones, so I changed batch norm to use 0.99 and epsilon 1e-3 as shown in the latest code (same as [EfficientNet](https://github.com/tensorflow/tpu/blob/f04e13e20a11d22514d55d1b7d188a55fc851f63/models/official/efficientnet/efficientnet_builder.py#L185)).
> 
> After changing BN and fixing some small bugs, I retrained all models. The latest d0 checkpoint has 33.4mAP for val and 33.8mAP for test-dev. Arxiv paper was also updated a few days ago to be aligned with the public repo: https://arxiv.org/pdf/1911.09070.pdf.
> 
> If you use the old parameters, then your results are aligned to my old results: 32.9mAP for 300 epochs and about 32.4mAP for 100 epochs. Could you retrain it with the latest code? (I will also train d0 for 100 epochs to provide you a better comparison).

![image](https://user-images.githubusercontent.com/34357479/78746364-2d963f80-7999-11ea-9bae-0cbc6decb20f.png)
use your latest version of `create_pascal_tfrecord.py` no use, still `-1` 
lotta people have the problems waiting your method to solve

**Comment by itsliupeng** [comment]
> Hi @itsliupeng , excited to see you have 32.46 mAP for d0!
> 
> My previous d0 checkpoint has 32.9mAP for val with batch norm 0.997 and epsilon 1e-4 (borrowed from RetinaNet), but later on I found I should use the same batch norm parameter as backbones, so I changed batch norm to use 0.99 and epsilon 1e-3 as shown in the latest code (same as [EfficientNet](https://github.com/tensorflow/tpu/blob/f04e13e20a11d22514d55d1b7d188a55fc851f63/models/official/efficientnet/efficientnet_builder.py#L185)).
> 
> After changing BN and fixing some small bugs, I retrained all models. The latest d0 checkpoint has 33.4mAP for val and 33.8mAP for test-dev. Arxiv paper was also updated a few days ago to be aligned with the public repo: https://arxiv.org/pdf/1911.09070.pdf.
> 
> If you use the old parameters, then your results are aligned to my old results: 32.9mAP for 300 epochs and about 32.4mAP for 100 epochs. Could you retrain it with the latest code? (I will also train d0 for 100 epochs to provide you a better comparison).

Hi @mingxingtan, thanks for your reply.
My 32.46 mAP for 100 epochs is got by training with the latest code (momentum  0.99 and epsilon 1e-3).
I will find more machines to train 350 epochs this weekend.

**Comment by qtw1998** [comment]
> > Hi @itsliupeng , excited to see you have 32.46 mAP for d0!
> > 
> > My previous d0 checkpoint has 32.9mAP for val with batch norm 0.997 and epsilon 1e-4 (borrowed from RetinaNet), but later on I found I should use the same batch norm parameter as backbones, so I changed batch norm to use 0.99 and epsilon 1e-3 as shown in the latest code (same as [EfficientNet](https://github.com/tensorflow/tpu/blob/f04e13e20a11d22514d55d1b7d188a55fc851f63/models/official/efficientnet/efficientnet_builder.py#L185)).
> > 
> > After changing BN and fixing some small bugs, I retrained all models. The latest d0 checkpoint has 33.4mAP for val and 33.8mAP for test-dev. Arxiv paper was also updated a few days ago to be aligned with the public repo: https://arxiv.org/pdf/1911.09070.pdf.
> > 
> > If you use the old parameters, then your results are aligned to my old results: 32.9mAP for 300 epochs and about 32.4mAP for 100 epochs. Could you retrain it with the latest code? (I will also train d0 for 100 epochs to provide you a better comparison).
> 
> Hi @mingxingtan, thanks for your reply.
> My 32.46 mAP for 100 epochs is got by training with the latest code (momentum  0.99 and epsilon 1e-3).
> I will find more machines to train 350 epochs this weekend.
> 

Hi how could you solve the eval problem?

**Comment by mingxingtan** [comment]
Hi @qtw1998 , I have found the issue (it is from dataseet), fix on the way.

**Comment by qtw1998** [comment]
> Hi @qtw1998 , I have found the issue (it is from dataseet), fix on the way.

Is it from the transfer script or my custom dataset? I'm sure it's available to use actually because I've already made comparison between the official json and mine
THX bro💗

**Comment by zzzxxxttt** [comment]
> @mingxingtan
> I trained d0 in 100 epochs and only got mAP 0.32462898.
> I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> I want to find why I can't achieve your precision.
> I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> 
> I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> I would appreciate that if you can help me analyze the reasons.
> 
> ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> 
> ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)

Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.

**Comment by itsliupeng** [comment]
> > @mingxingtan
> > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > I want to find why I can't achieve your precision.
> > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > I would appreciate that if you can help me analyze the reasons.
> > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> 
> Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.

Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.

**Comment by zzzxxxttt** [comment]
> > > @mingxingtan
> > > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > > I want to find why I can't achieve your precision.
> > > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > > I would appreciate that if you can help me analyze the reasons.
> > > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> > 
> > 
> > Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.
> 
> Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.

Thank you for your reply! I'll check my code accordingly.

**Comment by zzzxxxttt** [comment]
> > > @mingxingtan
> > > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > > I want to find why I can't achieve your precision.
> > > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > > I would appreciate that if you can help me analyze the reasons.
> > > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> > 
> > 
> > Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.
> 
> Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.

Sorry for bothering you again, could you run a D0 training for 36 epochs and tell me the result mAP? My code now reaches 29.4% mAP for 36 epochs training, I'm not sure whether it is because of the less training epochs or there are still some bugs, and training for more epochs is too expensive for me.

**Comment by itsliupeng** [comment]
> > > > @mingxingtan
> > > > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > > > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > > > I want to find why I can't achieve your precision.
> > > > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > > > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > > > I would appreciate that if you can help me analyze the reasons.
> > > > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > > > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> > > 
> > > 
> > > Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.
> > 
> > 
> > Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.
> 
> Sorry for bothering you again, could you run a D0 training for 36 epochs and tell me the result mAP? My code now reaches 29.4% mAP for 36 epochs training, I'm not sure whether it is because of the less training epochs or there are still some bugs, and training for more epochs is too expensive for me.

It reached approximately 29% mAP at the 36th epoch during my training for  100 epochs. I think you should try training more epochs.

The efficientnet network uses many depthwise convolutions instead of normal convolutions, so it needs much more training time for better convergence.

During another training for 300 epochs, It has reached  33.09%  at the 159th epoch, very close to the 33.5% mAP in the published checkpoint.

![image](https://user-images.githubusercontent.com/680843/79087527-1af18100-7d72-11ea-8517-e2e87c0f9cde.png)

**Comment by zzzxxxttt** [comment]
> > > > > @mingxingtan
> > > > > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > > > > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > > > > I want to find why I can't achieve your precision.
> > > > > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > > > > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > > > > I would appreciate that if you can help me analyze the reasons.
> > > > > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > > > > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> > > > 
> > > > 
> > > > Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.
> > > 
> > > 
> > > Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.
> > 
> > 
> > Sorry for bothering you again, could you run a D0 training for 36 epochs and tell me the result mAP? My code now reaches 29.4% mAP for 36 epochs training, I'm not sure whether it is because of the less training epochs or there are still some bugs, and training for more epochs is too expensive for me.
> 
> It reached approximately 29% mAP at the 36th epoch during my training for 100 epochs. I think you should try training more epochs.
> 
> The efficientnet network uses many depthwise convolutions instead of normal convolutions, so it needs much more training time for better convergence.
> 
> During another training for 300 epochs, It has reached 33.09% at the 159th epoch, very close to the 33.5% mAP in the published checkpoint.
> 
> ![image](https://user-images.githubusercontent.com/680843/79087527-1af18100-7d72-11ea-8517-e2e87c0f9cde.png)

Thank you very much! I will try more epochs, really appreciate for your help!

**Comment by itsliupeng** [comment]
Hi @mingxingtan 
During my training for 300 epochs, it reached the highest 33.71 mAP for val at about the 217th epoch, then begin to overfit the training data.

![image](https://user-images.githubusercontent.com/680843/79291897-65a20300-7f02-11ea-9348-2e759bc651d7.png)

![image](https://user-images.githubusercontent.com/680843/79291772-1c51b380-7f02-11ea-9c6f-c6ffcacdaccd.png)

**Comment by mingxingtan** [comment]
@itsliupeng  Wow, excellent! Your result 33.71 is slightly better than mine 33.5! Congratulations!

Yes, it is fine to see overfitting since you are training on validation set. Just take the checkpoint under "archive" folder and you are done. If you want to check the test accuracy, you can run eval on test-dev set using the archived checkpoint and submit to the COCO server (instructions are in tutorial and README).

Now, you can use the same training setting to train all other models if you want. Notably, bigger models will overfit at earlier stage, so you don't really need to train 300 epochs.

**Comment by shreymohan** [comment]
Hey @mingxingtan, how do we run this code on GPU? Every time I try it utilizes the CPU instead. Is there any flag to be set?

**Comment by mingxingtan** [comment]
hi @shreymohan it is handled by Tensorflow, which should automatically use GPU if GPU is available.

**Comment by 15241192958** [comment]
> Hey @mingxingtan, how do we run this code on GPU? Every time I try it utilizes the CPU instead. Is there any flag to be set?

may be the version not correct tf2.1 must use cuda 1.1

**Comment by shreymohan** [comment]
Thank you @15241192958 for your comment. I realized I was using TF 1.14. I will update and try, thanks again!

**Comment by shreymohan** [comment]
@mingxingtan I updated TF to 2.1 and now the script can see the GPUs. I can see the GPU memory getting loaded but just before it starts training, it freezes.

![tf_error](https://user-images.githubusercontent.com/24687852/80627800-71231d00-8a1e-11ea-94b7-490885e8ae57.PNG)

**Comment by claire-s11** [comment]
Hi @itsliupeng , congratulations on your 33.71 mAP! I tried your code with multi-gpu training with 2 GPU and batchsize == 16, but the step_time is so slow (around 5s per step, that is 3.2 examples/sec), while @mingxingtan 's code has 25 examples/sec on a single GPU. 
Also, if I changed the default batch_size 64, do I need to change the learning rate accordingly?
Thank you so much for your help!

**Comment by claire-s11** [comment]
> > > > @mingxingtan
> > > > I trained d0 in 100 epochs and only got mAP 0.32462898.
> > > > I saw that you mentioned mAP 32.9 in Table 2 of your paper and mAP 33.8 in your checkpoint.
> > > > I want to find why I can't achieve your precision.
> > > > I put my training details in https://github.com/itsliupeng/automl/tree/master/efficientdet#best_eval.
> > > > I find the settings of the synchronized batch normalization in the paper (0.997, 1e-4) are different from https://github.com/google/automl/blob/master/efficientdet/backbone/efficientnet_builder.py#L187.
> > > > I would appreciate that if you can help me analyze the reasons.
> > > > ![image](https://user-images.githubusercontent.com/680843/78738905-a4294200-7985-11ea-943c-d88df32ce7d0.png)
> > > > ![image](https://user-images.githubusercontent.com/680843/78739061-07b36f80-7986-11ea-89bf-dd8b4069b382.png)
> > > 
> > > 
> > > Hello, could you tell me the changes you made that cause the mAP jump from 24 to 32? I ported the code to pytorch but D0 only reaches ~26 mAP, so I wonder there must be something I missed.
> > 
> > 
> > Hi @zzzxxxttt I made a bug of forgetting to all reduce gradients across GPUs. After fixing it in https://github.com/itsliupeng/automl/blob/master/efficientdet/det_model_fn.py#L460 it works.
> 
> Sorry for bothering you again, could you run a D0 training for 36 epochs and tell me the result mAP? My code now reaches 29.4% mAP for 36 epochs training, I'm not sure whether it is because of the less training epochs or there are still some bugs, and training for more epochs is too expensive for me.

Hi @zzzxxxttt , sorry to bother you but can I know your batch_size, lr rate and num of gpus and step_time for training? I tried the code with multi-gpu training with 2 GPUs and batchsize == 16, but the step_time is so slow (around 5s per step, that is 3.2 examples/sec) and mAP only achieves 0.295 after 60 epochs so I wonder if I did wrong somewhere. Thank you so much for your help!
