### ISSUE TITLE
The args I set made it clear which GPUs were used, but all the GPUs were used automatically, and no solution was found.

### ISSUE THREAD

**Issue by qtw1998** [google/automl#133]
As the foregoing question!
I use commands:
`CUDA_VISIBLE_DEVICE=5 python main.py 
--training_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/train.tfrecord 
--model_name=efficientdet-d1 
--ckpt=/cluster/home/qiaotianwei/automl/efficientdet/efficientdet-d1 
--hparams="use_bfloat16=false" 
--use_tpu=False --train_batch_size 4 
--model_dir=/tmp/efficientdet/efficientdet-d1 
--mode='train' 
--validation_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/val.tfrecord`

but still, all the GPUs are running ...
![image](https://user-images.githubusercontent.com/34357479/78120748-0d1c3180-743d-11ea-82cc-78f0e4dd0099.png)
![image](https://user-images.githubusercontent.com/34357479/78120775-17d6c680-743d-11ea-84a0-0a1c41e8063c.png)
![image](https://user-images.githubusercontent.com/34357479/78120871-350b9500-743d-11ea-931d-369580f95bcd.png)

**Comment by Guzaiwang** [comment]
You may try to add the code "import os "

**Comment by Guzaiwang** [comment]
You may try to delete the line "CUDA_VISIBLE_DEVICE=5" in the command. 
And try to add the following code in the main.py 
import os
os.environ['CUDA_VISIBLE_DEVICE'] = '5'

**Comment by qtw1998** [comment]
I have solved this problem:
add in main.py
`os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = "5"
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)`

> You may try to delete the line "CUDA_VISIBLE_DEVICE=5" in the command.
> And try to add the following code in the main.py
> import os
> os.environ['CUDA_VISIBLE_DEVICE'] = '5'

thx bro
