### ISSUE TITLE
model_inspect.py，How many pictures can be processed in batch and where can I set them

### ISSUE THREAD

**Issue by honghande** [google/automl#134]

**Comment by mingxingtan** [comment]
model_inspect.py assume you have a file pattern, and it will use the batch size that equals to the number of images for this file pattern.

If you want to run with a specific batch size, I recommend directly using inference.py:

https://github.com/google/automl/blob/6da9a772796ce4c7a04ebeb299a1f07e432f155f/efficientdet/inference.py#L265

**Comment by honghande** [comment]
@mingxingtan 
export MODEL=efficientdet-d0
export CKPT_PATH=ckpt/pzy_v3
python model_inspect.py --runmode=infer --model_name=$MODEL --ckpt_path=$CKPT_PATH num_classes=3 --input_image=testdata/*.jpg --output_image_dir=testdata/
Why can I use the above command to process only 100 pieces of data and 200 pieces of data to infer the bug,

Using your suggestion, use the following command, very slow:
from PIL import Image
import os
import inference
import tensorflow.compat.v1 as tf
import numpy as np
import os.path as osp
tf.disable_v2_behavior()

MODEL='efficientdet-d0'
MODEL_DIR='ckpt/pzy_v3'
input_image="testdata/*.jpg"
output_image_dir="test/"
imgs_list=[]
for f in tf.io.gfile.glob(input_image):
  print("f:",f)
  imgs_list.append(f)
driver = inference.ServingDriver(MODEL, MODEL_DIR,batch_size=len(imgs_list))
driver.build()

for file in imgs_list:
  img_name=file.split("/")[-1]
  image = np.array(Image.open(file))
  predictions = driver.serve_images([image])
  out_image = driver.visualize(
      image,
      predictions[0],
      min_score_thresh=0.2,
      max_boxes_to_draw=10,
  )
  output_image_path = os.path.join(output_image_dir,img_name)
  Image.fromarray(out_image).save(output_image_path)

**Comment by yz-ju** [comment]
I have the same problem. Do you solve it?
