### ISSUE TITLE
AA could not be used , NameError: name 'contrib_image' is not defined

### ISSUE THREAD

**Issue by b03505036** [google/automl#135]
/home/kenny70037/automl/efficientdet/aug/autoaugment.py:1370 <lambda>
        image, bboxes, pixels, replace, shift_horizontal=True),
    /home/kenny70037/automl/efficientdet/aug/autoaugment.py:947 translate_bbox
        image = translate_x(image, pixels, replace)
    /home/kenny70037/automl/efficientdet/aug/autoaugment.py:877 translate_x
        image = contrib_image.translate(wrap(image), [-pixels, 0])

    NameError: name 'contrib_image' is not defined

I have successed in pretrain model in TPU, and when I'm trying  to use AA , facing this problem.

**Comment by wingedrasengan927** [comment]
> ```
> /home/kenny70037/automl/efficientdet/aug/autoaugment.py:1370 <lambda>
>     image, bboxes, pixels, replace, shift_horizontal=True),
> /home/kenny70037/automl/efficientdet/aug/autoaugment.py:947 translate_bbox
>     image = translate_x(image, pixels, replace)
> /home/kenny70037/automl/efficientdet/aug/autoaugment.py:877 translate_x
>     image = contrib_image.translate(wrap(image), [-pixels, 0])
> 
> NameError: name 'contrib_image' is not defined
> ```
> 
> I have successed in pretrain model in TPU, and when I'm trying to use AA , facing this problem.

the contrib image functionalilty has been pushed to tensorflow addons.
after installing tensorflow addons, you can do:
`import tensorflow_addons.image as contrib_image`
this should fix it.
