### ISSUE TITLE
Why can't I generate logs?

### ISSUE THREAD

**Issue by wangtianlong1994** [google/automl#136]
> python main.py 
> --training_file_pattern=tfrecord/train*
> --model_name=efficientdet-d3 
> --model_dir=tmp/model 
> --hparams="use_bfloat16=false, num_classes=6"
>  --use_tpu=False 
> --ckpt=tmp/efficientdet-d3
>  --validation_file_pattern=tfrecord/val*
>  --val_json_file=tfrecord/annotations/val2017.json 
> --mode='train_and_eval' 
> --logdir=logs

Even if I add -- logdir = logs, I don't generate log files. Who can tell me what's wrong with me? Thank you very much.

**Comment by WonTaeYeon** [comment]
maybe ... check 'tmp / model'. You will find the '* .tfevents' file.

**Comment by wangtianlong1994** [comment]
> 也许...检查“ tmp /模型”。您将找到“ * .tfevents”文件。

Thank you very much. Your suggestion is very effective
