### ISSUE TITLE
train error NaN loss

### ISSUE THREAD

**Issue by elesun2018** [google/automl#137]
when i run train code, meet a problem as follows:
/efficientdet# python main.py --training_file_pattern=tfrecord/train*     --model_name=$MODEL     --model_dir=model/$MODEL     --hparams="use_bfloat16=false" --use_tpu=False

INFO:tensorflow:examples/sec: 11.7567
I0402 11:01:06.012281 140192889546560 tpu_estimator.py:2308] examples/sec: 11.7567
ERROR:tensorflow:Model diverged with loss = NaN.
E0402 11:01:06.344348 140192889546560 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Error recorded from training_loop: NaN loss during training.
E0402 11:01:07.801579 140192889546560 error_handling.py:75] Error recorded from training_loop: NaN loss during training.
INFO:tensorflow:training_loop marked as finished
I0402 11:01:07.801944 140192889546560 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error

tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

thanks.

**Comment by WonTaeYeon** [comment]
Try :
hparams_config.py
h.learning_rate = 0.08 => 0.001
h.lr_warmup_init = 0.008 => 0.0001

**Comment by elesun2018** [comment]
thanks，but same error.  use coco dataset

tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by Li505358678** [comment]
why happen this question when I train with coco2017 dataset

**Comment by shivam-raj** [comment]
I am getting the same error when training with coco train2017 dataset. Is there any workaround ?

**Comment by tangyan-77** [comment]
the same fault!  i have change imge_size [512,256] then Nan loss erro

Try :
hparams_config.py
h.learning_rate = 0.08 => 0.001
h.lr_warmup_init = 0.008 => 0.0001
it don't work

**Comment by Li505358678** [comment]
> 同样的错误！我有换尺码[512，256]，那么南损失错误
> 
> 试着：
> hparams_config.py
> 学习率=0.08=>0.001
> h.lr_warup_init=0.008=>0.0001
> 不管用

you can turn the batch size up .I use your hyperparameter can train with 4 batch size .When I use lr=0.08,I need to change the batch size to 8 or larger

**Comment by elesun2018** [comment]
anyone can give a solution for this error. Thanks a lot.  train error NaN loss

**Comment by kento-kobayashi** [comment]
How about 
` rm -r model/$MODEL/* `
I can fix this problem by removing ckpt file and etc.

**Comment by hou2lin** [comment]
It might be caused by the groudtruth boxes values. Divide by zero encountered.
Try: 
object_detection/faster_rcnn_box_coder.py L79-82
tx = (xcenter - xcenter_a) / tf.maximum(wa, 1e-14)
ty = (ycenter - ycenter_a) / tf.maximum(ha, 1e-14)
tw = tf.log(tf.maximum(w / wa, 1e-14))
th = tf.log(tf.maximum(h / ha, 1e-14))

**Comment by elv-xuwen** [comment]
I'm using a custom dataset for D2 and got the same error. Has anyone solved it?

**Comment by Li505358678** [comment]
> I'm using a custom dataset for D2 and got the same error. Has anyone solved it?

Did you changed the model you used

**Comment by elv-xuwen** [comment]
> > I'm using a custom dataset for D2 and got the same error. Has anyone solved it?
> 
> Did you changed the model you used

Hi what do you mean change the model? How to change it?

**Comment by Li505358678** [comment]
Which command do you use?Did you changed --model_dir=${model-path}

**Comment by elv-xuwen** [comment]
This is the command I'm using; I use a new model-dir every time I start the job.
`export CUDA_DEVICE_ORDER='PCI_BUS_ID'
export CUDA_VISIBLE_DEVICES='4' 
python main.py --logtostderr --mode=train_and_eval \
    --training_file_pattern=data/OID/annotations/whole_set/train_tfrecord/oid*.tfrecord \
    --validation_file_pattern=data/OID/annotations/whole_set/val_tfrecord/oid*.tfrecord \
    --model_name=efficientdet-d2 \
    --model_dir=tmp/efficientdet-d2-oid-group3  \
    --backbone_ckpt=efficientnet-b2 \
    --train_batch_size=4 \
    --eval_batch_size=8 --eval_samples=6000 \
    --num_epochs=100  \
    --hparams="num_classes=601" \
    --use_tpu=False`

**Comment by Li505358678** [comment]
This is my problem. I thought you got the result which is the same as the other. I saw that you said is error just now. 

What's error?

**Comment by elv-xuwen** [comment]
@Li505358678  My error is tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by Li505358678** [comment]
> @Li505358678 My error is tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

h.learning_rate = 0.08 => 0.001
h.lr_warmup_init = 0.008 => 0.0001
Does the modification like the above not solve the problem?
This problem may caused by batch-size.If batch-size is too small,It will cause it.
What's more.I remember that the eval_batch_size must be 1.I forgot if this was necessary

**Comment by elv-xuwen** [comment]
> > @Li505358678 My error is tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
> 
> h.learning_rate = 0.08 => 0.001
> h.lr_warmup_init = 0.008 => 0.0001
> Does the modification like the above not solve the problem?
> This problem may caused by batch-size.If batch-size is too small,It will cause it.
> What's more.I remember that the eval_batch_size must be 1.I forgot if this was necessary

Thank you! I'll try it. Why decrease the loss from 0.08 to 0.001? It's a big change.

**Comment by Li505358678** [comment]
> > > @Li505358678 My error is tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
> > 
> > 
> > h.learning_rate = 0.08 => 0.001
> > h.lr_warmup_init = 0.008 => 0.0001
> > Does the modification like the above not solve the problem?
> > This problem may caused by batch-size.If batch-size is too small,It will cause it.
> > What's more.I remember that the eval_batch_size must be 1.I forgot if this was necessary
> 
> Thank you! I'll try it. Why decrease the loss from 0.08 to 0.001? It's a big change.

Let's talk about my own understanding. 
if you don't have a good GPU or TPU. You must reduce the batch-size. So you need to reduce your learning rate accordingly.The batch-size in the code I remember is 128.When I change it to 2.NAN,you can see det_model_fn.py. Though the default_batch_size will make your lr down. maybe not enough,This is not an order of magnitude

Specifically, you should consult the author.I'm also a student studying this field, and I don't know it very well

**Comment by Pari-singh** [comment]
I am getting the same error. Waiting for the author's comments. @mingxingtan

**Comment by mingxingtan** [comment]
We recently added a few more gradients/loss clipping. Could you try it again?

**Comment by Pari-singh** [comment]
@mingxingtan, thanks for the update. Yeah it works this time, along with generating checkpoints each time as I had created a separate issue for it, which I will close. I just have one quick question, has the new changes somehow changed the event generation for tfrecord? As I am now seeing only one graph for the loss and one for steps/sec as opposed to all the losses graph we used to get earlier.
