### ISSUE TITLE
trainning errror: tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [139]

### ISSUE THREAD

**Issue by Jucjiaswiss** [google/automl#141]
Trainning on my own dataset, using  [https://github.com/google/automl/blob/master/efficientdet/dataset/create_pascal_tfrecord.py](url) to convert my data to tfrecords, the generated tfrecords are like this:
![image](https://user-images.githubusercontent.com/18287639/78325628-bcc2e200-75aa-11ea-8ae3-9c4c8ca53e8a.png)
trainning still met the error, 
![image](https://user-images.githubusercontent.com/18287639/78325695-f398f800-75aa-11ea-8fde-359f9787ae6b.png)
has anyone solved this?

**Comment by mingxingtan** [comment]
Hmm, this is strange. I have verified it worked well on pascal 2012 on my local machine, Could you attach the full log and your full command line?

**Comment by Jucjiaswiss** [comment]
@mingxingtan Thanks for reply! here is my log.txt and trainning command:
[log.txt](https://github.com/google/automl/files/4425297/log.txt)
![image](https://user-images.githubusercontent.com/18287639/78329255-c56be600-75b3-11ea-9867-876744b68fea.png)

**Comment by mingxingtan** [comment]
Hmm, it is strange. I will try it in colab tmr.

**Comment by Jucjiaswiss** [comment]
@mingxingtan Thanks again! I'll try to solve it and check the error.

**Comment by phucnhs** [comment]
In file create_pascal_tfrecord has create file.json .maybe you have loaded file.json into the data pattern ,Please check that out

**Comment by Jucjiaswiss** [comment]
@phucnhs Thank you! error in my log.txt is solved(which is not the training error I opened this issue for)! I moved json file out and start train and after few minutes the InvalidArgumentError happened again, I'll attach the full log, @mingxingtan ,sorry about earlier, this is the log I reproduce the InvalidArgumentError. Training command is the same.
[log.txt](https://github.com/google/automl/files/4425652/log.txt)

**Comment by Jucjiaswiss** [comment]
@mingxingtan My images and xml files for converting to tfrecords are put together in two folders, 
train/JPEGImages/*.JPEG, train/Annotations/*.xml, I didn't put them by different classes folders, so I changed few lines in create_pascal_tfrecord.py to get the correct file. 
But I assue this won't be a problem (maybe?) since it generated .tfrecord succcessfully.

**Comment by phucnhs** [comment]
I used my dataset created from created_pascal_tfrecord.py and it work as usual ,probably not the problem from tfrecord

**Comment by Jucjiaswiss** [comment]
@phucnhs can you share your command running created_pascal_tfrecord.py? Thanks a lot!

**Comment by xiaopojizu123** [comment]
hi，I have the same problem with you，have you solved this problem？

**Comment by mingxingtan** [comment]
Hmm, looks like you use create_pascal_tfrecord.py, it creates both tfrecrod and json file under the same folder, so when you specify --training_file_pattern=train*, then it would also include the json file, which is not a valid tfrecord.

I will change the code to name the jason file differently (probably starting from json_xx) to avoid this issue.

**Comment by YangZhang-mizzou** [comment]
Similar problem happened on my coco dataset. Still don't know how to solve it.

**Comment by vamshi-vk** [comment]
@mingxingtan hi, My custom data is in this format:  
Data
 1. Images
       i.) Train.
       ii.) Val
2. Annotations
        i.) Train_XML
        ii.) Val_XMl
Please tell me how do I convert them to the required tfrecords and JSON format using create_pascal_tf_record.py ??

**Comment by vamshi-vk** [comment]
> @mingxingtan hi, My custom data is in this format:
> Data
> 1. Images
> i.) Train.
> ii.) Val
> 2. Annotations
> i.) Train_XML
> ii.) Val_XMl
> Please tell me how do I convert them to the required tfrecords and JSON format using create_pascal_tf_record.py ??

Solved it by 
[](https://gist.github.com/iamtodor/787aafbd15b99bf15eaf5bc31271e235)
changed line number 83
**Before**
`image/source_id': dataset_util.bytes_feature(data['filename'].encode('utf8')),`
**After** 
`'image/source_id': dataset_util.bytes_feature("".encode('utf8')),`

**Comment by vamshi-vk** [comment]
> > @mingxingtan hi, My custom data is in this format:
> > Data
> > 
> > 1. Images
> >    i.) Train.
> >    ii.) Val
> > 2. Annotations
> >    i.) Train_XML
> >    ii.) Val_XMl
> >    Please tell me how do I convert them to the required tfrecords and JSON format using create_pascal_tf_record.py ??
> 
> Solved it by using this script in Tensorflow Object Detection API
> [https://gist.github.com/iamtodor/787aafbd15b99bf15eaf5bc31271e235](url)
> changed line number 83
> **Before**
> `image/source_id': dataset_util.bytes_feature(data['filename'].encode('utf8')),`
> **After**
> `'image/source_id': dataset_util.bytes_feature("".encode('utf8')),`

Command That I Used for  training 
`**python3 main.py --training_file_pattern=Efficient_Det_Data_format_exp/tf_records/train.tfrecord --model_name=efficientdet-d0 --model_dir=eff_d0_exp_data_v2 --hparams="use_bfloat16=false,num_classes=1,var_exclude_expr=r'.*/class-predict/.*'"  --num_classes=1 --use_tpu=False --train_batch_size=8 --ckpt=efficientdet-d0/  --num_examples_per_epoch=720 --num_epochs=100 --eval_after_training=True --validation_file_pattern=Efficient_Det_Data_format_exp/`**

**Comment by mingxingtan** [comment]
Thanks @vamshi-vk Good to see it worked. I am closing this issue now, we can discuss the eval issue in #154

**Comment by qtw1998** [comment]
> > @mingxingtan hi, My custom data is in this format:
> > Data
> > 
> > 1. Images
> >    i.) Train.
> >    ii.) Val
> > 2. Annotations
> >    i.) Train_XML
> >    ii.) Val_XMl
> >    Please tell me how do I convert them to the required tfrecords and JSON format using create_pascal_tf_record.py ??
> 
> Solved it by using this script in Tensorflow Object Detection API
> [https://gist.github.com/iamtodor/787aafbd15b99bf15eaf5bc31271e235](url)
> changed line number 83
> **Before**
> `image/source_id': dataset_util.bytes_feature(data['filename'].encode('utf8')),`
> **After**
> `'image/source_id': dataset_util.bytes_feature("".encode('utf8')),`

HI bro the link is not available...

**Comment by mingxingtan** [comment]
You can use the new script: https://github.com/google/automl/blob/master/efficientdet/dataset/create_pascal_tfrecord.py

**Comment by qtw1998** [comment]
> You can use the new script: https://github.com/google/automl/blob/master/efficientdet/dataset/create_pascal_tfrecord.py

not available and in the wechat group lotta people meet the problem. would you like to deal with it
THX!!

**Comment by Jucjiaswiss** [comment]
Hi, I updated the latest version and using create_pascal_tfrecord.py and made a few changes:
replace pascal_label_map_dict = { my own data label}
delete year related variables since I don't have them
![image](https://user-images.githubusercontent.com/18287639/78851688-04cf8200-7a4d-11ea-92e6-41e8908b3859.png)

**Comment by Jucjiaswiss** [comment]
Finnaly, training and validation error solved! 
InvalidArgumentError: assertion failed solved by  #93 
validation 'Unicode' error solved by #178 
validation 'TypeError numpy.float64 object cannot be interpreted as an index' solved by `pip install numpy==1.17.0` downgrade numpy from 1.18 to 1.17
and get the right map (at early training)
![image](https://user-images.githubusercontent.com/18287639/78962854-0a4dca80-7b28-11ea-8807-37e0653ebb13.png)
