### ISSUE TITLE
Why so slow of postprocess

### ISSUE THREAD

**Issue by Root-9527** [google/automl#145]
EfficientDet-d0 inference time cost about 15ms;
But postprocess time cost about 35ms, much lager than inference time cost

**Comment by mingxingtan** [comment]
Yes, the current postprocessing is run with python on CPU mostly. There are many fast NMS and post-prrocessing implementations, but I haven't gotten a chance to implement that. PRs are welcome if you happen to have some better implementations.

**Comment by varghesealex90** [comment]
@Root-9527 can you let me know how to get the inference and postprocess time?

**Comment by Root-9527** [comment]
> @Root-9527 can you let me know how to get the inference and postprocess time?

Run graph just include inference, get time cost; then run graph inference and postprocess, get total time cost.

**Comment by mingxingtan** [comment]
Please checkout the latest README and tutorial, now the postprocessing is reasonably fast: end-to-end D0 latency on Testla T4 is 24ms.
