### ISSUE TITLE
Different Output from Saved Model

### ISSUE THREAD

**Issue by akashdeepjassal** [google/automl#146]
The Saved Model gives different Output.
The confidence is set as 0.2.
This is output of EfficientDet-D0 image using 
`python model_inspect.py --runmode=infer --model_name=$MODEL --ckpt_path=$CKPT_PATH --input_image=77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png --output_image_dir=/tmp`

![orig](https://user-images.githubusercontent.com/19704407/78353499-c870d180-75c7-11ea-8ca7-59f79890b4e6.jpg)

When the saved model infer is used as in 

` python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0/ --input_image=../../Desktop/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png --output_image_dir=../../Desktop/Test/ --saved_model_dir=../../efdet/efdet0/`

The output is 

![0](https://user-images.githubusercontent.com/19704407/78353390-9495ac00-75c7-11ea-963a-65a32974f274.jpg)

Using Tensorflow Serving the model output is

![1](https://user-images.githubusercontent.com/19704407/78353419-9f504100-75c7-11ea-97cd-2cd32ce45656.jpg)

**Comment by fsx950223** [comment]
please change max_output_size manually in related function.

**Comment by akashdeepjassal** [comment]
This is not a output size problem.
The model behaves differently when in Saved Model format.

**Comment by fsx950223** [comment]
What's your input_image_size?

**Comment by akashdeepjassal** [comment]
The default size in hparams_config is the input size.

**Comment by fsx950223** [comment]
> The default size in hparams_config is the input size.

Please change input_image_size to 1920.Thanks.

**Comment by akashdeepjassal** [comment]
> > The default size in hparams_config is the input size.
> 
> Please change input_image_size to 1920.Thanks.

Changed Image Size.
No change

**Comment by fsx950223** [comment]
> > > The default size in hparams_config is the input size.
> > 
> > 
> > Please change input_image_size to 1920.Thanks.
> 
> Changed Image Size.
> No change

You should export saved model again.

**Comment by fsx950223** [comment]
> The Saved Model gives different Output.
> The confidence is set as 0.2.
> This is output of EfficientDet-D0 image using
> `python model_inspect.py --runmode=infer --model_name=$MODEL --ckpt_path=$CKPT_PATH --input_image=testdata/img1.jpg --output_image_dir=/tmp`
> 
> ![orig](https://user-images.githubusercontent.com/19704407/78353499-c870d180-75c7-11ea-8ca7-59f79890b4e6.jpg)
> 
> When the saved model infer is used as in
> 
> ` python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0/ --input_image=../../Desktop/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png --output_image_dir=../../Desktop/Test/ --saved_model_dir=../../efdet/efdet0/`
> 
> The output is
> 
> ![0](https://user-images.githubusercontent.com/19704407/78353390-9495ac00-75c7-11ea-963a-65a32974f274.jpg)
> 
> Using Tensorflow Serving the model output is
> 
> ![1](https://user-images.githubusercontent.com/19704407/78353419-9f504100-75c7-11ea-97cd-2cd32ce45656.jpg)

I wonder how you can get the result.
Here is output from colab:
![image](https://user-images.githubusercontent.com/17592563/78360332-3974b100-75e9-11ea-9f76-d2174619d177.png)
And demo image format is png, why yours is jpg?

**Comment by akashdeepjassal** [comment]
> > > > The default size in hparams_config is the input size.
> > > 
> > > 
> > > Please change input_image_size to 1920.Thanks.
> > 
> > 
> > Changed Image Size.
> > No change
> 
> You should export saved model again.

I tried that multiple times, changed TF version as well and disabled pyfun and enabled it. But all in vain

**Comment by fsx950223** [comment]
> > > > > The default size in hparams_config is the input size.
> > > > 
> > > > 
> > > > Please change input_image_size to 1920.Thanks.
> > > 
> > > 
> > > Changed Image Size.
> > > No change
> > 
> > 
> > You should export saved model again.
> 
> I tried that multiple times, changed TF version as well and disabled pyfun and enabled it. But all in vain

Could you answer my question?

**Comment by akashdeepjassal** [comment]
> > > > > > The default size in hparams_config is the input size.
> > > > > 
> > > > > 
> > > > > Please change input_image_size to 1920.Thanks.
> > > > 
> > > > 
> > > > Changed Image Size.
> > > > No change
> > > 
> > > 
> > > You should export saved model again.
> > 
> > 
> > I tried that multiple times, changed TF version as well and disabled pyfun and enabled it. But all in vain
> 
> Could you answer my question?

I already tried that.

**Comment by fsx950223** [comment]
> > The Saved Model gives different Output.
> > The confidence is set as 0.2.
> > This is output of EfficientDet-D0 image using
> > `python model_inspect.py --runmode=infer --model_name=$MODEL --ckpt_path=$CKPT_PATH --input_image=testdata/img1.jpg --output_image_dir=/tmp`
> > ![orig](https://user-images.githubusercontent.com/19704407/78353499-c870d180-75c7-11ea-8ca7-59f79890b4e6.jpg)
> > When the saved model infer is used as in
> > ` python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0/ --input_image=../../Desktop/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png --output_image_dir=../../Desktop/Test/ --saved_model_dir=../../efdet/efdet0/`
> > The output is
> > ![0](https://user-images.githubusercontent.com/19704407/78353390-9495ac00-75c7-11ea-963a-65a32974f274.jpg)
> > Using Tensorflow Serving the model output is
> > ![1](https://user-images.githubusercontent.com/19704407/78353419-9f504100-75c7-11ea-97cd-2cd32ce45656.jpg)
> 
> I wonder how you can get the result.
> Here is output from colab:
> ![image](https://user-images.githubusercontent.com/17592563/78360332-3974b100-75e9-11ea-9f76-d2174619d177.png)
> And demo image format is png, why yours is jpg?

Could you answer above questions?

**Comment by akashdeepjassal** [comment]
> Could you answer above questions?

The input image is PNG.

**Comment by fsx950223** [comment]
> > Could you answer above questions?
> 
> The input image is PNG.

Why you get a different results with colab?

**Comment by akashdeepjassal** [comment]
> > > Could you answer above questions?
> > 
> > 
> > The input image is PNG.
> 
> Why you get a different result with colab?

I get different outputs when I use saved Model format instead of Checkpoint.

**Comment by fsx950223** [comment]
> > > > Could you answer above questions?
> > > 
> > > 
> > > The input image is PNG.
> > 
> > 
> > Why you get a different result with colab?
> 
> I get different outputs when I use saved Model format instead of Checkpoint.

I mean you get a different result with official implementation.

**Comment by akashdeepjassal** [comment]
> > > > > Could you answer above questions?
> > > > 
> > > > 
> > > > The input image is PNG.
> > > 
> > > 
> > > Why you get a different result with colab?
> > 
> > 
> > I get different outputs when I use saved Model format instead of Checkpoint.
> 
> I mean you get a different result with official implementation.

Yes.

**Comment by fsx950223** [comment]
> > > > > > Could you answer above questions?
> > > > > 
> > > > > 
> > > > > The input image is PNG.
> > > > 
> > > > 
> > > > Why you get a different result with colab?
> > > 
> > > 
> > > I get different outputs when I use saved Model format instead of Checkpoint.
> > 
> > 
> > I mean you get a different result with official implementation.
> 
> Yes.

Could you try the latest ckpt and source code?

**Comment by akashdeepjassal** [comment]
I'll try it once more

**Comment by fsx950223** [comment]
> I'll try it once more

Good luck to you.

**Comment by akashdeepjassal** [comment]
> > I'll try it once more
> 
> Good luck to you.

Still same Outputs.
There might be a issue with model conversion from checkpoint to saved model.

**Comment by fsx950223** [comment]
> > > I'll try it once more
> > 
> > 
> > Good luck to you.
> 
> Still same Outputs.
> There might be a issue with model conversion from checkpoint to saved model.

https://colab.research.google.com/drive/1sAV2Kar-mjdh8CNQ4Fb_eOC4uD5L_XbC
I believe you should check my notebook

**Comment by fsx950223** [comment]
Any question?

**Comment by akashdeepjassal** [comment]
> Any question?

I checked your notebook.
Same issue in the notebook.
Please visualize the output from 

`!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
                         --ckpt_path=./efficientdet-d0 --input_image_size=1920 \
                         --min_score_thresh=0.5 --saved_model_dir=./saved_model --max_boxes_to_draw=400 
from IPython import display
display.display(display.Image(os.path.join('./testdata', '0.jpg')))`

And compare with

 `python model_inspect.py --runmode=saved_model_infer --input_image=./img.png --output_image_dir=./testdata  --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 --input_image_size=1920 --saved_model_dir=./saved_model --max_boxes_to_draw=400   --min_score_thresh=0.5
from IPython import display
display.display(display.Image(os.path.join('./testdata', '0.jpg')))`

Then you will understand what I'm trying to highlight regarding saved model format.

**Comment by fsx950223** [comment]
First, my notebook return different result with yours, right? So they are different result.

**Comment by fsx950223** [comment]
> > Any question?
> 
> I checked your notebook.
> Same issue in the notebook.
> Please visualize the output from
> 
> `!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \ --ckpt_path=./efficientdet-d0 --input_image_size=1920 \ --min_score_thresh=0.5 --saved_model_dir=./saved_model --max_boxes_to_draw=400 from IPython import display display.display(display.Image(os.path.join('./testdata', '0.jpg')))`
> 
> And compare with
> 
> `python model_inspect.py --runmode=saved_model_infer --input_image=./img.png --output_image_dir=./testdata --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 --input_image_size=1920 --saved_model_dir=./saved_model --max_boxes_to_draw=400 --min_score_thresh=0.5 from IPython import display display.display(display.Image(os.path.join('./testdata', '0.jpg')))`
> 
> Then you will understand what I'm trying to highlight regarding saved model format.

Second, if you want more boxes, you could change vis related function params by yourself. As they just for display image and won't influence model performance. Default value is 50.

**Comment by fsx950223** [comment]
> please change max_output_size manually in related function.

I have told you change params here.

**Comment by akashdeepjassal** [comment]
> > please change max_output_size manually in related function.
> 
> I have told you to change params here.

Changed boxes to 400 and max_output_size to the same as that of image.
You are not understanding the problem. 
**Let me "rephrase".**
**The checkpoint and the saved model are giving different outputs (Less Bounding Box, Different Confidence score for objects.** 
Model conversion should not change output. 
So someone needs to take a look at saved model conversion implementation.

**Comment by fsx950223** [comment]
Could you give me a notebook which could reproduce the images upload by the issue?

**Comment by fsx950223** [comment]
> > > please change max_output_size manually in related function.
> > 
> > 
> > I have told you to change params here.
> 
> Changed boxes to 400 and max_output_size to the same as that of image.
> You are not understanding the problem.
> **Let me "rephrase".**
> **The checkpoint and the saved model are giving different outputs (Less Bounding Box, Different Confidence score for objects.**
> Model conversion should not how model performs.
> So someone needs to take a look at saved model conversion implementation.

I let you to change the code https://github.com/google/automl/blob/35a87186d8edbc8ee9c77978d929a4631297c383/efficientdet/inference.py#L208 by yourself. Do you undetstand?
Inference and saved model use same graph.They have same graph. I have check it several times.

**Comment by mingxingtan** [comment]
Take it easy!

Hi @fsx950223, I indeed noticed some difference in your [colab](https://colab.sandbox.google.com/drive/1sAV2Kar-mjdh8CNQ4Fb_eOC4uD5L_XbC#scrollTo=wg4HsofUHLHV): the image produced by --runmode=infer is different from the image produced by --runmode=saved_model_infer.  Did I miss anything?

**Comment by fsx950223** [comment]
> Take it easy!
> 
> Hi @fsx950223, I indeed noticed some difference in your [colab](https://colab.sandbox.google.com/drive/1sAV2Kar-mjdh8CNQ4Fb_eOC4uD5L_XbC#scrollTo=wg4HsofUHLHV): the image produced by --runmode=infer is different from the image produced by --runmode=saved_model_infer. Did I miss anything?

Yes, because of max_output_size and min_score_threshold useless in saved_model_infer mode,
their value is 0.2 and 50 in visualize_image although you change them to other values.

**Comment by fsx950223** [comment]
> Take it easy!
> 
> Hi @fsx950223, I indeed noticed some difference in your [colab](https://colab.sandbox.google.com/drive/1sAV2Kar-mjdh8CNQ4Fb_eOC4uD5L_XbC#scrollTo=wg4HsofUHLHV): the image produced by --runmode=infer is different from the image produced by --runmode=saved_model_infer. Did I miss anything?

And I suggest change default value of max_output_size and min_score_threshold to 100 and 0.2,
which could reduce controversy.

**Comment by mingxingtan** [comment]
Sure, we can change the default value in inference.py to be aligned with tutorial.

You are right, you did not change chose values in your colab.  I just modified your colab by changing:

```
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 \
  --input_image_size=1920 --saved_model_dir=./saved_model 
```

to 

```
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 \
  --input_image_size=1920 --saved_model_dir=./saved_model \
  --min_score_thresh={min_score_thresh} \
  --max_boxes_to_draw={max_boxes_to_draw} \
  --line_thickness={line_thickness}
```

But the results are still different from --runmode=infer. Is this the right way to specify min_score_thresh, max_boxes_to_draw, line_thickness (I meant at exporting time)?

**Comment by mingxingtan** [comment]
FYI, I am trying to update the tutorial to include the saved model usage.  Thanks for your great help, @fsx950223

**Comment by fsx950223** [comment]
> FYI, I am trying to update the tutorial to include the saved model usage. Thanks for your great help, @fsx950223

```min_score_thresh``` and ```max_boxes_to_draw``` are useful when you use native nms, but I keep nms_tf the same behavior as numpy nms, so ```min_score_thresh``` is useless. And ```line_thickness``` is used to draw boxes which won't include in saved model.

**Comment by fsx950223** [comment]
> Sure, we can change the default value in inference.py to be aligned with tutorial.
> 
> You are right, you did not change chose values in your colab. I just modified your colab by changing:
> 
> ```
> !python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 \
>   --input_image_size=1920 --saved_model_dir=./saved_model 
> ```
> 
> to
> 
> ```
> !python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=./efficientdet-d0 \
>   --input_image_size=1920 --saved_model_dir=./saved_model \
>   --min_score_thresh={min_score_thresh} \
>   --max_boxes_to_draw={max_boxes_to_draw} \
>   --line_thickness={line_thickness}
> ```
> 
> But the results are still different from --runmode=infer. Is this the right way to specify min_score_thresh, max_boxes_to_draw, line_thickness (I meant at exporting time)?

```min_score_thresh``` and ```max_boxes_to_draw``` are useful when you use native nms, but I keep nms_tf the same behavior as numpy nms, so min_score_thresh is useless. And line_thickness is used to draw boxes which won't include in saved model.

**Comment by fsx950223** [comment]
> FYI, I am trying to update the tutorial to include the saved model usage. Thanks for your great help, @fsx950223

I believe that I could merge ```saved_model``` and ```saved_model_infer later```

**Comment by mingxingtan** [comment]
Is there anyway I can specify min_score_thresh and max_boxes_to_draw in either exporting or serving the model? @fsx950223

**Comment by fsx950223** [comment]
> Is there anyway I can specify min_score_thresh and max_boxes_to_draw in either exporting or serving the model? @fsx950223

Need to convert them to saved_model_infer
https://github.com/google/automl/blob/a6effb4d696970d3f5fc0ddcedb1b678cbece77e/efficientdet/model_inspect.py#L354
I didn't add it.

**Comment by mingxingtan** [comment]
Agreed, a config should be used for visualization or inference. I will add that later. Thanks!

**Comment by sourabhyadav** [comment]
> > > please change max_output_size manually in related function.
> > 
> > 
> > I have told you to change params here.
> 
> Changed boxes to 400 and max_output_size to the same as that of image.
> You are not understanding the problem.
> **Let me "rephrase".**
> **The checkpoint and the saved model are giving different outputs (Less Bounding Box, Different Confidence score for objects.**
> Model conversion should not how model performs.
> So someone needs to take a look at saved model conversion implementation.

@akashdeepjassal  I am facing the same error with the latest code. How did you solve finally?
