### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Reciprocal' OpKernel for 'CPU' devices compatible with node

### ISSUE THREAD

**Issue by YangZhang-mizzou** [google/automl#153]
Train with customized coco dataset. Anyone who have met this error before? Here is full log:
[record.txt](https://github.com/google/automl/files/4433052/record.txt)
Thanks!

**Comment by KaqiKaqi** [comment]
It seems I have met this error and after setting use_btfloat16=False it's gone. Hope this is helpful : )

**Comment by YangZhang-mizzou** [comment]
> It seems I have met this error and after setting use_btfloat16=False it's gone. Hope this is helpful : )

Thank you for your reply but sadly it doesn't work for me.

**Comment by YangZhang-mizzou** [comment]
Sorry I updated a wrong file. Here is the log 
[record.txt](https://github.com/google/automl/files/4434302/record.txt)

**Comment by YangZhang-mizzou** [comment]
> It seems I have met this error and after setting use_btfloat16=False it's gone. Hope this is helpful : )

Hello! Could you tell me where to set use_btfloat? This is my command:
python main.py --mode=train_and_eval \
--training_file_pattern=./tfrecord/train* \
--validation_file_pattern=./tfrecord/val* \
--val_json_file=./bird/split_folder_V2/val_split/val_bird.json \
--num_classes=1 \
--model_name=efficientdet-d0 \
--ckpt=efficientdet-d0  \
--model_dir=./tmp/efficientdet\
--hparams="use_bfloat16=false" \
--use_tpu=False \
--train_batch_size 2

**Comment by KaqiKaqi** [comment]
> > It seems I have met this error and after setting use_btfloat16=False it's gone. Hope this is helpful : )
> 
> Hello! Could you tell me where to set use_btfloat? This is my command:
> python main.py --mode=train_and_eval 
> --training_file_pattern=./tfrecord/train* 
> --validation_file_pattern=./tfrecord/val* 
> --val_json_file=./bird/split_folder_V2/val_split/val_bird.json 
> --num_classes=1 
> --model_name=efficientdet-d0 
> --ckpt=efficientdet-d0 
> --model_dir=./tmp/efficientdet
> --hparams="use_bfloat16=false" 
> --use_tpu=False 
> --train_batch_size 2

I set use_bfloat16 in the same way. And the error looks the same. Maybe this error is caused by some other reason. Trying to upgrade tensorflow may be helpful, I tried tf1.14, tf2.0.0.

**Comment by YangZhang-mizzou** [comment]
Thank you! Problem solved after updating tf to 2.0.0

**Comment by lovepan1** [comment]
when i updata tf2.0.0, i also met this error, can you change others?

**Comment by lovepan1** [comment]
@YangZhang-mizzou
