### ISSUE TITLE
Train Error：tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.   (0) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]          [[{{node parser/GatherNd}}]]          [[IteratorGetNext]]

### ISSUE THREAD

**Issue by wwdok** [google/automl#156]
System information:
Windows10
tensorflow-gpu-2.1.0
i want to train my custom model, and i ran 
`python main.py --mode=train_and_eval   --num_classes=1   --training_file_pattern="D:/MachineLearning/DataSet/ObjectDetection/coco/coco_train.*"   --validation_file_pattern="D:/MachineLearning/DataSet/ObjectDetection/coco/coco_val.record-00000-of-00001"   --val_json_file="D:/MachineLearning/DataSet/ObjectDetection/coco/annotations/instances_val2017.json"   --model_name=efficientdet-d0   --model_dir=MyOwn/training_output    --ckpt=efficientdet-d0    --train_batch_size=1   --eval_batch_size=1 --eval_samples=200   --num_examples_per_epoch=3659 --num_epochs=1    --hparams="use_bfloat16=false" --use_tpu=False`
The log says it trains on CPU：
`INFO:tensorflow:Running train on CPU
I0406 11:57:20.235256 112384 tpu_estimator.py:3124] Running train on CPU
I0406 11:57:20.235256 112384 efficientdet_arch.py:548] {
    "name": "efficientdet-d0",
    "image_size": 512,
    "input_rand_hflip": true,
    "train_scale_min": 0.1,
    "train_scale_max": 2.0,
    "autoaugment_policy": null,
    "num_classes": 90,
    "skip_crowd_during_training": true,
    "min_level": 3,
    "max_level": 7,
    "num_scales": 3,
    "aspect_ratios": [
        [
            1.0,
            1.0
        ],
        [
            1.4,
            0.7
        ],
        [
            0.7,
            1.4
        ]
    ],
    "anchor_scale": 4.0,
    "is_training_bn": true,
    "momentum": 0.9,
    "learning_rate": 0.08,
    "lr_warmup_init": 0.008,
    "lr_warmup_epoch": 1.0,
    "first_lr_drop_epoch": 200.0,
    "second_lr_drop_epoch": 250.0,
    "clip_gradients_norm": 10.0,
    "num_epochs": 1,
    "alpha": 0.25,
    "gamma": 1.5,
    "delta": 0.1,
    "box_loss_weight": 50.0,
    "weight_decay": 4e-05,
    "use_bfloat16": false,
    "box_class_repeats": 3,
    "fpn_cell_repeats": 3,
    "fpn_num_filters": 64,
    "separable_conv": true,
    "apply_bn_for_resampling": true,
    "conv_after_downsample": false,
    "conv_bn_relu_pattern": false,
    "use_native_resize_op": false,
    "pooling_type": null,
    "fpn_name": null,
    "fpn_config": null,
    "survival_prob": null,
    "lr_decay_method": "cosine",
    "moving_average_decay": 0.9998,
    "ckpt_var_scope": null,
    "var_exclude_expr": ".*/class-predict/.*",
    "backbone_name": "efficientnet-b0",
    "backbone_config": null,
    "resnet_depth": 50,
    "model_name": "efficientdet-d0",
    "iterations_per_loop": 100,
    "model_dir": "MyOwn",
    "num_shards": 8,
    "num_examples_per_epoch": 3659,
    "use_tpu": false,
    "backbone_ckpt": "",
    "ckpt": "efficientdet-d0",
    "val_json_file": "D:\\MachineLearning\\DataSet\\ObjectDetection\\coco\\annotations\\instances_val2017.json",
    "testdev_dir": null,
    "mode": "train_and_eval",
    "batch_size": 1
}`
Finally i got this error：
`2020-04-06 12:56:43.125920: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
INFO:tensorflow:training_loop marked as finished
I0406 12:56:45.716192 109388 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0406 12:56:45.717911 109388 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1376, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1361, in _run_fn
    target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1454, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
         [[{{node parser/GatherNd}}]]
         [[IteratorGetNext]]`

**Comment by mingxingtan** [comment]
The error says it cannot find any valid input data. Most likely the input file "D:\MachineLearning\DataSet\ObjectDetection\coco\coco_val.record-00000-of-00001" doesn't exist?

**Comment by wadewangpower** [comment]
> The error says it cannot find any valid input data. Most likely the input file "D:\MachineLearning\DataSet\ObjectDetection\coco\coco_val.record-00000-of-00001" doesn't exist?

(i have modified the command line, and the output error is a little different now)
Do you mean `W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty. Params shape: [0,1]`  implys there is no valid input data ? Actually the record file exist, for the 'training_file_pattern' i 
 typed '.../coco_train.*', does it correct ? 
Or maybe my tfrecord file has error inside itself ? if so , is there any tools can checks the tfrecord is created correctly or not ?
![Snipaste_2020-04-06_13-01-34](https://user-images.githubusercontent.com/43233772/78524666-23dcd280-7807-11ea-9b4b-43a060ef91f8.png)

**Comment by wadewangpower** [comment]
These days, i'll check if it is the problem of tfrecord, if so, i will close this issue, so please wait ~

**Comment by anciubotaru** [comment]
Hello, everyone. I have a similar issue when I am trying to evaluate the model on a custom dataset. 
I am using TF v2.2.0.
In my case, the record file doesn't have an error inside it.

**Comment by DevashishPrasad** [comment]
I am facing same issue when I am trying to fine-tune efficientdet-d1 on custom coco dataset.

I am running following command
```
!python main.py --mode=train_and_eval \
    --training_file_pattern="/content/drive/My Drive/tfrecords/coco_train.record-00000-of-00100" \
    --validation_file_pattern="/content/drive/My Drive/tfrecords/coco_val.record-00000-of-00100" \
    --val_json_file="/content/drive/My Drive/DATASET/annotations/vipriors-object-detection-val.json" \
    --model_name="efficientdet-d1" \
    --model_dir="/content/drive/My Drive/EfficientDet/D1" \
    --ckpt="/content/drive/My Drive/EfficientDet/automl/efficientdet/efficientdet-d1/model" \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=200  \
    --num_examples_per_epoch=1000  --num_epochs=20  \
    --hparams="num_classes=80,moving_average_decay=0" \
    --use_tpu=False  
```

**Comment by Electrawizard** [comment]
That worked for me, just added in the beging of the main.py script 
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
