### ISSUE TITLE
converting custom dataset to tfrecord with coco tool = can't install protoc (no version that satisfies requirement)

### ISSUE THREAD

**Issue by lessw2020** [google/automl#157]
Hi - I'm trying to follow the included readme to build a tfrecord of our custom coco format dataset.

====
export PYTHONPATH=".:$PYTHONPATH"
    $ pip install protoc
 ...
======
 
However, I cannot get past the pip nistall protoc requirement - I receive:
ERROR: Could not find a version that satisfies the requirement protoc (from versions: none)
ERROR: No matching distribution found for protoc

As an effort to fix, I installed via gitclone the tensorflow/models repo and ran the requirements.txt and everything updated nicely but did not fix the above issue.

I attempted the first line of  pythonpath export in both jupyter notebook and terminal and then ran pip install protoc and receive the same error regardless.

Can anyone advise?  Should I proceed with a different tool (i.e. the tf/models) to make the tfrecords or any other ideas?  
Thanks!

**Comment by mingxingtan** [comment]
protoc is not needed anymore, you can skip that step (I will update dataset/README soon).

If you have your own dataset, you may want to follow this instructions: https://github.com/google/automl/tree/master/efficientdet#6-train-on-pascal-voc-2012-with-backbone-imagenet-ckpt
