### ISSUE TITLE
 module 'tensorflow.compat.v1' has no attribute 'repeat'

### ISSUE THREAD

**Issue by zhishao** [google/automl#159]
while running : python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 \
  --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --saved_model_dir=/tmp/saved_model
raise :
File "D:\Project\efficientdet\anchors.py", line 345, in _else
    tf.repeat(image_id, tf.size(top_detection_idx)), tf.float32),
AttributeError: module 'tensorflow.compat.v1' has no attribute 'repeat'

**Comment by vamshi-vk** [comment]
Use Tensorflow Version = 2.1

> while running : python model_inspect.py --runmode=saved_model
> --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0
> --input_image_size=1920 --max_boxes_to_draw=100 --min_score_thresh=0.2
> --saved_model_dir=/tmp/saved_model
> raise :
> File "D:\Project\efficientdet\anchors.py", line 345, in _else
> tf.repeat(image_id, tf.size(top_detection_idx)), tf.float32),
> AttributeError: module 'tensorflow.compat.v1' has no attribute 'repeat'

Install Tensorflow Version == 2.1

**Comment by zhishao** [comment]
@vamshi-vk thank you

**Comment by xiaopojizu123** [comment]
hi，besides upgrade the TensorFlow version，is there any other way to solve this problem？

**Comment by Sean0123456789** [comment]
hi, I update tf to version 2.1, but still have this problem, anyone can help?

**Comment by adizhol** [comment]
Same issue. Code is in tf 1.15, so I can't upgrade

**Comment by mingxingtan** [comment]
You can replace "tf.repeat" with "tf.tile"

**Comment by mingxingtan** [comment]
https://github.com/google/automl/commit/aa32e73ab03a4a8a37c45b003f9e6e6c9f5a9782 shows an example.

**Comment by adizhol** [comment]
Ok.thanks
