### ISSUE TITLE
Allow different image width and height

### ISSUE THREAD

**Issue by JunweiLiang** [google/automl#162]
Hi,
in https://github.com/google/automl/blob/master/efficientdet/efficientdet_arch.py#L83:
_, width, _, num_channels = feat.get_shape().as_list()
Shouldn't it be:
_, height, width, num_channels = feat.get_shape().as_list()
Maybe it is ok since you assume width==height. But I think this design will lead to much waste of computation especially with modern video format (The code will pad 1920x1080 frames to 1920x1920)

**Comment by mingxingtan** [comment]
Good point, I should change the code to support different width and height!

**Comment by JunweiLiang** [comment]
Cool! I have a working example [here](https://github.com/JunweiLiang/Object_Detection_Tracking). It is for inferencing in videos. Other than the fact that I have to make sure the image sizes are multipliers of 128 (2^7) with the following code example, it is a straightforward change (dataloader.py & efficientdet_arch.py).
```
max_size, short_edge_size = 1280, 720
fpn_resolution_requirement = 128.0  # 2 ** max_level
short_edge_size = np.ceil(short_edge_size / fpn_resolution_requirement) * fpn_resolution_requirement
max_size = np.ceil(max_size / fpn_resolution_requirement) * fpn_resolution_requirement
# this will become (1280, 768)
```

**Comment by mingxingtan** [comment]
With a few recent comments, now we should be able to handle image size  width x height, where width and height can be any size (not necessary to be multipliers of 128)
