### ISSUE TITLE
git clone on python

### ISSUE THREAD

**Issue by mohana-13** [google/automl#164]
under the 'download source code part', i put this in python:
if "efficientdet" not in os.getcwd():
...     git clone --depth 1 https://github.com/google/automl

and recieve this error:
git clone --depth 1 https://github.com/google/automl
            ^
SyntaxError: invalid syntax

I have also tried with the exclamation before git and still receive an error.

**Comment by mingxingtan** [comment]
"git clone ..." is a shell command, not a python code.  In colab/jupyter, you can mix python code and shell command (with !), but you can't mix them in a python file.

If you want to run shell command in python file, please refer https://stackoverflow.com/questions/89228/calling-an-external-command-from-python
