### ISSUE TITLE
pretrain efficientdet use backbone lite + performance on dataset coco

### ISSUE THREAD

**Issue by phucnhs** [google/automl#166]
Hi 
-  Where can I find pretrain efficientdet + backbone lite
- You have got the performance on dataset coco

**Comment by mingxingtan** [comment]
Still on going, will upload those weights soon.

**Comment by cnmckee** [comment]
Any update here? Am also interested in this

**Comment by OctaM** [comment]
https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/lite here are the ckpt for the lite models

**Comment by mingxingtan** [comment]
efficientdet-lite checkpoints are listed on README page: https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints
