### ISSUE TITLE
the results of different

### ISSUE THREAD

**Issue by an1018** [google/automl#167]
@willnorris Hello
I test figure( ./testdata/img1.jpg) with the downloaded model(efficientdet-d1),but the result is  different  from what you gave.
![image](https://user-images.githubusercontent.com/19808900/78645859-bbffb800-78ea-11ea-8ada-d924035d9621.png)

**Comment by an1018** [comment]
I have solved this problem by  modifying the parameters.
But  I use efficientdet-d7, It took 85.67s to test the whole picture.And runmode=infer .
How to speed up

**Comment by mingxingtan** [comment]
Do you run on CPU or GPU?  Maybe you should try a smaller model like D4 or D2 for faster speed?

We are also working on the fast post-processing, but that's still in progress.

**Comment by mingxingtan** [comment]
Use saved model instead of --infer to speed up the process (avoiding the graph construction)
