### ISSUE TITLE
ExponentialMovingAverage not found in checkpoint

### ISSUE THREAD

**Issue by chryslar** [google/automl#168]
I was trying to train my own dataset and I set only one class. The train progress was going well. Some checkpoints appeared in ckpt_stool folder.
`python main.py --num_classes=1 --training_file_pattern=/home/leo/Downloads/special2/1/train/coco/tfrecord/train* --model_name=efficientdet-d0 --model_dir=ckpt_stool --hparams="use_bfloat16=false,num_classes=1,moving_average_decay=0" --use_tpu=False --train_batch_size=1`

When I run model_inspect.py to do inference, there were 2 errors found.
`python model_inspect.py --runmode=infer --model_name=efficientdet-d0 --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 --ckpt_path=ckpt_stool --input_image=/home/leo/Downloads/special2/1/test/stool_1920/kvasir_v2__fold_1_test_class_stool_frame_55.jpg --output_image_dir=/tmp`

> tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
>   (0) Not found: Key box_net/box-0-bn-3/beta/**ExponentialMovingAverage** not found in checkpoint
> 	 [[{{node save/RestoreV2}}]]
>   (1) Not found: Key box_net/box-0-bn-3/beta/**ExponentialMovingAverage** not found in checkpoint
> 	 [[{{node save/RestoreV2}}]]
> 	 [[save/RestoreV2/_133]]

Does anyone has the same situation?

**Comment by mingxingtan** [comment]
Hi, since you sepecify moving_average_decay=0, you need to set "enable_ema=False" when using model_inspec.py, like this:

python model_inspect.py --runmode=infer --model_name=efficientdet-d0 --input_image_size=1920 --max_boxes_to_draw=100 --min_score_thresh=0.2 --ckpt_path=ckpt_stool  --input_image=/home/leo/Downloads/special2/1/test/stool_1920/kvasir_v2__fold_1_test_class_stool_frame_55.jpg --output_image_dir=/tmp  --enable_ema=False

**Comment by Jucjiaswiss** [comment]
same problem here, tried --enable_ema=False but it remains the same.

**Comment by mingxingtan** [comment]
My bad, I noticed enable_ema doesn't apply to inference.py. You can change the code (enable_ema=False) in this line for now:

https://github.com/google/automl/blob/fe439281c367b742dc2358fa9d13c55991b7dfda/efficientdet/inference.py#L537

I have a fix commit on the way.

**Comment by Jucjiaswiss** [comment]
@mingxingtan problem solved! Thank you!

**Comment by chryslar** [comment]
solved. thanks.
