### ISSUE TITLE
Using Efficentdet with TF serving

### ISSUE THREAD

**Issue by akashdeepjassal** [google/automl#17]
Hi, has anyone tried to convert the efficentdet model to saved model format for tensorflow serving.

**Comment by Byronnar** [comment]
Hi, have you produced the saved model?

**Comment by akashdeepjassal** [comment]
Yes I produced the Saved model but it has no Signature Definition

**Comment by Byronnar** [comment]
> Yes I produced the Saved model but it has no Signature Definition

Great , would you mind share u script? Thank you

**Comment by akashdeepjassal** [comment]
> > Yes I produced the Saved model but it has no Signature Definition
> 
> Great , would you mind share u script? Thank you

Hi @Byronnar . I think I am not able to save the Saved Model Correctly.
We should wait for support from the authors.
Or Else we can both contribute for conversion to saved model format.
