### ISSUE TITLE
Does anyone solve the problem meet ZERO AP values when eval?

### ISSUE THREAD

**Issue by qtw1998** [google/automl#170]
![2121586271224_ pic_hd](https://user-images.githubusercontent.com/34357479/78687639-f8510980-7926-11ea-8813-f56f5d9cf88f.jpg)
`CUDA_VISIBLE_DEVICES=2 python main.py --mode=eval --model_name=efficientdet-d1 --model_dir=efficientdet-d1/ --validation_file_pattern=/cluster/home/qiaotianwei/data/bdd100k2coco/val_all/-00000-of-00100.tfrecord --val_json_file=/cluster/home/qiaotianwei/data/bdd100k2coco/val_all/json_val.json --hparams="use_bfloat16=false, num_classes=90,var_exclude_expr=r'.*/class-predict/.*'" --use_tpu=False`
above is my command beside I've already transfer my XML into TFRECORD using the official offered code `create_pascal_tfrecord.py` and I'm sure there's no bugs in datasets.

and then I test the pretained ckpt offered by author, yet comes to `-1`
![image](https://user-images.githubusercontent.com/34357479/78688056-6d244380-7927-11ea-91d6-d73e4f31e1bd.png)
I wanna get your helping hands. THX !! 

ADD:#####################################
The coco official validation test transferred to TFRECORD has been runned(evaled) well and get the right final mAP value as below:
![image](https://user-images.githubusercontent.com/34357479/78754044-66d6ab80-79a9-11ea-83da-7769f033865f.png)

So I feel the bugs are related to the transforming phase.

**Comment by LucasSloan** [comment]
I have a similar issue when finetuning on  a custom dataset - all my APs are -1.0

```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
INFO:tensorflow:Finished evaluation at 2020-04-07-21:55:48
I0407 21:55:48.156980 140232971831104 evaluation.py:275] Finished evaluation at 2020-04-07-21:55:48
INFO:tensorflow:Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
I0407 21:55:48.157216 140232971831104 estimator.py:2049] Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
I0407 21:55:49.042325 140232971831104 estimator.py:2109] Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
INFO:tensorflow:evaluation_loop marked as finished
I0407 21:55:49.042971 140232971831104 error_handling.py:101] evaluation_loop marked as finished
I0407 21:55:49.043061 140232971831104 main.py:380] Evaluation results: {'AP': -1.0, 'AP50': -1.0, 'AP75': -1.0, 'APl': -1.0, 'APm': -1.0, 'APs': -1.0, 'ARl': -1.0, 'ARm': -1.0, 'ARmax1': -1.0, 'ARmax10': -1.0, 'ARmax100': -1.0, 'ARs': -1.0, 'box_loss': 0.0141728725, 'cls_loss': 1.7812426, 'loss': 2.5827844, 'global_step': 9500}
```

**Comment by qtw1998** [comment]
> I have a similar issue when finetuning on a custom dataset - all my APs are -1.0
> 
> ```
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> INFO:tensorflow:Finished evaluation at 2020-04-07-21:55:48
> I0407 21:55:48.156980 140232971831104 evaluation.py:275] Finished evaluation at 2020-04-07-21:55:48
> INFO:tensorflow:Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
> I0407 21:55:48.157216 140232971831104 estimator.py:2049] Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
> INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
> I0407 21:55:49.042325 140232971831104 estimator.py:2109] Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
> INFO:tensorflow:evaluation_loop marked as finished
> I0407 21:55:49.042971 140232971831104 error_handling.py:101] evaluation_loop marked as finished
> I0407 21:55:49.043061 140232971831104 main.py:380] Evaluation results: {'AP': -1.0, 'AP50': -1.0, 'AP75': -1.0, 'APl': -1.0, 'APm': -1.0, 'APs': -1.0, 'ARl': -1.0, 'ARm': -1.0, 'ARmax1': -1.0, 'ARmax10': -1.0, 'ARmax100': -1.0, 'ARs': -1.0, 'box_loss': 0.0141728725, 'cls_loss': 1.7812426, 'loss': 2.5827844, 'global_step': 9500}
> ```

yeah man, I've tried several methods to re-convert the tfrecord again and again. No way to solve it.

**Comment by qtw1998** [comment]
> I have a similar issue when finetuning on a custom dataset - all my APs are -1.0
> 
> ```
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> INFO:tensorflow:Finished evaluation at 2020-04-07-21:55:48
> I0407 21:55:48.156980 140232971831104 evaluation.py:275] Finished evaluation at 2020-04-07-21:55:48
> INFO:tensorflow:Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
> I0407 21:55:48.157216 140232971831104 estimator.py:2049] Saving dict for global step 9500: AP = -1.0, AP50 = -1.0, AP75 = -1.0, APl = -1.0, APm = -1.0, APs = -1.0, ARl = -1.0, ARm = -1.0, ARmax1 = -1.0, ARmax10 = -1.0, ARmax100 = -1.0, ARs = -1.0, box_loss = 0.0141728725, cls_loss = 1.7812426, global_step = 9500, loss = 2.5827844
> INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
> I0407 21:55:49.042325 140232971831104 estimator.py:2109] Saving 'checkpoint_path' summary for global step 9500: /tmp/efficientdet-d0-scratch/model.ckpt-9500
> INFO:tensorflow:evaluation_loop marked as finished
> I0407 21:55:49.042971 140232971831104 error_handling.py:101] evaluation_loop marked as finished
> I0407 21:55:49.043061 140232971831104 main.py:380] Evaluation results: {'AP': -1.0, 'AP50': -1.0, 'AP75': -1.0, 'APl': -1.0, 'APm': -1.0, 'APs': -1.0, 'ARl': -1.0, 'ARm': -1.0, 'ARmax1': -1.0, 'ARmax10': -1.0, 'ARmax100': -1.0, 'ARs': -1.0, 'box_loss': 0.0141728725, 'cls_loss': 1.7812426, 'loss': 2.5827844, 'global_step': 9500}
> ```

I'm gonna transform the JSON into COCO JSON element-wise tantamount. Hoping it makes sense.🤯

**Comment by mingxingtan** [comment]
It turns out that COCO requires all box_annotaiotn ids unique across images, and my previous script generate local annotation ids for each image.
https://github.com/google/automl/commit/39bbf8d273eef1b5ec24e5ecaae907f1435313fc should fix the issue.

I have verified that if rerun the tutorial, AP would not be -1 anymore.

**Comment by mingxingtan** [comment]
I am closing this issue. If you still have problems, feel free to add comments in https://github.com/google/automl/issues/94. Thanks!
