### ISSUE TITLE
2020-04-07 12:03:39.487637: W tensorflow/core/grappler/utils/graph_view.cc:830] No registered 'swish_f32' OpKernel for GPU devices compatible with node {{node class_net/swish_f32_14}}

### ISSUE THREAD

**Issue by YangZhang-mizzou** [google/automl#171]
After this warning, an error occurs. 

ERROR:tensorflow:Error recorded from training_loop:  assertion failed: [184]
	 [[{{node parser/Assert/Assert}}]]
	 [[IteratorGetNext]]
E0407 12:03:50.291949 140331795113792 error_handling.py:75] Error recorded from training_loop:  assertion failed: [184]
	 [[{{node parser/Assert/Assert}}]]
	 [[IteratorGetNext]]
INFO:tensorflow:training_loop marked as finished
I0407 12:03:50.292203 140331795113792 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0407 12:03:50.292300 140331795113792 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/yangzhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/yangzhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/yangzhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map__dataset_parser_1040}} assertion failed: [184]
	 [[{{node parser/Assert/Assert}}]]
	 [[IteratorGetNext]]

Has anyone met this error before?

**Comment by YangZhang-mizzou** [comment]
tensorflow-gpu 2.0.0
cuda 10.0
cudnn 7.6.5

**Comment by amr4i** [comment]
I am getting the same error when i try to run Efficient-d7

cuda 10.1
tf-gpu 2.0.0

**Comment by mingxingtan** [comment]
Can you  help try to change this line to "relu_fn = lambda x: x * tf.sigmoid(x)":
https://github.com/google/automl/blob/fe439281c367b742dc2358fa9d13c55991b7dfda/efficientdet/utils.py#L31
