### ISSUE TITLE
creating new tf records w/ create_coco_tfrecord.py after making param mistake = DuplicateFlagError, have to reset

### ISSUE THREAD

**Issue by lessw2020** [google/automl#175]
hi - I'm using the dataset/create_coco_tfrecord.py to make the relevant tfrecords for training.  It works as expected but if you happen to make a param mistake, and then attempt to re-run with corrected params, you hit this 'duplicate flag error'.  
Is there a quick way to clear the flag to run w/o having to reset the kernel?  

error:
'''

DuplicateFlagError                        Traceback (most recent call last)
/content/efficientdet/dataset/create_coco_tfrecord.py in <module>()
     46 
     47 flags.DEFINE_boolean(
---> 48     'include_masks', False, 'Whether to include instance segmentations masks '
     49     '(PNG encoded) in the result. default: False.')
     50 flags.DEFINE_string('image_dir', '', 'Directory containing images.')

2 frames
/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in __setitem__(self, name, flag)
    428         # module is simply being imported a subsequent time.
    429         return
--> 430       raise _exceptions.DuplicateFlagError.from_flag(name, self)
    431     short_name = flag.short_name
    432     # If a new flag overrides an old one, we need to cleanup the old flag's

DuplicateFlagError: The flag 'include_masks' is defined twice. First from create_coco_tfrecord.py, Second from create_coco_tfrecord.py.  Description from first occurrence: Whether to include instance segmentations masks (PNG encoded) in the result. default: False.
'''
I'll try and figure this out directly but if there's a known tip here to reset the relevant flags quickly, would appreciate it!
Thanks

**Comment by lessw2020** [comment]
actually if you just run it twice - in my case, once for making valid, then for making training...you'll hit the same issue (duplicate flag).

I see you can del the flags via a tf call so I'll see if I can make a script to clear these and post.  
Using a clear all messes up something for python pdb, a global delete of flags isn't suitable.

**Comment by lessw2020** [comment]
basic clearing of flags:
```

tf_coco_keys=["include_masks",
"image_dir",
"image_info_file",
"object_annotations_file",
"caption_annotations_file",
"output_file_prefix",
"num_shards"]

flags_dict = FLAGS._flags()
keys_list = tf_coco_keys
for keys in keys_list:
      FLAGS.__delattr__(keys)
```
if you clear all flags it destroys a global post mortem pdb...so testing the above now.

**Comment by lessw2020** [comment]
ok verified running the above fixes it!  
should probably be a flag or check to handle this automatically but worst case at least now we can rapidly clear even in a notebook and make val and train successively.

**Comment by mingxingtan** [comment]
Do you have command lines to reproduce the issues?

**Comment by lessw2020** [comment]
sure - I'm running inside colab in case that affects it.  If I run this:
`%run create_coco_tfrecord.py --image_dir=uw/images/train --object_annotations_file=uw/annotations/instances_train.json --output_file_prefix=tfrecord/train --num_shards=2`

and then this:
`%run create_coco_tfrecord.py --image_dir=uw/images/valid --object_annotations_file=uw/annotations/instances_valid.json --output_file_prefix=tfrecord/valid2 --num_shards=2`

I will hit the DuplicateFlagError.

**Comment by lessw2020** [comment]
note if you shell it out ala the readme style then the flag issue is avoided.
`!mkdir tfrecord
!PYTHONPATH=".:$PYTHONPATH"  python dataset/create_coco_tfrecord.py \
    --image_dir=val2017 \
    --caption_annotations_file=annotations/captions_val2017.json \
    --output_file_prefix=tfrecord/val \
    --num_shards=32
`
Anyway at least this is minor now at this point since the the diff is just if you use %run vs !cmd syntax.
