### ISSUE TITLE
Readme has error between file downloaded and sample inference (and can't get file to load in 2.2..)

### ISSUE THREAD

**Issue by lessw2020** [google/automl#180]
Hi - an easy typo on the homepage readme:

Section 3 - run inference uses the file img.png to download:
`!wget https://user-images.githubusercontent.com/11736571/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png -o **img.png**
`

However for inference, the command listed is for *img.jpg* which is not what was downloaded:
`# Run inference.
!python model_inspect.py --runmode=infer --model_name=$MODEL \
  --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --ckpt_path=$CKPT_PATH --input_image=**img.jpg** --output_image_dir=/tmp
 you can visualize the output /tmp/0.jpg

Beyond that though I can't get the file to load regardless as the inference.py always errs out.  I swapped in a .jpg incase it was a png not supported, manually updated the file open call,, etc. and can't get it to load.  
here's the error stack:
`WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-04-08 04:58:44.886463: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
where are we?? /content/automl/efficientdet
file to load ./img1.jpg
Traceback (most recent call last):
  File "model_inspect.py", line 376, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 370, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 342, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 220, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/content/automl/efficientdet/inference.py", line 535, in inference
    params['image_size'])
  File "/content/automl/efficientdet/inference.py", line 95, in build_inputs
    image = Image.open(f) #'/content/automl/efficientdet/img1.jpg')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file './img1.jpg'`

and inference call:
`!python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \
  --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --ckpt_path=efficientdet-d0 --input_image=img1.jpg --output_image_dir=/tfrecord`

that said, even just trying to open the image by hand in colab with PIL fails with the same issue:
`image = Image.open('img1.jpg')`
fails with:
`UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-77-9acab0993c1c> in <module>()
----> 1 image = Image.open('img1.jpg')

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2860         warnings.warn(message)
   2861     raise UnidentifiedImageError(
-> 2862         "cannot identify image file %r" % (filename if filename else fp)
   2863     )
   2864 

UnidentifiedImageError: cannot identify image file 'img1.jpg'`

it's enough to make me want to go right back to pytorch where things like this don't happen lol.  
I'll look into why PIL can't even open the image in colab tomorrow as I really want to get efficientdet official working (it's an awesome detector btw :)  but might be worth updating the readme so pure cut and paste works right out of the box. 
`

**Comment by lessw2020** [comment]
update - if I manually upload an image to colab,, Image.open works perfectly.
So I suspect wget is somehow mucking with it during the save?

**Comment by lessw2020** [comment]
ah at last - inference works great once I upload the photo instead of using wget :)
no idea what colab  or wget is doing to modify the image when pulled.

**Comment by mingxingtan** [comment]
You just need to change the --input_image=img.jpg  to --input_image=img.png
Fix on the way.
