### ISSUE TITLE
'image_id'(such as 10236529664) from PoseTrack dataset became different from the original 'image_id' after string encode and decode operations.

### ISSUE THREAD

**Issue by xiong-peng** [google/automl#182]

**Comment by qtw1998** [comment]
When eval error related？

**Comment by mingxingtan** [comment]
Yeah, 10236529664 is a large value, and internally we convert it to a float value and then to int value. Maybe you can use the same way as this:

https://github.com/google/automl/blob/5804815148b872c6afc63ccd234d27fa3f20c9c6/efficientdet/dataset/create_pascal_tfrecord.py#L69

**Comment by xiong-peng** [comment]
@mingxingtan emmm...I used 'tfrecord_util.int64_feature' to encode the large image_id, and **I got the correct decoding image_id(in my own test code)**. Still fail to get correct in the coco coding format, why??? My testing code is as following:
`    
for image_id in posetrack_img_id:
        feature_dict = {
            'source_id':
                tfrecord_util.int64_feature(image_id)}
        example = tf.train.Example(features=tf.train.Features(feature=feature_dict))
        example = example.SerializeToString()
        parsed_tensors = tf.io.parse_single_example(
            example, {'source_id': tf.FixedLenFeature((), tf.int64)})
        source_id = parsed_tensors['source_id']
        print(image_id)
        res = sess.run([source_id])
        print(int(res[0]))
        print('-------------------------')
        if not int(res[0]) == image_id:
            exit(1)
`
