### ISSUE TITLE
Box/class net

### ISSUE THREAD

**Issue by dkoguciuk** [google/automl#183]
Hi @mingxingtan ,

I have a question about the design of the box/class net. In the article it's shown like this:

![Screenshot from 2020-04-08 18-08-33](https://user-images.githubusercontent.com/9368849/78807196-043ed900-79c4-11ea-9038-050aad17cc24.png)

This suggests that convolutions are shared between different layers of the BiFPN pyramid, but in the code each layer has it's own classification and prediction net. Is the picture a bit misleading or I am missing something?

**Comment by mingxingtan** [comment]
Excellent question, @dkoguciuk !

It is a little more complicated: all BiFPN layers share the same convs class/box layers, but they use different BNs:
https://github.com/google/automl/blob/fe439281c367b742dc2358fa9d13c55991b7dfda/efficientdet/efficientdet_arch.py#L231
https://github.com/google/automl/blob/fe439281c367b742dc2358fa9d13c55991b7dfda/efficientdet/efficientdet_arch.py#L237

conv name is "box-%d" % i is the same for different levels,  batch norm name is "box-%d-bn-%d" % (i, level) is different for each level.

You can look at the graph (in tutorial) to see how box/class networks are shared.

**Comment by dkoguciuk** [comment]
Ah, right! Thanks @mingxingtan!
