### ISSUE TITLE
file split for annotations - main.py only has a flag for --valid_json_file but nothing for --train?

### ISSUE THREAD

**Issue by lessw2020** [google/automl#186]
Hi - I'm confused why in main.py there is only a flag for a --val_json_file but not one for a --train_json_file? 
I don't see any handling in the code for a seperate train/val files so are we expected to put all the annotations for bboxes (train and val) into a single json file instead of the usual split of instances_train.json and instances_valid.json?
Thanks

`!python main.py --mode=train_and_eval \
    --num_classes=6 \
    --training_file_pattern=tfrecord/train*.tfrecord \
    --validation_file_pattern=tfrecord/valid*.tfrecord \
    --val_json_file=tfrecord/annotation/instances_valid.json \
    --model_name=efficientdet-d1 \
    --model_dir=/tmp/efficientdet-d1-scratch  \`

**Comment by ESCEBT** [comment]
i have the same question, i guess it validate by json but train by tfrecord files

**Comment by mingxingtan** [comment]
You don't need json for train. the json file is needed for eval because the pycocotools need the json file for eval AP.

**Comment by lessw2020** [comment]
Hi @mingxingtan  - thanks for confirming.  Are the bounding boxes added into the tfrecords and thus no need for the train.json file?  (i.e. how is it otherwise calculating losses at the end of each training batch?)
Thanks very much for all your help here!

**Comment by lessw2020** [comment]
ok it's clear the bboxes are getting pulled into the tfrecords.  
The confusion for me was why a val.json would be needed if that was the case (i.e. should be all images need a matching json or none...not val only).
However, this commit an hour ago removes the need for specifying the val.json file so it's now symmetric.
I'll close this issue then - link to the commit:  https://github.com/google/automl/commit/6048346978639ed982ca1193f4b36366cd5ea2a8
and related:
https://github.com/google/automl/issues/187
