### ISSUE TITLE
val_json_file is not required

### ISSUE THREAD

**Issue by fsx950223** [google/automl#187]
https://github.com/google/automl/blob/5804815148b872c6afc63ccd234d27fa3f20c9c6/efficientdet/main.py#L138
Eval could run benchmark without val_json_file.
https://github.com/google/automl/blob/5804815148b872c6afc63ccd234d27fa3f20c9c6/efficientdet/coco_metric.py#L53-L55
and you could try ```--eval_after_training``` argument in train mode

**Comment by mingxingtan** [comment]
Excellent! I forgot the val is optional. Commit on the way to remove the check in main file.

Thanks a lot, @fsx950223
