### ISSUE TITLE
option to do eval inference on 'x' images with best checkpoint as a 'show_results' type visual grid?

### ISSUE THREAD

**Issue by lessw2020** [google/automl#191]
Hi - is there any plans to add (or something I'm not aware of) to quickly run some images from the best checkpoint eval batch to 'see' the training results?  
i.e. seeing the loss numbers is useful but ultimately need to see how the bounding boxes are looking compared to gt boxes to get a better feel for training.
I realize I could just setup some code to do inference on X images at end of training and display, but wanted to make sure I'm not overlooking this equivalent already or something that is pending.
Thanks

**Comment by mingxingtan** [comment]
Related to #396
