### ISSUE TITLE
Training losses fluctuate and don't converge

### ISSUE THREAD

**Issue by htx-DeepLearning** [google/automl#196]
After I run the main.py, the training losses fluctuate and don't converge. As showed in the following: 
![image](https://user-images.githubusercontent.com/51436385/78876786-71b13f00-7a82-11ea-9a64-438b23472b3d.png)
I follow the instructions by steps:
1. I convert coco val2017 dataset to tfrecord by commond:
`python dataset/create_coco_tfrecord.py \
    --image_dir=./data/coco/val2017 \
    --caption_annotations_file=./data/coco/annotations/instances_val2017.json \
    --output_file_prefix=./data/coco/tfrecord \
    --num_shards=100`
2. And I also change the hyperparameters in hparams_config.py
`h.learning_rate =0.08-->= 0.001`
`h.lr_warmup_init =0.008--> =0.0001`
3. I have tried to train the whole model by
`python main.py --training_file_pattern=./data/coco/tfrecord/-000* --model_name=efficientdet-d4 --model_dir=./logs/ --hparams="use_bfloat16=false,num_classes=90,moving_average_decay=0" --use_tpu=False --backbone_ckpt=./pretrained/efficientnet-b4/ --train_batch_size=1`
and I have also tried to fine tune the model by 
`python main.py --training_file_pattern=./data/coco/tfrecord/-000* --model_name=efficientdet-d4 --model_dir=./logs hparams="use_bfloat16=false,num_classes=90," --use_tpu=False  --ckpt=./pretrained/efficientdet-d4 --train_batch_size=1`

Training losses seem to fluctuate over time, does anybody know the reason?

**Comment by YinRui1991** [comment]
Because you set train_batch_size=1. And it seems you use coco val2017 for training.
