### ISSUE TITLE
After finetuned I got the new ckpt under the 'archive' directory, but I cannot load them when running model_inspect.py , why???

### ISSUE THREAD

**Issue by xiong-peng** [google/automl#200]
Traceback (most recent call last):
  File "model_inspect.py", line 378, in <module>
    tf.app.run(main)
  File "/home/.local/lib/python3.5/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/.local/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/.local/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 372, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 344, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 220, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/home/peng/code/efficientdet/inference.py", line 502, in inference
    restore_ckpt(sess, self.ckpt_path, enable_ema=True, export_ckpt=None)
  File "/home/peng/code/efficientdet/inference.py", line 134, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/home/.local/lib/python3.5/site-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by mingxingtan** [comment]
What's your command line?  The error says your ckpt_path is None.

**Comment by xiong-peng** [comment]
@mingxingtan 
python model_inspect.py --runmode=infer --model_name=$MODEL   --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2   --ckpt_path=models/efficientdet-d4-PoseTrack/archive --input_image=./testdata/img.jpg --output_image_dir=./testdata

**Comment by mingxingtan** [comment]
Can you double check what files are in models/efficientdet-d4-PoseTrack/archive/ ?

BTW, usually you shouldn't specify input_image_size=1920, better to use the same image size unless you have a very large image.

**Comment by xiong-peng** [comment]
Parsing Inputs...
Parsing Inputs...
models/efficientdet-d4-PoseTrack/archive
ERROR:tensorflow:Couldn't match files for checkpoint models/efficientdet-d4-PoseTrack/archive/../../../model.ckpt-83250 ??

**Comment by xiong-peng** [comment]
![image](https://user-images.githubusercontent.com/28092337/78963788-19824780-7b2b-11ea-8dc2-05c87492fc12.png)

**Comment by airqj** [comment]
same problem
change "model_checkpoint_path" to the checkpoint location  in models/efficientdet-d4-PoseTrack/archive/checkpoint

and it works

**Comment by xiong-peng** [comment]
@airqj thanks,bro!!!

**Comment by mingxingtan** [comment]
There was a bug when using relative path.  The bug is fixed in https://github.com/google/automl/commit/8e9d432adb1b84f2ea789bec18e1fcc79df8e743

**Comment by adarsh0906** [comment]
i  have same issue i tried to train the pretrained model d1 for detecting vehicle class for my own dataset but i used colab to train after 10hrs of training i downloaded  all files in the model when i tried to open it with following command 

python model_inspect.py --runmode=saved_model --model_name=efficientdet-d1 --ckpt_path=Model --saved_model_dir=Model/savedmodel

i get the same error as mentioned above
