### ISSUE TITLE
Generation of tfrecord for custom dataset

### ISSUE THREAD

**Issue by pentapatisivani** [google/automl#209]
I want to train my model for custom dataset. In the dataset folder there are only conversion scripts to convert VOC or COCO into tfrecord. How can I proceed further?
Also main.py (the main code used to train has a json input, If I am using other converters to generate tfrecord, how can I generate the json file which fits in the format required for training?

**Comment by gtgtgt1117** [comment]
> I want to train my model for custom dataset. In the dataset folder there are only conversion scripts to convert VOC or COCO into tfrecord. How can I proceed further?
> Also main.py (the main code used to train has a json input, If I am using other converters to generate tfrecord, how can I generate the json file which fits in the format required for training?

你可以把你的数据转换成voc或coco的格式，再转为tfrecord

**Comment by mingxingtan** [comment]
Hi @pentapatisivani I have updated the main file a few days ago, you don't need json file anymore (https://github.com/google/automl/commit/6048346978639ed982ca1193f4b36366cd5ea2a8)

**Comment by pentapatisivani** [comment]
@mingxingtan thanks for the update! Also the in create_pascal_tfrecord.py the label dictionary and the  examples_path is hardcoded for pascal voc dataset so custom data in VOC format cannot be directly used with the script to generate the tfrecord. If we are supposed to make changes what all are the places in the code where we should make changes to support our data?
(Because my custom dataset doesnt have aeroplane_train.txt so it is throwing an error that there is no such file)
![Screenshot from 2020-04-11 22-45-34](https://user-images.githubusercontent.com/32356876/79050282-9a823180-7c46-11ea-9583-91f4ee3e0490.png)

**Comment by Paarth3098** [comment]
@mingxingtan Can you please tell us in detail how to use your code for custom datasets.

**Comment by GotG** [comment]
Is this still necessary?  
 `--val_json_file=tfrecord/json_pascal.json`
If so, why? Also the tutorial example uses the entire Pascal dataset in this json for validation.

**Comment by angryhen** [comment]
> @mingxingtan感谢您的更新！同样在create_pascal_tfrecord.py标签字典中，并且为pascal voc数据集对examples_path进行了硬编码，因此VOC格式的自定义数据不能直接与脚本一起使用来生成tfrecord。如果我们应该进行更改，那么代码中应该在哪些地方进行更改以支持数据？
> （因为我的自定义数据集没有aeroplane_train.txt，所以抛出了一个错误，即没有这样的文件）
> ![2020-04-11 22-45-34的屏幕截图](https://user-images.githubusercontent.com/32356876/79050282-9a823180-7c46-11ea-9583-91f4ee3e0490.png)

hi，
I got the same problem, how did you solve it?

**Comment by pentapatisivani** [comment]
The script which they gave is specifically meant to convert data in VOC format to tfrecord. (Hardcoded for classes corresponding to VOC dataset) that might not work for all other cases so write your own script to convert data into tfrecord which is in the similar fomat as that of the one given in script
