### ISSUE TITLE
ExponentialMovingAverage not found in checkpoint

### ISSUE THREAD

**Issue by betterhalfwzm** [google/automl#214]
python main.py --mode=eval  \
    --model_name=efficientdet-d0  --model_dir=tmp/  \
    --validation_file_pattern=tfrecord/val*  \
    --val_json_file=annotations/instances_val2017.json  \
    --hparams="use_bfloat16=false" --use_tpu=False

Error recorded from evaluation_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at /home/wangzhaoming/work_code/automl/efficientdet/det_model_fn.py:577) ]]

**Comment by klyjm** [comment]
I have the same error. I think maybe it is because the enable_ema?But I haven't found this flag in main.py......

**Comment by mingxingtan** [comment]
Look slike your ckpt point is under tmp/. Did you train your model? If so, could you paste your training command?

In general, your training time hparams should be the same as eval time hparams.

**Comment by klyjm** [comment]
No, I just use the original d0 ckpt. When I train the model with hparam which is not moving_average_decay=0, there will be this error.-------- 原始邮件 --------发件人： Mingxing Tan <notifications@github.com>日期： 2020年4月13日周一 04:00收件人： google/automl <automl@noreply.github.com>抄送： klyjm <519812260@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [google/automl] ExponentialMovingAverage not found in checkpoint (#214)
Look slike your ckpt point is under tmp/. Did you train your model? If so, could you paste your training command?
In general, your training time hparams should be the same as eval time hparams.

**Comment by mingxingtan** [comment]
I just tried in tutorial colab and it worked well.
If you download the official checkpoint, should model_dir be "tmp/efficientdet-d0" instead of "tmp/"?

**Comment by klyjm** [comment]
Emmmm, I store the ckpt not like the questioner, I store it in home dir and use the absolutly path just like '/home/xxx/effiecientdet-d0'. But I think maybe it has nothing to do with model_dir?Because if I set the hparam moving_average_decay=0, there will be no error.

**Comment by mingxingtan** [comment]
The official checkpoints do have ema variables.  Maybe you can start from a clean environment?

**Comment by klyjm** [comment]
I just delete everything in the model dir and try it again, it is useful. Why? If there are ckpts in the model_dir, tf will read ckpt from --model_dir instead of --ckpt?

**Comment by mingxingtan** [comment]
yes, --ckpt is only used for initializing the model (before running any training), --model_dir is the actually model folder. If there are any checkpoints in model_dir, then it means your model has been trained for some steps, so --ckpt is ignored.

Maybe I should rename --ckpt to --init_ckpt or --pretrained_ckpt.

**Comment by betterhalfwzm** [comment]
Sorry, I just received your reply. When i training，i set moving_average_decay=0, but when i eval, i set 
set moving_average_decay=0 is not useful, i must change it in hparams_config.py and how change moving_average_decay in the training is the best?
