### ISSUE TITLE
inference, error

### ISSUE THREAD

**Issue by slience-ops** [google/automl#217]
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_979]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

**Comment by WonTaeYeon** [comment]
It is probably a problem with the ckpt path. Can you show the command you entered?

**Comment by slience-ops** [comment]
why ckpt file not contain this node? I train with examples. 
python main.py --mode=train_and_eval   --training_file_pattern=tfrecord/pascal*.tfrecord  --validation_file_pattern=tfrecord/pascal*.tfrecord  --val_json_file=tfrecord/json_pascal.json  --model_name=efficientdet-d0  --model_dir=/tmp/efficientdet-d0-scratch  --backbone_ckpt=images/efficientnet-b0  --train_batch_size=4  --eval_batch_size=4 --eval_samples=512  --num_examples_per_epoch=1000 --num_epochs=1   --hparams="use_bfloat16=false,num_classes=20,moving_average_decay=0"   --use_tpu=False

**Comment by slience-ops** [comment]
python model_inspect.py --runmode=infer --model_name=efficientdet-d0  --input_image_size=1920 --max_boxes_to_draw=200   --min_score_thresh=0.2   --ckpt_path=**C:\tmp\efficientdet-d0-scratch\archive** --input_image=testdata/img.png --output_image_dir=/tmp

**Comment by WonTaeYeon** [comment]
@slience-ops 
so ...
train_and_eval:
Are there any model files in the efficientnet-b0 directory that is the backbone network (without file damage)?
infer:
Are you sure of the ckpt path?
It is necessary to make sure that the path is loaded properly and that the model is correctly in the path.

**Comment by slience-ops** [comment]
# Download backbone checkopints.
!wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz
train_and_eval: 
the backbone network from [efficientnet-b0.tar.gz].file is ok
infer:
ckpt path is right.

**Comment by slience-ops** [comment]
inference.py: 
def restore_ckpt(sess, ckpt_path, enable_ema=Ture, export_ckpt=None):
mend:
def restore_ckpt(sess, ckpt_path, enable_ema=False, export_ckpt=None):
other:
Between differences set enable_ema Ture Or false?
