### ISSUE TITLE
Between differences set enable_ema Ture Or false?

### ISSUE THREAD

**Issue by slience-ops** [google/automl#226]

**Comment by mingxingtan** [comment]
https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage

Let's say you have a model with trainable variable x. If you train the model with ema, then you will have two variables x and x_ema in the graph.
At eval time, if you set enable_ema=True, then you will load checkpoint[x_ema] into x and use x to do eval;
if you set enable_ema=False, then you will load checkpoint[x] into x.

**Comment by slience-ops** [comment]
if trian set enable_ema=True,then eval ,set enable_ema=false,but still report error,
：Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
so,trian set enable_ema=False,eval set enable_ema=false
