### ISSUE TITLE
I cann't get the result as the paper shows

### ISSUE THREAD

**Issue by weichen456** [google/automl#227]
I trained the efficientdet-d1 in TPU v3-8 
detail like this：
batch size=64 hparams= h.momentum = 0.9
  h.learning_rate = 0.08
  h.lr_warmup_init = 0.008
  h.lr_warmup_epoch = 1.0
  h.first_lr_drop_epoch = 200.0
  h.second_lr_drop_epoch = 250.0
  h.clip_gradients_norm = 10.0
  h.num_epochs = 300
 the hparams is default parameters in hparams_config.py
 
this is my result:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.272
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.434
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.289
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.121
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.310
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.383
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.262
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.418
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.444
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.208
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.509
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.630
Please tell what is the problem， thanks a lot。

**Comment by mingxingtan** [comment]
Hmm, this is strange. Do you still have this issue?
I kicked off a training job (D0 on a TPUv3_8) a few hours ago and it already reached 31.2AP with 40 epochs.

**Comment by mingxingtan** [comment]
Please compare your runs with this tensorboard: https://tensorboard.dev/experiment/4IzZoQyAQLSManQfwaHyyQ/#scalars&_smoothingWeight=0
