### ISSUE TITLE
A wechat communication group

### ISSUE THREAD

**Issue by chunleiml** [google/automl#233]
![image](https://user-images.githubusercontent.com/29543941/79205729-e4e6f680-7e70-11ea-9c00-bf5a697a5871.png)

**Comment by wadewangpower** [comment]
这里也有一个https://github.com/google/automl/issues/151。。。

**Comment by 15241192958** [comment]
您好，能更新一下微信交流群二维码吗？我也想加入

**Comment by chunleiml** [comment]
> 您好，能更新一下微信交流群二维码吗？我也想加入

![image](https://user-images.githubusercontent.com/29543941/80072513-ec955200-8578-11ea-9bf7-8b51e7df6273.png)
你好，已经更新了

**Comment by fsx950223** [comment]
Out of date

**Comment by elv-xuwen** [comment]
@chunleiml 你好，可以重新分享一下吗？
