### ISSUE TITLE
Got an error when Inference with custom train checkpoint

### ISSUE THREAD

**Issue by yuuzaki** [google/automl#236]
InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
2 root error(s) found.
  (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,112,810] rhs shape= [1,1,112,9]
	 [[node save/Assign_143 (defined at C:\Users\User\Ipynb\PROJECT_DEEP\automl\efficientdet\inference.py:143) ]]
	 [[save/RestoreV2/_960]]
  (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,112,810] rhs shape= [1,1,112,9]
	 [[node save/Assign_143 (defined at C:\Users\User\Ipynb\PROJECT_DEEP\automl\efficientdet\inference.py:143) ]]
0 successful operations.
0 derived errors ignored.
![image](https://user-images.githubusercontent.com/63689054/79291382-b876bd00-7ef8-11ea-82e2-13dccac6a0d3.png)

**Comment by airqj** [comment]
add --num_classes to your command line

**Comment by yuuzaki** [comment]
> add --num_classes to your command line

thanks for you reply!
