### ISSUE TITLE
question about drop conect

### ISSUE THREAD

**Issue by hanguniverse** [google/automl#237]
hello

I saw drop connect was used in EfficientNet, do you use it in EfficientDet.  Survival prob seems to be None in hparams config.

**Comment by mingxingtan** [comment]
Hi @hanguniverse, we don't use drop connect for FPN, but  the backbone is not changed (still using the same drop connect as what is used for ImageNet training).

**Comment by zzzxxxttt** [comment]
Hi @mingxingtan , I have the same question, in your code there is
```
  # No stochastic depth in default.
  h.survival_prob = None
```
does it mean you don't use drop connect during training for all the EfficientDet models?

**Comment by mingxingtan** [comment]
Yeah, I should rename this as fpn_survival_prob and update the comment: no stochastic depth for FPN.
The backbone is the same as what it does for imagenet training (using 0.8 survival_prob)

**Comment by zzzxxxttt** [comment]
OK, thanks for your reply!

**Comment by hanguniverse** [comment]
Thanks！
