### ISSUE TITLE
Is there a difference between TPUEstimator and Estimator in Train?

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#244]
Thx for your code.

I am training a model on GPU on Local Computer.

In the code, even if USE_TPU = False, it will work in TPUEstimator.

I am wondering if this alone makes TPUEstimator the same as tf.estimator or what difference exists.

**Comment by mingxingtan** [comment]
Yeah, they are mostly the same now, but they used to have slightly different APIs: https://cloud.google.com/tpu/docs/tutorials/migrating-to-tpuestimator-api
