### ISSUE TITLE
Logical bug in create_pascal_tfrecord.py

### ISSUE THREAD

**Issue by Xiaokeai18** [google/automl#253]
Hello, thank you for your repo, this helps me a lot.  
When I try to train_and_eval in custom dataset (e.g. Pascal VOC), I use the script create_pascal_tfrecord.py to generate TFRecord examples, and then got an error while evaling.

> AssertionError: Results do not correspond to current coco set  

As you have said in  https://github.com/google/automl/issues/154#issuecomment-609896333  that this error usually caused by  the source_id in tfrecord doesn't match those in json file.  It confused me that I have used the latest branch of the repo.  

Finally I found the cause of this issue, that there's a logical bug in line 235 of create_pascal_tfrecord.py.
https://github.com/google/automl/blob/0397c60e9694116fca4d53730a676d99a77ec9de/efficientdet/dataset/create_pascal_tfrecord.py#L235  

The statement of dicr 'ann_json_dict' is in the for loop, **which my cause en error** the if you set the param 'year' equals 'merged', and this for loop may loop VOC2007 and VOC2012, when it get into the loop second time, **the data in ann_json_dict may get lost**. Thus, it result in the error of 'Results do not correspond to current coco set '

And it should be changed into the following, **just move out of the for loop**,and it works after my test:  
```python
  ann_json_dict = {
      'images': [],
      'type': 'instances',
      'annotations': [],
      'categories': []
  }
  for year in years:
    ...
```

best wishes

**Comment by mingxingtan** [comment]
@Xiaokeai18 Thanks a lot for pointing out this issue. I just fix it in https://github.com/google/automl/commit/53f3c2a3636e6b3ea41b0b2414a0dffc4318e893

FYI, we recently also add a support to make json file optional, so if you use create_pascal_tfrecord to create tfrecord files, then you don't need that json file anymore.
