### ISSUE TITLE
export model AttributeError

### ISSUE THREAD

**Issue by czy112** [google/automl#254]
运行命令python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=E:/efficientnet/efficientdet-d0/ --input_image_size=1920x1280 --max_boxes_to_draw=100   --min_score_thresh=0.2  --saved_model_dir=E:/efficientnet/efficientdet-d0/saved_model

报错：
AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'
请问有人知道怎么做吗？

**Comment by fsx950223** [comment]
upgrade your tensorflow

**Comment by gtgtgt1117** [comment]
> upgrade your tensorflow


AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'repeat'
这个呢

**Comment by gtgtgt1117** [comment]
> 运行命令python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=E:/efficientnet/efficientdet-d0/ --input_image_size=1920x1280 --max_boxes_to_draw=100 --min_score_thresh=0.2 --saved_model_dir=E:/efficientnet/efficientdet-d0/saved_model
> 
> 报错：
> AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'
> 请问有人知道怎么做吗？


请问一下你的tensorflow是什么版本呀

**Comment by czy112** [comment]
> > 运行命令python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=E:/efficientnet/efficientdet-d0/ --input_image_size=1920x1280 --max_boxes_to_draw=100 --min_score_thresh=0.2 --saved_model_dir=E:/efficientnet/efficientdet-d0/saved_model
> > 报错：
> > AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'
> > 请问有人知道怎么做吗？
> 
> 请问一下你的tensorflow是什么版本呀

tf-gpu==1.14

**Comment by gtgtgt1117** [comment]
> > > 运行命令python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=E:/efficientnet/efficientdet-d0/ --input_image_size=1920x1280 --max_boxes_to_draw=100 --min_score_thresh=0.2 --saved_model_dir=E:/efficientnet/efficientdet-d0/saved_model
> > > 报错：
> > > AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'
> > > 请问有人知道怎么做吗？
> > 
> > 
> > 请问一下你的tensorflow是什么版本呀
> 
> tf-gpu==1.14



那您那个问题解决了吗?

**Comment by gtgtgt1117** [comment]
> upgrade your tensorflow

请问一下,tensorflow版本需要2.0吗?

**Comment by Sean0123456789** [comment]
Anyone can help? 

Tried tf-1.13, 1.14, 2.1, but on one works.

**Comment by tangyan-77** [comment]
> > upgrade your tensorflow
> 
> AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'repeat'
> 这个呢

tensorflow1.15 就正常了
