### ISSUE TITLE
What does argument '--input_image_size' mean?? 

### ISSUE THREAD

**Issue by chohk88** [google/automl#257]
For EfficientDet-D0, whether we use default image size 512x512 or --input_image_size=1920x1280, the performance of inference is very different. 
I don't understand how performance can vary for input image size for fixed detection model. 
In my opinion, if we choose efficientDet-D0 for detection model, we don't need to set the input image size.
It because the input size of efficientDet-D0 is 512x512.
![image](https://user-images.githubusercontent.com/25674295/79549715-4ce84780-80d2-11ea-8bd9-66f74a8b01f3.png)

For your information, these are our results and commands for inference. 
`python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \\n  --input_image_size=1920x1280 --max_boxes_to_draw=100   --min_score_thresh=0.2 \\n  --ckpt_path=efficientdet-d0 --input_image=img.png --output_image_dir=results/
`
![image](https://user-images.githubusercontent.com/25674295/79549210-a734d880-80d1-11ea-8f72-13903a33f5d6.png)

`python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \\n  --max_boxes_to_draw=100   --min_score_thresh=0.2 \\n  --ckpt_path=efficientdet-d0 --input_image=img.png --output_image_dir=results/`

![image](https://user-images.githubusercontent.com/25674295/79549351-d6e3e080-80d1-11ea-9094-d3e055323200.png)

**Comment by fsx950223** [comment]
Bigger input size could get more information.
I haven't seen a detection model could work well with input size is 32 or smaller

**Comment by InfiniteLife** [comment]
It is not fixed in that sense that scripts makes tensorflow  graph for 1920 resolution in one case and 512 in the other, so happens for this image model works best on 1920. What's interesting other models, even big ones do not perform as well as the smallest model d0 on this image.

**Comment by mingxingtan** [comment]
Hi @chohk88, if your image size is reasonably similar to COCO, then you don't need to set image size.

However, for this input image that is very high-resolution 1920x1080, if you still use the default size, the the model would first downsample the image to 512x256 (after padding, become 512x512), which make those small objects very hard to detect (you can manually resize the image to 512x256 and see what blur the image is). Therefore, it is better to use a large resolution in this case.

@InfiniteLife we recommended 1920 because the image itself is 1920 size, but you have a good point: it is unclear why bigger models don't perform much better for this image.

**Comment by chohk88** [comment]
thank you for your comments @mingxingtan @InfiniteLife @fsx950223 
I have one more question.
When the size of the input is different, the size of the output of deep learning network also changes. Is there a layer such as maxpooling at the end of the network? So, can the size of network output be fixed regardless of the input size?

**Comment by InfiniteLife** [comment]
Is it possible to make model work without padding? If meaningful area of
512x512 image is 512x256 then we are loosing a lot in terms of
computational power?

**Comment by mingxingtan** [comment]
Hi @InfiniteLife The current code works with arbitrary image size like 512x256 or 500x300 (see README). However, if you don't specify input_size, then D0 would use 512x512 in default and D1 would use 640x640 in default.

@chohk88 I don't fully understand your question. What's the purpose of keeping the output size fixed?

**Comment by liminghuiv** [comment]
Hi @mingxingtan will it be the same for main.py training or just for inference, I checked main.py, I did not see input_image_size parameter. thanks.

**Comment by mingxingtan** [comment]
@liminghuiv I just added the support, now you can specify something like  hparams="image_size=640x320,use_bfloat16=false" for training or eval.
