### ISSUE TITLE
why the example training_file_pattern and validation_file_pattern  is the same

### ISSUE THREAD

**Issue by amitotcy** [google/automl#259]
In the readme about Train on PASCAL VOC 2012 with backbone ImageNet ckpt.
python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=/tmp/efficientdet-d0-scratch  \
    --backbone_ckpt=efficientnet-b0  \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=512 \
    --num_examples_per_epoch=5717 --num_epochs=1  \
    --hparams="use_bfloat16=false,num_classes=20,moving_average_decay=0" \
    --use_tpu=False 

Why the train and val use the same tfrecord? and what the eval_samples 512 means? Isn't  it the num of validation picture? 
And if I want to train a class not in the 20 classes of voc2012, what should  I do?
I made a class "screw" which is not in the 20 classes of voc2012 and tried the below but the ap is always 0.
python main.py --mode=train_and_eval \
    --training_file_pattern=./mytrain/tfrecord/pascal*.tfrecord \
    --validation_file_pattern=./mytrain/tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=./mytrain  \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=100 \
    --num_examples_per_epoch=200 --num_epochs=100  \
    --hparams="use_bfloat16=false,num_classes=1" \
    --use_tpu=False

please help me ,thank you

**Comment by 15241192958** [comment]
> In the readme about Train on PASCAL VOC 2012 with backbone ImageNet ckpt.
> python main.py --mode=train_and_eval 
> --training_file_pattern=tfrecord/pascal*.tfrecord 
> --validation_file_pattern=tfrecord/pascal*.tfrecord 
> --model_name=efficientdet-d0 
> --model_dir=/tmp/efficientdet-d0-scratch 
> --backbone_ckpt=efficientnet-b0 
> --train_batch_size=8 
> --eval_batch_size=8 --eval_samples=512 
> --num_examples_per_epoch=5717 --num_epochs=1 
> --hparams="use_bfloat16=false,num_classes=20,moving_average_decay=0" 
> --use_tpu=False
> 
> Why the train and val use the same tfrecord? and what the eval_samples 512 means? Isn't it the num of validation picture?
> And if I want to train a class not in the 20 classes of voc2012, what should I do?
> I made a class "screw" which is not in the 20 classes of voc2012 and tried the below but the ap is always 0.
> python main.py --mode=train_and_eval 
> --training_file_pattern=./mytrain/tfrecord/pascal*.tfrecord 
> --validation_file_pattern=./mytrain/tfrecord/pascal*.tfrecord 
> --model_name=efficientdet-d0 
> --model_dir=./mytrain 
> --train_batch_size=8 
> --eval_batch_size=8 --eval_samples=100 
> --num_examples_per_epoch=200 --num_epochs=100 
> --hparams="use_bfloat16=false,num_classes=1" 
> --use_tpu=False
> 
> please help me ,thank you

same question，have you resolved?

**Comment by mingxingtan** [comment]
> Why the train and val use the same tfrecord? and what the eval_samples 512 means? Isn't it the num of validation picture?

You should use separate train and eval set. These instructions are mostly copied from tutorial, which uses the same set to save some time for downloading data.

> And if I want to train a class not in the 20 classes of voc2012, what should I do? I made a class "screw" which is not in the 20 classes of voc2012 and tried the below but the ap is always 0.

Then you should modify the create_pascal_tfrecord.py accordingly.
