### ISSUE TITLE
why setting the box_loss_weight =50?

### ISSUE THREAD

**Issue by HardLaugh** [google/automl#26]
hello, i am confused about box_loss_weight for retinanet  , can somebody explain why box_loss_weight is 50.0 in tpu while it was setted to 1.0  in mmdetection or detectron

**Comment by mingxingtan** [comment]
@HardLaugh This is inherited from TPU-version RetinaNet, but the basic idea is to balance classification loss and bounding box loss.

**Comment by HardLaugh** [comment]
Thank you for your hard work and reply. BTW, if i read this right, i  see the setup here (fpn_cell_repeats) here is a little different from the paper, right?

**Comment by mingxingtan** [comment]
@HardLaugh what's the difference? They should be the same.

**Comment by HardLaugh** [comment]
@mingxingtan [https://github.com/google/automl/blob/61a73539b3417ebc3b740cd07c40c51e3a66a8f6/efficientdet/hparams_config.py#L206](url) here, but it looks like it's set to 3 in the paper

**Comment by mingxingtan** [comment]
Hi @HardLaugh, the updated paper is also 3.  It was 2 in v1, but we have updated it to be 3 in v2 arxiv.

**Comment by louisquinn** [comment]
> @HardLaugh This is inherited from TPU-version RetinaNet, but the basic idea is to balance classification loss and bounding box loss.

@mingxingtan is there a rough method you guys used to compute this weight value, or was it found empirically?
