### ISSUE TITLE
Command to run benchmark using Saved Model on Custom dataset

### ISSUE THREAD

**Issue by sourabhyadav** [google/automl#265]
Hi all,
What steps need to be taken to run the evaluation using the Saved/Exported Model on the custom dataset.

I get the eval command to run evaluation using checkpoint in Readme:
```
python main.py --mode=eval  \
    --model_name=${MODEL}  --model_dir=${CKPT_PATH}  \
    --validation_file_pattern=tfrecord/val*  \
    --val_json_file=annotations/instances_val2017.json  \
    --hparams="use_bfloat16=false" --use_tpu=False
```

I want to benchmark checkpoint vs saved model results.

**Comment by sourabhyadav** [comment]
I tried to benchmark with ```tfrecord/val*``` command to run on a batch of images:
```
python3 model_inspect.py --runmode=saved_model_benchmark --model_name=efficientdet-d1 --ckpt_path=$eff_path/pretrained/efficientdet-d1 --input_image=$eff_path/coco/tfrecord/val* --saved_model_dir=$eff_path/exported_models/pre_trrained_d1/
```

The above did not work. Looks like it works only when we provide single image s input like below:
```
python3 model_inspect.py --runmode=saved_model_benchmark --model_name=efficientdet-d1 --ckpt_path=$eff_path/pretrained/efficientdet-d1 --input_image=$eff_path/coco/val2017/000000158744.jpg --saved_model_dir=$eff_path/exported_models/pre_trrained_d1/
```

Is it possible to benchmark the same uinsg coco val json file?

**Comment by mingxingtan** [comment]
Hi @sourabhyadav  Please check out the latest README for benchmarking and inference with images using saved model.

**Comment by sourabhyadav** [comment]
> Hi @sourabhyadav Please check out the latest README for benchmarking and inference with images using saved model.

Thanks.
