### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'

### ISSUE THREAD

**Issue by Sean0123456789** [google/automl#267]
When run tutorial and inference, met this problem:"AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores"

Anyone can help?

**Comment by Sean0123456789** [comment]
different version tf has been tried: tf 2.1, tf 1.13, tf 1.14, but no one works.

**Comment by XhqGlorry11** [comment]
same problem here

**Comment by fsx950223** [comment]
You could change it to non max suppression by yourself.

**Comment by deepakcrk** [comment]
If you are using serving ServingDriver class, you can set:

`self.disable_pyfun = False`

**Comment by Sean0123456789** [comment]
@deepakcrk  can't save model to pb format with nms, any ideas?

**Comment by mingxingtan** [comment]
self.disable_pyfun = False does not support saved_model.

If you want to generate a saved_model or a frozen pb file, please see the updated README (make sure self.disable_pyfun = True as shown in the default):

```
!python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 \
  --saved_model_dir=/tmp/saved_model
```

This would generate both a saved_model, and a frozen pb file under /tmp/saved_model


The code should be good with tf2.1.0.

**Comment by Sean0123456789** [comment]
@mingxingtan  Thanks for your reply. But when I save model by following README, I still meet the problem:"AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'". Do I need to build tensorflow by myself?

**Comment by fsx950223** [comment]
> @mingxingtan Thanks for your reply. But when I save model by following README, I still meet the problem:"AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'". Do I need to build tensorflow by myself?

Yeah, you could build TensorFlow by yourself if you don't want to upgrade TensorFlow or change NMS.
