### ISSUE TITLE
Freeze training

### ISSUE THREAD

**Issue by fsx950223** [google/automl#273]
Maybe there should be an option to freeze backbone or backbone+fpn for fine-tuning model

**Comment by mingxingtan** [comment]
Good idea. The code already has the option: https://github.com/google/automl/blob/ef12ec66abf7758f8c6f85ef186577ad019f6246/efficientdet/det_model_fn.py#L495

but maybe we should make it as an explicit option.

**Comment by fsx950223** [comment]
```
I0610 01:53:26.004388 140066675570496 mAP.py:110] Execute time: 0.03148164788349637
I0610 01:53:29.300843 140066675570496 mAP.py:190] APs: 
I0610 01:53:29.301033 140066675570496 mAP.py:191] {1: 0.766150749066384, 2: 0.8597996369084346, 3: 0.76743932866071, 4: 0.627666497749191, 5: 0.5649626539590175, 6: 0.9019822411647831, 7: 0.8353485428366669, 8: 0.8811422501635355, 9: 0.5623156342059552, 10: 0.8067562107916536, 11: 0.6721418258834234, 12: 0.8438035252421605, 13: 0.8767644781209558, 14: 0.8216282947351573, 15: 0.7981710036902505, 16: 0.4446269230079246, 17: 0.7894564668731308, 18: 0.6923921067762173, 19: 0.8410965881476604, 20: 0.7864043410009635}
I0610 01:53:29.301160 140066675570496 mAP.py:192] mAP: 
I0610 01:53:29.301331 140066675570496 mAP.py:193] 0.7570024649492089
```
I got above results(mAP0.5) by freeze training on VOC2007 dataset with following command:
```python main.py --strategy=None --hparams="num_epochs=15,num_classes=21" --model_name=efficientdet-d0 --model_dir=${MODEL_DIR} --ckpt=./efficientdet-d0 --train_batch_size=32 --training_file_pattern=${DATASET}```

Env:GTX1080TI

**Comment by Gentlemen-s** [comment]
python main.py --strategy=None --num_examples_per_epoch=5011 --hparams="num_epochs=50,num_classes=21,var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'" --model_name=efficientdet-d0 --model_dir=${MODEL_DIR} --ckpt=./efficientdet-d0 --train_batch_size=64 --training_file_pattern=${DATASET}

Env:GTX1080TI

**Comment by Gentlemen-s** [comment]
> ```
> I0610 01:53:26.004388 140066675570496 mAP.py:110] Execute time: 0.03148164788349637
> I0610 01:53:29.300843 140066675570496 mAP.py:190] APs: 
> I0610 04:55:37.345306 140408594347840 mAP.py:191] {1: 0.754223836749629, 2: 0.8341261780927208, 3: 0.7873959909768331, 4: 0.6261547763061818, 5: 0.5548824051313777, 6: 0.8836932150962724, 7: 0.8501507103469115, 8: 0.8686772519057091, 9: 0.5465021023706005, 10: 0.8299983283152956, 11: 0.6870053771523303, 12: 0.8455793502122715, 13: 0.8760886716024743, 14: 0.8209413828988532, 15: 0.8007687574019038, 16: 0.4378068412218055, 17: 0.8067727080080371, 18: 0.6734279074837197, 19: 0.8435747061543866, 20: 0.7793179987293148}
> I0610 04:55:37.345413 140408594347840 mAP.py:192] mAP: 
> I0610 04:55:37.345569 140408594347840 mAP.py:193] 0.7553544248078314
> ```
> 
> I got above results(mAP0.5) by freeze training on VOC2007 dataset with following command:
> `python main.py --strategy=None --num_examples_per_epoch=5011 --hparams="num_epochs=50,num_classes=21,var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'" --model_name=efficientdet-d0 --model_dir=${MODEL_DIR} --ckpt=./efficientdet-d0 --train_batch_size=64 --training_file_pattern=${DATASET}`
> 
> Env:GTX1080TI
