### ISSUE TITLE
Training flags : Multi-GPU, train and val split,

### ISSUE THREAD

**Issue by Samjith888** [google/automl#274]
Your work is really great and thank for this repo.. I have few doubts about training flags

1) I have a custom dataset with 2000 images and labels in PascalVOC , Should i split it into training val manually and create the tfrecords seperately for train and validation .
eg : pass the tfrecord like below
       --training_file_pattern=tfrecord/train*.tfrecord 
       --validation_file_pattern=tfrecord/val*.tfrecord  
                                                (or) 
Is the `reate_pascal_tfrecord.py` file will split the whole data into train and validation ?

2) Is Multi-GPU training available here ? (The training is very slow when i used models higher than efficientdet-b0 by using single gpu)

3)  what is `--eval_samples` and `--num_examples_per_epoch`  What should i set if train with 1 class? is the `--eval_samples` means the number images for evaluation ?

**Comment by shreymohan** [comment]
I have a question, how did you run the training code on GPU? Is there a flag to be set? Whenever I try to train the model, it runs on the cpu. Any kind of help will be appreciated! Thanks!

**Comment by 15241192958** [comment]
> I have a question, how did you run the training code on GPU? Is there a flag to be set? Whenever I try to train the model, it runs on the cpu. Any kind of help will be appreciated! Thanks!

i have same question

**Comment by Samjith888** [comment]
> I have a question, how did you run the training code on GPU? Is there a flag to be set? Whenever I try to train the model, it runs on the cpu. Any kind of help will be appreciated! Thanks!

`--use_tpu=False` : this flag will disable the training on TPU and run on GPU.

You can mention the following line into the main.py for using specific GPU id.
`os.environ['CUDA_VISIBLE_DEVICES'] = "1"`

Is it not solved yet, create and new issue with full log..
