### ISSUE TITLE
paper confusion

### ISSUE THREAD

**Issue by lxy5513** [google/automl#278]
Thanks for your graet work!

I read the paper find some confusion problems.

![image](https://user-images.githubusercontent.com/39720528/79815542-90350580-83b3-11ea-82de-23732fe42199.png)
![image](https://user-images.githubusercontent.com/39720528/79815560-97f4aa00-83b3-11ea-8c7a-36c12e2260d0.png)

base on the two equation, for example, we should get  Input size = 1152 (512+5*128) where $\phi$ = 5,  

but below figure,  some data can't corresponding the two equation 

![image](https://user-images.githubusercontent.com/39720528/79816021-b9a26100-83b4-11ea-8420-f28faccb92f6.png)

Could you mind help me answer the question, thanks in advance

**Comment by mingxingtan** [comment]
Yeah, these are all heuristics. In general, you don't need to strictly follow these equations.

But you are correct, B5 should use 1152 image size, but I accidently used the wrong 1280 in my previous experiments. Given that the difference between 1152 and 1280 is small, but updating all docs and code is a little bit painful, I was kind of stuck there.

**Comment by lxy5513** [comment]
OK，thanks for your kind response.
