### ISSUE TITLE
CPU performance

### ISSUE THREAD

**Issue by fsx950223** [google/automl#280]
![Screenshot from 2020-04-21 17-41-22](https://user-images.githubusercontent.com/17592563/79851115-76b5ad00-83f7-11ea-8699-58e262f4dd9d.png)

It seems Cpu latency is wrong, I got:
Efficientdet-d0 batch-size=1 INTEL-E3
Inference time:  0.1377426457009278
FPS:  7.2599157284319835
Include postprocess.

**Comment by mingxingtan** [comment]
Yeah, you need to specify "single thread":

$python model_inspect.py --runmode=bm --threads=1

Somehow I was recommended to use single-thread to benchmarrk CPU performance, but maybe I should also show the latency with all CPU cores and threads.
