### ISSUE TITLE
Why --num_classes flag wrote two times in ' Finetune on PASCAL VOC 2012 with detector COCO ckpt.'

### ISSUE THREAD

**Issue by Samjith888** [google/automl#281]
Under  ' Finetune on PASCAL VOC 2012 with detector COCO ckpt.' in readme , **--num_classes** mentioned two times . why its mentioned two times ?
```
# Finetune needs to use --ckpt rather than --backbone_ckpt.
!python main.py --mode=train_and_eval \
    --num_classes=20 \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --val_json_file=tfrecord/json_pascal.json \
    --model_name=efficientdet-d0 \
    --model_dir=/tmp/efficientdet-d0-scratch  \
    --ckpt=efficientdet-d0  \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=1024 \
    --num_examples_per_epoch=5717 --num_epochs=1  \
    --hparams="use_bfloat16=false,num_classes=20,moving_average_decay=0" \
    --use_tpu=False
```

**Comment by mingxingtan** [comment]
It is a typo. The first num_classes is not needed.

**Comment by mfaramarzi** [comment]
@Samjith888 
I am doing the same process as you, and facing the same error. Could you handle it?

**Comment by mfaramarzi** [comment]
@Samjith888 @mingxingtan 

Would you please explain how we should select our training commands?
for example in our case, there is no json file. Should we omit the following part?

--val_json_file=tfrecord/json_pascal.json \

**Comment by mingxingtan** [comment]
--val_json_file is not needed anymore. I just updated the README.
