### ISSUE TITLE
question about FLOPS between BiFPN and FPN

### ISSUE THREAD

**Issue by dmuestc** [google/automl#284]
![image](https://user-images.githubusercontent.com/31580105/79940553-a5ce2c00-8494-11ea-8607-aae20c8be04d.png)

Thanks for the great work and released code! I have a question when reading the paper, as above, why BiFPN's FLOPS less  than FPN, and compared the code between them, it seems that BiFPN does more operation?

**Comment by mingxingtan** [comment]
BiFPN is using depthwise separable conv, which helps reduce the FLOPS/params.

**Comment by tjumiao** [comment]
Hi, thanks for the great work!

From reading your paper in ablation study section 6.2, you also compared BiFPN with FPN with the same backbone and replaced the convs in all networks with depthwise separable convs. Why does BiFPN still have much fewer FLOPS?  
![image](https://user-images.githubusercontent.com/18041918/93804197-f5677e00-fc13-11ea-8298-ae4616fd5854.png)

Thank you.

**Comment by tjumiao** [comment]
> BiFPN is using depthwise separable conv, which helps reduce the FLOPS/params.

Hi, thanks for the great work!

From reading your paper in ablation study section 6.2, you also compared BiFPN with FPN with the same backbone and replaced the convs in all networks with depthwise separable convs. Why does BiFPN still have much fewer FLOPS?  
![image](https://user-images.githubusercontent.com/18041918/93804197-f5677e00-fc13-11ea-8298-ae4616fd5854.png)

Thank you.
