### ISSUE TITLE
Does image format (non-JPEG) matter?

### ISSUE THREAD

**Issue by junyongyou** [google/automl#287]
When I created pascal tfrecord from non-jpeg images, I got the exception from this line:   if image.format != 'JPEG':
    raise ValueError('Image format not JPEG').

If I comment it, the tfrecord can still be created, and the model can be trained. So I am wondering if image format matters, should I convert my images to JPEG? Thanks a lot.

**Comment by mingxingtan** [comment]
Hi @junyongyou What's your data format?  Maybe the check is not necessary.

**Comment by junyongyou** [comment]
Thanks. @mingxingtan I am using PNG images.

**Comment by mingxingtan** [comment]
both JPG and PNG should be fine.
