### ISSUE TITLE
aspect ratio format

### ISSUE THREAD

**Issue by fsx950223** [google/automl#303]
https://github.com/google/automl/blob/aa798fef010e3974f46ed9729bf137882227d26a/efficientdet/anchors.py#L240

image size,strides are hw format, but aspect ratio is wh format?

**Comment by mingxingtan** [comment]
Good point. Because I always use symmetric aspect ratios, I did not consider it is WH or HW.
Maybe this should be: `anchor_size_x_2 = base_anchor_size_x * aspect[1] / 2.0`? Could you help double check?

**Comment by NgTuong** [comment]
Hi @fsx950223 , @mingxingtan.
How to modify haprams aspect_ratios, num_scale for my dataset?

**Comment by mingxingtan** [comment]
@NgTuong You can define a yaml file and load it using --hparams=xx.yaml
