### ISSUE TITLE
how to make logs for loss from training?

### ISSUE THREAD

**Issue by ycdhqzhiai** [google/automl#304]
Hi.I see below information when training on GPU.
![image](https://user-images.githubusercontent.com/12273405/80195064-e9b86100-864d-11ea-817e-191b56e9b44e.png)
how to revmoe it and to make logs for loss from training? 
I'm not sure whether to modify here:
https://github.com/google/automl/blob/006668f2af1744de0357ca3d400527feaa73c122/efficientdet/det_model_fn.py#L623
Is there anybody can help me?

**Comment by InfiniteLife** [comment]
Im not sure if you are aware you can use tensorboard log?

**Comment by ycdhqzhiai** [comment]
@InfiniteLife Thank you for your reply. I can't use the browser for some reasons
