### ISSUE TITLE
Error when trying to train on own dataset: StringToNumberOp could not correctly convert string

### ISSUE THREAD

**Issue by denisb411** [google/automl#307]
Tried to use the model to train on my own dataset, tfrecord created like I do with tensorflow's object detection api, but I stuck on the following error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: StringToNumberOp could not correctly convert string: capture_5ea34d4023b6ab0006acdf23.jpg
	 [[{{node parser/StringToNumber}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: StringToNumberOp could not correctly convert string: capture_5ea34d4023b6ab0006acdf23.jpg
	 [[{{node parser/StringToNumber}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_17475]]
0 successful operations.
0 derived errors ignored.
```

Is anything wrong?

I checked the way the tfrecord is created on create_coco_tfrecord.py and everything seems pretty similar with the way I'm creating. Can be followed here: [generate_tfrecord.py](https://gist.github.com/denisb411/67b03f17ddfe7b9ae800a4ceecfd3028).

Complete execution and error: [training.ipynb](https://gist.github.com/denisb411/76f35d1b18f6cacb3f8154b5ee5678e5)

**Comment by fsx950223** [comment]
> Tried to use the model to train on my own dataset, tfrecord created like I do with tensorflow's object detection api, but I stuck on the following error:
> 
> ```
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) Invalid argument: StringToNumberOp could not correctly convert string: capture_5ea34d4023b6ab0006acdf23.jpg
> 	 [[{{node parser/StringToNumber}}]]
> 	 [[IteratorGetNext]]
>   (1) Invalid argument: StringToNumberOp could not correctly convert string: capture_5ea34d4023b6ab0006acdf23.jpg
> 	 [[{{node parser/StringToNumber}}]]
> 	 [[IteratorGetNext]]
> 	 [[IteratorGetNext/_17475]]
> 0 successful operations.
> 0 derived errors ignored.
> ```
> 
> Is anything wrong?
> 
> I checked the way the tfrecord is created on create_coco_tfrecord.py and everything seems pretty similar with the way I'm creating. Can be followed here: [generate_tfrecord.py](https://gist.github.com/denisb411/67b03f17ddfe7b9ae800a4ceecfd3028).
> 
> Complete execution and error: [training.ipynb](https://gist.github.com/denisb411/76f35d1b18f6cacb3f8154b5ee5678e5)

Dataset only support number as image name, maybe you should comment ```tf.string_to_number```.

**Comment by denisb411** [comment]
> Dataset only support number as image name, maybe you should comment `tf.string_to_number`.
> https://github.com/google/automl/blob/e59688824a57c8cdd7ca8ded4716445b745906ab/efficientdet/dataloader.py#L301

I couldn't solve the problem by using your workaround. Later problems happen.

I had to convert all my dataset to numbers only (not even the .jpg I could use). Unfortunately the training doesn't converge and still don't know why. I'm seeing that is a recurrent problem on the issues sections.

**Comment by vakkov** [comment]
You shouls mention the later issues that happen... i believe they are evaluation-related? The get_detections method in anchors.py?

**Comment by blakenguyen97** [comment]
I am having the same issue, did you figure it out @denisb411?

**Comment by denisb411** [comment]
> I am having the same issue, did you figure it out @denisb411? I think we both used the older version of TF to convert (in my case it is 1.14, but I used TF 2.2.0 for training EfficientDet)

@blakenguyen97 I corrected this error by converting my entire dataset to numbers only for the filenames (even the '.jpg' you have to avoid). Despite that I don't know if this is a trustable solution as my model never converge on training and I just gave up on using this model because the TF OD Api (using faster_rcnn_resnet101) was enough for me.

**Comment by blakenguyen97** [comment]
> > I am having the same issue, did you figure it out @denisb411? I think we both used the older version of TF to convert (in my case it is 1.14, but I used TF 2.2.0 for training EfficientDet)
> 
> @blakenguyen97 I corrected this error by converting my entire dataset to numbers only for the filenames (even the '.jpg' you have to avoid). Despite that I don't know if this is a trustable solution as my model never converge on training and I just gave up on using this model because the TF OD Api (using faster_rcnn_resnet101) was enough for me.

How did you do that? Do you rename it all by using python script? When I try to remove the file extension ".jpg"  or ".xml" it loses its format.

**Comment by zishanahmed08** [comment]
In ur tf record creation script,change **source_id**

  ### 'image/source_id': dataset_util.bytes_feature(input_image_filename.encode('utf8')),
to
  ### 'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),

**Comment by blakenguyen97** [comment]
> ### 'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),
'0' means filename, right?

**Comment by blakenguyen97** [comment]
> In ur tf record creation script,change **source_id**
> 
> ### 'image/source_id': dataset_util.bytes_feature(input_image_filename.encode('utf8')),
> to
> 
> ### 'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),
> You dont need to modify any filenames.

Great solution, it works. Thank you so much

**Comment by mfaramarzi** [comment]
> '0'.encode('utf8')


I made that change to the "tf record creation script", but still getting the same error as below:

![errorED2](https://user-images.githubusercontent.com/44882423/82164335-20b11980-987e-11ea-862d-833c7e6d186c.png)

**Comment by zishanahmed08** [comment]
@mfaramarzi the error message clearly indictaes that you still use 'Czech_000157.jpg' (filename) as s source id

**Comment by blakenguyen97** [comment]
> I made that change to the "tf record creation script", but still getting the same error as below:

Try to use mine gen_tf_record.py file, remember to replace your label.


from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow.compat.v1 as tf

from PIL import Image
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict

flags = tf.app.flags
flags.DEFINE_string('csv_input', '', 'Path to the CSV input')
flags.DEFINE_string('output_path', '', 'Path to output TFRecord')
flags.DEFINE_string('image_dir', '', 'Path to images')
FLAGS = flags.FLAGS


# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'your_label':
        return 1
    else:
        None


def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]


def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example


def main(_):
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
    path = os.path.join(FLAGS.image_dir)
    examples = pd.read_csv(FLAGS.csv_input)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), FLAGS.output_path)
    print('Successfully created the TFRecords: {}'.format(output_path))


if __name__ == '__main__':
    tf.app.run()

**Comment by blakenguyen97** [comment]
> I made that change to the "tf record creation script", but still getting the same error as below:
Try my record_gen.py, don't forget yo replace my labels with yours.

```
"""
Usage:
  # From tensorflow/models/
  # Create train data:
  python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record

  # Create test data:
  python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=test.record
"""
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow.compat.v1 as tf

from PIL import Image
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict

flags = tf.app.flags
flags.DEFINE_string('csv_input', '', 'Path to the CSV input')
flags.DEFINE_string('output_path', '', 'Path to output TFRecord')
flags.DEFINE_string('image_dir', '', 'Path to images')
FLAGS = flags.FLAGS


# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'my_label':
        return 1
    else:
        None


def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]


def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example


def main(_):
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
    path = os.path.join(FLAGS.image_dir)
    examples = pd.read_csv(FLAGS.csv_input)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), FLAGS.output_path)
    print('Successfully created the TFRecords: {}'.format(output_path))


if __name__ == '__main__':
    tf.app.run()
```

**Comment by mingxingtan** [comment]
The latest create_pascal_tfrecord.py use integer as source_id, so you should not have this issue anymore.

**Comment by ChulanZhang** [comment]
> The latest create_pascal_tfrecord.py use integer as source_id, so you should not have this issue anymore.

Thanks for the info! May I know which line of code does this? 
I am trying to modify the code to create the tfrecord file for my custom dataset and got this error.

**Comment by kartik4949** [comment]
> The latest create_pascal_tfrecord.py use integer as source_id, so you should not have this issue anymore.

@mingxingtan @ChulanZhang setting source-id a fixed number will result in eval result discrepancy, 
You can use a unique id of each element.

**Comment by ChulanZhang** [comment]
> > The latest create_pascal_tfrecord.py use integer as source_id, so you should not have this issue anymore.
> 
> @ChulanZhang setting source-id a fixed number will result in eval result discrepancy,
> You can use a unique id of each element.
> P.S: just pull the latest commit as it is already been solved with UniqueId Class.
> Thanks

@kartik4949 Thanks for the help! I used the UniqueId Class and it works well now.

**Comment by BernardinD** [comment]
For anyone else who is a situation where it isn't a good option to rebuild the tfrecord it seems like I was able to fix the issue hashing at line:
https://github.com/google/automl/blob/4a2b324ae54eaeae2c7fb0e69195897d7e312425/efficientdet/dataloader.py#L342
with:
`source_id = tf.strings.to_hash_bucket_fast(source_id, 1)` 

Waiting to confirm that it can converge
