### ISSUE TITLE
Can you provide a tutorial on how to build a model ?

### ISSUE THREAD

**Issue by Cyril9227** [google/automl#31]
Hello,

I just need to build an EfficientDet model (from name) and experiment with it inside a jupyter notebook. Can someone explain to me what functions I need to call to do so ? I don't want to use the cli

Thank's

**Comment by mingxingtan** [comment]
Please refer to our [READM](https://github.com/google/automl/blob/master/efficientdet/README.md) or [Tutorial](https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb).
