### ISSUE TITLE
the bifpn's input makes me confused

### ISSUE THREAD

**Issue by Hamoni-XJTU** [google/automl#311]
this code in the function build_feature_network
for level in range(config.min_level, config.max_level + 1):
    if level in features.keys():
      feats.append(features[level])
    else:...
the feature is a dict {0: features, 1: u1, 2: u2, 3: u3, 4: u4, 5: u5}, so ,the level 6 and level 7 are not in features.keys(), right? they are calculated by downsampling the level 5. why not using level 6 and level 7's feature directly? Is there anything I have ignored?

**Comment by mingxingtan** [comment]
Hi @Hamoni-XJTU , good question.  This is because the backbones are originally designed for ImageNet, which only have up to feature u5  (similar to all other backbones like resnet, inception, alexnet, etc).
