### ISSUE TITLE
inferenced by pb

### ISSUE THREAD

**Issue by Jilliansea** [google/automl#32]
Hi, I want to detect a image lists in form of 'txt', and I change the code of build_input, but it also error in post process. Because the batch size of inference is 1, when send all images to the model, it also deal as 1 batch, then then anchor numbers will biger then index...
So, could you please publish an inference code to "change ckpt to pb " and inference by pb model for multi-images?

**Comment by mingxingtan** [comment]
@Jilliansea Thanks for pointing out, this is a bug of inference.py. I have fixed it in https://github.com/google/automl/commit/856d659bcc638a73d4ee9f88b466faf903cd4de3

Now you can do inference for multiple images. For example, this command line works well on my side:

python model_inspect.py --model_name=efficientdet-d0 --ckpt_path=/tmp/efficientdet/efficientdet-d0/ --runmode=infer --input_image=/tmp/images/*.jpg  --output_image_dir=/tmp/imagesout  --logtostderr

**Comment by Jilliansea** [comment]
Thank you very much!!! And what about the suggestion  to give a separated inference code which support inference multi images by for-loop?

**Comment by Jilliansea** [comment]
@mingxingtan Thank you very much!!! And what about the suggestion to give a separated inference code which support inference multi images by for-loop?

**Comment by mingxingtan** [comment]
you are welcome. If you look at the tutorial, you will find the code is pretty simple:

driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
driver.inference(img_path,
                 img_out_dir,
                 min_score_thresh=min_score_thresh,
                 max_boxes_to_draw=max_boxes_to_draw,
                 line_thickness=line_thickness)

I don't want to have too many files and binaries, so I simply put this logic into model_inspect.py.

If you really want to do inference by for loop, you can do this:

driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
for m in imag_list:
    driver.inference(m,
                 img_out_dir,
                 min_score_thresh=min_score_thresh,
                 max_boxes_to_draw=max_boxes_to_draw,
                 line_thickness=line_thickness)

But I don't see the benifit. Anyway, I am going to close this issue for now. If you have further questions, feel free to reopen it.

**Comment by Jilliansea** [comment]
@mingxingtan The final question, the separated inference is easy to test the inference time of the model(mean  time) without  time of  load model. Or do you have other  means to test the pure inference time?

**Comment by Jilliansea** [comment]
> you are welcome. If you look at the tutorial, you will find the code is pretty simple:
> 
> ```
> driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> driver.inference(img_path,
>              img_out_dir,
>              min_score_thresh=min_score_thresh,
>              max_boxes_to_draw=max_boxes_to_draw,
>              line_thickness=line_thickness)
> ```
> 
> I don't want to have too many files and binaries, so I simply put this logic into model_inspect.py.
> 
> If you really want to do inference by for loop, you can do this:
> 
> ```
> driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> for m in imag_list:
>     driver.inference(m,
>              img_out_dir,
>              min_score_thresh=min_score_thresh,
>              max_boxes_to_draw=max_boxes_to_draw,
>              line_thickness=line_thickness)
> ```
> 
> But I don't see the benifit. Anyway, I am going to close this issue for now. If you have further questions, feel free to reopen it.

I test the inference time(read image, preprocess and post process) of efficient-D4 in inference code, it took 2min, but I know the pure inference time should be  small. So how to check the speed of inference?

**Comment by deepakcrk** [comment]
> driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> for m in imag_list:
>     driver.inference(m,
>              img_out_dir,
>              min_score_thresh=min_score_thresh,
>              max_boxes_to_draw=max_boxes_to_draw,
>              line_thickness=line_thickness)
> ```

@mingxingtan I am getting the following error while looping through the images as above:


```
  File "model_inspect.py", line 331, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 325, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 303, in run_model
    **config_dict)
  File "model_inspect.py", line 183, in inference_single_image
    driver.inference("/home/deepak/Desktop/X_NEW_NEW/SMARTVu_Validation/cut_EastEntrance-10-11-2018_3_101.jpg", output_dir, **kwargs)
  File "/home/deepak/automl/tmp/automl/efficientdet/inference.py", line 283, in inference
    self.model_name, images, **self.params)
  File "/home/deepak/automl/tmp/automl/efficientdet/inference.py", line 110, in build_model
    class_outputs, box_outputs = model_arch(inputs, model_name, **kwargs)
  File "/home/deepak/automl/tmp/automl/efficientdet/efficientdet_arch.py", line 550, in efficientdet
    features = build_backbone(features, config)
  File "/home/deepak/automl/tmp/automl/efficientdet/efficientdet_arch.py", line 329, in build_backbone
    override_params=override_params)
  File "/home/deepak/automl/tmp/automl/efficientdet/backbone/efficientnet_builder.py", line 324, in build_model_base
    features = model(images, training=training, features_only=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /home/deepak/automl/tmp/automl/efficientdet/backbone/efficientnet_model.py:637 call  *
        outputs = self._relu_fn(
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/base.py:547 __call__
        outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:748 __call__
        self._maybe_build(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:2116 _maybe_build
        self.build(input_shapes)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/convolutional.py:158 build
        dtype=self.dtype)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/base.py:460 add_weight
        **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:446 add_weight
        caching_device=caching_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/tracking/base.py:744 _add_variable_with_custom_getter
        **kwargs_for_getter)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py:1572 get_variable
        aggregation=aggregation)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py:1315 get_variable
        aggregation=aggregation)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py:568 get_variable
        aggregation=aggregation)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py:520 _true_getter
        aggregation=aggregation)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py:861 _get_single_variable
        raise ValueError(err_msg)

    ValueError: Variable efficientnet-b6/stem/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

```

**Comment by YanqingWu** [comment]
> > you are welcome. If you look at the tutorial, you will find the code is pretty simple:
> > ```
> > driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> > driver.inference(img_path,
> >              img_out_dir,
> >              min_score_thresh=min_score_thresh,
> >              max_boxes_to_draw=max_boxes_to_draw,
> >              line_thickness=line_thickness)
> > ```
> > 
> > 
> > I don't want to have too many files and binaries, so I simply put this logic into model_inspect.py.
> > If you really want to do inference by for loop, you can do this:
> > ```
> > driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> > for m in imag_list:
> >     driver.inference(m,
> >              img_out_dir,
> >              min_score_thresh=min_score_thresh,
> >              max_boxes_to_draw=max_boxes_to_draw,
> >              line_thickness=line_thickness)
> > ```
> > 
> > 
> > But I don't see the benifit. Anyway, I am going to close this issue for now. If you have further questions, feel free to reopen it.
> 
> I test the inference time(read image, preprocess and post process) of efficient-D4 in inference code, it took 2min, but I know the pure inference time should be small. So how to check the speed of inference?

have you fix the problem, I have the same question, too.

**Comment by Jilliansea** [comment]
> > > you are welcome. If you look at the tutorial, you will find the code is pretty simple:
> > > ```
> > > driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> > > driver.inference(img_path,
> > >              img_out_dir,
> > >              min_score_thresh=min_score_thresh,
> > >              max_boxes_to_draw=max_boxes_to_draw,
> > >              line_thickness=line_thickness)
> > > ```
> > > 
> > > 
> > > I don't want to have too many files and binaries, so I simply put this logic into model_inspect.py.
> > > If you really want to do inference by for loop, you can do this:
> > > ```
> > > driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
> > > for m in imag_list:
> > >     driver.inference(m,
> > >              img_out_dir,
> > >              min_score_thresh=min_score_thresh,
> > >              max_boxes_to_draw=max_boxes_to_draw,
> > >              line_thickness=line_thickness)
> > > ```
> > > 
> > > 
> > > But I don't see the benifit. Anyway, I am going to close this issue for now. If you have further questions, feel free to reopen it.
> > 
> > 
> > I test the inference time(read image, preprocess and post process) of efficient-D4 in inference code, it took 2min, but I know the pure inference time should be small. So how to check the speed of inference?
> 
> have you fix the problem, I have the same question, too.

No,sorry

**Comment by Jilliansea** [comment]
@mingxingtan Hi, when I want to write the inference code, and change the original code  a little (build_and_save_model), I also can change ckpt to pb successfully, but when I predict ,it runs error"tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel
         [[node fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel/read (defined at /home/luban/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[all_outputs/_3]]
  (1) Failed precondition: Attempting to use uninitialized value fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel
         [[node fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel/read (defined at /home/luban/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored."

And I paste key code as follow, if you can help ,I will be very  appreciate!!!!!!
`def build_and_save_model(self):
    """build and save the model into self.logdir."""
    with tf.Graph().as_default(), tf.Session() as sess:
      # Build model with inputs and labels.
      inputs = tf.placeholder(tf.float32, name='input', shape=self.inputs_shape)
      cls_outputs, box_outputs = self.build_model(inputs, is_training=False)
      #outputs = list(cls_outputs) + list(box_outputs)
      outputs = tf.concat((cls_outputs, box_outputs), 2, name='all_outputs')
      # Run the model
      inputs_val = np.random.rand(*self.inputs_shape).astype(float)
      labels_val = np.zeros(self.labels_shape).astype(np.int64)
      labels_val[:, 0] = 1
      sess.run(tf.global_variables_initializer())
      # Run a single train step.
      sess.run(outputs, feed_dict={inputs: inputs_val})
      all_saver = tf.train.Saver(save_relative_paths=True)
      all_saver.save(sess, os.path.join(self.logdir, self.model_name))

      tf_graph = os.path.join(self.logdir, self.model_name + '_train.pb')
      with tf.io.gfile.GFile(tf_graph, 'wb') as f:
        f.write(sess.graph_def.SerializeToString())`

`class DetectionModel(object):
    def __init__(self, model_path, model_name='efficientdet-d4', image_size=None):
        self.detection_graph = tf.Graph()
        with self.detection_graph.as_default():
            od_graph_def = tf.GraphDef()
            with tf.gfile.GFile(model_path, 'rb') as fid:
                serialized_graph = fid.read()
                od_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(od_graph_def, name='')
        os.environ['CUDA_VISIBLE_DEVICES']='0'
        tf_config = tf.ConfigProto()
        tf_config.gpu_options.allow_growth = True

        tensor_name_list = [tensor.name for tensor in tf.get_default_graph().as_graph_def().node]
        for tensor_name in tensor_name_list:
            print(tensor_name,'\n')
        #for n in tf.get_default_graph().as_graph_def().node:
        #    print('*********',n)
        self.image_tensor = self.detection_graph.get_tensor_by_name('input:0')
        self.all_outputs = self.detection_graph.get_tensor_by_name('all_outputs:0')
        self.sess = tf.Session(graph=self.detection_graph, config=tf_config)`

`def predict(self, image):
        params = copy.deepcopy(self.params)
        all_outputs = self.sess.run(
                [self.all_outputs],
                feed_dict={self.image_tensor: image[None, :, :, :]})
        return all_outputs`
`all_outputs = detection_model.predict(image)`

**Comment by thangdt** [comment]
I got the same problem. Anyone have solution for this?

**Comment by thangdt** [comment]
> error"tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
> (0) Failed precondition: Attempting to use uninitialized value fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel
> [[node fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel/read (defined at /home/luban/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> [[all_outputs/_3]]
> (1) Failed precondition: Attempting to use uninitialized value fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel
> [[node fpn_cells/cell_4/fnode1/op_after_combine6/conv/pointwise_kernel/read (defined at /home/luban/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> 0 successful operations.
> 0 derived errors ignored."

I got the same problem. Have anyone solution for this?
