### ISSUE TITLE
Why set survival_prob=0.0 when 'b0' in backbone_name?

### ISSUE THREAD

**Issue by KaqiKaqi** [google/automl#330]
https://github.com/google/automl/blob/3614751749a21ca2fcb299b60238c6651ff51125/efficientdet/efficientdet_arch.py#L402

When survival_prob=0.0,   in both class_net and box_net, neither dropout or residual connection is applied. While in MBConvBlock, dropout is not applied but residual connection is still present. Did I get it right?

**Comment by mingxingtan** [comment]
Yes, you are right. D0 takes too long to train with surrvival_prob, so I disabled it for d0.
