### ISSUE TITLE
Eval on TPU

### ISSUE THREAD

**Issue by shivam-raj** [google/automl#333]
As I'm training my model on TPU the evaluation is very slow on CPU.
Is it possible to run evalutation on TPU ?

**Comment by LeCongThuong** [comment]
Hi @shivam-raj, 
Do you find the way to evaluate on TPU?
I tried to --eval_master=$(TPU_EVAL)  --mode=train_and_eval with main.py, but it generated error like that:
tensorflow.python.framework.errors_impl.InvalidArgumentError: The master (current machine) is not included in the provided cluster_def

**Comment by shivam-raj** [comment]
> Hi @shivam-raj,
> Do you find the way to evaluate on TPU?
> I tried to --eval_master=$(TPU_EVAL) --mode=train_and_eval with main.py, but it generated error like that:
> tensorflow.python.framework.errors_impl.InvalidArgumentError: The master (current machine) is not included in the provided cluster_def

Nope I left it
Apparently evaluation on TPU can only be done by one core instead of utilising all the cores on TPU which makes the process painfully slow. You'd be better off doing evals on GPU.

I started training the model on a Cloud TPU and used Colab GPU for evaluation separetely. At times I get a P100 which makes the process much faster when compared to CPU. Also easy integration of  GCP Bucket and free GPU made me chose Colab for evalutaion.
