### ISSUE TITLE
Running tutorial.ipynb in colab fails

### ISSUE THREAD

**Issue by jsuit** [google/automl#338]
2020-05-01 00:42:45.003762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] 
      Successfully opened dynamic library libcudart.so.10.1 Traceback (most recent call last):   File 
       "model_inspect.py", line 33, in <module>    
      import det_model_fn   File "/content/automl/efficientdet/det_model_fn.py",
      line 27, in <module>     import anchors   
      File "/content/automl/efficientdet/anchors.py", line 30, in <module>   
      import utils   File "/content/automl/efficientdet/utils.py", line 31, in <module>     from 
      tensorflow.tpu.python.tpu import tpu_function  # pylint:disable=g-direct-tensorflow-import 
      ModuleNotFoundError: No module named 'tensorflow.tpu.python'

**Comment by jliendo** [comment]
I believe this is a typo. There is an extra "tpu" at the import line.

Line 31 at utils.py I believe should be:

`from tensorflow.python.tpu import tpu_function`

Was having the same problem and when I changed the module name, then it worked.

I am using tensorflow 2.1 by the way.

**Comment by mingxingtan** [comment]
Thanks for pointing this out. Yes, it is a unexpected typo and should have been fixed.
