### ISSUE TITLE
spatial_partition flag?

### ISSUE THREAD

**Issue by jsuit** [google/automl#339]
flags.DEFINE_bool('use_spatial_partition', False, 'Use spatial partition.')

What does this mean? What are we partitioning?

    flags.DEFINE_multi_integer(
    'input_partition_dims', [1, 4, 2, 1],
    'A list that describes the partition dims for all the tensors.')
Similar to the above question, what the heck does this mean? what are we partitioning (and why?)

And in the config file, what do max_level and min_level refer from the configs refer to?

**Comment by mingxingtan** [comment]
Hi @jsuit  spatial partition is legacy code and I have never used or tested them. I may choose to delete them soon.

the min_level and max_level means the feature level (please see the BiFPN section in the EfficientDet paper).

**Comment by mingxingtan** [comment]
I a going to close this issue, but if you still have issues, feel free to reopen it.
