### ISSUE TITLE
will project move to TF2 soon or else get rid of all the pages of deprecated warnings?

### ISSUE THREAD

**Issue by lessw2020** [google/automl#340]
I'm having a hard time actually seeing what's happening with the model b/c there is so many pages of "this will be deprecated" ala tf.cast, etc. and buried in there is info I actually want to see. It makes it really hard to work with.
 
Will this excellent detector (and it is an outstanding detector) be upgraded to TF2 in the near future or or will the offending items at least be upgraded to avoid the 'this will be deprecated' warnings that fill the screen. 
Thanks very much!

**Comment by mingxingtan** [comment]
Hi @lessw2020 , moving to TF2 will take some time and efforts. For now, maybe you can suppress them.
There are also some obviously simple fixes to some of these warnings. I will try to clean them up when I got the time (or PRs are welcome).

**Comment by lessw2020** [comment]
Thanks for the reply @mingxingtan (and congrats on making such a great detection architecture :) 
 I would be interested to do some PR's to help clean those errors up, but I wasn't sure as there's a lot of PR's already pending that haven't been integrated yet.  
Thus I wasn't sure if PR's were welcome.  Thanks for confirming they are  (and closing this issue to reduce the open count).

**Comment by mingxingtan** [comment]
Of course, PRs are welcome.  The pending PRs are mostly wip and I will merge some of them soon.
