### ISSUE TITLE
cannot export to TFLite (from graph nor saved_model) - operand #0 for input image is tf.quint8,  not right tensor type

### ISSUE THREAD

**Issue by lessw2020** [google/automl#341]
Using TF 2.2.0.rc3 I am unable to export to TFLite due to the input image array being tf.quint8 (data type issue):

**from saved_model:**
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:3: 
error: 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 
8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x512x512x3x!tf.quint8>'

**from efficientdet-d0.pb:**

Exception: <unknown>:0: error: loc("strided_slice_1"): 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x512x512x3x!tf.quint8>'

------------

Is there a way to tf.cast or other fix to the right data type so we can export to TFLite?  

----- code I used on the above two errors ------
import tensorflow.compat.v1 as tf

tf.enable_v2_behavior()
model_dir='savedmodel'
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir, ['image_arrays'],
                                                         {'image_arrays': [None, image_size, image_size, channel_size]},
                                                         ['detections'],signature_key='serving_default')

converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

####
frozen_graph = 'savedmodel/efficientdet-d0_frozen.pb'
graph = tf.Graph()
with graph.as_default():
    with tf.gfile.GFile(frozen_graph, 'rb') as f:
      graph_def = tf.GraphDef()
      graph_def.ParseFromString(f.read())
    with tf.Session(graph=graph) as sess:
        tf.import_graph_def(graph_def, name='')
        input_tensor = graph.get_tensor_by_name('image_arrays:0')
        outputs = graph.get_tensor_by_name('detections:0')
        print(np.shape(sess.run([outputs], feed_dict={input_tensor: np.random.random(size=(1, 512, 512, 3))})))
        # explicit define input shapes below
        
        converter = tf.lite.TFLiteConverter.from_frozen_graph(frozen_graph, input_arrays=['image_arrays'],
                                                              output_arrays=['detections'],
                                                              input_shapes={'image_arrays': [1, 512, 512, 3]})
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
        tflite_quant_model = converter.convert()

**Comment by lessw2020** [comment]
Unfortunately TFLite export for D0 at least, still doesn't work.   I'm running  tf 2.2.0-rc4 and have exact same issue as before (running in colab if that matters). 

I ran:  
`!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
      --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
      --tflite_path=efficientdet-d0.tflite`

Received the same quint8 error:

2020-05-06 18:32:33.074750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6879 MB memory) -> physical GPU (device: 0, name: Tesla P4, pci bus id: 0000:00:04.0, compute capability: 6.1)
loc(callsite("strided_slice_1"("/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py":299:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py":324:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py":198:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py":837:0 at callsite("/content/automl/efficientdet/inference.py":696:0 at callsite("/content/automl/efficientdet/inference.py":736:0 at callsite("model_inspect.py":150:0 at callsite("model_inspect.py":432:0 at callsite("model_inspect.py":479:0 at "/usr/local/lib/python3.6/dist-packages/absl/app.py":250:0)))))))))): error: 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x512x512x3x!tf.quint8>'
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:3: error: 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x512x512x3x!tf.quint8>'
  return loader.load(sess, tags, import_scope, **saver_kwargs)
  ^
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:324:7: note: called from
      return func(*args, **kwargs)
      ^
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:5: note: called from
    loader.load(sess, meta_graph.meta_info_def.tags, saved_model_dir)
    ^
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:837:34: note: called from
                                 output_arrays, tag_set, signature_key)
                                 ^
/content/automl/efficientdet/inference.py:696:9: note: called from
        output_arrays=[self.signitures['prediction'].op.name])
        ^
/content/automl/efficientdet/inference.py:736:7: note: called from
      tflite_model = self.to_tflite(output_dir)
      ^
model_inspect.py:150:5: note: called from
    driver.export(self.saved_model_dir, tflite_path=self.tflite_path)
    ^
model_inspect.py:432:9: note: called from
        self.export_saved_model(**config_dict)
        ^
model_inspect.py:479:7: note: called from
      trace_filename=FLAGS.trace_filename)
      ^
/usr/local/lib/python3.6/dist-packages/absl/app.py:250:5: note: called from
    sys.exit(main(argv))

**Comment by mingxingtan** [comment]
sorry, it should rc5 (the next release, not available yet) or nightly after May 1. You can try "pip install tf-nightly"
