### ISSUE TITLE
how to change the position of the label on the inferred image?

### ISSUE THREAD

**Issue by xiaopojizu123** [google/automl#342]
hi,I trained and infer the model on my own dataset,but the label can not be fully displayed in the infered image ,just like this
![3](https://user-images.githubusercontent.com/56756310/80854010-6f986580-8c67-11ea-9917-4756b2468542.jpg)，how to solve this problem?thanks!

**Comment by mingxingtan** [comment]
You can change this line with use different text position or margin:

https://github.com/google/automl/blob/0fd7a1ba775d05894472d897676f355de72aaa64/efficientdet/visualize/vis_utils.py#L234

**Comment by xiaopojizu123** [comment]
> You can change this line with use different text position or margin:
> 
> https://github.com/google/automl/blob/0fd7a1ba775d05894472d897676f355de72aaa64/efficientdet/visualize/vis_utils.py#L234

thanks!
