### ISSUE TITLE
Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint 	 [[{{node save/RestoreV2}}]]

### ISSUE THREAD

**Issue by FancyFai** [google/automl#348]
I encountered this problem when testing with a single picture. Does anyone have this problem? Can you give me some advice? Thank you very much

tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_149]

this is my command
python main.py --mode=train_and_eval     --num_classes=6     --training_file_pattern=tfrecord/train*.tfrecord     --validation_file_pattern=tfrecord/val*.tfrecord     --val_json_file=tfrecord/json_val.json     --model_name=efficientdet-d3     --model_dir=tmp/efficientdet-d3-scratch     --ckpt=efficientdet-ckpt/efficientdet-d3       --train_batch_size=4     --eval_batch_size=4 --eval_samples=1284     --hparams="num_classes=6,moving_average_decay=0"     --use_tpu=False

python model_inspect.py --model_name=efficientdet-d3  --runmode=infer    --input_image_size=800 --max_boxes_to_draw=100   --min_score_thresh=0.4   --ckpt_path=tmp/efficientdet-d3-scratch     --input_image=testdata/091802_14781.jpg --output_image_dir=outimg/   --num_classes=6 --enable_ema = False

**Comment by thangdt** [comment]
You need set arg --hparams="moving_average_decay=0" in predict image command

**Comment by mingxingtan** [comment]
Yeah, we decided to use a consistent way for train/eval/inference, which are all controlled by hparams.  --enable_ema, --num_classes, and --input_image_size are deprecated.

I have submitted a change to raise errors if unknown args are passed to command line. Your second command should fail now.

You can either pass --hparams="num_classes=6,moving_average_decay=0,image_size=800, moving_average_decay=0". Or you can create a yaml file with (say with name config.yaml):

num_classes: 6
moving_average_decay: 0
image_size: 800

then you can pass --hparams='config.yaml'

**Comment by gtgtgt1117** [comment]
> Yeah, we decided to use a consistent way for train/eval/inference, which are all controlled by hparams. --enable_ema, --num_classes, and --input_image_size are deprecated.
> 
> I have submitted a change to raise errors if unknown args are passed to command line. Your second command should fail now.
> 
> You can either pass --hparams="num_classes=6,moving_average_decay=0,image_size=800, moving_average_decay=0". Or you can create a yaml file with (say with name config.yaml):
> 
> num_classes: 6
> moving_average_decay: 0
> image_size: 800
> 
> then you can pass --hparams='config.yaml'



when i load the meta,the error:
saver = tf.train.import_meta_graph('model.ckpt-60000.meta')
Error:
KeyError: "The name 'lrn_rate' refers to an Operation not in the graph."

could you solve the issue?thanks
