### ISSUE TITLE
Inference time by dynamic batch size is slower than static.

### ISSUE THREAD

**Issue by thangdt** [google/automl#349]
I'm just exported saved model by two method dynamic and static batch size. But when predicted single image, dynamic batch size taken time is about two times as long as static batch size. Can you check it?

**Comment by sourabhyadav** [comment]
Yes, I tried with inference with dynamic vs static batch size with checkpoint inference. Even that shows similar behaviour.

**Comment by mingxingtan** [comment]
Yes, I am aware of that. It is not recommended to use dynamic batch inference on GPU.

In order to support dynamic batch size, we have to use the batch version NMS, but unfortunately batch version NMS can only run on CPU, which causes the slowness. I couldn't find better solution except adding a GPU version of batch NMS in TF, which would take considerable time and efforts.

**Comment by thangdt** [comment]
> Yes, I am aware of that. It is not recommended to use dynamic batch inference on GPU.
> 
> In order to support dynamic batch size, we have to use the batch version NMS, but unfortunately batch version NMS can only run on CPU, which causes the slowness. I couldn't find better solution except adding a GPU version of batch NMS in TF, which would take considerable time and efforts.

But when i'm using static batch size > 1. I got problem with inference image (batch size in save_model and save_model_infer is the same). Can you check it?
```
(0) Invalid argument: Shapes of all inputs must match: values[0].shape = [50,7] != values[2].shape = [37,7]
	 [[{{node detections}}]]
	 [[detections/_2537]]
  (1) Invalid argument: Shapes of all inputs must match: values[0].shape = [50,7] != values[2].shape = [37,7]
	 [[{{node detections}}]]
```

**Comment by mingxingtan** [comment]
Oh, really? that shouldn't happen! Could you help paste your command line?
As long as batch size is the same in saved_model and saved_model_infer, there should be no problem.

**Comment by thangdt** [comment]
Thanks for your replies. This is my command line
```
python model_inspect.py --runmode=saved_model \
    --model_name=efficientdet-d3 \
    --ckpt_path=./checkpoints/archive \
    --saved_model_dir=./saved_model \
    --batch_size=4 \
    --hparams=voc_config.yaml

python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d3   --ckpt_path=../../checkpoints/archive \
  --hparams=voc_config.yaml --batch_size=4 \
  --saved_model_dir=./saved_model  \
  --input_image=./test/* --output_image_dir=./results
```

**Comment by mingxingtan** [comment]
@thangdt You are right, I can reproduced the issue. It is probably a bug recently introduced due to the dynamic batch size support. Will debug and fix it soon.

**Comment by thangdt** [comment]
@mingxingtan thanks you so much!

**Comment by sourabhyadav** [comment]
> Yes, I am aware of that. It is not recommended to use dynamic batch inference on GPU.
> 
> In order to support dynamic batch size, we have to use the batch version NMS, but unfortunately batch version NMS can only run on CPU, which causes the slowness. I couldn't find better solution except adding a GPU version of batch NMS in TF, which would take considerable time and efforts.

@mingxingtan Thanks for your proactive support on the dynamic batching issues. 
Is there any plan to make it working on GPU? How can we help you to solve this issue asap?
Thanks again.

**Comment by mingxingtan** [comment]
Reopen this issue. My commit only fixed the static batch size issue, but the dynamic batch size is still slow.

@sourabhyadav Yeah, I have informed TF team and they do plan to add GPU support for this, but seems like it would  take some time.

**Comment by mingxingtan** [comment]
With https://github.com/google/automl/commit/d4f38ec9a9bade77834cab7a44a28caa48557445, dynamic batch size should have the same fast speed as static batch size. Command line is the same as before.
