### ISSUE TITLE
NaN loss during trainning.

### ISSUE THREAD

**Issue by YanqingWu** [google/automl#35]
have someone successful run the trainning code?

**Comment by bitwangdan** [comment]
@YanqingWu hi, I met the same problem as you, how did you solve it?

**Comment by wangtianlong1994** [comment]
I met it, too. Have you solved it?

**Comment by elesun2018** [comment]
when i run train code, meet a problem as follows:
/efficientdet# python main.py --training_file_pattern=tfrecord/train* --model_name=$MODEL --model_dir=model/$MODEL --hparams="use_bfloat16=false" --use_tpu=False

tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
 I decrease the learning rate from 0.08---> 0.01, and the same error. Thanks.
