### ISSUE TITLE
d4 model on the tutorial image performs badly

### ISSUE THREAD

**Issue by JunweiLiang** [google/automl#352]
Hi,
thanks for the great work. I have tried to run d4 model on the tutorial image but it seems for this particular image, d4 performs a lot worse than d0 model:
![0](https://user-images.githubusercontent.com/22200250/81027238-efcaf080-8e4a-11ea-88ef-5cab4a4b4c28.jpg)

Any reason why this might be the case?

**Comment by lessw2020** [comment]
I saw a similar issue with D1 and D0 - two weeks ago I ran it and had lots of detections.  
When I re-ran with latest code about 4 days ago, the D0 only labeled around 8 boxes on the street image.  
Thus it seems something was affected.  When I ran coco eval however, the mAP was about the same.

**Comment by JunweiLiang** [comment]
For me D0 model can output the same results as the tutorial.

**Comment by lessw2020** [comment]
Thanks for the info, maybe it was with D1 then.  To test, I just updated with latest git update to re-run but thetutorial  image is now the 2 dogs...so I can't compare readily.

**Comment by JunweiLiang** [comment]
D0 output:
![0](https://user-images.githubusercontent.com/22200250/81103630-50a40880-8edf-11ea-99fd-5b1b80a10de6.jpg)
D1 output:
![0](https://user-images.githubusercontent.com/22200250/81103663-61547e80-8edf-11ea-8a1a-141154ac771e.jpg)
D2 output:
![0](https://user-images.githubusercontent.com/22200250/81103678-66b1c900-8edf-11ea-8066-946ef7a0f414.jpg)
D3 output:
![0](https://user-images.githubusercontent.com/22200250/81103694-6c0f1380-8edf-11ea-9f04-1819019f18ed.jpg)
D4 output:
![0](https://user-images.githubusercontent.com/22200250/81103712-716c5e00-8edf-11ea-8ac3-cba3bbe041a7.jpg)
@mingxingtan 
I visualize them with the same score threshold 0.4. Could it be due to the fact that COCO objects are in general bigger than this image?

**Comment by mingxingtan** [comment]
Hi @JunweiLiang Very interesting finding!  This is a little counter-intuitive, and I don't know the reason for now. It would be worthy to look deeper why and how to make large models perform better on this kind of images (many very small objects).

**Comment by JunweiLiang** [comment]
Agreed. My experience on the [VIRAT](https://viratdata.org/) dataset (outdoor surveillance videos with many small people) in this [repo](https://github.com/JunweiLiang/Object_Detection_Tracking) is that models work well on COCO do not always improve on such dataset. Closing this issue for now.
