### ISSUE TITLE
skip box_net/box-1-bn-5/beta/Momentum (box_net/box-1-bn-5/beta/Momentum) -- not in ckpt

### ISSUE THREAD

**Issue by FancyFai** [google/automl#354]
![QQ图片20200505121003](https://user-images.githubusercontent.com/48304999/81034459-d3ba6400-8ec9-11ea-9b9a-4b977713e58c.png)
I met this problem in the training. Has anyone ever met this problem? Could you give me some advice

1:53:06.099293 140572431021824 utils.py:101] skip box_net/box-1/bias/Momentum (box_net/box-1/bias/Momentum) -- not in ckpt
I0505 11:53:06.099334 140572431021824 utils.py:101] skip box_net/box-1-bn-3/gamma/Momentum (box_net/box-1-bn-3/gamma/Momentum) -- not in ckpt
I0505 11:53:06.099375 140572431021824 utils.py:101] skip box_net/box-1-bn-3/beta/Momentum (box_net/box-1-bn-3/beta/Momentum) -- not in ckpt
I0505 11:53:06.099416 140572431021824 utils.py:101] skip box_net/box-2/depthwise_kernel/Momentum (box_net/box-2/depthwise_kernel/Momentum) -- not in ckpt
I0505 11:53:06.099458 140572431021824 utils.py:101] skip box_net/box-2/pointwise_kernel/Momentum (box_net/box-2/pointwise_kernel/Momentum) -- not in ckpt
I0505 11:53:06.099499 140572431021824 utils.py:101] skip box_net/box-2/bias/Momentum (box_net/box-2/bias/Momentum) -- not in ckpt
I0505 11:53:06.099540 140572431021824 utils.py:101] skip box_net/box-2-bn-3/gamma/Momentum (box_net/box-2-bn-3/gamma/Momentum) -- not in ckpt
I0505 11:53:06.099582 140572431021824 utils.py:101] skip box_net/box-2-bn-3/beta/Momentum (box_net/box-2-bn-3/beta/Momentum) -- not in ckpt
I0505 11:53:06.099623 140572431021824 utils.py:101] skip box_net/box-predict/depthwise_kernel/Momentum (box_net/box-predict/depthwise_kernel/Momentum) -- not in ckpt
I0505 11:53:06.099664 140572431021824 utils.py:101] skip box_net/box-predict/pointwise_kernel/Momentum (box_net/box-predict/pointwise_kernel/Momentum) -- not in ckpt
I0505 11:53:06.099706 140572431021824 utils.py:101] skip box_net/box-predict/bias/Momentum (box_net/box-predict/bias/Momentum) -- not in ckpt
I0505 11:53:06.099749 140572431021824 utils.py:101] skip box_net/box-0-bn-4/gamma/Momentum (box_net/box-0-bn-4/gamma/Momentum) -- not in ckpt
I0505 11:53:06.099792 140572431021824 utils.py:101] skip box_net/box-0-bn-4/beta/Momentum (box_net/box-0-bn-4/beta/Momentum) -- not in ckpt
I0505 11:53:06.099834 140572431021824 utils.py:101] skip box_net/box-1-bn-4/gamma/Momentum (box_net/box-1-bn-4/gamma/Momentum) -- not in ckpt
I0505 11:53:06.099875 140572431021824 utils.py:101] skip box_net/box-1-bn-4/beta/Momentum (box_net/box-1-bn-4/beta/Momentum) -- not in ckpt
I0505 11:53:06.099916 140572431021824 utils.py:101] skip box_net/box-2-bn-4/gamma/Momentum (box_net/box-2-bn-4/gamma/Momentum) -- not in ckpt
I0505 11:53:06.099957 140572431021824 utils.py:101] skip box_net/box-2-bn-4/beta/Momentum (box_net/box-2-bn-4/beta/Momentum) -- not in ckpt
I0505 11:53:06.099998 140572431021824 utils.py:101] skip box_net/box-0-bn-5/gamma/Momentum (box_net/box-0-bn-5/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100040 140572431021824 utils.py:101] skip box_net/box-0-bn-5/beta/Momentum (box_net/box-0-bn-5/beta/Momentum) -- not in ckpt
I0505 11:53:06.100081 140572431021824 utils.py:101] skip box_net/box-1-bn-5/gamma/Momentum (box_net/box-1-bn-5/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100122 140572431021824 utils.py:101] skip box_net/box-1-bn-5/beta/Momentum (box_net/box-1-bn-5/beta/Momentum) -- not in ckpt
I0505 11:53:06.100164 140572431021824 utils.py:101] skip box_net/box-2-bn-5/gamma/Momentum (box_net/box-2-bn-5/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100205 140572431021824 utils.py:101] skip box_net/box-2-bn-5/beta/Momentum (box_net/box-2-bn-5/beta/Momentum) -- not in ckpt
I0505 11:53:06.100246 140572431021824 utils.py:101] skip box_net/box-0-bn-6/gamma/Momentum (box_net/box-0-bn-6/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100289 140572431021824 utils.py:101] skip box_net/box-0-bn-6/beta/Momentum (box_net/box-0-bn-6/beta/Momentum) -- not in ckpt
I0505 11:53:06.100331 140572431021824 utils.py:101] skip box_net/box-1-bn-6/gamma/Momentum (box_net/box-1-bn-6/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100373 140572431021824 utils.py:101] skip box_net/box-1-bn-6/beta/Momentum (box_net/box-1-bn-6/beta/Momentum) -- not in ckpt
I0505 11:53:06.100414 140572431021824 utils.py:101] skip box_net/box-2-bn-6/gamma/Momentum (box_net/box-2-bn-6/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100455 140572431021824 utils.py:101] skip box_net/box-2-bn-6/beta/Momentum (box_net/box-2-bn-6/beta/Momentum) -- not in ckpt
I0505 11:53:06.100496 140572431021824 utils.py:101] skip box_net/box-0-bn-7/gamma/Momentum (box_net/box-0-bn-7/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100537 140572431021824 utils.py:101] skip box_net/box-0-bn-7/beta/Momentum (box_net/box-0-bn-7/beta/Momentum) -- not in ckpt
I0505 11:53:06.100578 140572431021824 utils.py:101] skip box_net/box-1-bn-7/gamma/Momentum (box_net/box-1-bn-7/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100619 140572431021824 utils.py:101] skip box_net/box-1-bn-7/beta/Momentum (box_net/box-1-bn-7/beta/Momentum) -- not in ckpt
I0505 11:53:06.100661 140572431021824 utils.py:101] skip box_net/box-2-bn-7/gamma/Momentum (box_net/box-2-bn-7/gamma/Momentum) -- not in ckpt
I0505 11:53:06.100702 140572431021824 utils.py:101] skip box_net/box-2-bn-7/beta/Momentum (box_net/box-2-bn-7/beta/Momentum) -- not in ckpt
INFO:tensorflow:Done calling model_fn.
I0505 11:53:07.976429 140572431021824 estimator.py:1147] Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
I0505 11:53:07.977227 140572431021824 basic_session_run_hooks.py:541] Create CheckpointSaverHook.
WARNING:tensorflow:Issue encountered when serializing edsummaries.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'tuple' object has no attribute 'name'
W0505 11:53:10.070527 140572431021824 meta_graph.py:449] Issue encountered when serializing edsummaries.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'tuple' object has no attribute 'name'
INFO:tensorflow:Graph was finalized.
I0505 11:53:12.660612 140572431021824 monitored_session.py:240] Graph was finalized.
2020-05-05 11:53:12.660831: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-05 11:53:12.685842: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2020-05-05 11:53:12.687055: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55acc02515f0 executing computations on platform Host. Devices:
2020-05-05 11:53:12.687068: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-05-05 11:53:12.855382: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 11:53:12.855721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2020-05-05 11:53:12.855799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 11:53:12.855982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2020-05-05 11:53:12.856079: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856122: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856159: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856195: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856231: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856266: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
2020-05-05 11:53:12.856280: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-05-05 11:53:12.856285: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2020-05-05 11:53:12.856370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-05 11:53:12.856376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 
2020-05-05 11:53:12.856380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N 
2020-05-05 11:53:12.856382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N 
2020-05-05 11:53:12.857728: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 11:53:12.857781: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 11:53:12.858697: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55acbfb49f80 executing computations on platform CUDA. Devices:
2020-05-05 11:53:12.858707: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-05-05 11:53:12.858712: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-05-05 11:53:15.839365: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
INFO:tensorflow:Running local_init_op.
I0505 11:53:18.135562 140572431021824 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0505 11:53:18.412272 140572431021824 session_manager.py:502] Done running local_init_op.
WARNING:tensorflow:Issue encountered when serializing edsummaries.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'tuple' object has no attribute 'name'
W0505 11:53:26.784028 140572431021824 meta_graph.py:449] Issue encountered when serializing edsummaries.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'tuple' object has no attribute 'name'
INFO:tensorflow:Saving checkpoints for 0 into tmp/efficientdet-d2-scratch/model.ckpt.

**Comment by qtw1998** [comment]
> ![QQ图片20200505121003](https://user-images.githubusercontent.com/48304999/81034459-d3ba6400-8ec9-11ea-9b9a-4b977713e58c.png)
> I met this problem in the training. Has anyone ever met this problem? Could you give me some advice
> 
> 1:53:06.099293 140572431021824 utils.py:101] skip box_net/box-1/bias/Momentum (box_net/box-1/bias/Momentum) -- not in ckpt
> I0505 11:53:06.099334 140572431021824 utils.py:101] skip box_net/box-1-bn-3/gamma/Momentum (box_net/box-1-bn-3/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.099375 140572431021824 utils.py:101] skip box_net/box-1-bn-3/beta/Momentum (box_net/box-1-bn-3/beta/Momentum) -- not in ckpt
> I0505 11:53:06.099416 140572431021824 utils.py:101] skip box_net/box-2/depthwise_kernel/Momentum (box_net/box-2/depthwise_kernel/Momentum) -- not in ckpt
> I0505 11:53:06.099458 140572431021824 utils.py:101] skip box_net/box-2/pointwise_kernel/Momentum (box_net/box-2/pointwise_kernel/Momentum) -- not in ckpt
> I0505 11:53:06.099499 140572431021824 utils.py:101] skip box_net/box-2/bias/Momentum (box_net/box-2/bias/Momentum) -- not in ckpt
> I0505 11:53:06.099540 140572431021824 utils.py:101] skip box_net/box-2-bn-3/gamma/Momentum (box_net/box-2-bn-3/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.099582 140572431021824 utils.py:101] skip box_net/box-2-bn-3/beta/Momentum (box_net/box-2-bn-3/beta/Momentum) -- not in ckpt
> I0505 11:53:06.099623 140572431021824 utils.py:101] skip box_net/box-predict/depthwise_kernel/Momentum (box_net/box-predict/depthwise_kernel/Momentum) -- not in ckpt
> I0505 11:53:06.099664 140572431021824 utils.py:101] skip box_net/box-predict/pointwise_kernel/Momentum (box_net/box-predict/pointwise_kernel/Momentum) -- not in ckpt
> I0505 11:53:06.099706 140572431021824 utils.py:101] skip box_net/box-predict/bias/Momentum (box_net/box-predict/bias/Momentum) -- not in ckpt
> I0505 11:53:06.099749 140572431021824 utils.py:101] skip box_net/box-0-bn-4/gamma/Momentum (box_net/box-0-bn-4/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.099792 140572431021824 utils.py:101] skip box_net/box-0-bn-4/beta/Momentum (box_net/box-0-bn-4/beta/Momentum) -- not in ckpt
> I0505 11:53:06.099834 140572431021824 utils.py:101] skip box_net/box-1-bn-4/gamma/Momentum (box_net/box-1-bn-4/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.099875 140572431021824 utils.py:101] skip box_net/box-1-bn-4/beta/Momentum (box_net/box-1-bn-4/beta/Momentum) -- not in ckpt
> I0505 11:53:06.099916 140572431021824 utils.py:101] skip box_net/box-2-bn-4/gamma/Momentum (box_net/box-2-bn-4/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.099957 140572431021824 utils.py:101] skip box_net/box-2-bn-4/beta/Momentum (box_net/box-2-bn-4/beta/Momentum) -- not in ckpt
> I0505 11:53:06.099998 140572431021824 utils.py:101] skip box_net/box-0-bn-5/gamma/Momentum (box_net/box-0-bn-5/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100040 140572431021824 utils.py:101] skip box_net/box-0-bn-5/beta/Momentum (box_net/box-0-bn-5/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100081 140572431021824 utils.py:101] skip box_net/box-1-bn-5/gamma/Momentum (box_net/box-1-bn-5/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100122 140572431021824 utils.py:101] skip box_net/box-1-bn-5/beta/Momentum (box_net/box-1-bn-5/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100164 140572431021824 utils.py:101] skip box_net/box-2-bn-5/gamma/Momentum (box_net/box-2-bn-5/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100205 140572431021824 utils.py:101] skip box_net/box-2-bn-5/beta/Momentum (box_net/box-2-bn-5/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100246 140572431021824 utils.py:101] skip box_net/box-0-bn-6/gamma/Momentum (box_net/box-0-bn-6/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100289 140572431021824 utils.py:101] skip box_net/box-0-bn-6/beta/Momentum (box_net/box-0-bn-6/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100331 140572431021824 utils.py:101] skip box_net/box-1-bn-6/gamma/Momentum (box_net/box-1-bn-6/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100373 140572431021824 utils.py:101] skip box_net/box-1-bn-6/beta/Momentum (box_net/box-1-bn-6/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100414 140572431021824 utils.py:101] skip box_net/box-2-bn-6/gamma/Momentum (box_net/box-2-bn-6/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100455 140572431021824 utils.py:101] skip box_net/box-2-bn-6/beta/Momentum (box_net/box-2-bn-6/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100496 140572431021824 utils.py:101] skip box_net/box-0-bn-7/gamma/Momentum (box_net/box-0-bn-7/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100537 140572431021824 utils.py:101] skip box_net/box-0-bn-7/beta/Momentum (box_net/box-0-bn-7/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100578 140572431021824 utils.py:101] skip box_net/box-1-bn-7/gamma/Momentum (box_net/box-1-bn-7/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100619 140572431021824 utils.py:101] skip box_net/box-1-bn-7/beta/Momentum (box_net/box-1-bn-7/beta/Momentum) -- not in ckpt
> I0505 11:53:06.100661 140572431021824 utils.py:101] skip box_net/box-2-bn-7/gamma/Momentum (box_net/box-2-bn-7/gamma/Momentum) -- not in ckpt
> I0505 11:53:06.100702 140572431021824 utils.py:101] skip box_net/box-2-bn-7/beta/Momentum (box_net/box-2-bn-7/beta/Momentum) -- not in ckpt
> INFO:tensorflow:Done calling model_fn.
> I0505 11:53:07.976429 140572431021824 estimator.py:1147] Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> I0505 11:53:07.977227 140572431021824 basic_session_run_hooks.py:541] Create CheckpointSaverHook.
> WARNING:tensorflow:Issue encountered when serializing edsummaries.
> Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
> 'tuple' object has no attribute 'name'
> W0505 11:53:10.070527 140572431021824 meta_graph.py:449] Issue encountered when serializing edsummaries.
> Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
> 'tuple' object has no attribute 'name'
> INFO:tensorflow:Graph was finalized.
> I0505 11:53:12.660612 140572431021824 monitored_session.py:240] Graph was finalized.
> 2020-05-05 11:53:12.660831: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-05-05 11:53:12.685842: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
> 2020-05-05 11:53:12.687055: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55acc02515f0 executing computations on platform Host. Devices:
> 2020-05-05 11:53:12.687068: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): ,
> 2020-05-05 11:53:12.855382: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-05-05 11:53:12.855721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
> name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
> pciBusID: 0000:01:00.0
> 2020-05-05 11:53:12.855799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-05-05 11:53:12.855982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
> name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
> pciBusID: 0000:02:00.0
> 2020-05-05 11:53:12.856079: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856122: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856159: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856195: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856231: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856266: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/home/ubuntu/ns-allinone-2.35/otcl-1.14/:/home/ubuntu/ns-allinone-2.35/lib/:/usr/local/lib/
> 2020-05-05 11:53:12.856280: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2020-05-05 11:53:12.856285: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
> 2020-05-05 11:53:12.856370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-05-05 11:53:12.856376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187] 0 1
> 2020-05-05 11:53:12.856380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0: N N
> 2020-05-05 11:53:12.856382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1: N N
> 2020-05-05 11:53:12.857728: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-05-05 11:53:12.857781: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-05-05 11:53:12.858697: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55acbfb49f80 executing computations on platform CUDA. Devices:
> 2020-05-05 11:53:12.858707: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
> 2020-05-05 11:53:12.858712: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
> 2020-05-05 11:53:15.839365: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set. If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU. To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
> INFO:tensorflow:Running local_init_op.
> I0505 11:53:18.135562 140572431021824 session_manager.py:500] Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> I0505 11:53:18.412272 140572431021824 session_manager.py:502] Done running local_init_op.
> WARNING:tensorflow:Issue encountered when serializing edsummaries.
> Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
> 'tuple' object has no attribute 'name'
> W0505 11:53:26.784028 140572431021824 meta_graph.py:449] Issue encountered when serializing edsummaries.
> Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
> 'tuple' object has no attribute 'name'
> INFO:tensorflow:Saving checkpoints for 0 into tmp/efficientdet-d2-scratch/model.ckpt.

Yeah, I have the same problem...

**Comment by mingxingtan** [comment]
This is expected, I intended to remove Momentum in checkpoint. This is because momentum is highly coupled with my own COCO training, if you retrain your own dataset or model, you should initialize your optimizer (possibly momentum or others) by yourself.

I agree that printing all these logs seem to be not helpful. I will try to remove them later.
