### ISSUE TITLE
convert saved model to float16

### ISSUE THREAD

**Issue by waltermaffy** [google/automl#358]
Hi, thank you for sharing and sorry for opening an issue.
Is there an easy way to convert a frozen model to float16 ?

**Comment by mingxingtan** [comment]
Hi @waltermaffy , if you run this command:

```
python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 \
  --hparams="precision=mixed_float16" \
  --saved_model_dir=/tmp/saved_model
```
The generated frozen graph /tmp/saved_model_efficientnet-d0.pb should be float16.
