### ISSUE TITLE
Resource exhausted: OOM when training

### ISSUE THREAD

**Issue by hongrui16** [google/automl#368]
### **when training EfficientDet-D6 and EfficientDet-D7, i got the error as following.**
E0506 10:00:20.742132 140400481330944 error_handling.py:70] Error recorded from training_loop: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[8,240,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node efficientnet-b6/model/blocks_5/se/mul-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

### **after i added the below setting in main.py, the error still emerged.**
_tf.enable_resource_variables()
config = tf.ConfigProto()
config.graph_options.rewrite_options.auto_mixed_precision=rewriter_config_pb2.RewriterConfig.ON
config.graph_options.rewrite_options.memory_optimization = rewriter_config_pb2.RewriterConfig.RECOMPUTATION_HEURISTICS
config.gpu_options.allow_growth = True_

### **i also put the configuration below before last  line (return .....) in function detection_loss() in det_model_fn.py,** 
_optimizer = tf.train.AdagradOptimizer(...)  # Or another optimization algorithm.
train_op = optimizer.minimize(
    total_loss,
    aggregation_method=tf.AggregationMethod.EXPERIMENTAL_ACCUMULATE_N)_

### **but there was another error as following:**

Call initializer instance with the dtype argument instead of passing it to the constructor
ERROR:tensorflow:Error recorded from training_loop: Failed to convert object of type <class 'ellipsis'> to Tensor. Contents: Ellipsis. Consider casting elements to a supported type.
E0507 01:10:29.723464 140000872568576 error_handling.py:70] Error recorded from training_loop: Failed to convert object of type <class 'ellipsis'> to Tensor. Contents: Ellipsis. Consider casting elements to a supported type.
INFO:tensorflow:training_loop marked as finished
I0507 01:10:29.723700 140000872568576 error_handling.py:96] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0507 01:10:29.723783 140000872568576 error_handling.py:130] Reraising captured error

**Comment by hongrui16** [comment]
@fsx950223  have you had any method that works? thanks.

**Comment by fsx950223** [comment]
h.precision = 'mixed_float16'

**Comment by hongrui16** [comment]
> h.precision = 'mixed_float16'

thx
could you tell me where to add this?

**Comment by fsx950223** [comment]
hparams_config.py

**Comment by hongrui16** [comment]
> hparams_config.py
### **sorry, after putting h.precision = 'mixed_float16' in hparams_config.py, the error was the same as before.**

tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[4,320,320,240] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node efficientnet-b6/model/blocks_7/tpu_batch_normalization/FusedBatchNorm-2-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[add_4/_21061]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[4,320,320,240] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node efficientnet-b6/model/blocks_7/tpu_batch_normalization/FusedBatchNorm-2-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

### Is there any way to run training on multiple GPUs?
### Even though set the option with multiple GPUs in this：
_os.environ["CUDA_VISIBLE_DEVICES"]=‘0，1, 2’_
### it's still the first GPU used for training.

**Comment by fsx950223** [comment]
h.var_freeze_expr = 'efficientnet'

**Comment by qtw1998** [comment]
> h.precision = 'mixed_float16'

What is the solution of https://github.com/google/automl/issues/365

**Comment by hongrui16** [comment]
> var_freeze_expr


--model_name=efficientdet-d5 --model_dir=trainout_saved/ --ckpt=pretrain_model/efficientdet-d5/ 

> > h.precision = 'mixed_float16'
> 
> What is the solution of #365

because there is none pretrained model file in 'efficientnet-b1' dir

**Comment by qtw1998** [comment]
> > var_freeze_expr
> 
> --model_name=efficientdet-d5 --model_dir=trainout_saved/ --ckpt=pretrain_model/efficientdet-d5/
> 
> > > h.precision = 'mixed_float16'
> > 
> > 
> > What is the solution of #365
> 
> because there is none pretrained model file in 'efficientnet-b1' dir

but I have no `pretrain_model/` both int the original or my cloned repo

**Comment by hongrui16** [comment]
> h.var_freeze_expr = 'efficientnet'
> The behavior will freeze the backbone.

### i did as you taught me that put h.var_freeze_expr = 'efficientnet'.
ps. whether there is no influence or not  even if i use efficientdet-dx  as pretrain model.
### 
### Even though i added  h.var_freeze_expr = 'efficientnet' as well,  model efficientdet-d4 and the upper one were not available, as i could still got OOM error.

After i changed model to efficientdet-d3 and the lower one, it could run and there was a warning as following:

2020-05-07 03:35:23.158825: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-05-07 03:35:27.231011: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.25GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

### Without  " h.precision = 'mixed_float16' h.var_freeze_expr = 'efficientnet' ", OOM error could emerge when efficientdet-d3 was used.

**Comment by hongrui16** [comment]
> > > var_freeze_expr
> > 
> > 
> > --model_name=efficientdet-d5 --model_dir=trainout_saved/ --ckpt=pretrain_model/efficientdet-d5/
> > > > h.precision = 'mixed_float16'
> > > 
> > > 
> > > What is the solution of #365
> > 
> > 
> > because there is none pretrained model file in 'efficientnet-b1' dir
> 
> but I have no `pretrain_model/` both int the original or my cloned repo

you can leave --ckpt setting to default, which means delete --ckpt option in your cmdline

**Comment by qtw1998** [comment]
> > > > var_freeze_expr
> > > 
> > > 
> > > --model_name=efficientdet-d5 --model_dir=trainout_saved/ --ckpt=pretrain_model/efficientdet-d5/
> > > > > h.precision = 'mixed_float16'
> > > > 
> > > > 
> > > > What is the solution of #365
> > > 
> > > 
> > > because there is none pretrained model file in 'efficientnet-b1' dir
> > 
> > 
> > but I have no `pretrain_model/` both int the original or my cloned repo
> 
> you can leave --ckpt setting to default, which means delete --ckpt option in your cmdline

Even I give up using ckpt either backbone or pretained, it also has this error info...

**Comment by hongrui16** [comment]
![image](https://user-images.githubusercontent.com/9922473/81270044-bda0d500-907c-11ea-97ac-38f33f556bbc.png)
