### ISSUE TITLE
error in change num_classes

### ISSUE THREAD

**Issue by zhangchaosunshine** [google/automl#37]
To fit my task, i change num_classes from 90 to 6 in hparams_config.py and model_inspect.py. But error happens. 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [54] rhs shape= [810]
Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_363:
 class_net/class-predict/bias (defined at /home/work/zc/automl/efficientdet/efficientdet_arch.py:201)

I found it caused by somewhere about num_classed that not be changed . 
how can i fix it ? and when i train custom model, do I need to change other code?

**Comment by zhangchaosunshine** [comment]
I use efficientdet-d0 as model backbone.

**Comment by mingxingtan** [comment]
@zhangchaosunshine Looks like you are loading a coco-pretrained efficientdet-d0, which cause the shape mismatch.

You need to exclude the output layer weights since their #classes are different.

**Comment by mingxingtan** [comment]
To make it easier to specify num_classes, I have added https://github.com/google/automl/commit/4e7ae2b31c643ac68eba780fcf983e7c9f77e766

Since I have verified it works well on my computer, I am going to close this issue for now. Please feel free to reopen it if you still have this issue.
