### ISSUE TITLE
load meta

### ISSUE THREAD

**Issue by gtgtgt1117** [google/automl#374]
@mingxingtan 

hello,when i load the meta,the error append.:
KeyError: "The name 'lrn_rate' refers to an Operation not in the graph."
the ckpt_model is trained by  my datasets

why?

**Comment by gtgtgt1117** [comment]
> @mingxingtan
> 
> hello,when i load the meta,the error append.:
> KeyError: "The name 'lrn_rate' refers to an Operation not in the graph."
> the ckpt_model is trained by my datasets
> 
> why?

the command is 
python main.py  --mode=train --training_file_pattern=tfrecord/train* --model_name=efficientdet-d0 --train_batch_size=8 --eval_batch_size=8 --eval_samples=1024 --num_examples_per_epoch=53175 --num_epochs=1 --hparams=data_config.yaml --use_tpu=False --model_dir=./tmp --ckpt=./efficientdet-d0

**Comment by mingxingtan** [comment]
Since the tutorial runs well, I assume this is due to your local code issue. Closing this issue for now.
