### ISSUE TITLE
tflite model error

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#382]
I tried to infer after converting a pre-trained model to 'tflite' on Windows, but an error occurred while loading the model.

ValueError: Model provided has model identifier '|

**Comment by Ekta246** [comment]
Hey WonThaYeon

> I tried to infer after converting a pre-trained model to 'tflite' on Windows, but an error occurred while loading the model.
> 
> ValueError: Model provided has model identifier '|�

Do you mind sharing the .tflite model files for the pretrained Efficientdet models?
Somehow, I am unable to produce them.

**Comment by Ekta246** [comment]
> I tried to infer after converting a pre-trained model to 'tflite' on Windows, but an error occurred while loading the model.
> 
> ValueError: Model provided has model identifier '|�

@WonTaeYeon Would you mind sharing me the .tflite file for the pre-trained model?
How did you achieve converting it?

Looking forward to your help!

**Comment by sunshinee24** [comment]
> I tried to infer after converting a pre-trained model to 'tflite' on Windows, but an error occurred while loading the model.
> 
> ValueError: Model provided has model identifier '|�

hello, have you successfully converted the .ckpt to .tflite ? If so, can you share it ?

**Comment by Ekta246** [comment]
> > I tried to infer after converting a pre-trained model to 'tflite' on Windows, but an error occurred while loading the model.
> > ValueError: Model provided has model identifier '|�
> 
> hello, have you successfully converted the .ckpt to .tflite ? If so, can you share it ?

Yes, I have managed it to convert it by passing the Signature_def_keys to the concrete function and the TFLite Interpreter. I will share it with you.

**Comment by yaysummeriscoming** [comment]
I got conversion to work with an older tf nightly build:
pip install tf-nightly==2.2.0.dev20200405

**Comment by Ekta246** [comment]
@yaysummeriscoming Were you able to get a quantized .tflite file?

**Comment by mingxingtan** [comment]
Hello, if you checkout tf-2.3.0-dev20200521 or later (tf-nightly), then you should be able to run the following command line to generate tflite:

```
python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
      --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
      --tflite_path=efficientdet-d0.tflit
```
