### ISSUE TITLE
saved_model error

### ISSUE THREAD

**Issue by gtgtgt1117** [google/automl#383]
@mingxingtan 
python model_inspect.py --runmode=saved_model \
 --model_name=efficientdet-d0 --ckpt_path=model_grap/efficientdet-d0-scratch \
 --hparams="image_size=1920x1280" --saved_model_dir=tmp/model_dir

ValueError: At least two variables have the same name: box_net/box-0-bn-3/beta

thanks

**Comment by mingxingtan** [comment]
Hi @gtgtgt1117 Could you check out the latest code and try again? I just tried your command line and it worked well on my side.

**Comment by gtgtgt1117** [comment]
> Hi @gtgtgt1117 Could you check out the latest code and try again? I just tried your command line and it worked well on my side.



Thanks !
when i saved the efficientdet-b0's model,it worked well.
i think that i saved custom's model is incorrect.
