### ISSUE TITLE
does it means I'm using 'ciou' at present?

### ISSUE THREAD

**Issue by qtw1998** [google/automl#388]
![image](https://user-images.githubusercontent.com/34357479/81434783-5167c380-9199-11ea-8653-d02e4d99f0c4.png)
hoping for your helping hands!

**Comment by qtw1998** [comment]
![image](https://user-images.githubusercontent.com/34357479/81436568-48c4bc80-919c-11ea-826b-64a260310ad2.png)
Why the parts are not connceted?

**Comment by mingxingtan** [comment]
Hi @qtw1998 , iou_loss is not used in default. It is controlled by this hparams:

https://github.com/google/automl/blob/b51a960e6af1a48c19a15977a18760b0c824b511/efficientdet/hparams_config.py#L215

which is used in this code:

https://github.com/google/automl/blob/b51a960e6af1a48c19a15977a18760b0c824b511/efficientdet/det_model_fn.py#L311

I was not able to get good results with IOU loss so far. It might need more tuning.

**Comment by mingxingtan** [comment]
I am closing this issue for now, but if you have new findings about iou_loss, feel free to reopen it. Thanks!

**Comment by qtw1998** [comment]
> Hi @qtw1998 , iou_loss is not used in default. It is controlled by this hparams:
> 
> https://github.com/google/automl/blob/b51a960e6af1a48c19a15977a18760b0c824b511/efficientdet/hparams_config.py#L215
> 
> which is used in this code:
> 
> https://github.com/google/automl/blob/b51a960e6af1a48c19a15977a18760b0c824b511/efficientdet/det_model_fn.py#L311
> 
> I was not able to get good results with IOU loss so far. It might need more tuning.

thank you for your replying! by the way, What's your meaning? do u mean use the origin IOU is not working well? and ciou is better?

**Comment by mingxingtan** [comment]
I just replaced the original box loss weight iou loss, and did not get better results so far.  Haven't trred giou/ciou/diou loss yet.

**Comment by thangdt** [comment]
@mingxingtan i can training model with giou, diou loss type. But with ciou it's alway pending at "Saving checkpoints" and never run to next state. Can you check it? Thanks!
