### ISSUE TITLE
[Bug] inference will lose last class.

### ISSUE THREAD

**Issue by fsx950223** [google/automl#391]
If I set num_classes=20, I got
```
{1: 0.8251461474684836, 2: 0.6057265860729696, 3: 0.5669948076300985, 4: 0.4562657160206033, 5: 0.7429293036372138, 6: 0.8488521639745101, 7: 0.7505952338633199, 8: 0.4607134514016136, 9: 0.5838188873557933, 10: 0.6237728590208836, 11: 0.695892376993211, 12: 0.7641680764251374, 13: 0.7476111044488312, 14: 0.8243006377018767, 15: 0.47873758514597653, 16: 0.5927701428585805, 17: 0.6013602171194697, 18: 0.7806544212369046, 19: 0.6962750837697835, 20: 0}
```
The last class's AP is always zero.
I have to set num_classes=21 for training model to fix the issue.
Every class+1 may cause the bug.

**Comment by mingxingtan** [comment]
Good point.

Class id 0 is reserved for background (no object), maybe we should internally always use config.num_classes+1 . WDYT?

**Comment by fsx950223** [comment]
I agree.

**Comment by fsx950223** [comment]
My fault. I use my own tfrecord create script and forgot to add background

**Comment by mingxingtan** [comment]
Hi @fsx950223 How do you get per-class AP? 
I found some discussion like [this](https://github.com/tensorflow/models/issues/4778), but they all need some changes to pycocotools. I wonder do you happen to know some better way such that we can just enable per-class AP in this codebase? Thanks!
