### ISSUE TITLE
mixed_float16 and XLA not compatible

### ISSUE THREAD

**Issue by LucasSloan** [google/automl#392]
I tried out the h.precision = mixed_float16 flag, and it allowed me to up my batch size from 16 to 32 training with efficientdet-d0.

However, it dropped my training speed from ~50 images/s to ~14 images/s, which is approximately the speed I see when I don't set `TF_XLA_FLAGS=--tf_xla_auto_jit=2`.

**Comment by mingxingtan** [comment]
According to https://github.com/google/automl/issues/351, looks like you need to upgrade to tensorflow tensorflow 2.2.0rc4 or later (like nightly)?

**Comment by mingxingtan** [comment]
@reedwm to keep him posted.

**Comment by LucasSloan** [comment]
Using the tensorflow nightly build fixed the issue, thanks!
