### ISSUE TITLE
tflite: Inference based on model trained on PASCAL VOC2012.

### ISSUE THREAD

**Issue by cam145** [google/automl#395]
# Inference based on model trained on PASCAL VOC2012

Currently I am trying to tweaking the efficientdet model to speed it up a little bit further as it runs on my laptop (i7-7250) with throughput ~ 4 fps (close to the data shown in the paper). I am aware that that the model is not supported by the TFlite yet, otherwise it can run much faster. 

Firstly, I tried to plug efficientnet-lite0 model (downloaded from Google website) to replace the efficientnet-b0 backbone and trained on PASCAL VOC2012.  The training worked (I just need a model with efficientnet-lite0 as backbone).

Based on the trained model, I run the following command lines:
~~~~
# remove the existing folder
rm -rf savedmodel-lite0
# save model and frozen graph from ckpt
python model_inspect.py --runmode=saved_model --model_name=efficientdet-lite0 --ckpt_path=efficientdet-lite0 --saved_model_dir=savedmodel-lite0 --batch_size=1
# run inference on a single image
python model_inspect.py --runmode=saved_model_benchmark --model_name=efficientdet-lite0 --ckpt_path=efficientdet-lite0 --saved_model_dir=./savedmodel-lite0 --batch_size=1 --hparams="num_classes=20, act_type=relu6" --input_image=testdata/img1.jpg
~~~~
However, I got the following information and the process stopped:

tensorflow.python.framework.errors_impl.InvalidArgumentError: scores has incompatible shape
	 [[{{node non_max_suppression_with_scores/NonMaxSuppressionV5}}]]

==========================================================================
I also run the following command line to load frozen graph directly:
~~~~
python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-lite0 --ckpt_path=efficientdet-lite0 --saved_model_dir=./savedmodel-lite0/efficientdet-lite0_frozen.pb --batch_size=1 --hparams="moving_average_decay=0.998, num_classes=20, act_type=relu6" --input_image=testdata/img1.jpg
~~~~
I got the following error information:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 49104 and 10912 for 'non_max_suppression_with_scores/NonMaxSuppressionV5' (op: 'NonMaxSuppressionV5') with input shapes: [49104,4], [10912], [], [], [], [].

===========================================================================
I am not sure if this results from the training processes or something else.

So,  I moved back to  train Pascal VOC 2012 from ImageNet checkpoint for Backbone (efficientnet-b0) using the following command line:
~~~~
MODEL=efficientdet-d0
backbone_name=efficientnet-b0
file_pattern = 'pascal-*-of-00100.tfrecord'

python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/{file_pattern} \
    --validation_file_pattern=tfrecord/{file_pattern} \
    --val_json_file=tfrecord/json_pascal.json \
    --model_name={MODEL} \
    --model_dir={model_dir}/{MODEL}-scratch  \
    --backbone_ckpt={backbone_name} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=512  \
    --num_examples_per_epoch=5717 --num_epochs=20  \
    --hparams="num_classes=20,moving_average_decay=0.998" \
    --use_tpu=False 
~~~~
I then run the following command lines:
~~~~
# remove existing folder
rm -rf savedmodel-d0
# save model from ckpt
python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodel-d0 --batch_size=1  --hparams="moving_average_decay=0.998,num_classes=20" use_tpu=False
~~~~
 Then I tried to run benchmark .
~~~~
python model_inspect.py --runmode=saved_model_benchmark --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=./savedmodel-d0 --batch_size=1  --input_image=img.png --hparams="moving_average_decay=0.998,num_classes=20" use_tpu=False
~~~~
it worked.

Then I tried to do inference on a single image via the following command line:
~~~~
python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=./savedmodel-d0 --batch_size=1  --input_image=img.png --hparams="moving_average_decay=0.998,num_classes=20" use_tpu=False --output_image_dir=./
~~~~~
it worked as well.

=====================================================================

As I kept the training command line the same for both efficientnet-lite0 and efficientnet-b0 backbones. However, the model trained with efficientnet-lite0 backbone seems not work. 

I wonder if anyone has tried this and the Google Brain Team would be kind enough to give me some hints on the errors. If you are interested, I can share the ckpt for the trained model with efficientnet-lite0. 

Thanks in advance.

**Comment by zishanahmed08** [comment]
@cam145 I also face the same issue. To clarify,  By **efficientnet-lite0** you mean Section 4.2 in **tutorial.ipynb** and **efficientnet-b0** you refer to Section 4.3

**Comment by cam145** [comment]
> @cam145 I also face the same issue. To clarify, By **efficientnet-lite0** you mean Section 4.2 in **tutorial.ipynb** and **efficientnet-b0** you refer to Section 4.3

In Section 4.2, I modified a bit:
~~~~
# Train efficientdet from scratch with backbone checkpoint.
MODEL='efficientdet-lite0'
backbone_name = {
    'efficientdet-lite0': 'efficientnet-lite0',
    'efficientdet-d0': 'efficientnet-b0',
    'efficientdet-d1': 'efficientnet-b1',
    'efficientdet-d2': 'efficientnet-b2',
    'efficientdet-d3': 'efficientnet-b3',
    'efficientdet-d4': 'efficientnet-b4',
    'efficientdet-d5': 'efficientnet-b5',
    'efficientdet-d6': 'efficientnet-b6',
    'efficientdet-d7': 'efficientnet-b6',
}[MODEL]


# generating train tfrecord is large, so we skip the execution here.
import os
if backbone_name not in os.listdir():
  # !wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/{backbone_name}.tar.gz
  !wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/lite/{backbone_name}.tar.gz  
  !tar xf {backbone_name}.tar.gz
~~~~
So I train Pascal VOC 2012 from ImageNet checkpoint for Backbone with efficientnet-lite0.

**Comment by zishanahmed08** [comment]
@mingxingtan Should I open a seperate issue.  @cam145 faces this issue with efficientnet-lite0. However, i face it with  training from COCO checkpoint for the whole net

**Comment by mingxingtan** [comment]
@cam145 seems to have resolved this issue?

**Comment by cam145** [comment]
> @cam145 seems to have resolved this issue?

@mingxingtan Yes. I used to the following command line (based on the training command line):

~~~~
rm -rf savedmodel-lite0
python model_inspect.py --runmode=saved_model --model_name=efficientdet-lite0 --ckpt_path=efficientdet-lite0 --saved_model_dir=savedmodel-lite0 --batch_size=1 --hparams="moving_average_decay=0.998,num_classes=20"
~~~~

Previously, the " --hparams="moving_average_decay=0.998,num_classes=20"" was not include.

I am aware that the team behind this amazing work are working on a 'lite' version of efficientdet. 

I tried tflite as well and got the following error information:

~~~~
 raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
~~~~

Anyway, many thanks and this work is highly appreciated.

**Comment by mingxingtan** [comment]
Hi all, you should be able to convert tflite using this command: https://github.com/google/automl/tree/master/efficientdet#3-export-savedmodel-frozen-graph-tensort-models-or-tflite

**Comment by hungbui-io** [comment]
Hello @mingxingtan , 
I am interested in using quantization aware training as well as full integer quantization with EfficientDet. Are they going to be supported?
