### ISSUE TITLE
Convert to TensorRT and run inference 

### ISSUE THREAD

**Issue by JZlearnCode** [google/automl#399]
Hello, thanks a lot for sharing this great work! 

May I ask if anyone has successfully converted the models to TensorRT and ran inference on image? Thanks!

**Comment by mingxingtan** [comment]
https://github.com/google/automl/issues/389
@suhyung-code42 seems to be able to run with tensorRT.

**Comment by suhyung-code42** [comment]
@mingxingtan I met another error. I have not run inference with tensorRT.

**Comment by JZlearnCode** [comment]
The tensorRT inference speed is the same as frozen model. Saw similar question here, not sure if anyone got a better result. Thanks!  https://github.com/google/automl/issues/331

**Comment by suhyung-code42** [comment]
@JZlearnCode did you inference with tensorrt successfully?

**Comment by JZlearnCode** [comment]
@suhyung-code42 Sorry, it's not successful. For a successful conversion, there should be speed gains. I was seeing the same issue as mentioned here https://github.com/google/automl/issues/331

**Comment by RoboEvangelist** [comment]
Let me know what your findings are. Do you have any sample code that you are using? Also, do you run this in C++?

**Comment by JZlearnCode** [comment]
@RoboEvangelist I was using the same way described here. https://github.com/google/automl/issues/331   Seems like several posts here are for this TensorRT conversion topic. Please post here if you successfully converted the tensorRT.  To avoid confusion, I'll close this ticket for now since it's a duplicate of 331   : )
