### ISSUE TITLE
How to run Multi-GPU with Horovod

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#400]
Basically you need to install Horovod and make following changes in `main.py`:

```
import horovod.tensorflow as hvd
...

def main(argv):
  ....
  hvd.init()
  ....

  config_proto.gpu_options.visible_device_list = str(hvd.local_rank())

  .....
  run_config = tf.estimator.tpu.RunConfig(
      cluster=tpu_cluster_resolver,
      evaluation_master=FLAGS.eval_master,
      model_dir=(FLAGS.model_dir if hvd.rank() == 0 else None),
      log_step_count_steps=FLAGS.iterations_per_loop,
      session_config=config_proto,
      tpu_config=tpu_config,
      tf_random_seed=FLAGS.tf_random_seed
  )

```
And in `det_model_fn.py`:

```
import horovod.tensorflow as hvd

def _model_fn(features, labels, mode, params, model, variable_filter_fn=None):
     ...
    if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.train.MomentumOptimizer(
        learning_rate * hvd.size(), momentum=params['momentum'])
    if params['use_tpu']:
      optimizer = tf.tpu.CrossShardOptimizer(optimizer)

    optimizer = hvd.DistributedOptimizer(optimizer)
    hooks = [hvd.BroadcastGlobalVariablesHook(0)]

    ...
    
      return tf.estimator.tpu.TPUEstimatorSpec(
      mode=mode,
      loss=total_loss,
      train_op=train_op,
      eval_metrics=eval_metrics,
      host_call=utils.get_tpu_host_call(global_step, params),
      scaffold_fn=scaffold_fn,
      training_hooks=hooks)
```

And run `main.py` in `train` mode

for 4 GPU server like this:

```
horovodrun -np 4 -H localhost:4 python main.py --mode=train \
.....
```

**Comment by iamastar88** [comment]
So it really can work?

**Comment by hongrui16** [comment]
what is you environment? like tensorflow version, etc.

**Comment by elv-xuwen** [comment]
I followed this repo (https://github.com/itsliupeng/automl/tree/master/efficientdet) and it can work. I also tried running with single GPU with batchsize==8 but I can only get mAP 0.297. Did anyone reproduce the author's result without multi GPU?

**Comment by fsx950223** [comment]
Awesome.

**Comment by hongrui16** [comment]
> I followed this repo (https://github.com/itsliupeng/automl/tree/master/efficientdet) and it can work. I also tried running with single GPU with batchsize==8 but I can only get mAP 0.297. Did anyone reproduce the author's result without multi GPU?

do you mean you did training and evaluation on coco?

**Comment by elv-xuwen** [comment]
Hi @hongrui16 , yes, I trained D0 on coco.

**Comment by elv-xuwen** [comment]
Hi @fsx950223 , did you test the "add horovod" on multi gpu? Does it reproduce the mAP provided by the author?
