### ISSUE TITLE
tf 2.2 is slower than tf2.1

### ISSUE THREAD

**Issue by VicariNishimura** [google/automl#402]
On RTX 2080Ti with tf 2.1 I got FPS between 50/65 but with 2.2 it drops to 30/45. Have you any idea what can cause this ? (Not related to code as it the same that run on both cases)

**Comment by LucasSloan** [comment]
The same thing happened to me - my guess is a change in how XLA optimized it, I'll try to get the xla optimizater debug info later today, if @mingxingtan can pass that along to the tensorflow folks?

**Comment by LucasSloan** [comment]
I wasn't able to repro this - when I tried to run with tf 2.1, I got an Out of Memory error.  I also tried with tf 2.0, where it did run, but only at 30 examples/s.  tf 2.2 was 50 examples/s.  I definitely used to get 60-70 examples/s, but I think it was one of the tf 2.2 rc's.  I'll take another look tomorrow.

**Comment by mingxingtan** [comment]
Thanks @LucasSloan Do you happen to find out the problem?

**Comment by LucasSloan** [comment]
I wasn't able to find a version of tensorflow that got me back to the 60-70 examples/s I used to get.  I'm pretty sure that there was a change in the efficientdet codebase that made that no longer possible.  With the latest version of the code and tf 2.3, I'm getting 60 examples/s.
