### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by srika91** [google/automl#403]
In tensorflow 2.1.0 setting gpu to allow memory growth is not working yet.What is efficientDet's GPU memory Consumption,any benchmarks for that or can we calculate from the FLOPS itsel? Any recommended ways to find this? .Currently it always occupies the full gpu.

**Comment by VicariNishimura** [comment]
It is working for me, can you share how you try to do ? FYI I get 4.4Go for D0 and 7.3Go for D1
