### ISSUE TITLE
How to tune offset and scale

### ISSUE THREAD

**Issue by fsx950223** [google/automl#407]
https://github.com/google/automl/blob/031e8067a1140a89103d47fc12aa84dfb1f3596d/efficientdet/dataloader.py#L60
Do these values depend on datasets?

**Comment by VicariNishimura** [comment]
This is from Imagenet, it's commonly use for standardization of natural images. OFC one can change it by recompute mean/std of their own datasets

**Comment by fsx950223** [comment]
> This is from Imagenet, it's commonly use for standardization of natural images. OFC one can change it by recompute mean/std of their own datasets

Yes. It should be a hparam.

**Comment by VicariNishimura** [comment]
Yep, but with a warning message because as for manual anchors it might encourage overfitting

**Comment by mingxingtan** [comment]
Good point, this is borrowed from ImageNet, I am not sure how much impact do they have for detection. If they do, we should make it configurable. (but I doubt it probably doesn't matter much)
