### ISSUE TITLE
hparams="image_size=1920x1280" doesn't work when doing inference with saved model

### ISSUE THREAD

**Issue by KaqiKaqi** [google/automl#415]
I'm doing the following step in Readme section 5
`# Step 2: do inference with saved model.
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --hparams="image_size=1920x1280"  \
  --saved_model_dir=/tmp/saved_model  \
  --input_image=img.png --output_image_dir=/tmp/`

I found the detection result is different from the readme.  The result looks exactly same as image_size=512x512 using InfernceDriver.

In `model_inspect.py`, in `saved_model_inference` method, images got resized only `if len(set([m.size for m in images])) > 1`. Otherwise, hparams="image_size=1920x1280" is not used.

Besides,` images = [m.resize(height, width) for m in images] ` should be ` images = [m.resize((height, width)) for m in images]`. And the first dimension of `detections_bs` seem to remain 1, which causes bug in the following loop.

Thanks a lot : )

**Comment by KaqiKaqi** [comment]
hparams="image_size=1920x1280" is useful when exporting saved model.

**Comment by mingxingtan** [comment]
@KaqiKaqi thanks for pointing this out. Yes, image_size is actually determined when the model is exported. I updated the README to reflect this.
