### ISSUE TITLE
Incorrect detection boxes when inferring from a certain commit.

### ISSUE THREAD

**Issue by DamGameHero** [google/automl#417]
Hello,

With the latest version of the code, since this commit https://github.com/google/automl/commit/df587df77b7d7b6867259f378eb9bb7ed408383a and the deletion in _efficientdet/inference.py_ of this line:
`   boxes[:, 2:4] += boxes[:, 0:2]`

I have incorrect detection boxes (larger and slightly shifted).

When I put this line back, the detection boxes are correct again.

Here is my command line:
`python3 model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d5 --ckpt_path=/home/dam/models/efficientdet-d5 --saved_model_dir=/home/dam/saved_efficientdet-d5/  --hparams="image_size=1024,num_classes=1,moving_average_decay=0,label_id_mapping=id_map.yaml" --input_image=/home/dam/test_images/* --output_image_dir=/tmp/results`

Thank you in advance for the time invested in my problem.

**Comment by fsx950223** [comment]
You should try it on colab.

**Comment by DamGameHero** [comment]
Ok. I had saved the model with an old version of the code that may be the source of my problem. I'll see that tomorrow and update the issue. Thank you

**Comment by DamGameHero** [comment]
I confirm that by exporting the saved model again, I no longer have this problem with boxes.

Conclusion: I will always regenerate the saved model for inference in case modifications have been made. Thank you.
