### ISSUE TITLE
StringToNumberOp could not correctly convert string

### ISSUE THREAD

**Issue by mfaramarzi** [google/automl#418]
@juzhiyuan @willnorris @cdibona @dberlin @Ely-S @fsx950223 
Plz help. I am trying to train a custom datasets but getting the following error when start training:

![error-tf-conver string](https://user-images.githubusercontent.com/44882423/82216651-41fa2000-98e7-11ea-9d1d-44997329f3db.png)

here is my command line:

python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/train.record \
    --validation_file_pattern=tfrecord/test.record \
    --model_name=efficientdet-d0 \
    --model_dir=/tmp/efficientdet-d0-scratch  \
    --backbone_ckpt=efficientnet-b0  \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=512 \
    --num_examples_per_epoch=5717 --num_epochs=1  \
    --hparams="num_classes=4,moving_average_decay=0" \
    --use_tpu=False

**Comment by Electrawizard** [comment]
Have the same issue and can't find the sollution, have you solved?

**Comment by mfaramarzi** [comment]
> Have the same issue and can't find the sollution, have you solved?

unfortunately not.

**Comment by mingxingtan** [comment]
Hi @mfaramarzi 

Most likely, you are using a custom dataset, and the problem is caused by the way you convert your dataset.  Because pycocotools only allows image_id to be integer, but looks like you use filename "Czech_000319.jpg" as the image_id, and pycocool fails to convert it into integer.

If you are using create_pascal_tfrecord, could you check out the latest code and re-convert your data to tfrecord? (I changed the code to not use filename as image_id a while ago).

**Comment by mingxingtan** [comment]
the pycocotool restriction of "image_id must be integer" is quite annoying, we should get rid of it in future.

**Comment by Electrawizard** [comment]
> Hi @mfaramarzi
> 
> Most likely, you are using a custom dataset, and the problem is caused by the way you convert your dataset. Because pycocotools only allows image_id to be integer, but looks like you use filename "Czech_000319.jpg" as the image_id, and pycocool fails to convert it into integer.
> 
> If you are using create_pascal_tfrecord, could you check out the latest code and re-convert your data to tfrecord? (I changed the code to not use filename as image_id a while ago).

Yes, thats true, i am re-generating my tfrecords now, i found that .jpg extension was in image_id, i've deleted it generate records again, but had the same error without .jpg extesion

**Comment by mfaramarzi** [comment]
> Hi @mfaramarzi
> 
> Most likely, you are using a custom dataset, and the problem is caused by the way you convert your dataset. Because pycocotools only allows image_id to be integer, but looks like you use filename "Czech_000319.jpg" as the image_id, and pycocool fails to convert it into integer.
> 
> If you are using create_pascal_tfrecord, could you check out the latest code and re-convert your data to tfrecord? (I changed the code to not use filename as image_id a while ago).

I used the update "create_pascal_tfrecord"  ([https://github.com/google/automl/blob/master/efficientdet/dataset/create_pascal_tfrecord.py])
Does it mean that I have to change images' IDs to integers?

**Comment by mingxingtan** [comment]
Yes, please use create_pascal_tfrecord.py, which changes the image_id to be integer:

https://github.com/google/automl/blob/786f9f459e52d9d90650b1635f200ffaf21c6677/efficientdet/dataset/create_pascal_tfrecord.py#L97

Otherwise, you should change your own script to set image_id as integer.

**Comment by Electrawizard** [comment]
> Yes, please use create_pascal_tfrecord.py, which changes the image_id to be integer:
> 
> https://github.com/google/automl/blob/786f9f459e52d9d90650b1635f200ffaf21c6677/efficientdet/dataset/create_pascal_tfrecord.py#L97
> 
> Otherwise, you should change your own script to set image_id as integer.

That worked for me, i've changed the script a little for my data and training started with no errors, Thanks!
