### ISSUE TITLE
 Variable efficientnet-b3/stem/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

### ISSUE THREAD

**Issue by hongrui16** [google/automl#419]
### i wanted to run inference on an input image dir, so i modified the code in fun inference() in inference.py as following

      with tf.Session() as sess:
          # tf.reset_default_graph() 
        for img_name in image_names:
          image_path_pattern = os.path.join(input_dir, img_name)
          raw_images, images, scales = build_inputs(image_path_pattern,
                                                    params['image_size'])# Buid inputs and preprocessing.

          # image_name = image_path_pattern.split('/')[-1]
          if params['data_format'] == 'channels_first':
            images = tf.transpose(images, [0, 3, 1, 2])
          # Build model.
          class_outputs, box_outputs = build_model(self.model_name, images,
                                                   **self.params)

### i got the error:
 Variable efficientnet-b3/stem/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

### is there anyone ever solving the error?
many thanks

**Comment by fsx950223** [comment]
Try ServingDriver.

**Comment by mingxingtan** [comment]
Hi @hongrui16 The problem is that you call "build_model" in a loop, which would repeatedly construct new graphs with the same variable name.  You should build the graph before the loop, and then just run the sess.run in the loop.

As @fsx950223 pointed out, ServingDriver is highly recommended.
