### ISSUE TITLE
NameError: name 'unicode' is not defined   : pycocotools compatability issue

### ISSUE THREAD

**Issue by Samjith888** [google/automl#422]
I'm just informing you that , i got error ` 'NameError: name 'unicode' is not defined '`
I have installed the required packages using `pip install -r requirements.txt`
where [pycocotools==2.0.0](https://github.com/google/automl/blob/master/efficientdet/requirements.txt#L5) is installed which have compatible issues with this repo..

Solved issue by installing pycocotools with following command 
`pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`

Change the `requirements.txt`  with the right pycocotools

**Comment by mingxingtan** [comment]
Thanks for pointing this out.  @Samjith888
