### ISSUE TITLE
EfficientDet tflite inference crash

### ISSUE THREAD

**Issue by sathibault** [google/automl#426]
I've tried running inference with the .tflite file generated by `python model_inspect.py --runmode=saved_model ...` and it crashes with a SIGABRT in `BroadcastMul4DSlow`.  Same result with tensorflow v2.2.0 and v1.15.0.  My platform is Ubuntu 16, x86_64.

Here's my code:
```
  net = tflite::FlatBufferModel::BuildFromFile(model.c_str(), &error_reporter);
  if (!net) {
    sendBgError("", std::string("Failed to load: "+model));
    return;
  }

  tflite::ops::builtin::BuiltinOpResolver resolver;
  tflite::InterpreterBuilder builder(*net, resolver);
  builder(&interpreter);
  if (!interpreter) {
    sendBgError("", "InterpreterBuilder failed");
    return;
  }
  if (interpreter->AllocateTensors() != kTfLiteOk) {
    sendBgError("", "AllocateTensors failed");
    return;
  }

  auto imgUInt8 = interpreter->typed_tensor<uint8_t>(input);
  // ... fill imgUInt8 with data...

  // CRASHES HERE
  if (interpreter->Invoke() != kTfLiteOk)
    return;
```

**Comment by mingxingtan** [comment]
Hi @sathibault , you need latest TF version, see instructions here:

https://github.com/google/automl/tree/master/efficientdet#3-export-savedmodel-frozen-graph-tensort-models-or-tflite
