### ISSUE TITLE
Why do I get bad results

### ISSUE THREAD

**Issue by taingload** [google/automl#433]
when  I use efficientdet d0 to detect object，I get this result：
![d0--5](https://user-images.githubusercontent.com/15126847/82521926-817c7280-9b5a-11ea-9f45-e3981a387adf.jpg)

compare with your effect，my result is very bad
my configuration is
widows10
GTX 1660ti
i7

**Comment by mingxingtan** [comment]
Can you paste your command line?

**Comment by taingload** [comment]
> Can you paste your command line?

model_inspect.py --runmode=saved_model_infer  --model_name=efficientdet-d0  --hparams="image_size=1920x1280"   --saved_model_dir=tmp/saved_model_d0/efficientdet-d0_frozen.pb  --input_image=s_pic/img.png --output_image_dir=picture/

**Comment by mingxingtan** [comment]
How about your command line to export the model? 

I just checkouted the latest code and reran the command line in README, and it worked well. Here are the command line:

```
# Step 1: export saved model.
!python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 \
  --hparams="image_size=1920x1280" \
  --saved_model_dir=/tmp/saved_model

# Step 2: do inference with saved model.
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --hparams="image_size=1920x1280"  \
  --saved_model_dir=/tmp/saved_model  \
  --input_image=img.png --output_image_dir=/tmp/
```
I am going to close this issue, but feel free to add your comment if you still have issues.

**Comment by taingload** [comment]
I also try your command but effect is similar,I just want to know why I get bad result? 
  Maybe be my GTX1660ti?
