### ISSUE TITLE
Questions about the input size

### ISSUE THREAD

**Issue by ghoshaw** [google/automl#434]
Hi, I have a question about the input size of EfficientNet-B0 and EfficientDet D0. The input size of B0 is 224*1.15 and the input size of D0 is   512, So the paper said the "we can easily reuse their ImageNet-pretrained checkpoints."  So the pretrained model trained on different input image size could be used directly?

**Comment by mingxingtan** [comment]
Good question. Yes, we currently just reuse the same b0 model that is trained on 224.  It would be interesting to check whether train b0 on 512 would help the detection, but I haven't done that experiment.
