### ISSUE TITLE
How to reduce the eval frequency ?

### ISSUE THREAD

**Issue by fitoule** [google/automl#436]
When I train from 0 I loose lot of time on eval. I would like to reduce the frequency of eval please ?

**Comment by fitoule** [comment]
uh ok sorry I did'nt see the min_eval_interval flag !

**Comment by fitoule** [comment]
humm but it does not work .. I tried min_eval_interval=12000 and I have always eval every 200 steps :(

**Comment by mingxingtan** [comment]
What mode are you using? 

If you use "train_and_eval", it would automatically eval after every epoch, but you can change the value here:

https://github.com/google/automl/blob/74267d16b5e9ee061fd45db9196d3c45b37e944a/efficientdet/main.py#L367

for example, if you change it to `for cycle in range(0, config.num_epochs, 10)`, then it would eval every 10 epochs.

If you want to only eval after all training, then you can use `--mode=train --eval_after_training=True`.

**Comment by fitoule** [comment]
for cycle in range(0, config.num_epochs, 10)  Thank you very myuch
