### ISSUE TITLE
Training killed by the system

### ISSUE THREAD

**Issue by wenh06** [google/automl#445]
The last lines of the logs before the training process was killed by the system are as follows:

> 2020-05-24T16:55:17.061609387Z Parsing Inputs...
> 2020-05-24T16:55:20.778598241Z Parsing Inputs...
> 2020-05-24T16:55:23.582915211Z Parsing Inputs...
> 2020-05-24T17:00:21.122189408Z WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:00:21.122228277Z W0525 01:00:21.121968 139862823978816 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:00:21.638820061Z WARNING:tensorflow:Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25c4633268> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:00:21.638857615Z W0525 01:00:21.638554 139862823978816 ag_logging.py:146] Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25c4633268> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:00:26.269660274Z Parsing Inputs...
> 2020-05-24T17:00:29.410388622Z Parsing Inputs...
> 2020-05-24T17:00:31.643371343Z Parsing Inputs...
> 2020-05-24T17:03:08.643719771Z creating index...
> 2020-05-24T17:03:08.645065003Z index created!
> 2020-05-24T17:03:08.662099165Z Loading and preparing results...
> 2020-05-24T17:03:08.662110185Z Converting ndarray to lists...
> 2020-05-24T17:03:08.662129298Z (30400, 7)
> 2020-05-24T17:03:08.662132807Z 0/30400
> 2020-05-24T17:03:08.772022092Z DONE (t=0.11s)
> 2020-05-24T17:03:08.772034179Z creating index...
> 2020-05-24T17:03:08.784356677Z index created!
> 2020-05-24T17:03:08.784896315Z Running per image evaluation...
> 2020-05-24T17:03:08.784902338Z Evaluate annotation type *bbox*
> 2020-05-24T17:03:17.183296326Z DONE (t=8.40s).
> 2020-05-24T17:03:17.183321366Z Accumulating evaluation results...
> 2020-05-24T17:03:17.351342082Z DONE (t=0.17s).
> 2020-05-24T17:03:17.351787538Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.072
> 2020-05-24T17:03:17.351873632Z  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.238
> 2020-05-24T17:03:17.351878679Z  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.019
> 2020-05-24T17:03:17.3519944Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.144
> 2020-05-24T17:03:17.351998881Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> 2020-05-24T17:03:17.352002812Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> 2020-05-24T17:03:17.35211373Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.033
> 2020-05-24T17:03:17.352117931Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.139
> 2020-05-24T17:03:17.352216503Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.191
> 2020-05-24T17:03:17.352221709Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.191
> 2020-05-24T17:03:17.352225619Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> 2020-05-24T17:03:17.352314478Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> 2020-05-24T17:03:17.547416883Z WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:03:17.547454993Z W0525 01:03:17.547187 139862823978816 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:03:18.067949861Z WARNING:tensorflow:Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25be2fad08> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:03:18.067982158Z W0525 01:03:18.067712 139862823978816 ag_logging.py:146] Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25be2fad08> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:03:23.750064877Z Parsing Inputs...
> 2020-05-24T17:03:27.46622417Z Parsing Inputs...
> 2020-05-24T17:03:30.274934905Z Parsing Inputs...
> 2020-05-24T17:08:27.902664806Z WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:08:27.902707887Z W0525 01:08:27.902410 139862823978816 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:08:28.421527931Z WARNING:tensorflow:Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25b57a0b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:08:28.421576308Z W0525 01:08:28.421256 139862823978816 ag_logging.py:146] Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25b57a0b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:08:33.01588786Z Parsing Inputs...
> 2020-05-24T17:08:36.095971337Z Parsing Inputs...
> 2020-05-24T17:08:38.292549679Z Parsing Inputs...
> 2020-05-24T17:11:16.895992612Z creating index...
> 2020-05-24T17:11:16.897343113Z index created!
> 2020-05-24T17:11:16.914861302Z Loading and preparing results...
> 2020-05-24T17:11:16.914893402Z Converting ndarray to lists...
> 2020-05-24T17:11:16.914897648Z (30400, 7)
> 2020-05-24T17:11:16.914900805Z 0/30400
> 2020-05-24T17:11:17.026217022Z DONE (t=0.11s)
> 2020-05-24T17:11:17.026255167Z creating index...
> 2020-05-24T17:11:17.03945696Z index created!
> 2020-05-24T17:11:17.039999096Z Running per image evaluation...
> 2020-05-24T17:11:17.040010372Z Evaluate annotation type *bbox*
> 2020-05-24T17:11:25.462643574Z DONE (t=8.42s).
> 2020-05-24T17:11:25.462670353Z Accumulating evaluation results...
> 2020-05-24T17:11:25.630215775Z DONE (t=0.17s).
> 2020-05-24T17:11:25.630778614Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.074
> 2020-05-24T17:11:25.6307894Z  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.245
> 2020-05-24T17:11:25.630890538Z  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.019
> 2020-05-24T17:11:25.630902141Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.144
> 2020-05-24T17:11:25.630995373Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> 2020-05-24T17:11:25.630999898Z  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> 2020-05-24T17:11:25.631076212Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.034
> 2020-05-24T17:11:25.631080371Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.141
> 2020-05-24T17:11:25.631170926Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.191
> 2020-05-24T17:11:25.631186471Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.191
> 2020-05-24T17:11:25.631191158Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> 2020-05-24T17:11:25.631281154Z  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> 2020-05-24T17:11:25.826476647Z WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:11:25.826516236Z W0525 01:11:25.826242 139862823978816 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
> 2020-05-24T17:11:26.345600608Z WARNING:tensorflow:Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25af45ed90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:11:26.345627593Z W0525 01:11:26.345377 139862823978816 ag_logging.py:146] Entity <function InputReader.__call__.<locals>._dataset_parser at 0x7f25af45ed90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
> 2020-05-24T17:11:32.019898222Z Parsing Inputs...
> 2020-05-24T17:11:35.731014435Z Parsing Inputs...
> 2020-05-24T17:11:38.539643963Z Parsing Inputs...

It seems that the warning `Entity <function InputReader.__call__.<locals>._dataset_parser at (somewhere in the memory)> could not be transformed and will be executed as-is` was frequently raised, and finally the system killed it. Was this warning the essential cause? If so, how could it be fixed? Thank you! @mingxingtan

**Comment by mingxingtan** [comment]
This is a little outdated. closing now, but feel free to reopen it if you have further information.
