### ISSUE TITLE
save model is error?

### ISSUE THREAD

**Issue by tcxia** [google/automl#446]
/work/anaconda3/envs/efficient/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

/work/anaconda3/envs/efficient/lib/python3.6/site-packages/tensorflow_core/python/saved_model/utils_impl.py in build_tensor_info(tensor)
     64   """
     65   if context.executing_eagerly():
---> 66     raise RuntimeError("build_tensor_info is not supported in Eager mode.")
     67   return build_tensor_info_internal(tensor)
     68 

RuntimeError: build_tensor_info is not supported in Eager mode.

**Comment by mingxingtan** [comment]
yeah, sorry the current code doesn't support  eager mode. please ad tf.disable_eager_execution()
