### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by davidmurray** [google/automl#448]
Hello,

Thanks for the great work and research. Truly amazing results.

Are there any plans to port this code to use Tensorflow 2? (that is, stop relying on the compatibility layer). Or is a Keras implementation more likely?

Thanks!
David

**Comment by mingxingtan** [comment]
Keras layers are WIP and should be done soon, see:  https://github.com/google/automl/tree/master/efficientdet/keras

Thanks to @fsx950223 , @Ely-S , @VicariNishimura 

Contributions are welcome!
