### ISSUE TITLE
nms seems to be applied among all classes

### ISSUE THREAD

**Issue by KaqiKaqi** [google/automl#450]
In anchors.py, the function `_generate_detections_tf` seems to apply nms among all classes.

I trained a model, and used ckpt to do inference. The model got good results using commit c470de8915e320c02c8ed39d0b8fc3ded99cfc64, but quite poor performace using commit c7754ba9db5c71be4c7bee6c6b491ac600de5618. Because there're 2 classes which overlap quite a lot.

I'm afraid this is a bug...

**Comment by fsx950223** [comment]
> In anchors.py, the function `_generate_detections_tf` seems to apply nms among all classes.
> 
> I trained a model, and used ckpt to do inference. The model got good results using commit [c470de8](https://github.com/google/automl/commit/c470de8915e320c02c8ed39d0b8fc3ded99cfc64), but quite poor performace using commit [c7754ba](https://github.com/google/automl/commit/c7754ba9db5c71be4c7bee6c6b491ac600de5618). Because there're 2 classes which overlap quite a lot.
> 
> I'm afraid this is a bug...

You could set batch_size is None is you want to use class-specific nms.

**Comment by KaqiKaqi** [comment]
> > In anchors.py, the function `_generate_detections_tf` seems to apply nms among all classes.
> > I trained a model, and used ckpt to do inference. The model got good results using commit [c470de8](https://github.com/google/automl/commit/c470de8915e320c02c8ed39d0b8fc3ded99cfc64), but quite poor performace using commit [c7754ba](https://github.com/google/automl/commit/c7754ba9db5c71be4c7bee6c6b491ac600de5618). Because there're 2 classes which overlap quite a lot.
> > I'm afraid this is a bug...
> 
> You could set batch_size to None if you want to use class-specific nms.
> 
> ```python
>   boxes = tf.expand_dims(boxes, axis=2)
>   boxes = tf.tile(boxes, [1, 1, params['num_classes'], 1])
>   scales = tf.expand_dims(scales, axis=-1)
>   nmsed_boxes, nmsed_scores, nmsed_classes, valid_detections = (
>       tf.image.combined_non_max_suppression(
>           boxes,
>           scores,
>           max_boxes_to_draw,
>           max_boxes_to_draw,
>           score_threshold=min_score_thresh,
>           clip_boxes=False))
> ```

Exporting with `batch_size=None` made inference much slower than `batch_size=1`.
By the way, in my opinion class-specific nms is more reasonable than class-cross nms. Why not implement class-specific nms by default?

Thanks a lot.

**Comment by mingxingtan** [comment]
Unfortunately, there is no GPU support for per-class NMS in TF.  If you set batch_size=None, it would run a per-class NMS on CPU, that's why you see it is slower on GPU.

I have reported this to TF team. Hopefully we will have a GPU per-class NMS in TF soon.
