### ISSUE TITLE
How to batch inference images of varying sizes?

### ISSUE THREAD

**Issue by bzhangj13zzz** [google/automl#453]
I trained a d0 model, but the batch inference code takes only one unviersal image_size parameter. If the sizes and aspect ratio of images I want to inference vary quite a lot, how should I modify the code? Thanks in advance!

**Comment by mingxingtan** [comment]
Hi @bzhangj13zzz , sorry, this is a little difficult in the current settings. You should be able to feed the model with any image size (it would internally resize them).
