### ISSUE TITLE
Is it possible to start training with saved checkpoints

### ISSUE THREAD

**Issue by kerasus41** [google/automl#454]
Hi,
I want to start training with saved checkpoints is it possible? Because I use Colab. I can't train with one step. I can fininsh it in 12 hours.

**Comment by mingxingtan** [comment]
Hi @kento-kobayashi , wheneven you start a training job, it always reuses previous checkpoints.

I think the problem for your is that if you restart a colab runtime, then your previous saved checkpoints will be gone. So you need save those checkpoints to your own storage (like Google drive or others)
