### ISSUE TITLE
The influence of shortcut connection in BiFPN?

### ISSUE THREAD

**Issue by huangh12** [google/automl#456]
Hi @mingxingtan ,  I am curious about the influence of shortcut connection in the BiFPN structure. 
Q1: Will these connections affect the performance a lot in BiFPN?
Q2: From the table5, I suppose the `Repeated FPN+PANet` has no shortcut connection between each repeated units, and it achieves a similar accuracy as BiFPN.  Does this mean the shortcut is not necessary? What's more, could you please give a snippet of the impl. of `Repeated FPN+PANet`, does it use swish or feature weighted?
![图片](https://user-images.githubusercontent.com/18748036/83246201-5cc87080-a1d4-11ea-9445-8fa692da00f0.png)

**Comment by mingxingtan** [comment]
Hi @huangh12 ,

This table is to study the topology (top-down, bottom up, or combined), so I modified the original FPN+PANet to make it as close as BiFPN except keeping the nodes and topology. In particular, here  "FPN+PANet" uses the same shortcut, same scaling, same depthwise-conv, same swish, and same training settings as BiFPN, but no weighted sum (only the last row has weighted sum).   So it is actually quite different from the original FPN+PANet:  swish vs. relu, one topdown-bottomup vs. multiple repeats, w/o vs. w/ shortcut,  regular vs.  depthwise conv.

I don't recall the accuracy comparison for w/ and w/o shortcut, but it is a good question. I would guess it is probably more important for deeper models.

**Comment by huangh12** [comment]
Thank you @mingxingtan ,  I actually don't understand the difference between original top-down FPN and the `Fully-Connected FPN`, in table 5.  Could you please explain it to me.

**Comment by mingxingtan** [comment]
fully-connected FPN means connect all input features to all output features, so it is more expensive.
