### ISSUE TITLE
Inconsistent on the batch dimension for TensorRT model benchmark

### ISSUE THREAD

**Issue by centerseed** [google/automl#460]
I use docker with TensorRT (nvcr.io/nvidia/19.10-py3), Tensorflow version is 2.2.0

First, I export savedmodel with TensorRT:
`python3 model_inspect.py --runmode=saved_model --model_name=efficientdet-d1   --ckpt_path=efficientdet-d1 --saved_model_dir=savedmodeldir   --tensorrt=FP16 ----batch_size=1`

And I got TensorRT model in `savedmodeldir/tensorrt_fp16/`

Then I run benchmark without TensorRT:
`python3 model_inspect.py --runmode=saved_model_benchmark   --saved_model_dir=savedmodeldir   --model_name=efficientdet-d1  --input_image=testdata/img1.jpg    --output_image_dir=/tmp/`

Got result: `FPS:  24.6243552756778` on T4.

Finally, I try to use TensorRT model to benchmark:
`python3 model_inspect.py --runmode=saved_model_benchmark   --saved_model_dir=savedmodeldir/tensorrt_fp16   --model_name=efficientdet-d1  --input_image=testdata/img1.jpg    --output_image_dir=/tmp/`

And got error:
`File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 425, in run_model
    trace_filename=kwargs.get('trace_filename', None))
  File "model_inspect.py", line 205, in saved_model_benchmark
    driver.benchmark(raw_images, trace_filename)
  File "/yunyun/automl/efficientdet/inference.py", line 622, in benchmark
    feed_dict={self.signitures['image_arrays']: image_arrays})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input shapes are inconsistent on the batch dimension, for TRTEngineOp_29: [[5,4], [1], [1], [1], [1], [5], [5], [5]]
	 [[node TRTEngineOp_29 (defined at /yunyun/automl/efficientdet/inference.py:678) ]]
	 [[detections/_51]]
  (1) Invalid argument: Input shapes are inconsistent on the batch dimension, for TRTEngineOp_29: [[5,4], [1], [1], [1], [1], [5], [5], [5]]
	 [[node TRTEngineOp_29 (defined at /yunyun/automl/efficientdet/inference.py:678) ]]`

What's wrong with TensorRT model inferencing?

**Comment by mingxingtan** [comment]
I just tried it in colab and it worked well (colab is also using tf2.2.0). Is it because your tensorRT version doesn't match TF?

**Comment by centerseed** [comment]
I use tensorflow 2.2.0 with TensorRT6.0.1
ii  libnvinfer-dev                          6.0.1-1+cuda10.1                           amd64        TensorRT development libraries and headers
```
ii  libnvinfer-plugin6                      6.0.1-1+cuda10.1                           amd64        TensorRT plugin libraries
ii  libnvinfer6                             6.0.1-1+cuda10.1                           amd64        TensorRT runtime libraries
```
I can't find TensorRT version with colab, but colab not raise my issue. I'll try different TensorRT version

**Comment by centerseed** [comment]
After some testes, I found some results:
1. tensorrt 7.0 is not compatible for tensorflow 2.0 (from nvidia official docker)
2. save_model benchmark worked with tensorrt only on tensorflow/tf-nightly docker. 2.2.0-gpu, 2.1.0-gpu are fail with `Inconsistent on the batch dimension`

**Comment by mingxingtan** [comment]
@centerseed thank you for debugging this! 

Are you able to make it work on your own machine? If so, could you share your working version of TF and TRT? I am hoping to add it to [FAQ](https://github.com/google/automl/blob/master/efficientdet/g3doc/faq.md). Or you can also create a PR to add to FAQ if you want.

**Comment by centerseed** [comment]
@mingxingtan 
I can use tensorRT for saved_model benchmark only with docker `tensorflow/tensorflow:nightly-gpu` in GCP compute engine with T4 GPU.

Nightly gpu docker contains tensorflow_2.3.0_<xxx> and CUDA 10.1, TensorRT 6.1.

BTW，TensorRT is work with mode=bm with TensorFlow 2.2.0 on my compute instance, maybe error occurs on NMS processing with TensorRT.
