### ISSUE TITLE
   Error  KeyError: 'max_instances_per_image' when running a command with only a single gpu

### ISSUE THREAD

**Issue by Deep-learning999** [google/automl#462]
CUDA_VISIBLE_DEVICES ='0'
file_pattern = 'pascal-00000-of-00200.tfrecord'  # @param
images_per_epoch = 67 * len(tf.io.gfile.glob('tfrecord/' + file_pattern))
images_per_epoch = images_per_epoch // 8   # round to 64.
print('images_per_epoch = {}'.format(images_per_epoch))
# Train efficientdet from scratch with backbone checkpoint.
backbone_name = {
    'efficientdet-d0': 'efficientnet-b0',
    'efficientdet-d1': 'efficientnet-b1',
    'efficientdet-d2': 'efficientnet-b2',
    'efficientdet-d3': 'efficientnet-b3',
    'efficientdet-d4': 'efficientnet-b4',
    'efficientdet-d5': 'efficientnet-b5',
    'efficientdet-d6': 'efficientnet-b6',
    'efficientdet-d7': 'efficientnet-b6',
}[MODEL]

# generating train tfrecord is large, so we skip the execution here.
import os
if backbone_name not in os.listdir():
  !wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/{backbone_name}.tar.gz
  !tar xf {backbone_name}.tar.gz

!mkdir model_dir
# key option: use --backbone_ckpt rather than --ckpt.
# Don't use ema since we only train a few steps.
!python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/{file_pattern} \
    --validation_file_pattern=tfrecord/{file_pattern} \
    --val_json_file=tfrecord/json_pascal.json \
    --model_name={MODEL} \
    --model_dir=/tmp/model_dir/{MODEL}-scratch  \
    --backbone_ckpt={backbone_name} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples={images_per_epoch}  \
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=1  \
    --hparams="num_classes=44,moving_average_decay=0" \

images_per_epoch = 8
mkdir: 无法创建目录"model_dir": 文件已存在
WARNING:tensorflow:From main.py:234: The name tf.estimator.tpu.TPUConfig is deprecated. Please use tf.compat.v1.estimator.tpu.TPUConfig instead.

W0530 15:38:20.946032 140458406373184 module_wrapper.py:137] From main.py:234: The name tf.estimator.tpu.TPUConfig is deprecated. Please use tf.compat.v1.estimator.tpu.TPUConfig instead.

Traceback (most recent call last):
  File "main.py", line 420, in <module>
    app.run(main)
  File "/home/design/anaconda3/envs/fastai10/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/design/anaconda3/envs/fastai10/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 258, in main
    max_instances_per_image = config.max_instances_per_image
  File "/media/design/文档/automl/efficientdet/hparams_config.py", line 51, in __getattr__
    return self.__dict__[k]
KeyError: 'max_instances_per_image'

**Comment by mingxingtan** [comment]
Hmm, I couldn't reproduce the issue. Could you checkout the latest code and retry (Or rerun it in colab?)

**Comment by Deep-learning999** [comment]
I find MAX_Instents_Per_Image must be equal to Class quantity plus 1
