### ISSUE TITLE
How does the increase of batch size got a quicker inference on EfficientDet?

### ISSUE THREAD

**Issue by thimabru1010** [google/automl#464]
I already tried to concatenate x images to do a batch inference but I got the same inference time as I was doing x in inferences separated. The result was linear. How do you increase the batch size by 8, and only gets just 2 times the inference time [batch8 throughput]?

**Comment by mingxingtan** [comment]
What's your command line?  Can you try increasing batch size in our colab tutorial: https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb ?
