### ISSUE TITLE
Fake features

### ISSUE THREAD

**Issue by fsx950223** [google/automl#465]
![Screenshot from 2020-06-02 17-50-04](https://user-images.githubusercontent.com/17592563/83506307-944b5b80-a4f9-11ea-9a51-e7e8ef91fc4c.png)
Why the fake features' filters are fpn_num_filters. It's better than increment filters such as 640?

**Comment by mingxingtan** [comment]
Good point. The fake feature is constructed here: https://github.com/google/automl/blob/11574fd1c1aaf1ca3dc37639aa365802ba21f099/efficientdet/efficientdet_arch.py#L451

I was kind of overlooking this: probably thought 640 or larger channels may causes too many parameters and FLOPs. I will try some ablation studies on this when I I get the time.
