### ISSUE TITLE
Is it possible to resume training if stopped in the middle?

### ISSUE THREAD

**Issue by ifahim** [google/automl#482]
First of all thanks for this great tool. 

I am trying the efficientdet and struggling to figure out how to use it with my custom data. 
 
I am using my custom data set for finetuning. I have 7 classes. I used the following command: 
```
!python main.py --mode=train_and_eval \ --training_file_pattern=tfrecord/train-*.tfrecord \ --validation_file_pattern=tfrecord/valid-*.tfrecord \ --model_name={MODEL} \ --model_dir=/tmp/model_dir/{MODEL}-finetune \ --ckpt={MODEL} \ --train_batch_size=8 \ --eval_batch_size=8 --eval_samples={images_per_epoch} \ --num_examples_per_epoch={images_per_epoch} --num_epochs=1 \ --hparams="num_classes=8,moving_average_decay=0,precision=mixed_float16"
```

![image](https://user-images.githubusercontent.com/1225514/83902380-20839b80-a711-11ea-815b-c0494d38b7b0.png)

The training loss looks good but it keeps on training. I stopped after training for ~12 hours. I am perplexed to see the content of  model_dir/{MODEL}-finetune.

1) How can I inference if I stop the training in the middle? 
2) How to resume the training from the checkpoint? 

The following command results in error. I am sure I must be doing something wrong: 

!python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 \
--ckpt_path= model_dir/efficientdet-d0-finetune \
  --hparams="image_size=1920x1280" \
  --saved_model_dir=model_dir/{MODEL}

 '   checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: '

These are some of the files generated in the model directory:
![image](https://user-images.githubusercontent.com/1225514/83902870-0b5b3c80-a712-11ea-9e1e-d6ea4eb4dd9e.png)

**Comment by Ely-S** [comment]
Hi @ifahim,
Are you trying to train your model with `model_inspect.py`?

The way to resume training is by running the exact same training command you used on the first iteration but without the `--ckpt` argument. TPUEstimator should pick up the weights where it left off in the same model dir.

**Comment by ifahim** [comment]
> Hi @ifahim,
> Are you trying to train your model with `model_inspect.py`?
> 
> The way to resume training is by running the exact same training command you used on the first iteration but without the `--ckpt` argument. TPUEstimator should pick up the weights where it left off in the same model dir.

Thanks for your response. 

I am using the following command: `
!python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/train-*.tfrecord  \
    --validation_file_pattern=tfrecord/valid-*.tfrecord  \
    --model_name={MODEL} \
    --model_dir=/tmp/model_dir/{MODEL}-finetune \
    --ckpt={MODEL} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples={images_per_epoch}  \
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=1  \
    --hparams="num_classes=8,moving_average_decay=0,precision=mixed_float16"`. 

So if I remove the `--ckpt={MODEL} ` from above, the training should pickup from where it was interrupted? 

My first question waS: 
1. How can I inference if I stop the training in the middle? Is this possible? 

My next command two commands are: 
a. Export the model 
```
serve_image_out = 'serve_image_out'
!mkdir {serve_image_out}
saved_model_dir = 'savedmodel'
!rm -rf {saved_model_dir}

# Step 1: export model
!python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 \
  --hparams="image_size=1920x1280" --saved_model_dir={saved_model_dir}
```

and 
b. Infer single image: 
```
# Step 2: do inference with saved model.
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0 --saved_model_dir={saved_model_dir} \
  --input_image=img.png --output_image_dir={serve_image_out}
```

**Comment by mingxingtan** [comment]
@ifahim If you stop in the middle, and want to resume your training, then you should rerun exactlly the same command (it would automatically start from the previous checkpoint):
```

!python main.py --mode=train_and_eval \
 --training_file_pattern=tfrecord/train-*.tfrecord \
 --validation_file_pattern=tfrecord/valid-*.tfrecord \
 --model_name={MODEL} \
 --model_dir=/tmp/model_dir/{MODEL}-finetune \ 
 --ckpt={MODEL} \ 
 --train_batch_size=8 \
 --eval_batch_size=8 --eval_samples={images_per_epoch} \ 
--num_examples_per_epoch={images_per_epoch} --num_epochs=1 \ --hparams="num_classes=8,moving_average_decay=0,precision=mixed_float16"
```
You can do inference any time, just run something like:

```
    !python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \   
      --ckpt_path=/tmp/model_dir/{MODEL}-finetune --saved_model_dir=savedmodeldir
```

(here the ckpt_path needs to be the same as your model_dir)

**Comment by ifahim** [comment]
@mingxingtan  thanks. that worked.
