### ISSUE TITLE
Coco API Issues

### ISSUE THREAD

**Issue by ID56** [google/automl#487]
Hi there. The `requirements.txt` file for this repository contains the following lines at the end:

```
# pycocotools official release has some issues.`
git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`
```

However, this particular branch of pycocotools has a [bug](https://github.com/philferriere/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L507) in it's `np.linspace` calls. For example, the code calls one of its `linspace` calls like this:

```
self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
```

While it should actually be like this:

```
self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
```

This bug seems to have been fixed in the official pycocotools repo, looking at [here](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L506).

This issue seems to have already been raised once at here: #385. So it seems like the official repo of pycocotools causes some other problems, and this one causes this linspace problem? Is there a correct way to set requirements.txt so that this doesn't occur? Otherwise I'll keep using my current stopgap solution, which is to manually fix the small errors in the `cocoeval.py` file.

**Comment by mingxingtan** [comment]
Thank you, @ID56 

It was a mistake, the official code is right (I used the official code in colab), it is just the official pypy coco released version is not correct. I updated the requirement.

**Comment by ID56** [comment]
Alright thanks a lot for the quick response!
