### ISSUE TITLE
What change it up to 53.4? And vs DetectoRS.

### ISSUE THREAD

**Issue by zcode86** [google/automl#491]
I see that the mAP has increased to 53.4 again, I would like to ask what has changed to cause it up from 52.6? And is it stronger than DetectoRS? Because the DetectoRS used multi-scale, while efficientdet used single scale, and FPS is also bigger.

**Comment by mingxingtan** [comment]
We fixed some dataloader issues (thanks to a lot of contributors), and I retrained it with longer time.

What is the AP and FPS for DetectoRS?

**Comment by iamastar88** [comment]
Thanks for your reply. On COCO test-dev, DetectoRS achieved 54.7 when using ResNeXt-101-32x4d as backbone and TTA(test-time augmentation,which includes multi-scale testing, horizontal flipping,etc.), while 53.3 no TTA. And they only show FPS=3.9 when using ResNet-50 as backbone and no TTA, which achieved 51.3. So I guess it will cost much time if want to achieve upper mAP.

**Comment by mingxingtan** [comment]
Thanks for the info @iamastar88 

I noticed this paper is using soft-nms, so I also added soft-nms yesterday. Using the same ckpt, softnms (gaussian with sigma=0.5) improves D7 COCO AP from 53.4 to 53.7

**Comment by iamastar88** [comment]
Wow, that's amazing.
