### ISSUE TITLE
Augmentation error during training

### ISSUE THREAD

**Issue by bessszilard** [google/automl#494]
Hello! I tried to do augmentation during training with this config:

```python
images_per_epoch = int(3000)#3923)
images_per_eval = int(20)

train_batch_size = 10
eval_batch_size = 1
epochs = 20

!python main.py --mode=train_and_eval \
    --training_file_pattern={train_file} \
    --validation_file_pattern={eval_file} \
    --model_name={MODEL} \
    --model_dir=/content/tmp/model_dir/{MODEL}-finetune \
    --ckpt={MODEL} \
    --train_batch_size={train_batch_size} --eval_batch_size={eval_batch_size} \
    --eval_samples={images_per_eval}  \
    --num_examples_per_epoch={images_per_epoch} --num_epochs={epochs} \
    --hparams="num_classes=5,moving_average_decay=0,autoaugment_policy=v1" \
```

I was able only to test the code of [my previous issue](https://github.com/google/automl/issues/378) today. I saw the https://github.com/google/automl/commit/2da2c33cf59837f2f855b0883db79877784b7caa commit, but I still got the same error.
As I discribed in the post, I fix the error manually. When I modify the code, it is able to start to train.
On May 7 when I wrote this https://github.com/google/automl/issues/378#issue-613960393
it worked after the modification correctly. Although today I got his error at the end of the first epoch:

```shell
I0609 11:51:07.104773 140165709006720 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0609 11:51:07.105023 140165709006720 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map__dataset_parser_10592}} output dimensions must be positive
	 [[{{node parser/cond_22/then/_120/cond/then/_0/cond/else/_48/while/body/_81/cond/then/_161/PartitionedCall/translate/PartitionedCall/transform/Addons>ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 387, in main
    steps=int(FLAGS.num_examples_per_epoch / FLAGS.train_batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1518, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  output dimensions must be positive
	 [[{{node parser/cond_22/then/_120/cond/then/_0/cond/else/_48/while/body/_81/cond/then/_161/PartitionedCall/translate/PartitionedCall/transform/Addons>ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]
```

I was able to train the efficientDet without augmentation successfully. 
Questions:
1. What does it cause this error?
2. Can you insert this [cpu modification](https://github.com/google/automl/issues/161#issuecomment-612966054) the modification in the library?

**Comment by qtw1998** [comment]
> Hello! I tried to do augmentation during training with this config:
> 
> ```python
> images_per_epoch = int(3000)#3923)
> images_per_eval = int(20)
> 
> train_batch_size = 10
> eval_batch_size = 1
> epochs = 20
> 
> !python main.py --mode=train_and_eval \
>     --training_file_pattern={train_file} \
>     --validation_file_pattern={eval_file} \
>     --model_name={MODEL} \
>     --model_dir=/content/tmp/model_dir/{MODEL}-finetune \
>     --ckpt={MODEL} \
>     --train_batch_size={train_batch_size} --eval_batch_size={eval_batch_size} \
>     --eval_samples={images_per_eval}  \
>     --num_examples_per_epoch={images_per_epoch} --num_epochs={epochs} \
>     --hparams="num_classes=5,moving_average_decay=0,autoaugment_policy=v1" \
> ```
> 
> I was able only to test the code of [my previous issue](https://github.com/google/automl/issues/378) today. I saw the [2da2c33](https://github.com/google/automl/commit/2da2c33cf59837f2f855b0883db79877784b7caa) commit, but I still got the same error.
> As I discribed in the post, I fix the error manually. When I modify the code, it is able to start to train.
> On May 7 when I wrote this [#378 (comment)](https://github.com/google/automl/issues/378#issue-613960393)
> it worked after the modification correctly. Although today I got his error at the end of the first epoch:
> 
> ```shell
> I0609 11:51:07.104773 140165709006720 error_handling.py:115] training_loop marked as finished
> WARNING:tensorflow:Reraising captured error
> W0609 11:51:07.105023 140165709006720 error_handling.py:149] Reraising captured error
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
>     target_list, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map__dataset_parser_10592}} output dimensions must be positive
> 	 [[{{node parser/cond_22/then/_120/cond/then/_0/cond/else/_48/while/body/_81/cond/then/_161/PartitionedCall/translate/PartitionedCall/transform/Addons>ImageProjectiveTransformV2}}]]
> 	 [[IteratorGetNext]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 421, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "main.py", line 387, in main
>     steps=int(FLAGS.num_examples_per_epoch / FLAGS.train_batch_size))
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
>     rendezvous.raise_errors()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
>     six.reraise(typ, value, traceback)
>   File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
>     saving_listeners=saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1215, in _train_model_default
>     saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1518, in _train_with_estimator_spec
>     _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 778, in run
>     run_metadata=run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
>     run_metadata=run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
>     raise six.reraise(*original_exc_info)
>   File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
>     return self._sess.run(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
>     run_metadata=run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
>     return self._sess.run(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError:  output dimensions must be positive
> 	 [[{{node parser/cond_22/then/_120/cond/then/_0/cond/else/_48/while/body/_81/cond/then/_161/PartitionedCall/translate/PartitionedCall/transform/Addons>ImageProjectiveTransformV2}}]]
> 	 [[IteratorGetNext]]
> ```
> 
> I was able to train the efficientDet without augmentation successfully.
> Questions:
> 
> 1. What does it cause this error?
> 2. Can you insert this [cpu modification](https://github.com/google/automl/issues/161#issuecomment-612966054) the modification in the library?

The Same Problems。。

**Comment by mingxingtan** [comment]
Hi @bessszilard I already added that at top level code in May: https://github.com/google/automl/blob/e3833799aa83f68ef6c5ce757ab07f52cf9fa31b/efficientdet/aug/autoaugment.py#L1692   Do you still have CPU/GPU op problem?

If it still doesn't work, do you mind sending a PR?  Thank you!

**Comment by Koteswara-ML** [comment]
Hey i am getting the op problem while running on TPU how to solve that..?

**Comment by mingxingtan** [comment]
Hi @Koteswara-ML Could you prepare a colab to reproduce your error?
I personally don't get any errors for autoaug with TPUs and I thought it was fixed.
