### ISSUE TITLE
issue in inference after custom training 

### ISSUE THREAD

**Issue by adarsh0906** [google/automl#499]
i finetune d1 model with custom dataset with 4 class i trained it for 20 epoch the i freezed the model using saved model and tried to run it on single image which was in train dataset it returns an empty detection box

**Comment by sagarkarki136** [comment]
maybe 20 epochs is not enough
can you please share your notebook

**Comment by adarsh0906** [comment]
> 
> 
> maybe 20 epochs is not enough
> can you please share your notebook

yes 

https://colab.research.google.com/drive/1N7WUOJOURTAWT15BWUPeaWEVu4YjUbsb?usp=sharing

the zip contains the changed code according to my dataformat 

[create_pascal_tfrecord.zip](https://github.com/google/automl/files/4776018/create_pascal_tfrecord.zip)

**Comment by adarsh0906** [comment]
> 
> 
> maybe 20 epochs is not enough
> can you please share your notebook

also i tried for 70 epoch still same thing

**Comment by github2016-yuan** [comment]
Same issue. I extract one class from coco dataset and after training 10 epoch, the pb file detectes nothing.
#484 may be helpful.

**Comment by adarsh0906** [comment]
issue is solved by having number of class = number of class(in dataset) +1 further mentioned in issue #521
