### ISSUE TITLE
what the "tensorflow.google" and "tensorflow_addons"

### ISSUE THREAD

**Issue by shen865069799** [google/automl#5]
when i run python main.py , error below:
(1)import tensorflow.google as tf
ModuleNotFoundError: No module named tensorflow.google'
(2)import tensorflow_addons as tfa
ModuleNotFoundError: No module named 'tensorflow_addons'
(3)import tf_slim as slim
ModuleNotFoundError: No module named 'tf_slim'

**Comment by WonTaeYeon** [comment]
I am not good at English, but I will leave an answer.
(1) tensorflow.google -> tensorflow 
(2) pip install tensorflow_addons 
(tensorflow >= 2.x)
(3) 
1. Delete the pycache directory from the tf_slim path.
2. Download - https://github.com/google-research/tf-slim/tree/master/tf_slim
3. Paste in tf_slim path

**Comment by shen865069799** [comment]
thx

**Comment by shen865069799** [comment]
> I can't English well.... but I will answer the question.
> (1) tensorflow.google -> tensorflow
> (2) pip install tensorflow-addons
> (tensorflow >= 2.x)
> (3)
> 
> 1. Delete the files and dir from the tf_slim path.(left pycache directory)
> 2. Download - https://github.com/google-research/tf-slim/tree/master/tf_slim
> 3. Paste in tf_slim path

thx

**Comment by mingxingtan** [comment]
I have removed the dependence to slim and fix the tensorflow.google. Now you only need to pip install tensorflow_addons. (not need to copy tf_slim)

**Comment by shen865069799** [comment]
> I have removed the dependence to slim and fix the tensorflow.google. Now you only need to pip install tensorflow_addons. (not need to copy tf_slim)

Thank you for your prompt reply
