### ISSUE TITLE
How to export a saved model ?

### ISSUE THREAD

**Issue by Byronnar** [google/automl#50]
I found the output_node_names are a list, we should concat it to one tensor so that we can tranfer to saved model.　Have any methos?

['class_net/class-predict/BiasAdd', 'class_net/class-predict_1/BiasAdd', 'class_net/class-predict_2/BiasAdd', 
      'class_net/class-predict_3/BiasAdd', 'class_net/class-predict_4/BiasAdd', 'box_net/box-predict/BiasAdd', 'box_net/box-predict_1/BiasAdd',
       'box_net/box-predict_2/BiasAdd', 'box_net/box-predict_3/BiasAdd', 'box_net/box-predict_4/BiasAdd']

**Comment by jiaozhentian** [comment]
Well, actually we all looking for the approach, if we export the pb model, this algorithm could be implemented on the tf serving, which can accelerate the develop or research immediately... Everyone is looking for the cutway...

**Comment by mingxingtan** [comment]
Hi @Byronnar and @jiaozhentian , I don't have time to implement the complete serving flow, but I have add a utility here:

https://github.com/google/automl/blob/7768c499ede4a732fde022a24d8525b3396b50a4/efficientdet/inference.py#L240

You should be able to easily export a saved model based on this utility. PR is welcomed. Thanks!
