### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by sandstorm12** [google/automl#501]
Hi, I hope you're doing well. There is a type in the main readme, on section 8, for extracting the efficientdet-d0.tar.gz.
It is written:
``` !tar xf efficientnet-d0.tar.gz ```
It should be:
``` !tar xf efficientdet-d0.tar.gz ```

Thank you.

**Comment by mingxingtan** [comment]
Thank you @sandstorm12 for pointing this out. Fixed now.
