### ISSUE TITLE
CPU Float16

### ISSUE THREAD

**Issue by fsx950223** [google/automl#504]
https://colab.research.google.com/drive/1rjbQD115CVo3GLjraq8XBuOWonSVYh8o?usp=sharing

I can't get any bbox from CPU float16 model.
![Screenshot from 2020-06-12 13-53-08](https://user-images.githubusercontent.com/17592563/84469709-4a5e3480-acb4-11ea-8ad5-3c6bf8548c9c.png)

**Comment by mingxingtan** [comment]
Hmm, strange. How about GPU fp16?

**Comment by fsx950223** [comment]
> Hmm, strange. How about GPU fp16?

It's OK.
Obviously, there are some bugs in CPU float16 kernels.
