### ISSUE TITLE
tutorial.ipynb needs an update due to changes for #490

### ISSUE THREAD

**Issue by rayclwu** [google/automl#511]
tutorial.ipynb no longer works as it uses `--hparams="precision={precision}"`
f595e456579c39f5a9bfd20a05c9ef93fef93c00 had introduced `mixed_precision` to replace `precision`

**Comment by mingxingtan** [comment]
Thanks @rayclwu 

Fixed in https://github.com/google/automl/commit/db8d11b59c38b9d9ccaf69eaf2d0e744177e9792
