### ISSUE TITLE
[Help needed]train with multi gpu problem

### ISSUE THREAD

**Issue by HaoDreamlong** [google/automl#513]
I trid to train my dataset on 4 gpus in docker ,but I encontered problem below:

![image](https://user-images.githubusercontent.com/32117036/84584488-9e455680-ae37-11ea-9d1e-74baaca02134.png)

I am not familiar with Tensorflow  and horovod environment, I don`t know which part of the environment goes wrong?thanks

**Comment by mingxingtan** [comment]
Please refer README for multi-GPU training.
