### ISSUE TITLE
running inference via tflite on arm cpu

### ISSUE THREAD

**Issue by cam145** [google/automl#517]
Thanks for the continuous update.

Now I can convert the efficientdet-d0 model to tensorflow lite model.

The tensorflow lite model was generated via the default setting at the moment and run inference on ARM A-series cpu. 

I compared the inference speed for the two models with the same data input.

The tensorflow lite model performs a bit (20%) better than the tensorflow model via tflite run environment.  

I also quantised the model to int8 version (the size was reduce to a few Megabit), however the inference speed seems to be dropped 50%. Done in C++ inference environment, int8 version seems to be faster than float32 version.

I wonder if there is a better way to further speed up inference or some optimisation settings I missed.

Thanks in advance.

**Comment by tzekid** [comment]
Hey, can you please share the code where you converted to quantised model (int8)?

**Comment by Abdktefane** [comment]
@cam145  please share the code where you converted to int8
