### ISSUE TITLE
Resuming training

### ISSUE THREAD

**Issue by MrunaliniN** [google/automl#518]
Hi,
I have seen the discussion on this topic at #482 , however, when I re-run the same command as used for starting training, it restarts the training at epoch 0.
Is that expected? If yes, how would I find out how many epochs were trained in the previous session? 
this is the command I have used, it is for my custom data :
`python main.py --mode=train_and_eval 
--training_file_pattern=/path/to/data/tfrecord/train*.tfrecord 
--validation_file_pattern=/data/mlnalama/Masters/automl/data_ss_smd1/tfrecord/val*.tfrecord 
--model_name=efficientdet-d3 
--model_dir=/path/to/model/efficientdet-d3 
--ckpt=efficientdet-d3 
--train_batch_size=4 
--eval_batch_size=4 
--num_epochs=100 
--hparams=my_config.yaml 
--eval_samples=2730 
--num_examples_per_epoch=21838`

**Comment by Samjith888** [comment]
> Hi,
> I have seen the discussion on this topic at #482 , however, when I re-run the same command as used for starting training, it restarts the training at epoch 0.
> Is that expected? If yes, how would I find out how many epochs were trained in the previous session?
> this is the command I have used, it is for my custom data :
> `python main.py --mode=train_and_eval --training_file_pattern=/path/to/data/tfrecord/train*.tfrecord --validation_file_pattern=/data/mlnalama/Masters/automl/data_ss_smd1/tfrecord/val*.tfrecord --model_name=efficientdet-d3 --model_dir=/path/to/model/efficientdet-d3 --ckpt=efficientdet-d3 --train_batch_size=4 --eval_batch_size=4 --num_epochs=100 --hparams=my_config.yaml --eval_samples=2730 --num_examples_per_epoch=21838`

For resumig 

Use `--ckpt="checkpoint directory"`

This will automatically resume the training from where u left . 

It will start from the checkpoint , not from the epoch number. If your earlier training completed only few steps ,not 1 epoch , then the training will start from the steps or the specific checkpoint , So the epoch number will be zero in this case . You can see the epoch number in the training log

**Comment by MrunaliniN** [comment]
My earlier training completed about 25 epochs after which it terminated. 
I restarted the training and noticed that whether ckpt='checkpoint dir' or 'efficientdet-d1' , it still resumes from where the previous one terminated... however, the epoch # is still shown as 0. 
Tensorboard graphs are the only way to tell that the training has resumed from the last checkpoint. 

"You can see the epoch number in the training log"
---  which training log do you mean? 

Also, the tensorboard does not show epoch numbers, it shows the number of examples trained, right?

**Comment by Samjith888** [comment]
> My earlier training completed about 25 epochs after which it terminated.
> I restarted the training and noticed that whether ckpt='checkpoint dir' or 'efficientdet-d1' , it still resumes from where the previous one terminated... however, the epoch # is still shown as 0.
> Tensorboard graphs are the only way to tell that the training has resumed from the last checkpoint.
> 
> "You can see the epoch number in the training log"
> --- which training log do you mean?
> 
> Also, the tensorboard does not show epoch numbers, it shows the number of examples trained, right?

You can't find the epoch number in Tensorboard, but epoch number will be in the terminal .

**Comment by MrunaliniN** [comment]
ok. no worries. Thanks for your response.
It would have been nice if the epoch numbers were also saved with the model, so that it is easier to track and start/restart training. also helpful to know the epoch # during inferencing.

**Comment by xiaoxin05** [comment]
1、I wonder how to judge whether from the last training continue，，， “Tensorboard graphs are the only way to tell that the training has resumed from the last checkpoint.”
2、In other words: Resume actually succeeded, but only the epoch was shown from 0 again

**Comment by xiaoxin05** [comment]
1、I wonder how to judge whether from the last training continue，，， “Tensorboard graphs are the only way to tell that the training has resumed from the last checkpoint.”
2、In other words: Resume actually succeeded, but only the epoch was shown from 0 again？  @MrunaliniN

**Comment by MrunaliniN** [comment]
1. If you look at the graph, it will continue from the step that the last training had stopped.
2. Yes, it seems so ... the epoch # starts from 0 every time you start or continue training

**Comment by xiaoxin05** [comment]
thank you reply.&nbsp;
Excuse me , I have a question for you. details as follows:
1) I will train and eval&nbsp;separately, "mode=train" or "mode = eval". but&nbsp; when I see "coco eval"&nbsp; part ,&nbsp;

One line of command is required to create the dataset during validation :&nbsp;
 --caption_annotations_file=annotations/captions_val2017.json or  --image_info_file=annotations/image_info_test-dev2017.json 

because i use custom datasets, i want know : i need this above .json file ?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mrunalini"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 晚上6:27
收件人:&nbsp;"google/automl"<automl@noreply.github.com&gt;;
抄送:&nbsp;"张雯欣"<912650845@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [google/automl] Resuming training (#518)





  
If you look at the graph, it will continue from the step that the last training had stopped.
 
Yes, it seems so ... the epoch # starts from 0 every time you start or continue training
