### ISSUE TITLE
Multiple Anchor Scales

### ISSUE THREAD

**Issue by SiBensberg** [google/automl#524]
Hi,
the objects in my dataset are very small. I would like to modify the Anchor scales. 
Is it possible to add more scales?
How to do it with the config.yaml?

I tried to do:
```
num_classes: 4
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_id_mapping: {0: background, 1: one, 2: two 3: three, 4: four}
aspect_ratios: [[1.0, 1.0], [0.634, 1.577], [1.577, 0.634]]
num_scales: 5
anchor_scale: [0.2, 0.253, 0.3205, 0.5, 0.7932] 
```

But it got me the Error (like in #475):
```
    base_anchor_size_x = anchor_scale * stride[1] * 2**octave_scale
TypeError: can't multiply sequence by non-int of type 'float'
```

Thank you for your work

**Comment by SiBensberg** [comment]
Ok, I think I got it. 
"num_scales" is adding intermediate anchor scales [2^0, 2^0.5] on each level.
"anchor_scale" is the base scale.
Thus for the small Objects I have to scale down the base scale, right?
Is there a way to set a fixed set of scales like [0.2, 0.253, 0.3205, 0.5, 0.7932] for every level?

**Comment by vakkov** [comment]
Have you managed to reach a solution, @SiBensberg

**Comment by zishanahmed08** [comment]
@mingxingtan Could you please confirm @SiBensberg inputs above regarding anchor scales for small objects should be scaling down the anchor_scale: [0.2, 0.253, 0.3205, 0.5, 0.7932] ?

**Comment by mingxingtan** [comment]
anchor_scale is used to assign the predefined anchors, and currently we use a single value for anchor scale. It requires some additional work to support anchor_scale per layer.

In particular, the current default settings are level 3-7 and anchor_scale 4, which means they would cover object sizes from 4 * 2^3 = 32,  to 4 * 2^7 = 512.  You can use larger anchor scale (e.g. anchor_scale=5) if your datasets have a lot of big objects, or smaller anchor scale for smaller objects (e.g. anchor_scale=3 or 2).

To support per-layer anchor scale, the main changes would be for the label assignments in [this file](https://github.com/google/automl/blob/47489a0f9ab87f1c61856bf2ea81ed04bc2a67c4/efficientdet/anchors.py#L308).

**Comment by Samjith888** [comment]
> anchor_scale is used to assign the predefined anchors, and currently we use a single value for anchor scale. It requires some additional work to support anchor_scale per layer.
> 
> In particular, the current default settings are level 3-7 and anchor_scale 4, which means they would cover object sizes from 4 * 2^3 = 32, to 4 * 2^7 = 512. You can use larger anchor scale (e.g. anchor_scale=5) if your datasets have a lot of big objects, or smaller anchor scale for smaller objects (e.g. anchor_scale=3 or 2).
> 
> To support per-layer anchor scale, the main changes would be for the label assignments in [this file](https://github.com/google/automl/blob/47489a0f9ab87f1c61856bf2ea81ed04bc2a67c4/efficientdet/anchors.py#L308).

num_scales: 6

Got following error:
![fffer](https://user-images.githubusercontent.com/39676803/85981286-95d94800-ba01-11ea-8cce-89baa3c36b19.png)

**Comment by zishanahmed08** [comment]
@mingxingtan thanks for the answers.While finetuning a model with smalle anchor scale (2) from  a pre trained checkpoint(anchor sclae 4) does it make snense to freeze fpn/backbone with **var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'** or should in unfreeze(train) them also

**Comment by mingxingtan** [comment]
@Samjith888 num_scales will determine how many anchors per pixel, so it would change the output shape, where the box_net channel size would be: num_scales * 4, causing the shape mismatch.  You can exclude these variables.
[After reading your problem, I realized that regexp might be too complicated for many users, we should provide an option like "by_name": only load weights if their shapes match]

@zishanahmed08 If you freeze those variables, it would train faster.

**Comment by staeff777** [comment]
@zishanahmed08 I just made a test, without freezing resample_p6 and it is defently an improvment. Unfreezing fpn_cells currently throws an error for me, but I assume that this also might help.
