### ISSUE TITLE
Can you report map on voc dataset ? 

### ISSUE THREAD

**Issue by djaym7** [google/automl#527]
Train : 2007+2012 trainval
test : 2007 test

**Comment by fsx950223** [comment]
Train : 2007 trainval
test : 2007 test

Efficientdet-d0
mAP: 75.7

**Comment by XinyuKang** [comment]
> Train : 2007 trainval
> test : 2007 test
> Efficientdet-d0
> mAP: 75.7

Hi @fsx950223 , is this result of mAP50?
