### ISSUE TITLE
Always returning 100 detections with .tflite

### ISSUE THREAD

**Issue by aocz1** [google/automl#529]
I've successfully managed to train and export models to .tflite with this library, though it appears as though the shape returned with .tflite is [1, 100, 7]. I would like to return less detection's in order to speed up the inference time on mobile devices, is there a way to do this? I have already tried using the hparam "max_instances_per_image", but that doesn't seem to change anything.

**Comment by mingxingtan** [comment]
Hi @aocz1 You should change this flag to smaller value (it is 100 if None): https://github.com/google/automl/blob/df1238779a0f34af309fd072a36d229d7b7b0d8a/efficientdet/model_inspect.py#L69

Also, if you want fast, the easy way is to use smaller images (the current input images are pretty big).

**Comment by aocz1** [comment]
Cheers, so the setting only needs to be changed when using model_inspect.py to generate the model files from the checkpoint?

**Comment by mingxingtan** [comment]
that's right

**Comment by zishanahmed08** [comment]
@aocz1 Hi Ales, Is there a open source android app example for use with efficient det tflite?

**Comment by aocz1** [comment]
@zishanahmed08 Yes there are several example android apps using tensorflow lite, like here (https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android).

Basically you would have to adapt the TFLiteObjectDetectionAPIModel class so that it can read your efficientdet model. The example app I've linked above has a model that returns the following arrays:

    outputLocations = new float[1][NUM_DETECTIONS][4];
    outputClasses = new float[1][NUM_DETECTIONS];
    outputScores = new float[1][NUM_DETECTIONS];
    numDetections = new float[1];

While our efficientdet model will return a single 3D array with dimensions of [1][MAX_BOXES][7]. 

Once you've mapped the results into the array, you can access the results programatically and process them however you wish.

**Comment by zishanahmed08** [comment]
@aocz1 Alex, thanks for the info. Do you have fork with these changes?

**Comment by zishanahmed08** [comment]
@aocz1 A gentle reminder

**Comment by aocz1** [comment]
@zishanahmed08 Apologies, I was out of office the last few days.

I do not have a fork with the changes, however you can find some useful information about using EfficientDet with TensorflowLite on android in another issue https://github.com/google/automl/issues/533 

If you're looking to learn about running a tflite model on android, I would suggest building and having a play around with https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android and look to gain an understanding of how the code works. 

Once you understand how it works, then it's a matter of changing some of the variables (such as input size) and the output array in the TFLiteObjectDetectionAPIModel class to match your own efficientdet model.

**Comment by Abdktefane** [comment]
after i try this :
`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tflite_path=efficientdet-d0.tflite --max_boxes_to_draw=20`
still return 100 and preduce this error
`Cannot copy from a TensorFlowLite tensor (detections) with shape [1, 100, 7] to a Java object with shape [1, 20, 7]`

**Comment by mingxingtan** [comment]
@Abdktefane I recently made some changes that invalid those options. Will be fixed in https://github.com/google/automl/pull/601/commits/db40ab71e2ae09d57ab50b6e2a894e452b0274dc
