### ISSUE TITLE
Retinanet model

### ISSUE THREAD

**Issue by Samjith888** [google/automl#535]
I can see there will be efficientDet and Retinanet  models in the hparams_config.py. But why you @mingxingtan @fsx950223  have added retinanet model in the efficientDet repo?

https://github.com/google/automl/blob/master/efficientdet/hparams_config.py#L431

**Comment by mingxingtan** [comment]
RetinaNet code is kind of legacy code. We probably will delete those code soon since we are are actively maintaining it anymore.
