### ISSUE TITLE
load a trained weight 

### ISSUE THREAD

**Issue by Samjith888** [google/automl#539]
In the repo, model_inspect.py files is using for inference and model conversion and related stuffs. Will u make script to load a trained model(.pb file) for inference. 

Eg:

```
import tensorflow as tf
from efficientdet import load_model

effdet = load_model('trained_model.pb')
im_size = model.config.input_size
images  = tf.random.uniform((3, *im_size, 3)) # 3 Mock images

boxes, labels, scores = effdet(images, training=False)

for im_boxes, im_labels in zip(boxes, labels):
    # Process boxes of a specific image
```

@mingxingtan @fsx950223

**Comment by mingxingtan** [comment]
Hi @Samjith888 
If you specify --saved_model_dir as a pb file, then it would use the pb file to do inference, like this:

```
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --saved_model_dir=trained_model.pb  \
  --input_image=img.png --output_image_dir=/tmp/
```

**Comment by Samjith888** [comment]
> Hi @Samjith888 
> 
> If you specify --saved_model_dir as a pb file, then it would use the pb file to do inference, like this:
> 
> 
> 
> ```
> 
> !python model_inspect.py --runmode=saved_model_infer \
> 
>   --model_name=efficientdet-d0  \
> 
>   --saved_model_dir=trained_model.pb  \
> 
>   --input_image=img.png --output_image_dir=/tmp/
> 
> ```

 I meant can u just  make one line code to load the model
