### ISSUE TITLE
cannot train with ciou enabled

### ISSUE THREAD

**Issue by leedewdew** [google/automl#543]
When I train with different iou loss, diou and giou works fine, but ciou does not.
It blocks the training  telling "Saving checkpoints for 0 into ..."  and no more progess.

**Comment by zishanahmed08** [comment]
i face the same issue

**Comment by zpillio** [comment]
Maybe it's related (maybe not) but for me 'iou_utils_test.py' fails in 'ciou' cases with tensorflow version < 2.0:
"TypeError: If using @custom_gradient with a function that uses variables, the enclosing variable scope must have use_resource=True."

**Comment by leedewdew** [comment]
> Maybe it's related (maybe not) but for me 'iou_utils_test.py' fails in 'ciou' cases with tensorflow version < 2.0:
> "TypeError: If using @custom_gradient with a function that uses variables, the enclosing variable scope must have use_resource=True."

Yes, tf1.0 fails with ciou but tf2.0 works.
