### ISSUE TITLE
Eval Metrics not Calculating Object Sizes Correctly

### ISSUE THREAD

**Issue by mm7721** [google/automl#544]
I'm using tf-nightly 2.3.0.dev20200621, and training on a custom dataset.  I've built a tfrecord according to the required format, and training runs successfully.  However, eval is reporting that there are only small objects:

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.250
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.426
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.277
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.309
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.232
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.373
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.378
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.378
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

I've manually read in the validation set and verified that there are plenty of small (<32^2), medium (>=32^2, <96^2), and large (>=96^2) objects.  I'm assuming here that the standard COCO definitions are used.

Any ideas what could be causing this eval problem?

**Comment by zishanahmed08** [comment]
I also face the same issue

**Comment by mingxingtan** [comment]
@mm7721 @zishanahmed08 did you change any settings (like image size, anchor scale, etc)?

**Comment by mm7721** [comment]
@mingxingtan, my image sizes are adjusted to 500x500, and anchor scales are default.  I can try increasing the image size to see if there's any impact on the metrics output.  (Note that in my assessment of small/medium/large objects with my manual tfrecord reader, the image size was also 500x500.)

**Comment by etam103** [comment]
I am also running into this issue.

**Comment by mingxingtan** [comment]
There must be some bugs. Looking now.

**Comment by etam103** [comment]
Thanks @mingxingtan!

**Comment by etam103** [comment]
Hey @mingxingtan any updates?

**Comment by u10116032** [comment]
Same problem here

**Comment by etam103** [comment]
I noticed https://github.com/google/automl/blob/master/efficientdet/coco_metric.py#L199 area was returning as a ratio for me.  I made a change on my local copy to calculate area every time and now I am getting medium and large for precision and recall.  Not sure if that is the correct code change, but just something I noticed.

**Comment by mingxingtan** [comment]
Wow, thank you so much, @etam103 

This is a hidden bug when val_json_file is None.  I missed this because my old script always had val_json_file.

The previous AP_m=-1 issue can be reproduced by setting val_json_file=None.  With the latest commit https://github.com/google/automl/commit/bc115638acb1332343a058a5df0330a982f82035, you should be able to get reasonable AP_m and AP_large now.
