### ISSUE TITLE
APm and APl values are -1 always

### ISSUE THREAD

**Issue by Samjith888** [google/automl#547]
Noticed that the APm and APl values are always -1 while training on custom objects, I have tested this on couple of different datasets ,but always those values are -1.

![apm](https://user-images.githubusercontent.com/39676803/85823205-74c2ee00-b79a-11ea-94db-9c40bbe1ca89.png)
![apl](https://user-images.githubusercontent.com/39676803/85823208-75f41b00-b79a-11ea-8186-68f29c47d590.png)

Note : This is happened after a specific commit in this repo. I got +ve values  before those commits .
The dataset which i tested this on contains small , medium and large objects .

**Comment by zishanahmed08** [comment]
Same as https://github.com/google/automl/issues/544
