### ISSUE TITLE
Not an issue want to learn biFPN working and implementation 

### ISSUE THREAD

**Issue by adarsh0906** [google/automl#548]
The code for biFPN is bit complicated to understand, so some resource to learn it and also some re implement it will be helpful

**Comment by mingxingtan** [comment]
Hi @adarsh0906 Hmm, I think BiFPN by itself is pretty simple, you might find this comment helpful: https://github.com/google/automl/blob/14548b7175e093c9f0586b372180c41ffc04fbc1/efficientdet/efficientdet_arch.py#L454
and here is the implementation: https://github.com/google/automl/blob/14548b7175e093c9f0586b372180c41ffc04fbc1/efficientdet/efficientdet_arch.py#L567
