### ISSUE TITLE
how to do Quantization aware training?

### ISSUE THREAD

**Issue by aa12356jm** [google/automl#553]
i am not  familiar with tf, who can give some tips or codes ? thanks

**Comment by mingxingtan** [comment]
Good pont. We don't support quantization aware training, but we just added the [kera model](https://github.com/google/automl/blob/14548b7175e093c9f0586b372180c41ffc04fbc1/efficientdet/keras/efficientdet_keras.py#L891), which should make it easy to add quantization-aware training according to https://www.tensorflow.org/model_optimization/guide/quantization/training_example

**Comment by aa12356jm** [comment]
thanks ,but   the model weights of keras quantization-aware training   is  int8  datatype , i need unit8 model to run in dsp,  can you add the quantization-aware training of tf1.x？ thanks

**Comment by mingxingtan** [comment]
We added pretrained checkpoints for efficientdet-lite, and you can easily do post-training quantization (with very small accuracy drop: see this table:  https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints

**Comment by mingxingtan** [comment]
Accuracy drop is within 0.4 (e.g., lite2 accuracy dropped from 35.0 -> 34.69)

**Comment by drahmad89** [comment]
I tried to directly take the model built in train.py and pass it to tfmot.quantization.keras.quantize_model. 
I got a value error ValueError: `to_quantize` can only either be a tf.keras Sequential or Functional model.
It seems the model class is composed of layers which are classes inherited from tf.keras.model. What should the approach be to quantize the model?
