### ISSUE TITLE
How to know which detection result corresponds to which image when i use batchsize images?

### ISSUE THREAD

**Issue by yl305237731** [google/automl#557]
here is my  code:
`
class DetectionServingDriver(object):

    def __init__(self):
        """Initialize the inference driver.
        """
        self.signitures = None
        self.sess = None

    def __del__(self):
        if self.sess:
            self.sess.close()

    def serve_image(self, image_array):
        predictions = self.sess.run(self.signitures['prediction'], feed_dict={self.signitures['image_arrays']: image_array})
        return predictions

    def load(self, saved_model_dir_or_frozen_graph: Text):
        """Load the model using saved model or a frozen graph."""
        self.signitures = {
            'image_arrays': 'image_arrays:0',
            'prediction': 'detections:0',
        }

        # Load a frozen graph.
        graph_def = tf.GraphDef()
        with tf.gfile.GFile(saved_model_dir_or_frozen_graph, 'rb') as f:
            graph_def.ParseFromString(f.read())
        graph = tf.import_graph_def(graph_def, name='')
        self.sess = tf.Session(graph=graph)
`

and detection code

`
images_np, origin_sizes = self.pre_process_img_batch(images)

detections_bs = self.driver.serve_image(images_np)
`
![image](https://user-images.githubusercontent.com/9928596/86123077-7890a080-bb0b-11ea-94fe-5961f09eba38.png)

I got 9 detection boxes, But I don't know which box corresponds to which image?

**Comment by xiaoxin05** [comment]
This is your own implementation of batch data testing

**Comment by yl305237731** [comment]
I got it, because when exporting a frozen model, batchsize is set to 1, the model can only accept one input
