### ISSUE TITLE
TPU evaluation failure

### ISSUE THREAD

**Issue by fishyboy** [google/automl#558]
this evaluation failure only occurs on TPU, but with colab GPU it just works fine. 
the error says that the graph has been changed, which is not true though.
tf version 1.15.3
tpu v3-8 tf version 1.15.3
`
!python main.py --mode=eval \
    --validation_file_pattern={bucket_root}/tfrecord/{val_pattern} \
    --val_json_file=tfrecord/json_val.json \
    --model_name={MODEL} \
    --model_dir={MODEL}-finetune \
    --eval_batch_size=8 --eval_samples={val_per_epoch}  \
    --hparams=voc.yaml \
    --strategy="tpu" \
    --eval_master={TPU_ADDRESS} \
    --tpu={TPU_ADDRESS} \
`

`
INFO:tensorflow:Restoring parameters from gs://?/efficientdet-d7-finetune/model.ckpt-1400
I0701 17:19:57.635934 140446633092928 saver.py:1284] Restoring parameters from gs://?/efficientdet-d7-finetune/model.ckpt-1400
ERROR:tensorflow:Error recorded from evaluation_loop: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

No OpKernel was registered to support Op 'PyFunc' used by node PyFunc (defined at /home/?/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [_xla_inferred_shapes=[<unknown>], token="pyfunc_0", Tout=[DT_FLOAT], Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32]]
Registered devices: [CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[PyFunc]]
E0701 17:20:02.161428 140446633092928 error_handling.py:75] Error recorded from evaluation_loop: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

No OpKernel was registered to support Op 'PyFunc' used by node PyFunc (defined at /home/?/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [_xla_inferred_shapes=[<unknown>], token="pyfunc_0", Tout=[DT_FLOAT], Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32]]
Registered devices: [CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[PyFunc]]
INFO:tensorflow:evaluation_loop marked as finished
I0701 17:20:02.161969 140446633092928 error_handling.py:101] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0701 17:20:02.162150 140446633092928 error_handling.py:135] Reraising captured error
`

**Comment by mingxingtan** [comment]
Hi @fishyboy yeah, due to the pyfun, evaluation cannot run on TPU.
Thanks to the keras efforts, we are in the process of rewriting train/eval/postprocessing, and hopefully we can support TPU eval soon.
