### ISSUE TITLE
Are kernel weights the only parameters regularized?

### ISSUE THREAD

**Issue by LinHungShi** [google/automl#559]
Based on this snippet of code
(https://github.com/google/automl/blob/acb0d47a12e4df63c0f69a0b493d8c669bff806a/efficientdet/det_model_fn.py#L405)

It seems you only regularize kernel weight in cnn layers. It is correct?

**Comment by mingxingtan** [comment]
Hi @LinHungShi  That's right!  bias/batch_norm should not be regularized.

**Comment by LinHungShi** [comment]
OK. Thanks.
