### ISSUE TITLE
File "main.py", line 318, in main     current_step = int(os.path.basename(ckpt).split('-')[1]) IndexError: list index out of range

### ISSUE THREAD

**Issue by honghande** [google/automl#56]
what's wrong with it?

**Comment by mingxingtan** [comment]
Could you run "git pull" to get the latest result? The original code is assuming the checkpoint files are in the format of "xx-step.yy". The issue had been fixed a few days ago:

https://github.com/google/automl/blob/89f2e50e7bdf3a6539dcbb0b80bbb6658913eb0c/efficientdet/main.py#L318

**Comment by mingxingtan** [comment]
I am going to close this issue for now, but please feel free to reopen it if you still have problems.
