### ISSUE TITLE
Why the 'max_steps' is calculated like this?

### ISSUE THREAD

**Issue by huangh12** [google/automl#562]
Hi @mingxingtan ,
     In the main.py, the `max_steps` is calculated like:

```Python
    ...
    train_estimator.train(
        input_fn=dataloader.InputReader(
            FLAGS.training_file_pattern,
            is_training=True,
            use_fake_data=FLAGS.use_fake_data,
            max_instances_per_image=max_instances_per_image),
        max_steps=int((config.num_epochs * FLAGS.num_examples_per_epoch) /
                      FLAGS.train_batch_size))
```
But I think this may be somewhat unreasonable (or maybe I am wrong..).
The `num_examples_per_epoch` is a fixed number for a specific dataset, e.g., 5717 for pascal voc. And the `train_batch_size` means the global batch size. Let's assume two cases.
First case, training on singe GPU with `train_batch_size(global batch size)=64`, while in the second case we train with 8 GPUs with `train_batch_size(global batch size)=64` .  With above max_steps calculation, we will obtain same max_steps number.  However, since in 8-gpu training case, the global steps will increase 8 times faster (because its steps_per_run is 8 instead of 1), it will reach the max_steps much quicker than the single-gpu training case.  Considering both cases are trained with **same** global batch size, the 8-gpu case has only 1/8 session run of 1-gpu case.  This seems irrational.

How do you think of the above cases. Could you please correct me if I am thinking wrong?

Thank you very much!

**Comment by mingxingtan** [comment]
hi @huangh12 

Good point. This code assume global_step is increased by 1 for each step. If you train on TPU, then there is only one global_step, which will increase by 1 for each step.

For multi-GPU, I haven't verified. If the the global step increased 8 for each step, then you are right and you need to adjust the max_step accordingly. If you have verified horovod indeed works like this, feel free add a PR to change the max_steps for horovod in this line:

https://github.com/google/automl/blob/14548b7175e093c9f0586b372180c41ffc04fbc1/efficientdet/main.py#L244

You can add @fsx950223 and me to review your PR. Thank you!

**Comment by fsx950223** [comment]
It means per replica batch size in horovod, you could submit a PR to unify it to global batch size.

**Comment by huangh12** [comment]
Thanks for the reply, I'll check it.
