### ISSUE TITLE
Low performance on saved_model using batch_size parameter

### ISSUE THREAD

**Issue by physxP** [google/automl#575]
When I save the model using the following command:
`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir `
I get 25 fps on gtx 1050ti on single batch. But if I specify batch size like this:
`python model_inspect.py --runmode=saved_model --batch_size=1 --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir `
i.e. I set --batch_size=1 I get 8 fps. And if I set --batch_size=8 I get 1 fps. I would like to understand why this is happening as I need high throughput in my current project. Thanks.

**Comment by mingxingtan** [comment]
You probably changed some code,  --batch_size=1 is equivalent to omitting this option (because the default value of batch_size is 1), so your two command lines should be equivalent.  Could you retry it with a clean code?

**Comment by physxP** [comment]
Thanks this seems to have fixed the fps issue.
