### ISSUE TITLE
35.1 % mAP with a modified D0 model

### ISSUE THREAD

**Issue by shivam-raj** [google/automl#578]
Hey @mingxingtan 
Amazing paper !!! I really got inspired by your model's simplicity 
I am a college student and I just started with CV research (Please excuse my noobness 😬).
I really wanted to know why you went with just one FPN extracting from backbone and not paralleling this process of feature fusion (Multiple FPNs learning features from backbone) ?
I modified your network a bit and got a minimum of 1.2% mAP improvement on all your base models ( I didn't have the resources to train the bigger models but I think they should work with the other variant I used).
The results I got from using more FPNs for extracting features and learning directly from backbone was as follows :
D0 in 4.1 million parameters and 35.1 % test-dev mAP (2.54B FLOPS)
D1 with 7.35M parameters and 40.8% '' mAP (7.15B FLOPS)
D2 with  9.7M parameters getting 44.2% '' mAP  (14.35B FLOPS)
Same backbone for all the networks
I created another variant of this model which achieves even better results (35.2%mAP D0 using less parameters). I'm really starting to doubt my methods.

Is it like a speed vs accuracy trade off ?
I'm really confused. Can you please help me ??

**Comment by mingxingtan** [comment]
Wow, that's amazing.  I am very interested in your changes. Could you prepare a PR and I am happy to help verify your code (potentially retrain bigger models).

BTW, welcome to the CV research community. Looks like you have a good start!

**Comment by shivam-raj** [comment]
Thanks man !! It really means alot
I'll make a PR by evening and let you know about the details of the modified model
Thanks again 👍
