### ISSUE TITLE
TFLite: Several operations don't supported by the GPU delegate

### ISSUE THREAD

**Issue by alexiniestags** [google/automl#585]
Here I attach the traceback obtained: 
```
E/tensorflow: CameraActivity: Exception!
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    ADD: OP is supported, but tensor type isn't matched!
    ADD_N: Operation is not supported.
    ARG_MAX: Operation is not supported.
    CAST: Operation is not supported.
    DIV: Op can only handle 1 or 2 operand(s).
    EXP: Operation is not supported.
    GATHER: Operation is not supported.
    NON_MAX_SUPPRESSION_V5: Operation is not supported.
    PACK: Operation is not supported.
    REDUCE_MAX: Operation is not supported.
    STRIDED_SLICE: S
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:132)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1209)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    ADD: OP is supported, but tensor type isn't matched!
    ADD_N: Operation is not supported.
    ARG_MAX: Operation is not supported.
    CAST: Operation is not supported.
    DIV: Op can only handle 1 or 2 operand(s).
    EXP: Operation is not supported.
    GATHER: Operation is not supported.
    NON_MAX_SUPPRESSION_V5: Operation is not supported.
    PACK: Operation is not supported.
    REDUCE_MAX: Operation is not supported.
    STRIDED_SLICE: S
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:347)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:130)
        	... 9 more
```
Any solution for this? Maybe the postprocess is the responsible of this.  If you consider this issue should not be here, please feel free of closing it.
Thanks in advance

**Comment by alexiniestags** [comment]
I update here in case someone is interested in:
I have tried the NNApi Delegate with a few things worth to mention:
First one, I have found that in Android 10 the app crashes (I am using the TFLite Detect App that tensorflow provides)
Then, the results obtained in the devices tested using the NNApi (which works) are slower than using CPU. It might be due to some unsupported operations, which in this case I think the API is copying the data to CPU and back to GPU, which has a big overhead.
That's all for now, any suggestions or questions please feel free to let them here.

**Comment by InfiniteLife** [comment]
@alexiniestags I managed to run d0 with GPU-delegate:
```
      GpuDelegate delegate = new GpuDelegate();
      Interpreter.Options options = (new Interpreter.Options()).addDelegate(delegate);
      d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename),options);
```
and did not get an error about unsupported operations.
But it works slow anyways.
I do not know what our differences, may be dependencies? 
I use these in my Gradle script:
```
    implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') { changing = true }
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.2.0' 
```
It will be interesting to know whether model also runs slow on your device if you will be able to run it.

**Comment by InfiniteLife** [comment]
I've measured inference time in CPU version and with GPU-delegate. It is the same. Seems like model runs on CPU even with GPU delegate. I found related issue here: https://github.com/tensorflow/tensorflow/issues/40144 altough no solution.

**Comment by Abdktefane** [comment]
I try GPU delegate but inference time same as CPU
and same issue when i try NNapi 
`java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    ADD: OP is supported, but tensor type isn't matched!
    ADD_N: Operation is not supported.
    ARG_MAX: Operation is not supported.
    CAST: Operation is not supported.
    DIV: Op can only handle 1 or 2 operand(s).
    EXP: Operation is not supported.
    GATHER: Operation is not supported.
    NON_MAX_SUPPRESSION_V5: Operation is not supported.
    PACK: Operation is not supported.
    REDUCE_MAX: Operation is not supported.`
any solution ?

**Comment by alexiniestags** [comment]
Hello @InfiniteLife ,
I think the problem is that some opperations are not yet supported and the API moves back to CPU the tensors in order to compute these operations. I do not think the whole model is running on CPU using the GPU/NNApi delegates. Very interesting issue, I guess the solution must come from an update to the TFLite gpu delegate. I was using the TFLite-gpu 0.0.0 though, I'll try to update, but I do not expect major improvements by now. 

@Abdktefane I had the same log error using the GPUDelegate, but with NNApi I was able to run the model. As you can see, by now the usage of NNApi or GPUDelegate are not good choices though.

**Comment by mingxingtan** [comment]
I believe the latest code and tflite models can run well on mobile GPUs.
