### ISSUE TITLE
Image resolution is different wrt EfficientNets?

### ISSUE THREAD

**Issue by anuar12** [google/automl#587]
Hi, I wanted to confirm that the image resolutions that you use for EfficientDets are different (higher) than the original backbone EfficientNets. E.g. 512 for d0 and 224 for b0. You just resize inputs and reuse Efficientnet with the same width/depth?

**Comment by mingxingtan** [comment]
Yes, this is expected. Detection needs to localize each object, so it need higher resolution.
Notably, convnet weights are independent of resolution, so you can still load the original weights and retrain with any resolution.
