### ISSUE TITLE
Not able to export model for inference after finetune

### ISSUE THREAD

**Issue by rezabasiri** [google/automl#597]
My issue is similar to #214 

On Colab, I have finetuned the model on custom data. Now I have model_dir directory with the new ckpts (efficientdet-d1-finetune) and automl directory with the original efficientdet-d1 ckpt. During inference, for "saved_model" runmode where the model needs to be exported first, can you clarify where ckpt_path should be pointing to? 

I tried pointing it to content/model_dir/efficientdet-d1-finetune where the new ckpts are saved but I get "ExponentialMovingAverage not found in checkpoint" and "Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint" errors.

I also tried pointing it to the original ckpt (/content/automl/efficientdet/efficientdet-d1) assuming based on your #214 reply it will skip the original ckpt and read the new ones under model_dir. But I get very suboptimal inference results. During train_eval I was getting high AP values, so I was expecting accurate detection in testing. How can I make sure it is reading the finetuned ckpts?

Thanks

**Comment by rezabasiri** [comment]
Re_specifying the same hparams at saved_model fixed it.

**Comment by BernardinD** [comment]
@rezabasiri could you specify specifically which hparams and where?
