### ISSUE TITLE
How to add background image that not have labeled object  to train

### ISSUE THREAD

**Issue by northeastsquare** [google/automl#598]
Hello, How to add background image, not have any class image to train
Some images may not contain any labeled objects. How to add these images to the dataset as negative examples
as it is import to remove false positive detections

**Comment by fitoule** [comment]
add this in tfrecord with class = 0

**Comment by northeastsquare** [comment]
Then how about the ground truth box

**Comment by kartik4949** [comment]
@northeastsquare refer #695
