### ISSUE TITLE
How can I predict an image?

### ISSUE THREAD

**Issue by levanpon98** [google/automl#6]
Anyone could tell me how to predict an image?

**Comment by levanpon98** [comment]
Anyone could tell me how to predict an image?

**Comment by deepakcrk** [comment]
`python3 model_inspect.py --runmode infer --model_name efficientdet-d1 --input_image abc.jpg ....`

**Comment by kaikaizhu** [comment]
@deepakcrk When I use this command,an error occurred：
Segmentation fault (core dumped)
Do you know how to slove it?
Thanks!

**Comment by levanpon98** [comment]
@kaikaizhu 
`python model_inspect.py --runmode=infer --model_name=efficientdet-d0 --ckpt_path=/tmp/efficientdet-d0/ --input_image=/tmp/img1.jpg --output_image_dir=/tmp/det1/`
Run this command instead
Remember dowload pre-train before excute this command

**Comment by MarsTT** [comment]
> @kaikaizhu
> `python model_inspect.py --runmode=infer --model_name=efficientdet-d0 --ckpt_path=/tmp/efficientdet-d0/ --input_image=/tmp/img1.jpg --output_image_dir=/tmp/det1/`
> Run this command instead
> Remember dowload pre-train before excute this command

Hi, how do you predict more than one picture at a time?

**Comment by levanpon98** [comment]
@MarsTT 
Hi, you can replace the value of param `input_image` to image file pattern.

**Comment by Zumbalamambo** [comment]
+1

**Comment by Jilliansea** [comment]
> @MarsTT
> Hi, you can replace the value of param `--input_image` to image file pattern.

Hi, I want to detect a image lists in form of 'txt', and I change the code to build_input, but it also error in post process. Because the batch size of  inference is 1, when send all images to the model, it also deal as 1 batch, then then anchor numbers will biger then index...

**Comment by Jilliansea** [comment]
@deepakcrk Could you please publish  an inference code to "change ckpt to pb " and inference by pb model for multi-images? Thanks a lot

**Comment by xafarranxera** [comment]
> Hi, you can replace the value of param `--input_image` to image file pattern.

Can you please give an example? If I replace it with /folder/*.jpg, it doesn't take all images inside folder...

**Comment by mingxingtan** [comment]
Please find instructions on  README: https://github.com/google/automl/blob/master/efficientdet/README.md
or the tutorial: https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb

Regarding inference multiple issues, there was a small bug in inference.py, and I have fixed that in https://github.com/google/automl/commit/856d659bcc638a73d4ee9f88b466faf903cd4de3

I have verified the following commands run well:

$ python model_inspect.py --model_name=efficientdet-d0 --ckpt_path=/tmp/efficientdet/efficientdet-d0/ --runmode=infer --input_image=/tmp/effin/*.jpg  --output_image_dir=/tmp/effout

I would close this bug now, but feel free to reopen it if you still have issues.
