### ISSUE TITLE
what is the best way to inference for specific classes like person and car 

### ISSUE THREAD

**Issue by Abdktefane** [google/automl#603]

**Comment by mingxingtan** [comment]
You can either filer the class early or use per-class nms.

1. If you are using global_nms, you can add some code to filer out other classes here: https://github.com/google/automl/blob/e4b504d73fec80343683563305bfcaddb93139e7/efficientdet/keras/postprocess.py#L251

2. If you are using per-class-nms, you can simply change this for loop:

https://github.com/google/automl/blob/e4b504d73fec80343683563305bfcaddb93139e7/efficientdet/keras/postprocess.py#L290

to something like for `for cid in [0, 5]` (assuming person is 0 and car is 2)
