### ISSUE TITLE
Difference between TF object detection API and this repo

### ISSUE THREAD

**Issue by zishanahmed08** [google/automl#604]
[ TF object detection-TFOD ](https://github.com/tensorflow/models/tree/master/research/object_detection) recently added support for Efficient det and have comparable results. Does the author see any potential drawback of using TFOD instead of this repo?

**Comment by mingxingtan** [comment]
Hi @zishanahmed08 Please feel free to choose any one that is more convenient to you.

TFOD is a more stable and more complicated codebase with also more choices, while this repo is more focused on efficientnet/det/seg and we may add some improvements more frequently.
