### ISSUE TITLE
What does it mean gnorm value?

### ISSUE THREAD

**Issue by sakulh** [google/automl#606]
I train on my own dataset with these parameters: 

_MODEL = 'efficientdet-d3'
NUM_EPOCHS = 300
BATCH_SIZE = 1
IMAGES_PER_EPOCH = 56 
num_classes = '9'
moving_average_decay = '0'
label_id_mapping = '{1: car, 2: truck, 3: bicycle, 4: bus, 5: person, 6: tir, 7: morcycle, 8: ship}'
mixed_precision = 'true'
var_freeze_expr = 'efficientnet'_

Train command:

_!python main.py \
    --training_file_pattern=/mydataset/tfrecord/train* \
    --model_name={MODEL} \
    --model_dir={MODEL_BASE_DIR}/{MODEL}-{DT} \
    --train_batch_size={BATCH_SIZE} \
    --ckpt_path=/efficientdet-d3 \
    --hparams=config.yaml_

The graphs in the tensorboard look as follows

![image](https://user-images.githubusercontent.com/30235823/87789936-18566a00-c840-11ea-90b2-f59211b8f47e.png)

What does the gnorm value mean? Is its shape on the graph right?

Thank you.

**Comment by mingxingtan** [comment]
gnorm is "global norm". Here is a doc on how "global norm" is computed: https://www.tensorflow.org/api_docs/python/tf/clip_by_global_norm

**Comment by sakulh** [comment]
Thank you. Do you have an explanation for why the graph first decreases and then increases? Is it overfitting?
