### ISSUE TITLE
How long does it take to train (finetune) on COCO for a single Titan RTX ?

### ISSUE THREAD

**Issue by doduythao** [google/automl#607]
Hi everyone,
I only have a machine with titan rtx and other machine with 2 titan xp.
I want to fine-tune train on COCO but I really consider the training time.
Thank you all.

**Comment by kartik4949** [comment]
@doduythao Hi
it depends on total_trainging_steps , image_size and efficientdet model i.e d0,d1,etc

roughly for me it took less than 24hours ,d0 on tesla v100 32gigs ,it takes to train 60-70k steps  
thanks

**Comment by mingxingtan** [comment]
Thanks @kartik4949 !
