### ISSUE TITLE
how to use keras model

### ISSUE THREAD

**Issue by Abdktefane** [google/automl#608]

**Comment by Abdktefane** [comment]
i try this 
`config = hparams_config.get_efficientdet_config('efficientdet-d0')
    config.is_training_bn = False
    config.image_size = image_size
    config.nms_configs.score_thresh = nms_score_thresh
    config.nms_configs.max_output_size = nms_max_output_size
    config.anchor_scale = [1.0, 1.0, 1.0, 1.0, 1.0]
    # Create and run the model.
    model = efficientdet_keras.EfficientDetModel(config=config)
    height, width = utils.parse_image_size(config['image_size'])
    model.build((1, height, width, 3))
    model.load_weights()
    model.summary()`
but i get :
`OSError: Unable to open file (file read failed: time = Sun Jul 19 15:48:19 2020
, filename = 'efficientdet-d0', file descriptor = 5, errno = 21, error message = 'Is a directory', buf = 0x7fff6b9af7b0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)
`

**Comment by mingxingtan** [comment]
Maybe you need to specify a filename for 'model.load_weights()'?
See this example: https://github.com/google/automl/blob/master/efficientdet/keras/infer.py

**Comment by mingxingtan** [comment]
Also, please delete config.anchor_scale = [1.0, 1.0, 1.0, 1.0, 1.0] (it as a mistake and has been fixed in the example a few days ago)

**Comment by mm7721** [comment]
@mingxingtan, I'm trying to get the keras version going too.  I've sourced the latest repo, so should have the fix you mention above.  A couple additional questions:

1. How are pre-trained model weights loaded?
2. Does the equivalent of train_and_eval exist in the keras version?  If not, can you suggest how to add it?

Thanks.

**Comment by mm7721** [comment]
Also, in attempting to train on Pascal val dataset, the following error is encountered on the dataloader.InputReader() call:

ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor

The input are the Pascal val tfrecords used successfully in the non-keras version.  So this adds a third question:

3. How do we set up the input dataset for the keras model training?

**Comment by Abdktefane** [comment]
@mingxingtan 
i try `keras/infer.py` but i get this:
`line 2785, in _is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or AttributeError: 'NoneType' object has no attribute 'endswith'`
is there error in ckpt file or what i did wrong ?
