### ISSUE TITLE
change the tmp directory

### ISSUE THREAD

**Issue by chaohuang** [google/automl#609]
Hi,

I'm training with checkpoint efficientDet-d6, and set the `--model_dir = ./model`.

But it keeps generating temporary files in the /tmp directory, and exhausts the disk space, so I wonder if we can turn off the tmp files generation, or if we can change the directory of the generated tmp files.

Thanks.

**Comment by mingxingtan** [comment]
Hmm, do you know what temporary files are generated?

If you are using linux, you might want to set TMPDIR=xxx as a workaround.

**Comment by chaohuang** [comment]
> Hmm, do you know what temporary files are generated?
> 
> If you are using linux, you might want to set TMPDIR=xxx as a workaround.

@mingxingtan  Hi, setting the TMPDIR env variable works, thanks!

The generated temporary files are like:

![image](https://user-images.githubusercontent.com/1179764/88014573-1dcbe280-cad4-11ea-9577-99980b5341e9.png)

And the subdirectories, e.g. tmph_voifu7, contain the checkpoints:

![image](https://user-images.githubusercontent.com/1179764/88014728-7c915c00-cad4-11ea-8973-a8eaae62f6c8.png)

But I already set `--model_dir = ./model`, and it indeed saves model checkpoints in the model folder, so I don't know why it generates so many additional folders with checkpoints.
