### ISSUE TITLE
A bug with network resolution? 

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#616]
I have converted same network setting up default resolution and without it:
model d3:
```
python model_inspect.py --runmode=saved_model --model_name='efficientdet-d3' \
  --ckpt_path='/d3' --saved_model_dir='/d3_896x896' \
  --hparams="moving_average_decay=0,num_classes=2,image_size=896x896"
```
and
```
python model_inspect.py --runmode=saved_model --model_name='efficientdet-d3' \
  --ckpt_path='/d3' --saved_model_dir='/d3_default' \
  --hparams="moving_average_decay=0,num_classes=2"
```
The output results are different.
For first model:
![0___](https://user-images.githubusercontent.com/7304884/88062035-f4ad5f80-cb70-11ea-9005-b94c5b73e99a.jpg)

for second one:
![0](https://user-images.githubusercontent.com/7304884/88062057-fb3bd700-cb70-11ea-9c5a-c09536fa49c8.jpg)
I do not really understand from where this difference might come.
As I understand there is resize inside the network graph which is being set during conversion. May be there is some other tensors which are affected by passing parameter` image_size`?

**Comment by yl305237731** [comment]
In hparams_config.py, for d0 - d7, Each has a default input size, which will be overridden if you specify a size. If you have not retrained the model, it is not recommended to specify the input size. The default is OK @InfiniteLife

**Comment by InfiniteLife** [comment]
> In hparams_config.py, for d0 - d7, Each has a default input size, which will be overridden if you specify a size. If you have not retrained the model, it is not recommended to specify the input size. The default is OK @InfiniteLife

I have retrained model, and I am specifying default size which is 896 for this model, that's why I see this is a problem. Image supposed to be the same.

**Comment by InfiniteLife** [comment]
Nvm, I made mistake somewhere during conversion. Double checked today and output is the same.
