### ISSUE TITLE
Validation Accuracy Regression

### ISSUE THREAD

**Issue by LucasSloan** [google/automl#619]
Before 52ea7a690d158d8de29d99ce614275715e50dc8f, d0 had a validation AP of 33.5, after, it has a validation AP of 32.8.  I've traced the difference to the change of nms method from 'hard' to 'gaussian'.  Is that change intentional?

**Comment by mingxingtan** [comment]
Hmm, I thought 'gaussian' is better, but look like the tf version of gaussian has some issue.  I will revert it back to hard.

**Comment by fsx950223** [comment]
No, gussian nms calculate ap0.3 but hard nms calculate ap0.5, so gussian nms got lower ap.
Why do you set iou 0.3 in gussian nms @mingxingtan ?

**Comment by LucasSloan** [comment]
I tried running the gaussian nms with IOU 0.5, but it was still lower than
hard nms (33.4 versus 33.5).

**Comment by mingxingtan** [comment]
The TF version of soft nms seems to has some issues, see this link: https://github.com/google/automl/blob/ca851ff4e4c421f1777ae5b677472d34ed068555/efficientdet/det_model_fn.py#L457

**Comment by fsx950223** [comment]
soft nms won't be influenced by iou, I made some mistake.
