### ISSUE TITLE
How to enable gpu inference?

### ISSUE THREAD

**Issue by evanmartua34** [google/automl#620]
Hi, I am running the inference on a machine with gpu available , does it will automatically run with gpu? thank you

**Comment by yl305237731** [comment]
yes, at least for me

**Comment by Ely-S** [comment]
Yes. Run `nvidia-smi` while training to verify that it is using the GPU.

**Comment by mingxingtan** [comment]
Yes, it use GPU for inference in default (if your machine has GPUs)
