### ISSUE TITLE
How to train using the new Keras model

### ISSUE THREAD

**Issue by davidmurray** [google/automl#628]
Hello,

It seems that the Keras implementation is now ready for deployment. I would like to fine-tune the model D0 using the new keras implementation.

Do you have an example of how to use the `keras/train.py` script?

Thanks!

**Comment by mingxingtan** [comment]
Do you mean the flags for keras/train.py? It is pretty much the same as the original main.py

@fsx950223 Could you help give an example for finetuning?

**Comment by fsx950223** [comment]
python3 train.py --model_name=efficientdet-d0 --model_dir=${MODEL_DIR} --batch_size=${BATCH_SIZE} --training_file_pattern=${DATASET}/train/* --validation_file_pattern=${DATASET}/test/* --num_examples_per_epoch=${EXAMPLES}

**Comment by davidmurray** [comment]
Thanks guys!
