### ISSUE TITLE
TensorRT: unable to convert to .uff

### ISSUE THREAD

**Issue by swchew** [google/automl#630]
I tried to convert efficientdet-d0_frozen.pb into a .uff file for integration with TensorRT, using the TensorRT function "convert-to-uff". However, I encountered the following error:

lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 126, in as_numpy_dtype
    return _TF_TO_NP[self._type_enum]
KeyError: 21

In fact, I have never been unable to convert .pb files generated by automl. Does anybody know the reason to this kindly share please. Thank you.

**Comment by mingxingtan** [comment]
@swchew You can try the newly added simple script: https://github.com/google/automl/blob/master/efficientdet/tensorrt.py

**Comment by swchew** [comment]
Thank you @mingxingtan, the script is very helpful and I managed to convert the model for use with TF-TRT. I still have not managed, however, to convert into .uff for pure TensorRT.

**Comment by hoangmt** [comment]
I am also interested in converting the model into pure TensorRT. Is it possible to do it or the network or the network has some customized layer that can not be converted to pure TensorRT?
