### ISSUE TITLE
Network latency benchmark for saved models

### ISSUE THREAD

**Issue by huyhung411991** [google/automl#631]
Hi,

I would like to ask if it is possible to implement network latency benchmark for saved models, especially for tensorrt ones.

The reason is, as far as I understand, the current option (_python model_inspect.py --runmode=bm_) parsing the checkpoint to TensorRT model on-the-fly, and when I tried to perform such benchmark of EfficientDet with EfficientNet-lite2 to lite4 backbone on Jetson TX2, it almost filled the shared CPU/GPU memory. As a result, the measurements were no longer correct (TRT FP32 was worse than nonTRT, and TRT FP16 was not much an improvement).

![Capture](https://user-images.githubusercontent.com/994484/88707944-ea312e00-d14d-11ea-88be-c98801e22f5f.PNG)

**Comment by mingxingtan** [comment]
You can export network freeze graph with:

`python model_inspect.py  --runmode=freeze --model_name=efficientdet-d0 --ckpt_path=ckpt/efficientdet-d0 --logdir=/tmp/net/`

Then you will see `/tmp/net/efficientdet-d0_frozen.pb`

**Comment by huyhung411991** [comment]
@mingxingtan What I asked is if there is anyway to measure network latency with saved models, due to the reason I mentioned previously. At the moment, we can only measure the end-to-end latency with saved models, as far as I know.

**Comment by huyhung411991** [comment]
@mingxingtan Then, can I use the frozen graph to measure the network latency?

**Comment by mingxingtan** [comment]
Yes, you can use the frozen graph to measure the latency (or convert the tensorRT)

**Comment by mingxingtan** [comment]
What's your command flow for TensorRT inference? Does it take a frozen graph or a saved model? Does it require converting to onnx?

**Comment by mingxingtan** [comment]
frozen network input is `input`, 
outputs are `class_net/class-predict_1/BiasAdd:0,class_net/class-predict_2/BiasAdd:0,class_net/class-predict_3/BiasAdd:0,class_net/class-predict_4/BiasAdd:0,box_net/box-predict/BiasAdd:0,box_net/box-predict_1/BiasAdd:0,box_net/box-predict_2/BiasAdd:0,box_net/box-predict_3/BiasAdd:0,box_net/box-predict_4/BiasAdd:0`

**Comment by huyhung411991** [comment]
@mingxingtan
All the training and benchmark were performed using your source. First I convert KITTI training dataset to tfrecord format and trained the models using command: 

`python main.py --mode=train_and_eval --training_file_pattern=tfrecord_kitti/kitti_train*.tfrecord --validation_file_pattern=tfrecord_kitti/kitti_val*.tfrecord --model_name=efficientdet-lite3 --model_dir=models/efficientdet-lite3-kitti --backbone_ckpt=checkpoints/efficientnet-lite3 --train_batch_size=8 --eval_batch_size=8 --eval_samples=512 --num_examples_per_epoch=6481 --num_epochs=400 --use_xla=True --hparams=kitti.yaml`

Then I try to benchmark the network latency with the trainned checkpoints using:
```
python model_inspect.py --runmode=saved_model --model_name=efficientdet-lite3 --ckpt_path=models/efficientdet-lite3-kitti/archive --saved_model_dir=models_2/efficientdet-lite3 --hparams=kitti.yaml

python model_inspect.py --runmode=saved_model --model_name=efficientdet-lite3 --ckpt_path=models/efficientdet-lite3-kitti/archive --saved_model_dir=models_2/efficientdet-lite3_fp32 --tensorrt=FP32 --hparams=kitti.yaml

python model_inspect.py --runmode=saved_model --model_name=efficientdet-lite3 --ckpt_path=models/efficientdet-lite3-kitti/archive --saved_model_dir=models_2/efficientdet-lite3_fp16 --tensorrt=FP16 --hparams=kitti.yaml
```

Content of the kitti.yaml file:
```
num_classes: 2
moving_average_decay: 0
mixed_precision: True
```

The benchmark result in the non-TensorRT mode was normally. But in TensorRT FP32 and FP16 mode there seemed to be memory problem as the 8GB shared memory of the Jetson TX2 was almost filled and the latency results were not as I expected.
The coressponding results for EfficientDet-Lite0 and Lite1 are: 16.5fps 20.0fps 22.2fps, 8.9fps 9.1fps 10.6fps.
From Lite2 to Lite4, the throughput in TensorRT FP32 mode became worse than natively without TensorRT.

**Comment by huyhung411991** [comment]
@mingxingtan
Then I tried to measure the network latency using:
```
python model_inspect.py --runmode=bm --model_name=efficientdet-lite3 --batch_size=1 --bm_runs=10 --hparams=kitti.yaml

python model_inspect.py --runmode=bm --model_name=efficientdet-lite3 --batch_size=1 --bm_runs=10 --hparams=kitti.yaml --tensorrt=FP32

python model_inspect.py --runmode=bm --model_name=efficientdet-lite3 --batch_size=1 --bm_runs=10 --hparams=kitti.yaml --tensorrt=FP16
```

Content of the kitti.yaml file:
```
num_classes: 2
moving_average_decay: 0
mixed_precision: True
```

The benchmark result in the non-TensorRT mode was normally. But in TensorRT FP32 and FP16 mode there seemed to be memory problem as the 8GB shared memory of the Jetson TX2 was almost filled and the latency/throughput results were not as I expected.
The coressponding results for EfficientDet-Lite0 and Lite1 are: 16.5fps 20.0fps 22.2fps, 8.9fps 9.1fps 10.6fps.
From Lite2 to Lite4, the throughput in TensorRT FP32 mode became worse than natively without TensorRT.

**Comment by huyhung411991** [comment]
@mingxingtan
I also had the trained checkpoints on KITTI dataset with:

`python main.py --mode=train_and_eval --training_file_pattern=tfrecord_kitti/kitti_train*.tfrecord --validation_file_pattern=tfrecord_kitti/kitti_val*.tfrecord --model_name=efficientdet-lite3 --model_dir=models/efficientdet-lite3-kitti --backbone_ckpt=checkpoints/efficientnet-lite3 --train_batch_size=8 --eval_batch_size=8 --eval_samples=512 --num_examples_per_epoch=6481 --num_epochs=400 --use_xla=True --hparams=kitti.yaml`

The training step was perform on one Nvidia GTX Titan X.

I can export the trained checkpoints to saved models. But I found no way to measure the network latency using the saved model.
