### ISSUE TITLE
Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint

### ISSUE THREAD

**Issue by mhcao916** [google/automl#632]
I train a detection model based on efficientdet-d0 on my own dataset, after i get the trained ckpt model, and i want to use it to infer, so i run this command:
python model_inspect.py --runmode=infer --model_name=efficientdet-d0  --hparams="image_size=1920x1280"  --max_boxes_to_draw=100   --min_score_thresh=0.4 --ckpt_path=model_dir/d0-finetune/ --input_image='images/q300939xbr7.jpg' --output_image_dir =serve_image_out 

and i get following error:

tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
 (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

afetr get this error, i try this command:
python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=model_dir/d0-finetune --saved_model_dir=finetune-d0
but this error come out again. 
and before i infer my image, i have changed inference.py coco_id={1: 'person', 2:'human_hand'}
anyone can help?

**Comment by BernardinD** [comment]
Same issue for me

**Comment by mingxingtan** [comment]
What is your training command line? It is likely that you train your model with moving_average_decay=0, so your checkpoint doesn't have any ema variables.

If you want, you can use this simple program to list all your checkpoint variables:

```
import tensorflow as tf
import pprint
get_checkpoint = tf.train.latest_checkpoint('.')
var_list = tf.train.list_variables(get_checkpoint)
pprint.pprint(var_list)
```

**Comment by mhcao916** [comment]
> What is your training command line? It is likely that you train your model with moving_average_decay=0, so your checkpoint doesn't have any ema variables.
> 
> If you want, you can use this simple program to list all your checkpoint variables:
> 
> ```
> import tensorflow as tf
> import pprint
> get_checkpoint = tf.train.latest_checkpoint('.')
> var_list = tf.train.list_variables(get_checkpoint)
> pprint.pprint(var_list)
> ```

yes, you are right, i use this command in my train command line, moving_average_decay=0,  and i have solved it by adding the line --hparams=voc_config.yaml in my inference line, thank you.
