### ISSUE TITLE
how to do inference on saved_model with tf serving

### ISSUE THREAD

**Issue by tiru1930** [google/automl#634]
I have trained model and exported to saved_model on custom data served with tf-serving

```
(512, 512, 3)
response.status_code: 400
response.status_code: b'{\n    "error": "scores has incompatible shape\\n\\t [[{{node combined_non_max_suppression/CombinedNonMaxSuppression}}]]"\n}'
````

**Comment by hlemoine3000** [comment]
Did you use this command to export your model?
python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=tmp/efficientdet-d0-finetune \
  --saved_model_dir=tmp/saved_model

When I used the following command to test the saved model on one image, I had the following error:
python3 model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --saved_model_dir=tmp/saved_model  \
  --input_image=img.png --output_image_dir=tmp/

tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: scores has incompatible shape
         [[{{node NonMaxSuppressionV5}}]]
  (1) Invalid argument: scores has incompatible shape
         [[{{node NonMaxSuppressionV5}}]]
         [[NonMaxSuppressionV5/_2883]]

To solve that problem, I added --hparams="num_classes=11" to my export command. By default, it will take num_classes=90 which is not the number of classes of my model.

**Comment by mingxingtan** [comment]
Thanks @hlemoine3000 
@tiru1930  Yes, you need to make sure you use the same hparams during training and serving.
