### ISSUE TITLE
EfficientDet-D5 Weights Missing from README Table

### ISSUE THREAD

**Issue by varunnair18** [google/automl#635]
Hello,

I was trying to use the pre-trained weights from the EfficientDet-D5 model but when downloading the checkpoint [linked](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco2/efficientdet-d5.tar.gz) in the README table I only get txt files and don't see any model weights. Could this [link](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco2/efficientdet-d5.tar.gz) be updated to contain the model weights as well? In the meantime I will try out a different backbone.

Thanks!

**Comment by mingxingtan** [comment]
Ooops, just uploaded the new checkpoint. Thanks for pointing out the issue.
