### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: efficientdet-d0

### ISSUE THREAD

**Issue by nicolas-gervais** [google/automl#64]
![image](https://user-images.githubusercontent.com/46652050/77695210-cb454400-6f81-11ea-9a2e-2641b5b96f4e.png)

**Comment by mingxingtan** [comment]
Hi @nicolas-gervais  It generally means you did not specify the correct checkpoint path. could you verify that?

**Comment by nicolas-gervais** [comment]
I just cloned the repo and ran the 5 lines you gave, that's it.

> ValueError: The passed save_path is not a valid checkpoint: efficientdet-d0

**Comment by mingxingtan** [comment]
Could you post your command lines? Let me try it by myself.

**Comment by nicolas-gervais** [comment]
Solved by making sure `efficientdet-d0` is in `/automl/efficientdet-d0/`.

**Comment by mingxingtan** [comment]
Cool. good to know!
