### ISSUE TITLE
Get intermediate layers of keras model

### ISSUE THREAD

**Issue by kcrumb** [google/automl#641]
In the keras inference script I am trying to get accees to the intermediate layer (output of efficientnet-bx model) and later I want to obtain the gradients. To access a intermediate layer I need to create a  second Model
`keras.Model(inputs=model.get_layer(index=0).inputs, outputs=model.get_layer(index=0).outputs)`
but on creation I get following error: `ValueError: Unknown graph. Aborting.`
Does this have something to do with the fact the the model is subclassed from `tf.keras.Model`? I was searching but I can't find other ways how I could accomplish that.

**Comment by mingxingtan** [comment]
You need to pass in a keras Input, according to this page: https://stackoverflow.com/questions/59383356/accessing-layers-input-output-using-tensorflow-2-0-model-sub-classing

Here is an example:

import tensorflow as tf
import efficientdet_keras

```
m = efficientdet_keras.EfficientDetNet('efficientdet-d0')
inputs = tf.keras.Input(shape=(512, 512, 3))
m(inputs)
for i in m.layers:
  print(i.name, i.input, i.output)
```'

It would output something like this:

```
efficientnet-b0 Tensor("input_1:0", shape=(None, 512, 512, 3), dtype=float32) Tensor("efficientnet-b0/Identity:0", shape=(None, 16, 16, 320), dtype=float32)

resample_p6 Tensor("efficientnet-b0/blocks_15/Identity_3:0", shape=(None, 16, 16, 320), dtype=float32) Tensor("resample_p6/Identity:0", shape=(None, 8, 8, 64), dtype=float32)

resample_p7 Tensor("resample_p6/Identity:0", shape=(None, 8, 8, 64), dtype=float32) Tensor("resample_p7/Identity:0", shape=(None, 4, 4, 64), dtype=float32)

fpn_cells...
```

**Comment by kcrumb** [comment]
Thank you @mingxingtan. I used `EfficientDetModel `instead of `EfficientDetNet`.
I have one more question:
I try to apply [Grad-CAM](https://arxiv.org/abs/1610.02391) to class_net. If I understand it correctly, then a class is determined on the basis of the output of class_net with NMS. For now I only have the gradient of class_net w.r.t efficientnet last_layer. Is it even possible to get the gradient of a specfic class w.r.t the last layer?

[Excerpt](https://github.com/kcrumb/automl/blob/master/efficientdet/keras/infer_grad_cam.py#L88-L95):
```
with tf.GradientTape() as tape:
  cls_outputs, box_outputs, efficientnet_last_layer = effdet_model(inputs, False)

# save gradients
grads = None
if FLAGS.gradient_type == 'cls':
  grads = tape.gradient(cls_outputs, efficientnet_last_layer)
```

**Comment by IngoDbg** [comment]
Did you find an answer to your question if it's possible to apply Grad-Cam to EfficientDet @kcrumb ? I'm stuck with the same question right now.

**Comment by kcrumb** [comment]
@IngoDbg No sry, not to my last question. I dismissed this exploration path. I got it to work, but only w.r.t the last layer. You can view [the code](https://github.com/kcrumb/automl/blob/master/efficientdet/keras/infer_grad_cam.py) in my repo. It produces a picture but you have to figure out how to interpret the resulted heatmap. No guarantee that I implemented it correctly.
