### ISSUE TITLE
is augmix still has problem?

### ISSUE THREAD

**Issue by evanmartua34** [google/automl#642]
I read on #447 that augmix is not recommended as it has some trouble, but I wonder if the issue still goes on ?

**Comment by mingxingtan** [comment]
I believe augmix is still not ready to use.  @fsx950223 may have the latest information.

**Comment by evanmartua34** [comment]
I see thank you for the confirmation

**Comment by fsx950223** [comment]
It's too difficult to fusion bboxs. Maybe I will remove augmix later.
