### ISSUE TITLE
is examples same as image?

### ISSUE THREAD

**Issue by evanmartua34** [google/automl#649]
Hi I actually confuse about the number of examples per epoch parameter, is it the same as number of image that is use in every epoch? How can I use all of my image in every epoch when using custom dataset, I use 1 shards of tfrecords. Thank you

**Comment by mingxingtan** [comment]
num_examples_per_epoch specifies the number of images for each epoch.
We need this to determine the training steps = (num_examples_per_epoch * num_epochs) / batch_size
You can just specify the number of examples in your shards in your case.
