### ISSUE TITLE
Keras loss values are arrays

### ISSUE THREAD

**Issue by staeff777** [google/automl#650]
I got some problems with callback functions that monitor the validation loss.
During the value comparision following error was raised.
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

I found, that the loss values in the log dict are arrays:

```
{
'box_iou_loss': 143.21189880371094, 
'det_loss': 20.50137710571289, '
cls_loss': 5.066265106201172, 
'box_loss': 0.022278420627117157, 
'loss': array([ 21.702984 ,   6.2678723,   1.2238855, 144.41351  ], dtype=float32), 
'gnorm': 2788.44677734375,
'val_box_iou_loss': 19.29452133178711,
'val_det_loss': 4.303554534912109, 
'val_cls_loss': 1.6226767301559448,
 'val_box_loss': 0.015028510242700577,
 'val_loss': array([ 5.5051613,  2.8242831,  1.216635 , 20.496128 ], dtype=float32)
}
```
It seems that the `+` in `total_loss += det_loss` makes an array concatenation.
One solution that works for is to reduce the array to a sum:
```
loss_vals['loss'] =  tf.math.reduce_sum(total_loss)
```

It could be, that the behavior is different in TF 2.3.0. I'm currently working with TF 2.2.0 due to Nvidia reasons.

**Comment by fsx950223** [comment]
we don't support tf2.2
