### ISSUE TITLE
Is there a way to add custom augmentation to training written with Numpy and OpenCV?

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#659]
I see that in preprocessor.py everything written as part of tensorflow graph. Can I somehow add an augmentation processing which is executed in Python, using numpy and openCV?

**Comment by Steve-2040** [comment]
I also have not found a transparent way of using augmentation, and decided to pre-process the augmentation images. This have downsides e.g. big dataset file but work for me currently. This is my script to create new augmented images. The new image and annotation xml files is then combined with the original training images in train.record file. I use labelImg for annotation in PascalVOC format. This may be of help.

import glob
from lxml import etree
import os
from PIL import Image, ImageOps
import numpy as np
import cv2

augAnnDir = "C:/Users/...../Images/AugAnnotations/"
augImgDir = "C:/Users/...../Images/AugImages/"

files = glob.glob("C:/Users/....../Annotations/class1/*.xml")
files += glob.glob("C:/Users/....../Annotations/class2/*.xml")
files += glob.glob("C:/Users/....../Annotations/class3/*.xml")
files += glob.glob("C:/Users/....../Annotations/class4/*.xml")

def horizontal_flip (files, prefix):
    for f in files:
        tree = etree.parse(f)
        root = tree.getroot()
        el_filename = root.xpath('//filename')[0]
        el_path = root.xpath('//path')[0]
        el_bboxs = root.xpath('//object/bndbox')
        el_bbox_names = root.xpath('//object/name')
        size_width = int(root.xpath('//size/width')[0].text)
        size_height = int(root.xpath('//size/height')[0].text)

        org_img_path = el_path.text
        new_ann_filename = prefix + os.path.basename(f)
        new_img_filename = prefix + os.path.basename(el_filename.text)
        new_ann_path = augAnnDir + new_ann_filename
        new_img_path = augImgDir + new_img_filename

        # modify and save as new xml
        for b in el_bboxs:
            x1 = int(b[0].text)
            y1 = int(b[1].text)
            x2 = int(b[2].text)
            y2 = int(b[3].text)
            x1new = size_width - 1 - x1
            x2new = size_width - 1 - x2
            if x1new > x2new:
                x1 = x2new
                x2 = x1new
            else:    
                x1 = x1new
                x2 = x2new
            b[0].text = str(x1)
            b[1].text = str(y1)
            b[2].text = str(x2)
            b[3].text = str(y2)

        el_filename.text = new_img_filename
        el_path.text = new_img_path
        tree.write(new_ann_path)

        # modify and save as new image
        im = Image.open(org_img_path)
        im_aug = ImageOps.mirror(im) # h flip
        im_aug.save(new_img_path, quality=90)

def vertical_flip (files, prefix):
    for f in files:
        tree = etree.parse(f)
        root = tree.getroot()
        el_filename = root.xpath('//filename')[0]
        el_path = root.xpath('//path')[0]
        el_bboxs = root.xpath('//object/bndbox')
        el_bbox_names = root.xpath('//object/name')
        size_width = int(root.xpath('//size/width')[0].text)
        size_height = int(root.xpath('//size/height')[0].text)

        org_img_path = el_path.text
        new_ann_filename = prefix + os.path.basename(f)
        new_img_filename = prefix + os.path.basename(el_filename.text)
        new_ann_path = augAnnDir + new_ann_filename
        new_img_path = augImgDir + new_img_filename

        # modify and save as new xml
        for b in el_bboxs:
            x1 = int(b[0].text)
            y1 = int(b[1].text)
            x2 = int(b[2].text)
            y2 = int(b[3].text)
            y1new = size_height - 1 - y1
            y2new = size_height - 1 - y2
            if y1new > y2new:
                y1 = y2new
                y2 = y1new
            else:    
                y1 = y1new
                y2 = y2new
            b[0].text = str(x1)
            b[1].text = str(y1)
            b[2].text = str(x2)
            b[3].text = str(y2)

        el_filename.text = new_img_filename
        el_path.text = new_img_path
        tree.write(new_ann_path)

        # modify and save as new image
        im = Image.open(org_img_path)
        im_aug = ImageOps.flip(im) # v flip
        im_aug.save(new_img_path, quality=90)

def adj_CLAHE (files, prefix):
    for f in files:
        tree = etree.parse(f)
        root = tree.getroot()
        el_filename = root.xpath('//filename')[0]
        el_path = root.xpath('//path')[0]
        el_bboxs = root.xpath('//object/bndbox')
        el_bbox_names = root.xpath('//object/name')
        size_width = int(root.xpath('//size/width')[0].text)
        size_height = int(root.xpath('//size/height')[0].text)

        org_img_path = el_path.text
        new_ann_filename = prefix + os.path.basename(f)
        new_img_filename = prefix + os.path.basename(el_filename.text)
        new_ann_path = augAnnDir + new_ann_filename
        new_img_path = augImgDir + new_img_filename

        # modify and save as new xml
        el_filename.text = new_img_filename
        el_path.text = new_img_path
        tree.write(new_ann_path)

        # modify and save as new image
        im = Image.open(org_img_path).convert('L')
        im_cv = np.array(im)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        im_aug = Image.fromarray(clahe.apply(im_cv))
        im_aug.save(new_img_path, quality=90)

horizontal_flip(files, 'ah')
vertical_flip(files, 'av')
adj_CLAHE(files, 'ac')

**Comment by kartik4949** [comment]
@InfiniteLife  @Steve-2040  wrap your numpy,cv2 code in tf.py_function
e.g 
`def numpy_cv2_code(input_to_function):
     ....
     return float32_out, int32_out

def map_numpy_code(input_to_function):
      out1, out2 = tf.py_function(func=numpy_cv2_code,
                                    inp=[input_to_function],
                                    Tout=[tf.float32, tf.int32])
      #assertions
      return out1,out2
dataset = dataset.batch()
dataset = dataset.map(map_func=map_numpy_code,
                          num_parallel_calls=tf.data.experimental.AUTOTUNE)

`
p.s
please dont use tf.py_function inside tf.function can cause deadlocks!!

Thanks

**Comment by Steve-2040** [comment]
@kartik4949  Thanks, I will also look into this option.
