### ISSUE TITLE
How can I save it as an ONNX model?

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#66]
hi, thx for your code...

How can I save it as an ONNX model?

**Comment by haritsahm** [comment]
The only possible way to do this is to use tf2onnx opset 10 without the final nms layer.
Use _freeze runmode_ and preprocess the output from build_model using [postprocess.pre_nms](https://github.com/google/automl/blob/b5404c2e36829ceffe0aede1b7b852f133332fcf/efficientdet/keras/postprocess.py#L112).

Using:
> tensorflow 2.4.0
> tf2onnx 1.8.1
> onnx 1.8.0

```python
  def build_model_with_head(self, inputs: tf.Tensor) -> List[tf.Tensor]:
    """Build model with inputs and labels and print out model stats."""
    logging.info('start building model')
    
    cls_outputs, box_outputs = inference.build_model(
        self.model_name,
        inputs,
        **self.model_config)
    
    # Build postprocessing.
    params = copy.deepcopy(self.model_config.as_dict())
	
    # From det_model_fn eval mode
    params.update(dict(is_training_bn=False))
    params['nms_configs']['max_nms_inputs'] = 3000 #To apply topk ops with TopK Max num in TRT = 3840
	
    cls_outputs = postprocess.to_list(cls_outputs)
    box_outputs = postprocess.to_list(box_outputs)

    # Post process withuot pre nms
    boxes, scores, classes = postprocess.pre_nms(params, cls_outputs, box_outputs)

    # Write to tfevent for tensorboard.
    train_writer = tf.summary.FileWriter(self.logdir)
    train_writer.add_graph(tf.get_default_graph())
    train_writer.flush()

    return [boxes, scores, classes] 
```

Here is the result on TRT Engine

> [01/20/2021-13:20:53] [I] Host latency
> [01/20/2021-13:20:53] [I] min: 6.29041 ms (end to end 6.38879 ms)
> [01/20/2021-13:20:53] [I] max: 6.41406 ms (end to end 11.5585 ms)
> [01/20/2021-13:20:53] [I] mean: 6.33285 ms (end to end 11.3116 ms)
> [01/20/2021-13:20:53] [I] median: 6.328 ms (end to end 11.3507 ms)
> [01/20/2021-13:20:53] [I] percentile: 6.39037 ms at 99% (end to end 11.4932 ms at 99%)
> [01/20/2021-13:20:53] [I] throughput: 172.432 qps
> [01/20/2021-13:20:53] [I] walltime: 3.00408 s
> [01/20/2021-13:20:53] [I] GPU Compute
> [01/20/2021-13:20:53] [I] min: 5.75745 ms
> [01/20/2021-13:20:53] [I] max: 5.86829 ms
> [01/20/2021-13:20:53] [I] mean: 5.79436 ms
> [01/20/2021-13:20:53] [I] median: 5.78723 ms
> [01/20/2021-13:20:53] [I] percentile: 5.84607 ms at 99%
> [01/20/2021-13:20:53] [I] total compute time: 3.00148 s

**Comment by hoangmt** [comment]
@haritsahm Look like you are able to convert tf to tensorRT. Can you share the whole code/procedure?

**Comment by haritsahm** [comment]
> @haritsahm Look like you are able to convert tf to tensorRT. Can you share the whole code/procedure?

Sorry it's been a long time since I tried it and I lost the code due to storage error. Maybe you can try the new steps from PR#962 using tf2onnx.

But the idea is this: 
1) freeze the model without the pre-processing since ONNX/TensorRT doesn't support TF Image Placeholder etc.
2) Use tf2onnx to export the freezed model and check the onnx model using Netron to see it is correctly exported and no pruned graphs
3) Try to add the nms post-processing and export the model again using tf2onnx

The problem that I had before was the NMS post processing since it has some ops that aren't supported by TensorRT so the model was badly pruned. I notice that the TensorRT version wasn't the latest (7.0)

**Comment by hoangmt** [comment]
@haritsahm Thank you so much for suggestion. I was able to convert the model without preprocessing and without postprocessing. The steps are (just in case other people also face the problem):
1. Freeze the model without pre and post processing:
```python
import sys
sys.path.append('automl/efficientdet')
from keras import inference
driver = inference.ServingDriver('efficientdet-d0','efficientdet-d0_checkpoint_folder',only_network=True, model_params={'num_classes': 90, 'moving_average_decay': 0})
driver.build()
driver.export('efficientdet-d0-saved_model_dir')
```
2. Convert to ONNX:
`python3 -m tf2onnx.convert  --saved-model efficientdet-d0-saved_model_dir --output efficientdet-d0_nwonly.onnx --opset 11 --fold_const --target tensorrt`

3. Convert to RT:
`trtexec --onnx=efficientdet-d0_nwonly.onnx --saveEngine=efficientdet-d0_nwonly.trt --fp16 --buildOnly --workspace=1000`

I need to work on adding preprocessing and postprocessing before and after running efficientdet-d0_nwonly.trt. Will update here for others to follow.

**Comment by hoangmt** [comment]
A quick update. When running trt model, the output is different from running tf model, using tensor of shape (512,512,3) contains all 0. Most of the output from trt model are 0 while output from tf model are not. I am investigating.

**Comment by haritsahm** [comment]
> A quick update. When running trt model, the output is different from running tf model, using tensor of shape (512,512,3) contains all 0. Most of the output from trt model are 0 while output from tf model are not. I am investigating. Might be a bug generated by trtexec? Did you try running trt model on some input @haritsahm ?

Yes the same thing also happened to me. Did you check the onnx graph before exporting it to TensorRT? I don't think it's a bug because trtexec will delete/prune/merge some useless nodes, graphs, ops (correct me if Im wrong) to optimize the engine.

**Comment by hoangmt** [comment]
@haritsahm, Thank you so much for replying. I have checked onnx model, the graph is connected.
I have also tried onnx model using onnxruntime. The result from tf and onnx are closed to each other but totally different from trt.

**Comment by haritsahm** [comment]
> @haritsahm, Thank you so much for replying. I have checked onnx model, the graph is connected.
> I have also tried onnx model using onnxruntime. The result from tf and onnx are closed to each other but totally different from trt.

Ah good to know! So the problem must be with TensorRT. I suggest to try debug the whole TensorRT process with [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy). I will try it later on my spare time

**Comment by hoangmt** [comment]
@haritsahm Thank you. I posted an issue in tensorRT repo on detail how to replicate as well as the models. Just for reference: https://github.com/NVIDIA/TensorRT/issues/1194

**Comment by VeeranjaneyuluToka** [comment]
@hoangmt , looks like you converted original tpu EfficientDet model in your first step (freeze model without pre and post processing) and used automl APIs. Would you have any suggestions to apply for the custom model trained using tensorflow object detection API 2?

**Comment by hoangmt** [comment]
I believe there is no difference. I will try it after fixing the above issue.

**Comment by VeeranjaneyuluToka** [comment]
Looks like inference that you used above is specific to automl. I am checking it and post here if i find a way.

**Comment by hoangmt** [comment]
@haritsahm [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy) is a great tool. It confirms that 
the results are different. Not sure how to proceed from here then. I am trying to look for the part of the network I start to see the difference, however, this will take time and don't know how to fix the issue afterward.
