### ISSUE TITLE
Source of street.jpg

### ISSUE THREAD

**Issue by JSGrondin** [google/automl#664]
Hi, 
I would like to know what is the source of the image 'street.jpg'. Is it part of an open source dataset? This kind of image would supplement very well my own dataset. Thanks
![street](https://user-images.githubusercontent.com/38842865/89784111-18b3ef00-dae6-11ea-84cc-c252565c30b9.jpg)

**Comment by kcrumb** [comment]
No, the [image](https://i.ytimg.com/vi/5H1fzBVmPIQ/maxresdefault.jpg) was taken from google image search (look [here](https://github.com/google/automl/issues/27#issuecomment-602771818)).

**Comment by mingxingtan** [comment]
Yes, it is a single image from google image search. No large dataset for it.
