### ISSUE TITLE
Skipping training since max_steps has already saved

### ISSUE THREAD

**Issue by NPetsky** [google/automl#666]
After the first training epoch the model was stuck in evaluation forever with giving the info "Skipping training since max_steps has already saved" when another training epoch should have started. I discovered this was due to setting "max_steps" in train_estimator.train in _train in main.py. When I set "steps" instead of "max_steps" (like it is done in _eval), everything works as intended.

**Comment by NPetsky** [comment]
"max_steps" has been introduced in the latest commit to main.py, was this behavior expected?

**Comment by NikZak** [comment]
I have the same issue. It happens to me only if I launch "train_and_eval" mode and only when I resume training. A quick-and-dirty workaround is to launch "train" mode and eval "mode" as two separate processes

**Comment by NikZak** [comment]
I have the same issue. It happens to me only if I launch "train_and_eval" mode and only when I resume training. A quick-and-dirty workaround is to launch "train" mode and eval "mode" as two separate processes

**Comment by NikZak** [comment]
The bug should be easy to correct. In [main.py](https://github.com/google/automl/blob/master/efficientdet/main.py):
```
-    train_estimator.train(
-        input_fn=dataloader.InputReader(
-            FLAGS.training_file_pattern,
-            is_training=True,
-            use_fake_data=FLAGS.use_fake_data,
-            max_instances_per_image=max_instances_per_image),
-        max_steps=steps)
+    if FLAGS.mode == 'train': 
+        train_estimator.train(
+            input_fn=dataloader.InputReader(
+                FLAGS.training_file_pattern,
+                is_training=True,
+                use_fake_data=FLAGS.use_fake_data,
+                max_instances_per_image=max_instances_per_image),
+            max_steps=steps)
+    if FLAGS.mode == 'train_and_eval': 
+        train_estimator.train(
+            input_fn=dataloader.InputReader(
+                FLAGS.training_file_pattern,
+                is_training=True,
+                use_fake_data=FLAGS.use_fake_data,
+                max_instances_per_image=max_instances_per_image),
+            steps=steps)
```

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Same here, @NikZak' workaround is good but I think @mingxingtan want to reuse the function. In my case I just increase the max_step at [here](https://github.com/google/automl/blob/master/efficientdet/main.py) like this:

```diff
-      _train(FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
+     _train((cycle + 1) * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
```

**Comment by mingxingtan** [comment]
Thank you @88d52bdba0366127fffca9dfa93895 and @NikZak for the solutions!

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
@mingxingtan your `max_steps` intend to train only one time, right? 
IMO, it's worth mentioning in README that the `num_epochs` is the maximum num epochs and if someone want to continue to train model, he/she should increase the max `num_epochs` and re-run training command.

**Comment by mingxingtan** [comment]
Good point! Yes, we should add that. Do you want to give it a try and prepare a PR?

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Ok, let me give it a try,
