### ISSUE TITLE
input layers for BiFPN

### ISSUE THREAD

**Issue by waldemarmeier** [google/automl#667]
Hi,

in issue #311 is explained that the backbones "only have up to feature u5". Recently, in tensorflow 2.3 pretrained EfficientNetx implementations have been added with pretrained weights. They include blocks 1-7.

Additionally, I have noticed, that EfficientNet blocks [1, 2, 3, 5, 7] are used [tf object_detection](https://github.com/tensorflow/models/blob/f68a262d75ae702a2707b3b3feda4f60b3308038/research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py)  and this project [xuannianz/EfficientDet](https://github.com/xuannianz/EfficientDet/blob/030fb7e10ab69a297c7723120c2d1be856a852c0/efficientnet.py#L445)

So my questions are:
- are blocks are 4 & 6 not used, because there is no resizing of the feature maps?
- when you use the pretrained EfficientNet models from tensorflow, is it appropriate to use the output of blocks 5&7 instead of downsampling block 3?

Thank you!

**Comment by mingxingtan** [comment]
Hi @waldemarmeier,  EfficientNet has 7 blocks, some some blocks don't change the resolutions, and they only have 5 levels of features. For example, if the input is 224x224, then the output feature size would be 7x7

However, for detection, we need feature level 3-7, so starting the the feature level 5 (or block7) of the backbone, we apply two additional downsampling to get the extra features.
