### ISSUE TITLE
inference videos: CAP_IMAGES: can't find starting n umber

### ISSUE THREAD

**Issue by juanmanuelrq** [google/automl#668]
when I run https://github.com/google/automl/tree/master/efficientdet#5-inference-for-images

I have this error:

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fda7443340] moov atom not found
[ERROR:0] VIDEOIO(cvCreateFileCapture_Images(filename.c_str())): raised OpenCV exception:
OpenCV(3.4.9) ../modules/videoio/src/cap_images.cpp:246: error: (-5:Bad argument) CAP_IMAGES: can't find starting n
umber (in the name of file): input.mov in function 'icvExtractPattern'
Error opening input video: input.mov

**Comment by mingxingtan** [comment]
I reran the command in colab and did not see this issue.
Maybe it is an issue of your OpenCV version? (like [this](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/OpenCV-4-1-2-openvino-CAP-IMAGES-can-t-find-starting-number-in/td-p/1129111)?)
