### ISSUE TITLE
typo of image_info_file in file create_coco_tfrecord.py

### ISSUE THREAD

**Issue by 88d52bdba0366127fffca9dfa93895** [google/automl#670]
Hi @mingxingtan, I see in file create_coco_tfrecord.py line [344](https://github.com/google/automl/blob/cbe4f2beeb8d9ac55d2164ccfb92b392396dea3d/efficientdet/dataset/create_coco_tfrecord.py#L344), your flag `FLAGS.image_info_file` is passed to function `_load_images_info(images_info_file)`, is it a typo or as intended. I run the code directly in my terminal instead of command line, so it makes an error `NameError: name 'images_info_file' is not defined`. If you want, I can make a PR for this case and a little bit formatting enhancement in this file, please let me know your thought.

**Comment by mingxingtan** [comment]
It was a typo. Fixed now.
