### ISSUE TITLE
test-dev2017 mAP consistently outperforms val2017 mAP

### ISSUE THREAD

**Issue by glenn-jocher** [google/automl#671]
@mingxingtan from https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints I see that test-dev mAP consistently outperforms val mAP across all models, often by a significant amount, up to +0.7.

This seems to be a very desireable result because it indicates that your trained models are generalizing better on the unseen test-dev set (20k images with labels on the server) than on the val set (5k images with local labels). 

I'm very confused about why this is happening though, or what's driving this trend. Do you have any ideas about why or how this is happening? Thanks!

**Comment by mingxingtan** [comment]
Good question.  It might be caused by the difference of data distribution in COCO testdev and val, but I don't know what's the exact reason. I agree these results are quite interesting.
