### ISSUE TITLE
 Export pretrained model to tflite no working

### ISSUE THREAD

**Issue by tT0NG** [google/automl#673]
TF: 2.3.0-dev20200617
python: 3.6

when I try:

`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite `

saw following error:

`.../envs/t2p36/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
`

and 

`.../envs/t2p36/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py:299:0: note: see current operation: %1650 = "tf.TensorListReserve"(%720, %721) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>`

Could not find associated info online. Any help or pointer would be helpful! Thanks!

**Comment by mingxingtan** [comment]
It has been fixed in https://github.com/google/automl/commit/4d670078d1f211953895a3b9b57068e9bbcab660
It is because tflite doesn't support tf.map_fn and dynamic batch size, so we add the support for both.  Your command should work well with the latest code.
