### ISSUE TITLE
In "train_and_eval" mode resuming training starts with eval cycles instead of train cycles until reaching current epoch 

### ISSUE THREAD

**Issue by NikZak** [google/automl#680]
In "train_and_eval" mode, if I stop training after a few epochs and then resume from checkpoint, training would not start right away. It starts with evaluation cycles until reaching current epoch and only then starts training again. Expected behavior is to start training from the epoch where it left off.
This happens because in [main.py](https://github.com/google/automl/blob/master/efficientdet/main.py) the cycle through epochs always starts with 1. The for-loop is currently defined as follows:

```python
    for e in range(1, config.num_epochs + 1, epochs_per_cycle):
```
I suggest calculating current epoch first. E.g. like this:
```python
      ckpt = tf.train.latest_checkpoint(FLAGS.model_dir)                      
         try:                                                                    
             current_step = int(os.path.basename(ckpt).split("-")[1])            
             current_epoch = 1 + current_step // math.ceil(                      
                 FLAGS.num_examples_per_epoch / FLAGS.train_batch_size           
             )                                                                   
         except IndexError:                                                      
             logging.info("%s has no global step info: stop!", ckpt)             
             sys.exit("%s has no global step info: stop!" % ckpt)                                     
```
and then changing the for-loop definition to start from current epoch:
```python                                                                                 
         for e in range(current_epoch, config.num_epochs + 1, epochs_per_cycle): 
```

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Good point! I noticed this behavior.

**Comment by mingxingtan** [comment]
Good catch. Thanks for the suggestion. Fixed now.
