### ISSUE TITLE
"*/Momentum" not found in Checkpoint while training on custom data.

### ISSUE THREAD

**Issue by kartik4949** [google/automl#683]
2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
         [[node save/RestoreV2 (defined at /home/cgiuser/.conda/envs/effdet/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py:1493) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
         [[node save/RestoreV2 (defined at /home/cgiuser/.conda/envs/effdet/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py:1493) ]]
         [[save/RestoreV2/_4511]]
0 successful operations.
0 derived errors ignored.

command -:
python main.py --mode=train_and_eval --training_file_pattern=dataset/train_label.record --validation_file_pattern=dataset/test_label.record --model_name=efficientdet-d7x --model_dir=efficientdet-d7x/  --ckpt=efficientdet-d7x --train_batch_size=4 --num_epochs=300 --num_examples_per_epoch=6323 --hparams="num_classes=2" --use_tpu=false

Can you guys Add CKPTS with Momentum or can you guys add skipping these Variable support?

**Comment by kartik4949** [comment]
@mingxingtan Tried debugging "var_map" dictionary and found Momentum was absent.

**Comment by kartik4949** [comment]
@mingxingtan I Have solved the issue by explicitly making a tf.saver object with only variable that were in checkpoints  and initializing the variables which were not in the checkpoint
further i pass this saver object to the scaffold function 

Im filling a PR to basically load eval checkpoints(in this case your checkpoints without BN momentum) to train on custom data.

**Comment by NikZak** [comment]
I have same issue. I have trained with adam and then experienced issues with NaN after 150k iterations and now I try to switch to SGD but have no momentum saved in ckpt. Could you please post your code here? Or point to your PR (I can't find it)?

**Comment by kartik4949** [comment]
@NikZak Hi,
can you share your command for training?

**Comment by NikZak** [comment]
@kartik4949, no problem. Here is my command for training 
```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so python main.py --mode=train_and_eval \
    --training_file_pattern=....tfrecord \
    --validation_file_pattern=....tfrecord \
    --model_name=efficientdet-d6 \
    --model_dir=logs/ckpt/..._d6  \
    --ckpt=logs/ckpt/..._d6 \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples=1024 \
    --num_examples_per_epoch=6100 --num_epochs=300  \
    --hparams=..._d6.yaml > logs/run/train_logs/log_train_d6_b4_$(date +'%Y%m%d%H%M') 2>&1
```
and the params yaml  file:
```
num_classes: 2
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_id_mapping: {0: background, 1: table}
input_rand_hflip: False
max_instances_per_image: 100
aspect_ratios: [[1.0, 1.0], [0.521, 1.921], [1.921, 0.521], [0.25, 4.0], [4.0, 0.25]]
mixed_precision: True
optimizer: 'adam'
learning_rate: 0.004
lr_warmup_init: 0.0004
clip_gradients_norm: 5.0
jitter_min: 0.8
jitter_max: 1.2
```

Hope it helps

I assume that when you said "explicitly making a tf.saver object with only variable that were in checkpoints and initializing the variables" you made an code injection in [here](https://github.com/google/automl/blob/c35c3ec6ccd4e7778af413256060b49993770288/efficientdet/det_model_fn.py):
```python
    def scaffold_fn():
      """Loads pretrained model through scaffold function."""
      logging.info('restore variables from %s', checkpoint)

      var_map = utils.get_ckpt_var_map(
          ckpt_path=checkpoint,
          ckpt_scope=ckpt_scope,
          var_scope=var_scope,
          skip_mismatch=params['skip_mismatch'])

      tf.train.init_from_checkpoint(checkpoint, var_map)

      return tf.train.Scaffold()
```
I just wanted to see what kind of injection you made and try the same. I'm not sure how to initialize variables after creating a tf.train.Saver object

**Comment by kartik4949** [comment]
@NikZak Hi,
your --model_dir and --ckpt dir are same
Please change --model_dir name i.e for example logs/ckpt/..._d6_adam_model
and training will work fine!
Thanks

**Comment by NikZak** [comment]
Thanks, @kartik4949 . This is helpful
