### ISSUE TITLE
Is it feasible to train efficientdet-d5 in tesla v100 32 gb single GPU with batch-size 1 or 2 ,whole model.

### ISSUE THREAD

**Issue by kartik4949** [google/automl#685]
Is it feasible to train efficientdet-d5 in tesla v100 32 gb single GPU with batch-size 1 or 2 ,whole model.
num_epochs = 100
my dataset is 6323 images allocated on single tfrecord file
and eval-data - 627 images tfrecord

Im asking will the training complete in feasible time say 3-4 days ?
i will be using the checkpoints given in the readme

**Comment by NikZak** [comment]
Presumably, yes. I have a similar size dataset and an RTX 2080Ti 11Gb card. I used half precision. I trained d6 with batch size of 4 over weekends and got past 100 epochs. However, AP was still improving when I stopped.

**Comment by kartik4949** [comment]
@NikZak Sure Thanks!
