### ISSUE TITLE
Memory leak in train_and_eval mode

### ISSUE THREAD

**Issue by NikZak** [google/automl#688]
I've been observing that memory (RAM) usage is creeping up in train_and_eval mode. I had to stop training and launch it again every ~12 hours to prevent the process being killed by the system due to memory overuse. I have found based on this [thread](https://github.com/tensorflow/tensorflow/issues/32052) that this is a general problem with Estimator.train inside a loop through epochs. There are suggestions that google TCMalloc library helps. TCMalloc seems to have alleviated the problem a little bit but did not solve it for me. After 12 hours running before TCMalloc I had ~70% eaten, after TCMalloc ~50% eaten.

Below is an analysis comparing the memory heap in the middle of execution and in the end of execution and showing only the difference (run by command: google-pprof --text --base=/tmp/profile.0500.heap main.py /tmp/profile.0676.heap | head -n 15)

Total: 860.1 MB
   193.4  22.5%  22.5%    216.2  25.1% google::protobuf::DynamicMessage::New
   170.0  19.8%  42.3%    170.0  19.8% std::vector::emplace_back
   102.5  11.9%  54.2%    102.5  11.9% std::string::_Rep::_S_create
    81.7   9.5%  63.7%     81.7   9.5% 00000000005b7fa4
    64.7   7.5%  71.2%    121.5  14.1% tensorflow::ShapeRefiner::AddNode
    46.7   5.4%  76.6%     51.6   6.0% tensorflow::shape_inference::InferenceContext::InferenceContext
    33.4   3.9%  80.5%     33.4   3.9% google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend@d4de0
    29.7   3.5%  84.0%     29.7   3.5% google::protobuf::internal::InternalMetadata::mutable_unknown_fields_slow
    21.4   2.5%  86.4%     20.5   2.4% google::protobuf::Arena::CreateMaybeMessage
    9.5   1.1%  94.1%     25.9   3.0% tensorflow::NodeDef::NodeDef
    20.7   2.4%  88.9%     41.5   4.8% tensorflow::Graph::AddNode
    14.3   1.7%  90.5%     14.3   1.7% google::protobuf::Map::InnerMap::CreateEmptyTable
    11.1   1.3%  91.8%     12.5   1.5% google::protobuf::Map::operator[]
    10.1   1.2%  93.0%     22.8   2.6% google::protobuf::internal::DynamicMapField::DynamicMapField
    9.5   1.1%  94.1%     25.9   3.0% tensorflow::NodeDef::NodeDef

**Comment by kartik4949** [comment]
@mingxingtan seems like interesting finding. 
@NikZak  Nice!

**Comment by mingxingtan** [comment]
yeah, this is a bug in estimator, you can launch separate "train" and "eval" job  (or maybe use tf2 training)

**Comment by s0r2637** [comment]
Hi,

I am facing the same problem in TF 2.0, using tf keras model.fit.  Even after using the tcmalloc for memory allocation, my RAM usage is going up linearly.  Any clue why is that happening?  The memory increase is rather slow in the first 8-9 epochs, but it increases dramatically in the 10-th epoch.  There is a bit of improvement in performance and memory usage with the tcmalloc library, but it doesn't solve the problem.

**Comment by NikZak** [comment]
I think that memory is being accumulated during data loading and augmentation. Maybe because data is different every epoch due to jitter and random flips. There could be a way to clear memory through end-of-session hook.
In the meantime, here is a workaround that is working for me so far. Eventually, I just launched every epoch in a different process in [main.py](https://github.com/google/automl/blob/master/efficientdet/main.py#L341)
Instead of just running 
```python
    for e in range(current_epoch + 1, config.num_epochs + 1, epochs_per_cycle):
      print('-----------------------------------------------------\n'
            '=====> Starting training, epoch: %d.' % e)
      _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
      print('-----------------------------------------------------\n'
            '=====> Starting evaluation, epoch: %d.' % e)
      eval_results = _eval(eval_steps)
      ckpt = tf.train.latest_checkpoint(FLAGS.model_dir)
      utils.archive_ckpt(eval_results, eval_results['AP'], ckpt)
```
I put the content of the loop into a function **run_train_and_eval** and then run this function in a separate process inside the loop:

```python
        def run_train_and_eval(e):
            print(
                "-----------------------------------------------------\n"
                "=====> Starting training, epoch: %d." % e
            )
            _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
            print(
                "-----------------------------------------------------\n"
                "=====> Starting evaluation, epoch: %d." % e
            )
            eval_results = _eval(eval_steps)
            ckpt = tf.train.latest_checkpoint(FLAGS.model_dir)
            utils.archive_ckpt(eval_results, eval_results["AP"], ckpt)

        for e in range(
            current_epoch + 1, config.num_epochs + 1, epochs_per_cycle
        ):
            p = multiprocessing.Process(target=lambda: run_train_and_eval(e))
            p.start()
            p.join()
```
the memory is being released between epochs:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
 174514 nikolay   20   0   22.5g   5.9g 991816 S 330.4  12.4 118:02.85 main.py
 174472 nikolay   20   0 2258188 334924 167604 S   0.0   0.7   0:03.35 main.py
 183717 nikolay   20   0   21.6g   5.1g 990928 S 106.2  10.9   2:47.63 main.py
 174472 nikolay   20   0 2258188 334924 167604 S   0.0   0.7   0:03.35 main.py
```

Drawback: you need to kill 2 processes instead of one if you want to interrupt training

Maybe this can be added as an option. Something like this:

```python
        def run_train_and_eval(e):
            print(
                "-----------------------------------------------------\n"
                "=====> Starting training, epoch: %d." % e
            )
            _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
            print(
                "-----------------------------------------------------\n"
                "=====> Starting evaluation, epoch: %d." % e
            )
            eval_results = _eval(eval_steps)
            ckpt = tf.train.latest_checkpoint(FLAGS.model_dir)
            utils.archive_ckpt(eval_results, eval_results["AP"], ckpt)

        for e in range(
            current_epoch + 1, config.num_epochs + 1, epochs_per_cycle
        ):
            if FLAGS.each_epoch_in_separate_process:
                p = multiprocessing.Process(target=lambda: run_train_and_eval(e))
                p.start()
                p.join()
            else:
                run_train_and_eval(e)
```

**Comment by NikZak** [comment]
I've added a pull request to make it easier

**Comment by YXZhai97** [comment]
I try to replace default glibc memory allocator with tcmalloc and the memory leak problem is gone!!
First install google-perftools in you environment and then run your training script with LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 python train.py xxxx
Here are the memory monitor plots that show the improvement!!
![mem_leak](https://github.com/google/automl/assets/86350797/d5b84b73-083a-4b3f-ac7f-54d28188bb8c)
![tc_malloc](https://github.com/google/automl/assets/86350797/b167f6bf-b698-4504-bb40-242ee98ca517)
