### ISSUE TITLE
Conversion to TFLite failure

### ISSUE THREAD

**Issue by aocz1** [google/automl#689]
I've recently updated my copy of the efficientdet repository a few days ago and I am now unable to generate a .tflite model using model_inspect.py. I've updated all of the dependencies in requirements.txt.

I used the following commands:

**YAML Config**
num_classes: 6
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map: {1: Healthy, 2: Fe deficient, 3: K deficient, 4: Mg deficient, 5: N deficient}
image_size: 300

**Training**
horovodrun -np 2 -H localhost:2 python3 main.py --mode=train \
    --training_file_pattern=/home/user/Desktop/Projects/efficientdet/models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_train.record \
    --validation_file_pattern=/home/user/Desktop/Projects/efficientdet/models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_val.record \
    --model_name=efficientdet-d0 \
    --model_dir=/home/user/Desktop/Projects/efficientdet/models/vine-nutrition/checkpoints-main-d0_b4_im300  \
    --ckpt=/home/user/Desktop/Projects/efficientdet/models/efficientdet-d0 \
    --train_batch_size=4 \
    --eval_batch_size=1 --eval_samples=50 \
    --num_examples_per_epoch=500 --num_epochs=15  \
    --hparams=models/vine-nutrition/config.yaml \
    --strategy=horovod

**Export TfLite Model**
python3 model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
      --ckpt_path=/home/user/Desktop/Projects/efficientdet/models/vine-nutrition/checkpoints-main-d0_b4_im300 --saved_model_dir=saved_model_dir/vine-nutrition_efficientnet-d0_b4_im300 \
      --tflite_path=tflite_models/vine-nutrition_efficientnet-d0_b4_im300.tflite \
      --tensorrt=FP32 \
      --hparams=models/vine-nutrition/config.yaml

**Export Tfite Log:**
loc(callsite("map/TensorArrayV2_3"("/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py":299:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py":324:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py":198:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py":1921:0 at callsite("/home/user/Desktop/Projects/efficientdet/inference.py":602:0 at callsite("model_inspect.py":151:0 at callsite("model_inspect.py":462:0 at callsite("model_inspect.py":513:0 at callsite("/home/user/.local/lib/python3.6/site-packages/absl/app.py":250:0 at "/home/user/.local/lib/python3.6/site-packages/absl/app.py":299:0)))))))))): error: requires element_shape to be 1D tensor during TF Lite transformation pass
loc(callsite("map/TensorArrayV2_3"("/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py":299:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py":324:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py":198:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py":1921:0 at callsite("/home/user/Desktop/Projects/efficientdet/inference.py":602:0 at callsite("model_inspect.py":151:0 at callsite("model_inspect.py":462:0 at callsite("model_inspect.py":513:0 at callsite("/home/user/.local/lib/python3.6/site-packages/absl/app.py":250:0 at "/home/user/.local/lib/python3.6/site-packages/absl/app.py":299:0)))))))))): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: requires element_shape to be 1D tensor during TF Lite transformation pass
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:324:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:1921:0: note: called from
/home/user/Desktop/Projects/efficientdet/inference.py:602:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:250:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:299:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: note: see current operation: %1650 = "tf.TensorListReserve"(%720, %721) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:324:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:1921:0: note: called from
/home/user/Desktop/Projects/efficientdet/inference.py:602:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:250:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:299:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: note: see current operation: %1650 = "tf.TensorListReserve"(%720, %721) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 151, in export_saved_model
    driver.export(self.saved_model_dir, self.tflite_path, self.tensorrt)
  File "/home/user/Desktop/Projects/efficientdet/inference.py", line 604, in export
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1970, in convert
    return super(TFLiteConverter, self).convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1330, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 574, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: requires element_shape to be 1D tensor during TF Lite transformation pass
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:324:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:1921:0: note: called from
/home/user/Desktop/Projects/efficientdet/inference.py:602:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:250:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:299:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: note: see current operation: %1650 = "tf.TensorListReserve"(%720, %721) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:324:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:1921:0: note: called from
/home/user/Desktop/Projects/efficientdet/inference.py:602:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:250:0: note: called from
/home/user/.local/lib/python3.6/site-packages/absl/app.py:299:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py:299:0: note: see current operation: %1650 = "tf.TensorListReserve"(%720, %721) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>

Also for some context, my goal is to have a model that overrides the COCO checkpoint label_map and uses the new labels in the YAML config file

**Comment by BernardinD** [comment]
@aocz1 How did you get passed this?
