### ISSUE TITLE
About "drop_connect_rate" & "survival_prob" in EfficientDet

### ISSUE THREAD

**Issue by zimoqingfeng** [google/automl#690]
https://github.com/google/automl/blob/master/efficientdet/backbone/backbone_factory.py#L53

Hi,

In my view, the EfficientDet use the EfficientNet as the backbone for Objection-Detection. I want to **confirm** that：When training EfficientDet, the survival_prob is always 0? In other words, do we do not randomly connected in EfficientNet when training EfficientDet? 
 
Another question: the "dropout_rate" in Efficient is useless when training EfficientNet, is it?

Sincerely hope to get your reply
binghong

**Comment by mingxingtan** [comment]
Hi Binghong,  we keep the same survival_prob=0.8 for backbone (only b0 has survival_prob=0 for faster convergence).

Do you find any issue to use survival_prob in backbone?

**Comment by zimoqingfeng** [comment]
Hi Mingxing,

Thanks for your replay!
I'm re-implementing EfficientDet by PaddlePaddle & Pytorch, so I found some difference between your project and others, which may have influence on model performance.
