### ISSUE TITLE
How to train with a custom dataset

### ISSUE THREAD

**Issue by aocz1** [google/automl#691]
I've recently updated efficientdet to the latest version, and I've been unable to train accurate models using custom datasets. I was able to successfully train models with excellent accuracy in the past using the hyper parameter 

var_exclude_expr = r'./class-predict/.'

I've noticed now this has been removed from the list of possible hyper parameters. 

What is the recommended approach to training a model using a COCO checkpoint that overrides the labels of the COCO checkpoint in favour of the new dataset? I've tried following the 'finetune on PASCAL' approach with the config file, but the resulting models didn't have an improved accuracy.

**Comment by kartik4949** [comment]
@aocz1 when training on custom  data
generally you will need
add --hparams="num_classes='num of classes in your dataset' + 1"
i.e lets say you have one class - num_classes=2

--hparams="moving_decay_average=0"
if training steps are very small

also you can try reducing learning rate and warm_up learning rate and train if model not converging or nans.

Batch_size should be >=8 generally i noticed this atleast for my dataset.

**Comment by kartik4949** [comment]
@aocz1 can you give me commit id when you you got good results as you said and also command you used for training and eval.

**Comment by aocz1** [comment]
Thanks for the suggestions! I'll do some testing with the suggested hparams and see how it goes.

The train/eval command was:
horovodrun -np 2 -H localhost:2 python3 main.py --mode=train_and_eval \
    --training_file_pattern=models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_train.record \
    --validation_file_pattern=models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_val.record \
    --model_name=efficientdet-d0 \
    --model_dir=models/vine-nutrition/checkpoints-main-d0_b4_im300  \
    --ckpt=models/efficientdet-d0 \
    --train_batch_size=4 \
    --eval_batch_size=1 --eval_samples=50 \
    --num_examples_per_epoch=500 --num_epochs=15  \
    --hparams=models/vine-nutrition/config.yaml \
    --strategy=horovod

(using a low num_epochs for testing the configuration purposes)

And **confg.yaml**:
num_classes: 6
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map: {1: Healthy, 2: Fe deficient, 3: K deficient, 4: Mg deficient, 5: N deficient}
image_size: 300


I believe the working version I had would have been early June, definitely before commit abca604f4982853466a897a41dafc74ad0b2baec, which is the commit that var_exclude_expr = r'./class-predict/.' was removed for skip_mismatch. Is there some way to use 'skip_mismatch' to achieve a similar overriding of the labels?

**Comment by kartik4949** [comment]
@aocz1 Skip_mismatch is basically handling r'./class-predict/.' ,hence they removed r'class-predict'.
but we need to specify correct num_classes.

**Comment by aocz1** [comment]
So if I'm to understand correctly, I don't need to use var_freeze_expr or specify a label_map for this? I can just use the number of classes + 1?

**Comment by kartik4949** [comment]
1.var_freeze_expr is for freezing layers i.e making them non trainables -> this is different thing and num_classes or label_map

2.label_map i think u need to specify correct label_map just for correct verbosity in predictions 

3. you definately will need to specify num_classes +1

**Comment by aocz1** [comment]
I will try this with a larger num_epochs and see if the accuracy improves, I'll update here tomorrow.

**Comment by WangBoying** [comment]
I'm looking forward to the results of your experiment. I used the same command, but I couldn't train very well. The final AP was  @aocz1

**Comment by WangBoying** [comment]
![image](https://user-images.githubusercontent.com/15812564/90585592-cec6b980-e207-11ea-903b-a831ee01366b.png)

**Comment by WangBoying** [comment]
python main.py --mode=train_and_eval  --training_file_pattern=tfrecord/train*.tfrecord  --validation_file_pattern=tfrecord/val*.tfrecord     --model_name=efficientdet-d0  --model_dir=model_dir/efficientdet-d0 --ckpt=efficientdet-d0  --train_batch_size=64 --eval_batch_size=64 --eval_samples=5005  --num_examples_per_epoch=29457 --num_epochs=200  --hparams=config.yaml 
**config.yaml:**
num_classes: 12+1
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map:{}
I use the default experimental parameters.

**Comment by WangBoying** [comment]
@mingxingtan

**Comment by aocz1** [comment]
After leaving it to train overnight, the accuracy did improve significantly. with over 50% accuracy with several classes, and better than random overall.

**Some notes about the experiment:**
- **config.yaml:** 
num_classes: 6
image_size: 300

- **train/eval command:**
horovodrun -np 2 -H localhost:2 python3 main.py --mode=train_and_eval \
    --training_file_pattern=models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_train.record \
    --validation_file_pattern=models/vine-nutrition/tfrecords/vine-nutrition_efficientdet_val.record \
    --model_name=efficientdet-d0 \
    --model_dir=models/vine-nutrition/checkpoints-main-d0_b4_im300  \
    --ckpt=models/efficientdet-d0 \
    --train_batch_size=4 \
    --eval_batch_size=1 --eval_samples=50 \
    --num_examples_per_epoch=500 --num_epochs=300  \
    --hparams=models/vine-nutrition/config.yaml \
    --strategy=horovod

- I left it to train for 300 epochs (which is standard for d0), though it crashed several times overnight (I suspect over memory issues), so the training is less than 50% complete. I didn't used to have these issues before, I will see if I can complete the training over the next day or two and update how the experiment goes.

**Comment by WangBoying** [comment]
@aocz1  
1.Does your training set contain 500 pictures and your test set contains 50 pictures?
2.Do you use the default settings for your parameters (such as learning rate==0.08)?

**Comment by aocz1** [comment]
> @aocz1
> 1.Does your training set contain 500 pictures and your test set contains 50 pictures?
> 2.Do you use the default settings for your parameters (such as learning rate==0.08)?

@WangBoying Yes to both 1 and 2.

**Comment by kartik4949** [comment]
@WangBoying 
1. Train for higher steps if training not converging 
2. Also you can reduce lr and warmup_lr in hparams

**Comment by WangBoying** [comment]
Thanks for your reply, I will try it! @kartik4949

**Comment by kartik4949** [comment]
@WangBoying closing issue for now.

**Comment by WangBoying** [comment]
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
INFO:tensorflow:Inference Time : 778.09162s
I0820 11:11:36.021666 140698655983424 evaluation.py:273] Inference Time : 778.09162s
INFO:tensorflow:Finished evaluation at 2020-08-20-11:11:36
I0820 11:11:36.022377 140698655983424 evaluation.py:276] Finished evaluation at 2020-08-20-11:11:36
INFO:tensorflow:Saving dict for global step 46026: AP = 0.0, AP50 = 0.0, AP75 = 0.0, APl = 0.0, APm = 0.0, APs = 0.0, ARl = 0.0, ARm = 0.0, ARmax1 = 0.0, ARmax10 = 0.0, ARmax100 = 0.0, ARs = 0.0, box_loss = 12.226901, cls_loss = 21097726.0, global_step = 46026, loss = 21098336.0

这个是训练了50个Epoch之后的结果 @kartik4949

**Comment by WangBoying** [comment]
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
INFO:tensorflow:Inference Time : 778.09162s
I0820 11:11:36.021666 140698655983424 evaluation.py:273] Inference Time : 778.09162s
INFO:tensorflow:Finished evaluation at 2020-08-20-11:11:36
I0820 11:11:36.022377 140698655983424 evaluation.py:276] Finished evaluation at 2020-08-20-11:11:36
INFO:tensorflow:Saving dict for global step 46026: AP = 0.0, AP50 = 0.0, AP75 = 0.0, APl = 0.0, APm = 0.0, APs = 0.0, ARl = 0.0, ARm = 0.0, ARmax1 = 0.0, ARmax10 = 0.0, ARmax100 = 0.0, ARs = 0.0, box_loss = 12.226901, cls_loss = 21097726.0, global_step = 46026, loss = 21098336.0
This is the result after 50 Epoch. @kartik4949

**Comment by WangBoying** [comment]
![image](https://user-images.githubusercontent.com/15812564/90718534-b4aed900-e2e4-11ea-954e-34c15482777c.png)

**Comment by aocz1** [comment]
@WangBoying I've also had very similar results to this with my training. I'm not sure if its some incorrect hyper parameter, some dependency issue or whether the expected format for the tfrecords changed. I will investigate this further.

**Comment by WangBoying** [comment]
Okay, I used the default parameters. You said above that you have got 50% accuracy with several classes after leaving it to train overnight, but my result is 0. @aocz1

**Comment by aocz1** [comment]
@WangBoying Apologies, I was testing using the tflite model. But on closer inspection, the confidence was always the same on each result returned, so its possible there was some issue with the tflite conversion process. 

My Tensorboard graphs look very similar to yours with the experiments I've done, though the class accuracy doesn't change much.

**Comment by kartik4949** [comment]
@WangBoying share your evaluation command used?

**Comment by WangBoying** [comment]
python -u main.py --mode=eval --training_file_pattern=tfrecord/train*.tfrecord --validation_file_pattern=tfrecord/val*.tfrecord --model_name=efficientdet-d0 --model_dir=efficientdet-d0-finetune --ckpt=efficientdet-d0-finetune --eval_batch_size=64 --eval_samples=5005 --hparams=config.yaml @kartik4949

**Comment by kartik4949** [comment]
@WangBoying config.yaml?

**Comment by kartik4949** [comment]
@WangBoying @aocz1 please refer this #676

**Comment by aocz1** [comment]
Just to update, I have found that I am able to get the best results training with a blank .config file.

![image](https://user-images.githubusercontent.com/11779864/91273812-21344700-e7c1-11ea-8dad-04d042d28a41.png)

**Comment by WangBoying** [comment]
config.yaml
num_classes: 13
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map: {1: ,2: , ... ,12: }
moving_average_decay: 0
@kartik4949

**Comment by WangBoying** [comment]
How did you solve it? Can you share your solution? @aocz1

**Comment by aocz1** [comment]
@WangBoying Basically I just kept my command the same (like below):

horovodrun -np 2 -H localhost:2 python3 main.py --mode=train_and_eval \
    --training_file_pattern=PATH_TO_TFRECORD \
    --validation_file_pattern=PATH_TO_TFRECORD  \
    --model_name=efficientdet-d7x \
    --model_dir=DIR  \
    --ckpt=models/efficientdet-d7x \
    --train_batch_size=4 \
    --num_examples_per_epoch=320 \
    --eval_samples=81 \
    --num_epochs=150 \
    --hparams=config.yaml \
    --strategy=horovod

Except I changed the config.yaml file so that it was blank. Also it turned out that one of the dependencies wasn't pointing to the correct version for the project even after installing them via -r requirements.txt. So after double checking them and upgrading to those requirements, it seems to work well, though I'm still in the process of figuring out the optimal num_epochs/batch size etc.

Have also been having some issues with memory leaks while training seemingly, though it seems like this will be solved in https://github.com/google/automl/issues/688

**Comment by WangBoying** [comment]
How do you set the value of num_classes? You mentioned num above_ classes = 6, but here you use an blank yaml file. @aocz1

**Comment by aocz1** [comment]
@WangBoying I didn't end up setting the number of classes. I monitor the loss via tensorboard and then use model_inspect.py to test/export the trained model.

**Comment by Pari-singh** [comment]
So @aocz1 you left your class same as coco. I guess that's fine as long as your classes are the subset of it?

**Comment by Pari-singh** [comment]
I am having trouble getting good results on BDD dataset even when finetuning from coco. I changed the config file with classes and since I am training with batch size 16, I lowered the learning rate and warmup. But I suspect its due to the tfrecord file generated. Could we have an option to directly load the dataset?

**Comment by aocz1** [comment]
@Pari-singh Yes, I left the class_ids same as coco, but used my own dataset. My dataset doesn't have any of the same classes as coco, but it still got SOTA results,

**Comment by lsunku** [comment]
> I've recently updated efficientdet to the latest version, and I've been unable to train accurate models using custom datasets. I was able to successfully train models with excellent accuracy in the past using the hyper parameter
> 
> var_exclude_expr = r'./class-predict/.'
> 
> I've noticed now this has been removed from the list of possible hyper parameters.
> 
> What is the recommended approach to training a model using a COCO checkpoint that overrides the labels of the COCO checkpoint in favour of the new dataset? I've tried following the 'finetune on PASCAL' approach with the config file, but the resulting models didn't have an improved accuracy.

Did you use custom dataset with different classes? If yes, could you please kindly guide?

**Comment by aocz1** [comment]
@lsunku Yes I did use a custom dataset with different classes to COCO. 

What ended up working for me was to prepare my own custom dataset with tfrecords (with my own labels). Then once the data is prepared, it's possible to train using a COCO checkpoint and a config file without any labels specified. The resulting model will have overridden the COCO labels with whatever class labels were used with your tfrecords.

**Comment by lsunku** [comment]
> @lsunku Yes I did use a custom dataset with different classes to COCO.
> 
> What ended up working for me was to prepare my own custom dataset with tfrecords (with my own labels). Then once the data is prepared, it's possible to train using a COCO checkpoint and a config file (without any labels specified in the config file). The resulting model will have overridden the COCO labels with whatever class labels were used with your tfrecords.

Thanks. I have a completely different dataset with tfrecords. I have only 4 classes. let me give a try.

**Comment by Padlu** [comment]
I went through this thread to try and train my own custom dataset with 5 object classes using the baseline EfficientDet-d0. 
I tried training using the same commands as for fine-tuning in the tutorial.py, and then saved my the model to run inference on my test data. But, I still see coco dataset classes on my dataset objects. I wonder if it's actually training using my given .tfrecord files or not. 

My process of dataset formation and training so far for your reference:
1. I created my own object detection dataset of 5 classes and then converted it to .tfrecord file using "Roboflow" webapp.
2. I used tutorial.py file to start with the fine-tuning of EfficientDet-d0 on my dataset.
3. My train/eval cmd:
    !python main.py --mode=train_and_eval \
    --train_file_pattern=tfrecord/{train_record_fname} \
    --val_file_pattern=tfrecord/{valid_record_fname} \
    --model_name=efficientdet-d0 \
    --model_dir=/tmp/model_dir/efficientdet-d0-finetune \
    --ckpt=efficientdet-d0 \
    --train_batch_size=32 \
    --eval_batch_size=32 --eval_samples=56  \
    --num_examples_per_epoch=56  --num_epochs=20  \
    --hparams=tfrecord/config_1.yaml
4. My config_1.yaml file:
    num_classes: 6
    moving_average_decay: 0
    mixed_precision: true
    label_map: {1: hdpe_02, 2: other_07, 3: pet_01, 4: pp_05, 5: ps_06}
    learning_rate: 0.005
    lr_warmup_init: 0.0005
    image_size: !!python/tuple
    - 412
    - 412
5. Model Saving:

    ckpt_path = '/tmp/model_dir/efficientdet-d0-finetune'
    
    config_file = '/tmp/model_dir/efficientdet-d0-finetune/config.yaml'
    
    # first export a saved model.
    saved_model_dir = 'savedmodel'
    !rm -rf {saved_model_dir}
    !mkdir {saved_model_dir}
    
    !python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
      --ckpt_path={ckpt_path} --saved_model_dir={saved_model_dir} --hparams={config_file}

6. Run Inference on test image
    serve_image_out = 'serve_image_out'
    !mkdir {serve_image_out}
    
    !python model_inspect.py --runmode=saved_model_infer \
      --saved_model_dir={saved_model_dir} \
      --model_name=efficientdet-d0  --input_image=testdata/0010_a02b01c2d1e0f1g0h1.jpg  \
      --output_image_dir={serve_image_out} \
      --min_score_thresh={min_score_thresh}  --max_boxes_to_draw={max_boxes_to_draw}

7. The result image shows "car" as the label for my object which label actually should be "hdpe_02"
<img width="783" alt="Screen Shot 2021-07-28 at 2 22 34 AM" src="https://user-images.githubusercontent.com/30406681/127248752-d7ba02e2-aea9-4498-9aff-c1f99d2f0b9e.png">

I made the necessary changes of num_classes=actual_classes + 1, then also added my own label_map in the config.yaml file, made sure that while saving the model I'm using the new ckpt_path and final config.yaml file. I really need help to make it train on my dataset with the final correct inference classes.

I also tried using the approach of @aocz1, where I didn't use hparams and thus leaving the model to figure out my classes using my custom dataset. But, I still got similar result where labels are from coco dataset.

What is it that I'm doing wrong here? Can someone help? @kartik4949 @aocz1 @mingxingtan 
Thanks :)

**Comment by mingxingtan** [comment]
You need to copy hparams={config_file} in your final command line:

```
!python model_inspect.py --runmode=saved_model_infer
--saved_model_dir={saved_model_dir}
--model_name=efficientdet-d0 --input_image=testdata/0010_a02b01c2d1e0f1g0h1.jpg
--output_image_dir={serve_image_out}
--min_score_thresh={min_score_thresh} --max_boxes_to_draw={max_boxes_to_draw}
--hparams={config_file}
```

**Comment by ameyparanjape** [comment]
Looks like you will also need to add `--hparams` in the `model_inspect.py` run

**Comment by Padlu** [comment]
> You need to copy hparams={config_file} in your final command line:
> 
> ```
> !python model_inspect.py --runmode=saved_model_infer
> --saved_model_dir={saved_model_dir}
> --model_name=efficientdet-d0 --input_image=testdata/0010_a02b01c2d1e0f1g0h1.jpg
> --output_image_dir={serve_image_out}
> --min_score_thresh={min_score_thresh} --max_boxes_to_draw={max_boxes_to_draw}
> --hparams={config_file}
> ```

Thankyou. @mingxingtan and @ameyparanjape. That solved the problem :)

**Comment by ssbodapati** [comment]
Hi , just retrained effdet-d1 with a subset of coco data ~ 17 classes. After training when I ran the eval , the overall mAP is very low even though individual label APs are decently high.

I did pass the hparams with num_classes , label_map and freeze expressions during training and during eval as well. 

sample output : 

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.097
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.137
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.104
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.046
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.103
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.145
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.081
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.119
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.125
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.136
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.170
INFO:tensorflow:Inference Time : 376.68098s
I1013 07:42:26.074282 139630174544448 evaluation.py:273] Inference Time : 376.68098s
INFO:tensorflow:Finished evaluation at 2021-10-13-07:42:26
I1013 07:42:26.075114 139630174544448 evaluation.py:275] Finished evaluation at 2021-10-13-07:42:26
INFO:tensorflow:Saving dict for global step 31250: 
AP = 0.09724971, 
AP50 = 0.13705292, 
AP75 = 0.10434632, 
AP_/1= 0.65302527, 
AP_/2 = 0.32106984, 
AP_/3 = 0.3513957, 
AP_/4 = 0.4371422, 
AP_/5 = 0.29419678, 
AP_/6 = 0.217876, 
AP_/7 = 0.4052579, 
AP_/8 = 0.19347385, 
AP_/9 = 0.6852114, 
AP_/10 = 0.61909986, 
AP_/11 = 0.66056526, 
AP_/12 = 0.49727288, 
AP_/13 = 0.58349335, 
AP_/14 = 0.652606, 
AP_/15 = 0.63678664, 
AP_/16 = 0.3476304, 
AP_/17 = 0.22387312, 
APl = 0.14509085, 
APm = 0.10299378, 
APs = 0.046318278, 
box_loss = 0.0, cls_loss = 21.15329, global_step = 31250, loss = 21.24375

Why is the MeanAP so low? is it averaging over the entire COCO objects? TFrecords for training and eval were from the entire coco dataset.
