### ISSUE TITLE
Why  all new model writed by tf1.x???

### ISSUE THREAD

**Issue by Lannister-Xiaolin** [google/automl#7]
Is there many problem in tensorflow 2.0?

**Comment by moyans** [comment]
Maybe [EfficientDet.Pytorch](https://github.com/toandaominh1997/EfficientDet.Pytorch) is a good choice  = .=

**Comment by bilel-bj** [comment]
We are asking the same question. We get confused because Google recommends highly to move to TF2 for all new codes. Why it does not use TF2 in this recently delivered code?

**Comment by bilel-bj** [comment]
> Maybe [EfficientDet.Pytorch](https://github.com/toandaominh1997/EfficientDet.Pytorch) is a good choice = .=

Could this repository be better than the official release?

**Comment by moyans** [comment]
> > Maybe [EfficientDet.Pytorch](https://github.com/toandaominh1997/EfficientDet.Pytorch) is a good choice = .=
> 
> Could this repository be better than the official release?

I think so

**Comment by CraigWang1** [comment]
In my experience, that repo hasn't been very effective for me. 
This is an example of that repo's results: https://www.youtube.com/watch?v=VyBbQQb4goY&t=170s
And it doesn't look too good

**Comment by Root-9527** [comment]
> > Maybe [EfficientDet.Pytorch](https://github.com/toandaominh1997/EfficientDet.Pytorch) is a good choice = .=
> 
> Could this repository be better than the official release?

I have tried it, but not good; and official implement of tensorflow some differ from paper

**Comment by fsx950223** [comment]
Now, you could follow https://github.com/google/automl/blob/master/efficientdet/keras/README.md to use keras model.
