### ISSUE TITLE
Doubt on inputs_offsets in pyramid config

### ISSUE THREAD

**Issue by bluesky314** [google/automl#70]
Can someone please explain me how inputs_offsets is exactly working:

```
p = hparams_config.Config()
  p.nodes = [
      {'width_ratio': F(6), 'inputs_offsets': [3, 4]},
      {'width_ratio': F(5), 'inputs_offsets': [2, 5]},
      {'width_ratio': F(4), 'inputs_offsets': [1, 6]},
      {'width_ratio': F(3), 'inputs_offsets': [0, 7]},
      {'width_ratio': F(4), 'inputs_offsets': [1, 7, 8]},
      {'width_ratio': F(5), 'inputs_offsets': [2, 6, 9]},
      {'width_ratio': F(6), 'inputs_offsets': [3, 5, 10]},
      {'width_ratio': F(7), 'inputs_offsets': [4, 11]},
  ]
  p.weight_method = 'sum'
  return p
```

I understand it has to do with the numbering of the nodes on the pyramid, but not able to exactly see the structure. Why does the first element connect to element 3,4?  Where are 0,11,10... coming from?

**Comment by mingxingtan** [comment]
They are basically the id of each nodes starting from the P3-P7 inputs. I attached a figure here better show the id (red color numbers):

<img width="276" alt="BiFPN" src="https://user-images.githubusercontent.com/6027221/77727023-98697300-6fb6-11ea-8fdc-74fe3091ce6c.png">

Does it answer your question?
