### ISSUE TITLE
Is there something wrong here in README

### ISSUE THREAD

**Issue by VIS-VAR** [google/automl#702]
There may be something wrong in README. The FLOPs of EfficientDet-D5 should be 130B not 13.0B.

EfficientDet-D5 (ckpt, val, test-dev) | 51.5 | 70.5 | 56.1 | 33.9 | 54.7 | 64.1 | 51.2 |   | 33.7M | **13.0B**
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by kartik4949** [comment]
@mingxingtan

**Comment by mingxingtan** [comment]
Yes, it was a typo. Thanks for pointing it out.
