### ISSUE TITLE
incompatible Shapes while starting Keras train

### ISSUE THREAD

**Issue by centerseed** [google/automl#704]
My train command:
```
m='d0'
python3 train.py --mode=train \
    --training_file_pattern=train*.records \
    --validation_file_pattern=val0*.records \
    --model_name=efficientdet-${m}\
    --model_dir=./train_${m}_20200824\
    --pretrained_ckpt=efficientdet-$m  \
    --batch_size=18 \
    --num_examples_per_epoch=20000 --num_epochs=80  \
    --hparams=\config.yaml \
```

And I got error:
```Traceback (most recent call last):
  File "train.py", line 230, in <module>
    app.run(main)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 217, in main
    model.load_weights(ckpt_path)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2182, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 1294, in restore
    existing_trackable._name_based_attribute_restore(restore_coordinator)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 646, in _name_based_attribute_restore
    checkpoint.eager_restore(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 388, in eager_restore
    restored_tensors=restored_tensors, restored_shapes=None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 127, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 311, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1, 64, 72) and (1, 1, 64, 810) are incompatible
```

If I change to D1, error will like `ValueError: Shapes (1, 1, 88, 72) and (1, 1, 88, 810) are incompatible`

Can train normally for compat.v1 version(estimator) with same configuration

**Comment by kartik4949** [comment]
@centerseed  num_classes = 1 + your_classes
and try  to skip  .*/class_predict/*. layers  from pretained checkpoint.

**Comment by centerseed** [comment]
@kartik4949 
Thanks for you advise, I've check my num_class is corrected. 72 is 8(my class num)x9 and 810 is 90(coco class num)x9
How to skip ./class_predict/. layers? I tried `var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'` but it's didn't help.

**Comment by kartik4949** [comment]
skip_mismatch=True in load_weights 
in train.py line 217

**Comment by centerseed** [comment]
If load_weights, by_name is also need to set True, and still got same error above
`model.load_weights(ckpt_path, by_name=True, skip_mismatch=True)`

**Comment by kartik4949** [comment]
@fsx950223 can help here

**Comment by LaurensHagendoorn** [comment]
I am trying to use the pre-trained weights as well. skip mismatch would be great, except it requires the by_name to be true, and that doesn't work for these checkpoint files?
`NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights).`

**Comment by XinyuKang** [comment]
> I am trying to use the pre-trained weights as well. skip mismatch would be great, except it requires the by_name to be true, and that doesn't work for these checkpoint files?
> NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights).

Hi@LaurensHagendoorn, I managed to load pretrained weights in h5 format using by_name=True

**Comment by LaurensHagendoorn** [comment]
Yeah with .h5 it should work fine. Are they available somewhere or did you convert the ckpt yourself?

**Comment by XinyuKang** [comment]
> Yeah with .h5 it should work fine. Are they available somewhere or did you convert the ckpt yourself?

I found it here: https://github.com/Callidior/keras-applications/releases

**Comment by kartik4949** [comment]
This is a hacky way.
```
        # Exclude some layers
       exclude = ["class_predict"]
        if exclude:
            layers = filter(lambda l: l.name not in exclude, layers)

        if by_name:
            saving.load_weights_from_hdf5_group_by_name(f, layers)
        else:
            saving.load_weights_from_hdf5_group(f, layers)
        if hasattr(f, 'close'):
            f.close()
```

**Comment by LaurensHagendoorn** [comment]
> This is a hacky way.
> f is loaded checkpoint
> 
I don't think I understand, is f the checkpoint? or the hdf5 file?
if it is the checkpoint, what file of the checkpoint did you open?

**Comment by kartik4949** [comment]
> > This is a hacky way.
> > f is loaded checkpoint
> 
> I don't think I understand, is f the checkpoint? or the hdf5 file?
> if it is the checkpoint, what file of the checkpoint did you open?

the above code snippet is generic , the point was you can load checkpoint weights by filtering some layers

**Comment by LaurensHagendoorn** [comment]
OK. I don't think there's an easy way to exclude layers when loading a checkpoint (and with h5 files it's not really needed in this case, since you can skip mismatched layers)

Since I'd rather use the ckpt files provided here (I guess they are the "official ones") I converted them to .h5, after which they are easy to load.

```
effConfig = efficientdet.hparams_config.get_efficientdet_config(
    config.model_specific_logic.model_version
)
model.build((None, effConfig.image_size, effConfig.image_size, 3))
ckpt_path = tf.train.latest_checkpoint(config.weights)
model.load_weights(ckpt_path)
model.save_weights("<PATH WHERE THE WEIGHTS SHOULD BE STORED>.h5")
```

**Comment by mingxingtan** [comment]
Thanks for the suggestion. I added h5 file links to README.

@fsx950223  Maybe we should update keras train and eval scripts to use h5 files?

**Comment by fsx950223** [comment]
> Thanks for the suggestion. I added h5 file links to README.
> 
> @fsx950223 Maybe we should update keras train and eval scripts to use h5 files?

Tf2 checkpoints could fix the bug too. It only happens when you use tf2 load_weights loads tf1 checkpoints.

**Comment by kevinkvothe** [comment]
> Thanks for the suggestion. I added h5 file links to README.
> 
> @fsx950223 Maybe we should update keras train and eval scripts to use h5 files?



> > Thanks for the suggestion. I added h5 file links to README.
> > @fsx950223 Maybe we should update keras train and eval scripts to use h5 files?
> 
> Tf2 checkpoints(object-based) could fix the bug too. It only happens when you use tf2 load_weights loads graph-based checkpoints.
> We should use checkpoints, because it's better than hdf5.

Any update on either of this two options?
