### ISSUE TITLE
How to train on multi gpus without horovod ?

### ISSUE THREAD

**Issue by xzswater** [google/automl#709]
My env is glibc2.23,  and always have problems when installing horovod.

tensorflow.python.framework.errors_impl.NotFoundError: /root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0
.19.5-py3.6-linux-x86_64.egg/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: **undefined symbol: _ZGVcN4v___log_finite**

**Comment by xzswater** [comment]
@kartik4949  Hi, i reinstall on other machine with glibc2.17, but have problem:
**mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaLaunch**

**There's no cudaLaunch in cuda-10.1, but in cuda-10.0 and below. However, tensorflow 2.3.0 need cuda-10.1.**

![image](https://user-images.githubusercontent.com/52267702/91929379-d52d5900-ed10-11ea-806c-c548a4bc151a.png)

**Comment by sadransh** [comment]
I think this is solved by  #732
