### ISSUE TITLE
How do I identify only one class of a picture, such as  “person”?

### ISSUE THREAD

**Issue by quuhua911** [google/automl#71]

**Comment by Xiaokeai18** [comment]
Just change the code in visualize/vis_utils.py  
change a line the function "visualize_boxes_and_labels_on_image_array"  
from `if scores is None or scores[i] > min_score_thresh:`
to: `if scores is None or scores[i] > min_score_thresh and classes[i] == 1:`

**Comment by mingxingtan** [comment]
Thanks @Xiaokeai18 !
