### ISSUE TITLE
Converting to INT8 tflite 

### ISSUE THREAD

**Issue by tT0NG** [google/automl#712]
Hi I am trying to convert the pretrained model to INT8 using:

python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0/  --saved_model_dir=savedmodeldir_d0_int --tensorrt=INT8 --tflite_path=efficientdet-d0_int_8.tflite 

However, the output "efficientdet-d0_int_8.tflite" still has weights in float32. What is the best way to convert the model?

**Comment by mingxingtan** [comment]
the latest code should support int8 tflite.
