### ISSUE TITLE
Memory Leak in "mode=train", strange evaluation curve

### ISSUE THREAD

**Issue by SiBensberg** [google/automl#719]
Thank you for your great work, at the moment I am experiencing 2 problems i want to solve.

1. The recent fix for the memory leak in "train_and_eval" worked well _(Thank you for that!)_. But I still have a memory leak in "train" mode. In about 4 hours the RAMs usage got up to 60gb and gets terminated by the system. I can restart the training without problems. So it is more an minor inconvenience. Am I doing something wrong? using `tf 2.2` + `Cuda 10.1.243`

2. The eval AP50 curve in tensorboard looks strange. The AP is about 0.022 which is not good. But the inference looks very good and way better than an AP50 of 0.022. Am I doing something wrong with the eval params?
![image](https://user-images.githubusercontent.com/55738346/91832295-85359000-ec45-11ea-844a-0f7c3c79e6b6.png)
![image](https://user-images.githubusercontent.com/55738346/91832597-e8bfbd80-ec45-11ea-8558-3d9db05d9b6d.png)

I made some minor changes to the training and loaded Efficientdet-D1 Coco weights.
I am using (**voc-config.yaml**)

```
num_classes: 5
var_freeze_expr: '(efficientnet)'
label_map: {1: blue, 2: yellow, 3: orange, 4: orange_big}
use_keras_model: False
anchor_scale: 1  #smallest Objects to detect are ~8px so an anchor scale of 1 should do it
num_scales: 5
aspect_ratios: [[1.0, 1.0], [0.634, 1.577], [1.577, 0.634]]
learning_rate: 0.015
lr_warmup_init: 0.0015
max_instances_per_image: 200     # got an error at one time
```
**eval:**
```
python3 main.py --mode=eval  \
    --model_name=efficientdet-d1  --model_dir=efficientdet-d1-sgd_anchor  \
    --validation_file_pattern=/home/val*.record  \ # Just one file
    --hparams=voc_config.yaml \
    --eval_batch_size=1 --eval_samples=5000
```

**train:**
```
python3 main.py --mode=train \
    --training_file_pattern=/home/train*.record \
    --validation_file_pattern=/home/val*.record \
    --model_name=efficientdet-d1 \
    --model_dir=efficientdet-d1-sgd_anchor \
    --ckpt=efficientdet-d1 \
    --train_batch_size=22 \
    --eval_batch_size=1 --eval_samples=1000 \
    --hparams=voc_config.yaml \
    --num_examples_per_epoch=22000 --num_epochs=200 \
```

**Comment by kartik4949** [comment]
@SiBensberg have you tried with --val-json in eval?

**Comment by SiBensberg** [comment]
Sorry, I forgot to mention it is a custom dataset without a json.

**Comment by kartik4949** [comment]
@SiBensberg can you try mode= train_and_eval

**Comment by SiBensberg** [comment]
with mode=train_and_eval it looks better. But I also changed the eval batch size to train batch size. It looks better now.
