### ISSUE TITLE
some questions about GPU Devices

### ISSUE THREAD

**Issue by Guzaiwang** [google/automl#72]
dear authors:
thanks for your great work. however, I have some concerns about training from GPU devices.  On my custom GPU device ( Tesla V100 Memory - 32GB), I can only train the efficientdet-b3 with batch_size=4 on the single GPU card. 

What is your training parameters setting, such as gpu_devices and memory, batch_size?

**Comment by mingxingtan** [comment]
Hi @Guzaiwang , all models are trained with TPUv3, which has 16GB memory per core. I am able to train EfficientDet-D7 with batch size 4 per core.

GPU memory seems to be an issue, I haven't looked into this. I am closing this bug for now, and use https://github.com/google/automl/issues/85 to track GPU memory related issues.
