### ISSUE TITLE
min_level Features is it possible to change ?

### ISSUE THREAD

**Issue by fitoule** [google/automl#724]
I have small objects to detect I would like to test training by changing min leel from default 3 to 2. But It fails the training goes in a loop. I was trying fine tuning and was wondering if this change require a training from scratch only ? ( not finetuning)

**Comment by mingxingtan** [comment]
You should be able to change min_level=2, but make sure you set skip_mismatch=True (in default)
What error do you have?

**Comment by fitoule** [comment]
I added use_keras_model=False and now it works ! I am not sure if it is relied. have to re try without after my long training

**Comment by mingxingtan** [comment]
Does it mean keras model doesn't work, but the non-keras model works well?
Could you paste your command?

**Comment by fitoule** [comment]
It works now .. I don't understand what I changed. Works with and without keras ...

**Comment by fitoule** [comment]
..? I closed the issue. Removed the use_keras_model=False again .. But then it fails
So for me : 
- with use_keras_model=False works always
- without use_keras_model=False works sometimes only

command line : python3 main.py --mode=train_and_eval --training_file_pattern=/home/train/*.record --validation_file_pattern=/home/val/* --model_name=efficientdet-d2 --model_dir=model/d2C3/BS2_lr005_cst_A2_NEX2000_min2 --ckpt=ref_backbone/efficientdet-d2 --train_batch_size=2 --num_examples_per_epoch=2000 --num_epochs=120 --eval_batch_size=2 --eval_samples=416 --hparams="num_classes=4,learning_rate=0.05,lr_decay_method='constant',min_level=2";

**Comment by fitoule** [comment]
python3 main.py --mode=train_and_eval --training_file_pattern=/home/obs/BoutiqueDetection/train/*.record --validation_file_pattern=/home/obs/BoutiqueDetection/val/* --model_name=efficientdet-d2 --model_dir=model/d2C3/BS2_lr005_cst_A2_NEX2000_min2 --ckpt=ref_backbone/efficientdet-d2 --train_batch_size=2 --num_examples_per_epoch=2000 --num_epochs=120 --eval_batch_size=2 --eval_samples=416 --hparams="num_classes=4,learning_rate=0.05,lr_decay_method='constant',min_level=2";
