### ISSUE TITLE
module 'inference' has no attribute 'InferenceDriver'

### ISSUE THREAD

**Issue by wadewangpower** [google/automl#73]
Hi, efficientdet team ~
I copied the codes in the tutorial.ipynb and want to run it on pycharm locally, below is the codes on my pycharm: `
import os
import sys
import tensorflow.compat.v1 as tf
import os
import PIL
import inference
from IPython import display

os.chdir('automl/efficientdet')
sys.path.append('.')

MODEL = 'efficientdet-d0'
ckpt_path = os.path.join(os.getcwd(), MODEL)
print('Use model in {}'.format(ckpt_path))

"""### Inference a single image."""

img_path = os.path.join(os.getcwd(), 'test_images/0.png')
img_out_dir = os.path.join(os.getcwd(), 'efficientdet_output')

if not os.path.exists(img_out_dir):
  os.mkdir(img_out_dir)

image_size = max(PIL.Image.open(img_path).size)  // 128 * 128

min_score_thresh = 0.2  
max_boxes_to_draw = 100  
line_thickness = 3  

tf.reset_default_graph()
driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
driver.inference(img_path,
                 img_out_dir,
                 min_score_thresh=min_score_thresh,
                 max_boxes_to_draw=max_boxes_to_draw,
                 line_thickness=line_thickness)

display.display(display.Image(os.path.join(img_out_dir, '0.jpg')))
`
After runing the .py file, pycharm report this error:
Traceback (most recent call last):
  File "C:/MachineLearning/CV/efficientdet_eval_inference_train_demo.py", line 47, in <module>
    driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
AttributeError: module 'inference' has no attribute 'InferenceDriver'
What is the probable cause ? Is it because i didn't install pytype ? （It seems pytype is a little troublesome to install for Windows 10 user, now i 'm trying to install it） Thanks !

**Comment by CraigWang1** [comment]
Maybe try to place the import inference after you append the path because it might be importing a different module?

So it would be
```
import os
import sys
import tensorflow.compat.v1 as tf
import os
import PIL
from IPython import display

os.chdir('automl/efficientdet')
sys.path.append('.')

import inference   #moved after adding path
```

**Comment by mingxingtan** [comment]
Thanks @CraigWang1 ! Yes, please include automl/efficientdet into your path.

**Comment by wadewangpower** [comment]
Thank you ! It is really the problem of current working directory. But i can't fixed it by moving 'import inference' after adding path, instead i put the efficientdet_eval_inference_train_demo.py inside automl/efficientdet directory, and it works !

**Comment by CraigWang1** [comment]
That's great! Happy that you fixed the issue

**Comment by wadewangpower** [comment]
Hi, i inspect the time of inferrence by `model_inference_start_time = time.time()
driver.inference(img_path,
                 img_out_dir,
                 min_score_thresh=min_score_thresh,
                 max_boxes_to_draw=max_boxes_to_draw,
                 line_thickness=line_thickness)
inference_time = time.time() - model_inference_start_time
display.display(display.Image(os.path.join(img_out_dir, '0.jpg'))) 
print('efficientdet-d0_inference_time:{}'.format(inference_time))`
As a result, it print out 51.117167472839355. Is this time  normal ? isn't it a little long ?
