### ISSUE TITLE
SyntaxError: invalid syntax with model_inspect.py

### ISSUE THREAD

**Issue by vxgu86** [google/automl#730]
the error points to the ":" between model_name and Text, what is the problem?
File "model_inspect.py", line 79
    model_name: Text,
                        ^
SyntaxError: invalid syntax

**Comment by kartik4949** [comment]
@vxgu86 what is your python version?

**Comment by vxgu86** [comment]
@kartik4949 it's python3.5.2, is there a problem?

**Comment by kartik4949** [comment]
@vxgu86 use python 3.7+
