### ISSUE TITLE
 latest_checkpoint(FLAGS.ckpt) error in TUTORIAL-4.2-Train Pascal VOC 2012 from ImageNet checkpoint for Backbone

### ISSUE THREAD

**Issue by vxgu86** [google/automl#733]
in TUTORIAL 4.2 chapter
!mkdir /tmp/model_dir
# key option: use --backbone_ckpt rather than --ckpt.
# Don't use ema since we only train a few steps.
!python3 main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/{file_pattern} \
    --validation_file_pattern=tfrecord/{file_pattern} \
    --model_name={MODEL} \
    --model_dir=/tmp/model_dir/{MODEL}-scratch  \
    --backbone_ckpt={backbone_name} \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples={images_per_epoch}  \
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=1  \
    --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true"

when I tried to exec TUTORIAL-4.2-Train Pascal VOC 2012 from ImageNet checkpoint for Backbone
the ERROR pop out in HERE:
    ckpt = tf.train.latest_checkpoint(FLAGS.model_dir)    ### IT IS NONE
    if not ckpt:
      ckpt = tf.train.latest_checkpoint(FLAGS.ckpt)

right now  the directory /tmp/model_dir is empty,so no </tmp/model_dir/{MODEL}-scratch>
I found that the FLAGS.ckpt is also NONE ,that 's why the error pop out.
what's the problem?

the error tips as follow:::::::::
Traceback (most recent call last):
  File "main.py", line 383, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 348, in main
    ckpt = tf.train.latest_checkpoint(FLAGS.ckpt)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_management.py", line 351, in latest_checkpoint
    ckpt = get_checkpoint_state(checkpoint_dir, latest_filename)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_management.py", line 272, in get_checkpoint_state
    latest_filename)

**Comment by mingxingtan** [comment]
Yeah, we should check whether FLAGS.ckpt is None before loading it.
It should be fixed in https://github.com/google/automl/pull/740/files#diff-63e70a25f43a410e30f2f7bd89275295R342  (line 342 of main.py)
