### ISSUE TITLE
differences between model_name model_dir ckpt??

### ISSUE THREAD

**Issue by vxgu86** [google/automl#735]
what is the difference between the following?
   --model_name=efficientdet-d7x \
    --model_dir=/tmp/d7x/efficientdet-d7x-finetune  \
    --ckpt=efficientdet-d7x  \

could not understand

**Comment by kartik4949** [comment]
model_name is which model architecture you want to train 
model_dir is folder name where you want to save model trained weights 
ckpt  is coco pretrained checkpoint path (whole architecture)
p.s : dont keep ckpt and model_dir same when training for first time.
thanks

**Comment by vxgu86** [comment]
@kartik4949  thanks but I could not get it for now
I want to train on my dataset with 4 kinds of objects. here are my profiles
initially /tmp/d7x/efficientdet-d7x-finetune is empty
efficientdet-d7x/ contains the ckpt downloaded from 
https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco2/efficientdet-d7x.tar.gz


!mkdir /tmp/d7x/
!python3 main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d7x \
    --model_dir=/tmp/d7x/efficientdet-d7x-finetune \
    --ckpt=efficientdet-d7x  \
    --train_batch_size=32 \
    --eval_batch_size=1 --eval_samples=100 \
    --num_examples_per_epoch=6575 --num_epochs=50  \
    --hparams=voc_config.yaml

voc_config.yaml
num_classes: 5
label_map: {1: aa, 2: bb, 3: cc, 4: dd}

the training did not improved at all.
I could only see one point in the tensorboard

**Comment by vxgu86** [comment]
by the way, the jpg is about 3000*2000 pixel.
@kartik4949

**Comment by kartik4949** [comment]
refer #767
