### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Pari-singh** [google/automl#736]
Hello Authors!
I was trying to run train_and_eval on my custom dataset, using the same steps given for training PASCAL from COCO checkpoint. However I am getting the following error:
File "main.py", line 348, in main     step = int(os.path.basename(ckpt).split("-")[1]) 

I suppose it has something to do with the changes made around 8 days ago in the main.py file for train_and_eval, and what I suspect is the line 
ckpt = tf.train.latest_checkpoint(FLAGS.ckpt)
outputs 'efficientdet-d7x/model' and has no '-'. The efficientdet-d7x is the folder extracted from the zip file available on the readme.
@kcrumb @mingxingtan

**Comment by kartik4949** [comment]
@Pari-singh Hi
can you provide full error stack
Thanks

**Comment by kcrumb** [comment]
I had the same error message. If this is the same issue as mine then this should be fixed (look at #734). Update your codebase and try again. But training should still work even with this error message and only appears at the beginning.
