### ISSUE TITLE
How to load dataset without tfrecords, but with instances.xxx.json ? tfrecords cost too much disk

### ISSUE THREAD

**Issue by xzswater** [google/automl#752]
I convert my demo custum dataset (with only 5k images, 1920 * 1080) to tfrecord, but it cost 31G disk.
If i convert the normal size custum dataset, with 2M images, it should be exploding.

Why not record only the paths of images into tfrecords, instead of writing themselves into tfrecords ?

I have 5T(in size) images through mount, but don't want to convert them to tfrecords.

**Comment by kartik4949** [comment]
you can write tfrecord with GZIP which will compress it (smaller than original size)

**Comment by xzswater** [comment]
> you can write tfrecord with GZIP which will compress it (smaller than original size)

I have 5T(in size) images through mount, but don't want to convert them to tfrecords.

**Comment by fsx950223** [comment]
You could record file path or url in the tfrecord instead of binary file content.
