### ISSUE TITLE
max_instances_per_image should be "class_number+1 " or the possible existed max instances number of image

### ISSUE THREAD

**Issue by williamhyin** [google/automl#754]
Hi all,

I have a dataset which contain **200 classes** . As the author of efficientdet said , the num_classes should be "**class_number+1** " in config file.  I find the default  max_instances_per_image is 100 for coco dataset.
But i know in one image the  instance  is maximal 20.

So in this situation **, should i set max_instances_per_image 201? or 200? or 20? or remain 100?**
Is there any influence for training?

Thanks

**Comment by mingxingtan** [comment]
max_instances_per_image means the max number of boxes. For your case, it seems to be 20?  (If any image has >20 instances, it would cause an error during training).
