### ISSUE TITLE
how to fix (terminate called after throwing an instance of 'std::bad_alloc')?

### ISSUE THREAD

**Issue by tongxiaortx** [google/automl#760]
when I run this script:

// Run eval.
!python main.py --mode=eval  \
    --model_name=${MODEL}  --model_dir=${CKPT_PATH}  \
    --validation_file_pattern=tfrecord/val*  \
    --val_json_file=annotations/instances_val2017.json

it appears a bug:
I0911 15:36:06.639371 140160699741952 session_manager.py:508] Done running local_init_op.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Fatal Python error: Aborted

how to fix it?
thanks.

**Comment by Pari-singh** [comment]
This is the recent error during evaluation, meaning the process is going out of memory. I have also created an issue #770 which is the same error as yours with the only difference in the machine they are running, thus giving different error message.

**Comment by mingxingtan** [comment]
The eval batch size issue should have fixed. Closing it now.
Feel free to reopen it if you still have issues.
