### ISSUE TITLE
0 mAP with custom dataset

### ISSUE THREAD

**Issue by Samjith888** [google/automl#763]
**command used:**

python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d4 \
    --model_dir=checkpoints  \
    --ckpt=efficientdet-d4  \
    --train_batch_size=8 \
    --eval_batch_size=32 --eval_samples=800 \
    --num_examples_per_epoch=50000 --num_epochs=500  \
    --hparams=voc_config.yaml
 
**Results :**

```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.014
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.042
```

**voc_config.yaml**

```
num_classes: 2
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map: {1: Plm}
moving_average_decay: 0
autoaugment_policy: v2
learning_rate: 0.002
lr_warmup_init: 0.0002
first_lr_drop_epoch: 50.0
second_lr_drop_epoch: 150.0
use_keras_model: False
```

**Comment by Steve-2040** [comment]
Have you tried to remove moving_average_decay: 0
I had issues with inference when moving_average_decay: 0 is used https://github.com/google/automl/issues/676#issuecomment-692364529

**Comment by Samjith888** [comment]
Tried that also, but still 0.00 mAP.

**Comment by kartik4949** [comment]
@Samjith888 you can reduce num_train_steps and increase num_epochs , and let it train completely

**Comment by Steve-2040** [comment]
@Samjith888 how do the training losses look on TensorBoard?

**Comment by kartik4949** [comment]
refer #676
