### ISSUE TITLE
Conversion to TRT with INT8 quantization.

### ISSUE THREAD

**Issue by MartinBrazdil** [google/automl#77]
Hi, I am trying to create TRT engine quantized to int8 precision. It seemed to me like a good idea to run model_inspect with:

`--runmode=bm --bm_runs=1 --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --input_image=img.png --output_image_dir=img_out --tensorrt=INT8 --min_score_thresh=0.2 --input_image_size=1920 --max_boxes_to_draw=100`

and intercept it it convert_tr method and adding some code after [convert()](https://github.com/google/automl/blob/master/efficientdet/model_inspect.py#L280)

import cv2
img = cv2.imread("img.png")
img = cv2.resize(img, (1920, 1920))
img = img.astype(float)
img = img / 256
fetch_names = [t.split(':')[0] for t in fetches]
converter.calibrate(fetch_names, 1, feed_dict_fn=lambda: {'input:0': [img]})

However I do get nonsensical error:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float and shape [1,1920,1920,3]
	 [[node input (defined at host_home/smartcamera/automl/efficientdet/model_inspect.py:366) ]]`

But img is numpy array with shape [1920, 1920, 3] and dtype=float and since it is in list it is [1, 1920, 1920, 3]. Maybe I am using wrong fetches (I do not REALLY know what I am doing, I am not tensorflow expert).

`fetch_names = [t.split(':')[0] for t in fetches]`

I would appreciate any help, thank you for this wonderful repository! :-)

**Comment by CraigWang1** [comment]
Maybe try expanding img to shape [1, 1920, 1920, 3] by using 
```
import numpy as np
# assuming image is [1920,1920,3]
img = np.expand_dims(img, axis=0)   #this will change the shape to [1,1920,1920,3]
```

**Comment by MartinBrazdil** [comment]
Thanks for tip! Unfortunately I have already tried expand_dims and feeding with {'input:0': img} without list brackets with the same result - there is flatten further in pipeline so feeding [img] with shape [1920,1920,3] is equivalent to feeding img with [1,1920,1920,3].

**Comment by mingxingtan** [comment]
Hi @MartinBrazdil Please change " feed_dict_fn=lambda: {'input:0': [img]})" to feed_dict={'input:0': [img]})".

**Comment by MartinBrazdil** [comment]
Hi, I have solved this -> problem was that 'input' was among fetch_names. But next error occured "Attempting to use uninitialized value fpn_cells/cell_1/fnode3/op_after_combine8/bn/beta". I will create separate issue for this.
