### ISSUE TITLE
Error yaml in inference 

### ISSUE THREAD

**Issue by JK-Pair** [google/automl#774]
![image](https://user-images.githubusercontent.com/22557628/93196711-f7918e80-f774-11ea-98be-8f2160e25d4d.png)

**Comment by JK-Pair** [comment]
from => https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

pip install --ignore-installed PyYAML

**Comment by mingxingtan** [comment]
Thanks for the solution!
