### ISSUE TITLE
Archive ckpt disappeared from main.py

### ISSUE THREAD

**Issue by NPetsky** [google/automl#776]
In commit f73694441aca76379cb71ae675098a393eaec8f9 (simplifying estimator train_and_eval) on Sep 7 the utils.archive_ckpt function was removed from mode train_and_eval so the best checkpoints are not saved any more resulting in getting only the latest checkpoints when training has finished. 
Is there any possibility to include this function again? I do not know how to integrate that in the current code because estimator.evaluate is never called explicitly, training and evaluation is all integrated in one single estimator call.
(As a sidenote: the flag "run_epoch_in_child_process" is not used any more because of this commit, maybe it can be removed)

**Comment by mingxingtan** [comment]
Good pont. I will try to revert the change and add it back.

**Comment by k11-cmd** [comment]
@mingxingtan, have you reverted the changes?

**Comment by mingxingtan** [comment]
yes, it is fixed in https://github.com/google/automl/commit/fc9cd66253003d26265bd8f2c4b34e313783c8b6

**Comment by k11-cmd** [comment]
thank you @mingxingtan

**Comment by fitoule** [comment]
but now TensorBoard learning rate metric has disappeard @mingxingtan  :(

**Comment by NPetsky** [comment]
That has been fixed today see #801
