### ISSUE TITLE
What is the num_shards, Do I have to define it by myself or use the default?

### ISSUE THREAD

**Issue by JK-Pair** [google/automl#783]
If I have 100 images in my dataset, how much the num_shards that I have to choose?

Thank you for all replying.

**Comment by kartik4949** [comment]
10 can be a good start

**Comment by JK-Pair** [comment]
> 10 can be a good start

Thank you for your help.
You mean If I have 100k images in my dataset, the number of num_shards more than 10k?

**Comment by kartik4949** [comment]
No

**Comment by JK-Pair** [comment]
> No
> 
> 

So, what do you mean about that?

**Comment by kartik4949** [comment]
@JK-Pair Better use the default one

**Comment by JK-Pair** [comment]
> , you'll just have some useless empty shards.

Thank you for your help!
