### ISSUE TITLE
Question about FLOPS comparison between BiFPN and FPN

### ISSUE THREAD

**Issue by tjumiao** [google/automl#790]
BiFPN is using depthwise separable conv, which helps reduce the FLOPS/params.

_Originally posted by @mingxingtan in https://github.com/google/automl/issues/284#issuecomment-618216171_

> BiFPN is using depthwise separable conv, which helps reduce the FLOPS/params.

Hi, thanks for the great work!

I have similar questions with a previous issue. I'm just trying to understand what is the key factor that reduces the FLOPS significantly. Although you said the depthwise convolution reduces the FLOPS, by reading your paper in ablation study section 6.2, you also compared BiFPN with FPN with the same backbone and replaced the convs in all networks with depthwise separable convs. Why does BiFPN still have much fewer FLOPS?  
![image](https://user-images.githubusercontent.com/18041918/93804197-f5677e00-fc13-11ea-8298-ae4616fd5854.png)

Thank you.

**Comment by mingxingtan** [comment]
yes, this is because BiFPN has 8 nodes (1 for P3, 1 for P7, 2 for P4-P6) for each top-down-bottom-up path, while FPN/PANet have 10 nodes (2 for P3-P7). NAS-FPN only has 7 nodes, but its nodes are more expensive (3 for P4, 1 for others).
