### ISSUE TITLE
Exported saved_model twice as large as frozen.pb or TensorRT

### ISSUE THREAD

**Issue by Steve-2040** [google/automl#799]
When I export using:
```bash
python efficientdet/model_inspect.py --runmode=saved_model --model_name=efficientdet-d4 ^
  --ckpt_path=model/efficientdet-d4-scratch ^
  --saved_model_dir=savedmodeldir ^
  --hparams="data/config.yaml"
```
The savedmodeldir have the saved_model.pb and variables.data-00000-of-00001 files but the variables.data-00000-of-00001 file is 158 MB almost twice as large as the frozen.pb or TensorRT files.

Currently I work around that by specifying moving_average_decay: 0 in the config.yaml file when exporting. When I export with --runmode=saved_model and specify moving_average_decay: 0 the variables.data-00000-of-00001 file size reduces to 79.0 MB (and inference seems to be faster or uses less memory. I have not benchmarked this.)

Will it be better to always set moving_average_decay: 0 when using --runmode=saved_model? (or another method may be to remove ema/training variables after the graph is loaded (with --runmode=saved_model) and before export is done?)
Any advice will be appreciated. I also have mentioned this in issue https://github.com/google/automl/issues/676#issuecomment-692364529.

**Comment by fsx950223** [comment]
Try keras/inspector.py

**Comment by Steve-2040** [comment]
@fsx950223 thanks for the suggestion to use inspector.py. When I export (on Windows10) using:
```
setlocal
set PYTHONPATH=C:\Users\...\efficientdet;

python efficientdet/keras/inspector.py --mode=export --model_name=efficientdet-d4 ^
  --ckpt_path=model/efficientdet-d4-scratch ^
  --saved_model_dir=savedmodeldir ^
  --hparams="data/config.yaml"
```
the file size is smaller but still larger than using model_inspect.py:
```
keras/inspector.py (setting moving_average_decay: 0 makes no difference in file size)
saved_model.pb : 28.4 MB
variables.data-00000-of-00001 : 89.5 MB

model_inspect.py and moving_average_decay: 0
saved_model.pb : 9.74 MB
variables.data-00000-of-00001 : 79.0 MB
```
I was using the chkpoint created by efficientdet/main.py --mode=train, and then thinking I may need to train with keras/train.py?

Trying to train with keras/train.py produced this error:
```
I0924 11:32:05.301941  5876 api.py:598] Project shape: (1, 32, 40, 448)
Traceback (most recent call last):
  File "efficientdet/keras/train.py", line 234, in <module>
    app.run(main)
  File "C:\Users\...\Python\Python38\lib\site-packages\absl\app.py", line 299, in run
...
  File "C:\Users\...\Python\Python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
...
    C:\Users\...\Python\Python38\lib\site-packages\tensorflow\python\framework\ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimension size must be evenly divisible by 102400 but is 1 for '{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](FocalLoss/weighted_loss/Sum, Reshape_1/shape)' with input shapes: [], [5] and with input tensors computed as partial shapes: input[1] = [1,128,160,?,5].
```
using the following command:
```
setlocal
set PYTHONPATH=C:\Users\...\efficientdet;

python efficientdet/keras/train.py --mode=train ^
    --training_file_pattern="data/train.record" ^
    --validation_file_pattern="data/train.record" --eval_samples=0 ^
    --model_name=efficientdet-d4 ^
    --model_dir=model/efficientdet-d4-scratch ^
    --batch_size=1 ^
    --num_examples_per_epoch=9696 --num_epochs=600 ^
    --hparams="data/config.yaml"
```
```yaml
num_classes: 5
label_map: {1: c1name, 2: c2name, 3: c3name, 4: c4name}
max_instances_per_image: 20
regenerate_source_id: True
image_size: 1280x1024
jitter_min: 0.5
jitter_max: 2.0
```
I have tried to remove --hparams="data/config.yaml" but the error remains.
