### ISSUE TITLE
Runtime error TFlite

### ISSUE THREAD

**Issue by kevkid** [google/automl#802]
When running my model on a raspberry pi I get the following error when loading the model:
`self.model = tflite.Interpreter(model_path=MODEL)`

```
ValueError: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
Registration failed.
```

I build the model by using this code:
`python3 model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir --tflite_path=efficientdet-d0.tflite`

and downloaded the efficientdet tar.gz from [here](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco2/efficientdet-d0.tar.gz)

The tflite runtime I am using is: https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl
Any idea what I am doing wrong?

**Comment by hamhochoi** [comment]
I installed tensorflow 2.3.1 and solved this problem.

**Comment by jeffzhengye** [comment]
it seems this kind of problems has never been resolved.

**Comment by fsx950223** [comment]
Yes, since tf2.1 only supports  RESIZE_NEAREST_NEIGHBOR version 2, you should use tflite 2.3 or modify tf.Graph by yourself
