### ISSUE TITLE
Importing ABC directly from collections has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [google/automl#809]
Use collections in Python 2 and collections.abc in Python 3.

https://github.com/google/automl/blob/1ec78d22aa9f8b7d33b9cf3a177e05dcc6b4a093/efficientdet/hparams_config.py#L145

**Comment by mingxingtan** [comment]
Thanks for pointing this out. I have changed it to collections.abc.
