### ISSUE TITLE
Predict Problem

### ISSUE THREAD

**Issue by HK017** [google/automl#81]
my custom dataset have two classes, i convert the dataset to coco format; The training process is normal, but predict some images, I looked at the picture results,  to my surprise, only one category can be predicted，another category of object is missing in predicting images.
@mingxingtan，I hope you can give me some suggestions to solver this bug, thanks a lot

**Comment by CraigWang1** [comment]
What was your training command? What were your validation results (mAP)?

**Comment by honghande** [comment]
@HK017 I also use the custom data set to transform the coco format and conduct training and error reporting. Do you encounter this problem?
https://github.com/google/automl/issues/93

**Comment by CraigWang1** [comment]
@HK017 
How did you inference an image?
I'm having trouble on my end inferencing with 1 class.
Thanks

**Comment by HK017** [comment]
> What was your training command? What were your validation results (mAP)?

python main.py --mode='train'  \
               --training_file_pattern=tfrecord/train*  \
               --hparams="use_bfloat16=false,num_classes=2" \
               --use_tpu=False  \
               --model_dir=model/efficientdet-d0/ \
               --backbone_ckpt=ckpt/noisy_student_efficientnet-b0
my classes is 2, So it need to set up --hparams="use_bfloat16=false,num_classes=2", if your classes is 1, you need to set up --hparams="use_bfloat16=false,num_classes=1", hope to help you

**Comment by mingxingtan** [comment]
Thanks @HK017, I added this "num_classes=xx" in README for pascal. I am going to close this issue, if people still have issues, feel free to add comments to https://github.com/google/automl/issues/94
