### ISSUE TITLE
k-means anchor ratios from XML file annotations

### ISSUE THREAD

**Issue by Steve-2040** [google/automl#810]
@JK-Pair I use the following method to calculate k-means anchor ratios: I do the image annotation with labelImg that create XML files. From #412 I use https://github.com/mnslarcher/kmeans-anchors-ratios kmeans_anchors_ratios.py script to calculate the aspect_ratios. This script requires a json instances file. I have written a script that convert only the necessary fields from XML to json (xml_annotation2json.py):
```python
import glob
from lxml import etree
 
files = glob.glob("C:/Users/.../Annotations/*.xml")
'''
image{"id": int, "width": int, "height": int, "file_name": str, "license": int, "flickr_url": str, "coco_url": str, "date_captured": datetime,}
annotation{"id": int, "image_id": int, "category_id": int, "segmentation": RLE or [polygon], "area": float, "bbox": [x,y,width,height], "iscrowd": 0,}
'''
print("annotations: ", str(len(files)))
im_id = 0
json_images = ""
json_annotations = ""
for f in files:
    tree = etree.parse(f)
    xml = tree.getroot()
    size_width = xml.xpath('//size/width')[0].text
    size_height = xml.xpath('//size/height')[0].text
    obj_bbox = xml.xpath('//object/bndbox')
    objs_difficult = xml.xpath('//object/difficult')
    objs_name = xml.xpath('//object/name')
    im_id += 1
    if json_images != "": json_images += ','
    json_images += f'{{"id": {im_id}, "width": {size_width}, "height": {size_height}}}'
    for b in obj_bbox:
        x = int(b[0].text)
        y = int(b[1].text)
        w = int(b[2].text) - x
        h = int(b[3].text) - y
        if json_annotations != "": json_annotations += ','
        json_annotations += f'{{"id": 0, "image_id": {im_id}, "category_id": 0, "bbox": [{x},{y},{w},{h}]}}'
            
with open('jsonfile.txt', 'w') as jsonfile:
    jsonfile.write('{ "images":[' + json_images + '],"annotations":[' + json_annotations + '] }')
```
then calculate the aspect ratios with:
```
python kmeans_anchors_ratios.py ^
           --instances jsonfile.txt ^
           --anchors-sizes 32 64 128 256 512 ^
           --input-size 1280 ^
           --normalizes-bboxes True ^
           --num-runs 3 ^
           --num-anchors-ratios 4 ^
           --max-iter 30 ^
           --min-size 0 ^
           --iou-threshold 0.5 ^
           --decimals 1 ^
           --default-anchors-ratios "[(0.7, 1.4), (1.0, 1.0), (1.4, 0.7)]"
```
that produces output like this:
```
[09/29 10:40:04] Reading jsonfile.txt
[09/29 10:40:04] Starting the calculation of the optimal anchors ratios
[09/29 10:40:04] Extracting and preprocessing bounding boxes
[09/29 10:40:04] Discarding 0 bounding boxes with size lower or equal to 0
[09/29 10:40:04] K-Means (3 runs): 100%|██████████████████| 3/3 [00:00<00:00, 17.47it/s]
        Runs avg. IoU: 81.92% ± 0.20% (mean ± std. dev. of 3 runs, 0 skipped)
        Avg. IoU between bboxes and their most similar anchors after norm. them to make their area equal (only ratios matter): 82.08%
[09/29 10:40:05] Default anchors ratios: [(0.7, 1.4), (1.0, 1.0), (1.4, 0.7)]
        Avg. IoU between bboxes and their most similar default anchors, no norm. (both ratios and sizes matter): 60.02%
        Num. bboxes without similar default anchors (IoU < 0.5):  2646/10878 (24.32%)
[09/29 10:40:05] K-Means anchors ratios: [(0.3, 2.9), (0.5, 1.9), (0.7, 1.4), (1.2, 0.9)]
        Avg. IoU between bboxes and their most similar K-Means anchors, no norm. (both ratios and sizes matter): 68.33%
        Num. bboxes without similar K-Means anchors (IoU < 0.5):  252/10878 (2.32%)
[09/29 10:40:05] K-Means anchors have an IoU < 50% with bboxes in 22.01% less cases than the default anchors, you should consider to use them
```
then I calculate aspect ratios 0.3/2.9 = 0.1; 0.5/1.9 = 0.26; 0.7/1.4 = 0.5; 1.2/0.9 = 1.33. This seems to work OK for me. Hope this helps. If anyone has suggestions for improvements, or if this method is not accurate please leave a comment.

**Comment by JK-Pair** [comment]
> @JK-Pair I use the following method to calculate k-means anchor ratios: I do the image annotation with labelImg that create XML files. From #412 I use https://github.com/mnslarcher/kmeans-anchors-ratios kmeans_anchors_ratios.py script to calculate the aspect_ratios. This script requires a json instances file. I have written a script that convert only the necessary fields from XML to json (xml_annotation2json.py):
> 
> ```python
> import glob
> from lxml import etree
>  
> files = glob.glob("C:/Users/.../Annotations/*.xml")
> '''
> image{"id": int, "width": int, "height": int, "file_name": str, "license": int, "flickr_url": str, "coco_url": str, "date_captured": datetime,}
> annotation{"id": int, "image_id": int, "category_id": int, "segmentation": RLE or [polygon], "area": float, "bbox": [x,y,width,height], "iscrowd": 0,}
> '''
> print("annotations: ", str(len(files)))
> im_id = 0
> json_images = ""
> json_annotations = ""
> for f in files:
>     tree = etree.parse(f)
>     xml = tree.getroot()
>     size_width = xml.xpath('//size/width')[0].text
>     size_height = xml.xpath('//size/height')[0].text
>     obj_bbox = xml.xpath('//object/bndbox')
>     objs_difficult = xml.xpath('//object/difficult')
>     objs_name = xml.xpath('//object/name')
>     im_id += 1
>     if json_images != "": json_images += ','
>     json_images += f'{{"id": {im_id}, "width": {size_width}, "height": {size_height}}}'
>     for b in obj_bbox:
>         x = int(b[0].text)
>         y = int(b[1].text)
>         w = int(b[2].text) - x
>         h = int(b[3].text) - y
>         if json_annotations != "": json_annotations += ','
>         json_annotations += f'{{"id": 0, "image_id": {im_id}, "category_id": 0, "bbox": [{x},{y},{w},{h}]}}'
>             
> with open('jsonfile.txt', 'w') as jsonfile:
>     jsonfile.write('{ "images":[' + json_images + '],"annotations":[' + json_annotations + '] }')
> ```
> 
> then calculate the aspect ratios with:
> 
> ```
> python kmeans_anchors_ratios.py ^
>            --instances jsonfile.txt ^
>            --anchors-sizes 32 64 128 256 512 ^
>            --input-size 1280 ^
>            --normalizes-bboxes True ^
>            --num-runs 3 ^
>            --num-anchors-ratios 4 ^
>            --max-iter 30 ^
>            --min-size 0 ^
>            --iou-threshold 0.5 ^
>            --decimals 1 ^
>            --default-anchors-ratios "[(0.7, 1.4), (1.0, 1.0), (1.4, 0.7)]"
> ```
> 
> that produces output like this:
> 
> ```
> [09/29 10:40:04] Reading jsonfile.txt
> [09/29 10:40:04] Starting the calculation of the optimal anchors ratios
> [09/29 10:40:04] Extracting and preprocessing bounding boxes
> [09/29 10:40:04] Discarding 0 bounding boxes with size lower or equal to 0
> [09/29 10:40:04] K-Means (3 runs): 100%|██████████████████| 3/3 [00:00<00:00, 17.47it/s]
>         Runs avg. IoU: 81.92% ± 0.20% (mean ± std. dev. of 3 runs, 0 skipped)
>         Avg. IoU between bboxes and their most similar anchors after norm. them to make their area equal (only ratios matter): 82.08%
> [09/29 10:40:05] Default anchors ratios: [(0.7, 1.4), (1.0, 1.0), (1.4, 0.7)]
>         Avg. IoU between bboxes and their most similar default anchors, no norm. (both ratios and sizes matter): 60.02%
>         Num. bboxes without similar default anchors (IoU < 0.5):  2646/10878 (24.32%)
> [09/29 10:40:05] K-Means anchors ratios: [(0.3, 2.9), (0.5, 1.9), (0.7, 1.4), (1.2, 0.9)]
>         Avg. IoU between bboxes and their most similar K-Means anchors, no norm. (both ratios and sizes matter): 68.33%
>         Num. bboxes without similar K-Means anchors (IoU < 0.5):  252/10878 (2.32%)
> [09/29 10:40:05] K-Means anchors have an IoU < 50% with bboxes in 22.01% less cases than the default anchors, you should consider to use them
> ```
> 
> then I calculate aspect ratios 0.3/2.9 = 0.1; 0.5/1.9 = 0.26; 0.7/1.4 = 0.5; 1.2/0.9 = 1.33. This seems to work OK for me. Hope this helps. If anyone has suggestions for improvements, or if this method is not accurate please leave a comment.

Thank you so much for your help.
