### ISSUE TITLE
About AutoAugment

### ISSUE THREAD

**Issue by Qianshaowei** [google/automl#814]
Hello, I found there are autoaugment.py in the Repositrory. And I want to reimplement it to search the effective data augment method to my data. Do you have any good suggestions?  I will be grateful your answers.

**Comment by mingxingtan** [comment]
Yes, you can search for different policies for your dataset if you want.  For example, you can search which set of aug policies to appoly and what's the order to apply them. You probably don't need to reimplement it if you are using TF

**Comment by Qianshaowei** [comment]
> Yes, you can search for different policies for your dataset if you want. For example, you can search which set of aug policies to apply and what's the order to apply them. You probably don't need to reimplement it if you are using TF

Thanks for your reply. I still have some questions. After I went through the entire Repositrory, i didn't find the search code. I only found some search policies.

**Comment by Qianshaowei** [comment]
> Yes, you can search for different policies for your dataset if you want. For example, you can search which set of aug policies to apply and what's the order to apply them. You probably don't need to reimplement it if you are using TF
Thanks for your reply. I still have some questions. After I went through the entire Repositrory, i didn't find the search code. I only found some data augment policies.

**Comment by Qianshaowei** [comment]
> Yes, you can search for different policies for your dataset if you want. For example, you can search which set of aug policies to apply and what's the order to apply them. You probably don't need to reimplement it if you are using TF

Thanks for your reply. I still have some questions. After I went through the entire Repositrory, i didn't find the search code. I only found some data augment policies.

**Comment by kartik4949** [comment]
@Qianshaowei search aug/autoaugment.py

**Comment by Qianshaowei** [comment]
> @Qianshaowei search aug/autoaugment.py

I’m sorry to disturb you, I still haven’t been able to find the RNN neural network function

**Comment by kartik4949** [comment]
> > @Qianshaowei search aug/autoaugment.py
> 
> I’m sorry to disturb you, I still haven’t been able to find the RNN neural network function

Linux have a technology called grep , use it!
:)

**Comment by Qianshaowei** [comment]
> > > @Qianshaowei search aug/autoaugment.py
> > 
> > 
> > I’m sorry to disturb you, I still haven’t been able to find the RNN neural network function
> 
> Linux have something called grep , use it!
> :)


After I read the code some times, I am sure that the code of the RNN controller part does not exist.
There are only a series of policies that have been searched.

Here are some other evidence.
https://github.com/tensorflow/tpu/issues/754
