### ISSUE TITLE
Why training=True in test_step when using keras train_lib.py?

### ISSUE THREAD

**Issue by thnkinbtfly** [google/automl#817]
Hi, Thanks for the awesome works!
I got a question while reading the code.

Why did you change to use training=True in test_step like below? (https://github.com/google/automl/commit/d514d6c5d5188532597aec66931f5ec867aaf7e7)
https://github.com/google/automl/blob/0f22ed5570a532945ca0bd5f73814e8d89701685/efficientdet/keras/train_lib.py#L561-L566

**Comment by fsx950223** [comment]
> Hi, Thanks for the awesome works!
> I got a question while reading the code.
> 
> Why did you change to use training=True in test_step like below? ([d514d6c](https://github.com/google/automl/commit/d514d6c5d5188532597aec66931f5ec867aaf7e7))
> https://github.com/google/automl/blob/0f22ed5570a532945ca0bd5f73814e8d89701685/efficientdet/keras/train_lib.py#L561-L566

Good point! Fix it later.
