### ISSUE TITLE
inference.ServingDriver can 't work

### ISSUE THREAD

**Issue by mmzmagic** [google/automl#82]
thanks good work for the easy use new Class  "inference.ServingDriver"
but i tested use  below code:

import inference
driver = inference.ServingDriver(MODEL, MODEL)
driver.build()
i=0;
for f in tf.io.gfile.glob('./testdata/*.jpg'):
  image = Image.open(f)
  predictions = driver.serve(image)
  out_image = driver.visualize(image, predictions[0])
  i=i+1
  output_image_path = os.path.join('./tmp', str(i) + '.jpg')
  Image.fromarray(out_image).save(output_image_path)

------------------------------------------------------------------------------------
but the result images is same as input image ,no visualize any classe boxs on image, 
mabye there is a small bug?  
thanks  for check this.

**Comment by mingxingtan** [comment]
Hi @mmzmagic , looks like you feed the Image object rather than a numpy array, which might cause some troubles.

I just tried the following code and it works well:

```
from PIL import Image
import os
import inference
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_v2_behavior()

MODEL='efficientdet-d0'
MODEL_DIR='/tmp/efficientdet-d0'
driver = inference.ServingDriver(MODEL, MODEL_DIR)
driver.build()
i=0;
for f in tf.io.gfile.glob('./testdata/*.jpg'):
  image = np.array(Image.open(f))
  predictions = driver.serve_images([image])
  out_image = driver.visualize(
      image,
      predictions[0],
      min_score_thresh=0.5,
      max_boxes_to_draw=10,
  )
  i=i+1
  output_image_path = os.path.join('./tmp', str(i) + '.jpg')
  Image.fromarray(out_image).save(output_image_path)
```

**Comment by mingxingtan** [comment]
Notably, we just changed the serving function name to serve_images.

I am going to close this issue for now, but please feel free to reopen it if you still have problems.

**Comment by mmzmagic** [comment]
@mingxingtan  thanks resb so fast! i test your new code but the same as yestday . 
 i founded the problem  beacuse i don't get the last new model ,
so i download the new model ,it's works well.
thanks your greate  work  again!
