### ISSUE TITLE
AutoAugmentation

### ISSUE THREAD

**Issue by JK-Pair** [google/automl#822]
Hello everyone,

In this repository, It seems to only used auto-augmentation with training mode, why didn't use auto-augmentation with both training and validation mode? After that question, I did some experiments to compare using auto-augmentation with training mode and both modes.
 
These are the results that I got.

![image](https://user-images.githubusercontent.com/22557628/95288293-28f00c80-0892-11eb-89cd-da877b037a77.png)
AP = 0.167 only training mode

![image](https://user-images.githubusercontent.com/22557628/95288328-36a59200-0892-11eb-89ff-454d26597328.png)
AP = 0.212 both modes

If I used auto-augmentation with both modes, The results that I got seem better than only training mode, but it has more variance.

Please suggestion me, Can I use auto-augmentation with both modes? I don't know what I thought its right or not.

Thank you for your reply.

**Comment by Steve-2040** [comment]
I think in general you do not want to change your validation samples with augmentation that add random changes to the samples. You want a fixed set of validation samples to compare across training runs. I think it is good to have a large number of validation samples that are accurately annotated. There may be specific cases where auto-augmentation validation samples may be helpful?

**Comment by JK-Pair** [comment]
> I think in general you do not want to change your validation samples with augmentation that add random changes to the samples. You want a fixed set of validation samples to compare across training runs. I think it is good to have a large number of validation samples that are accurately annotated and represent the data you will see in 'production'. There may be specific cases where auto-augmentation validation samples may be helpful? Not sure if this answers the question? (If augmentation is also disabled for the training part of mode=train_and_eval then it may be a potential issue)

Thank you, It's help ful.
