### ISSUE TITLE
why the default efficientdet-d1 num_classes for coco is 90

### ISSUE THREAD

**Issue by b03505036** [google/automl#83]
In the config.py

# dataset specific parameters
  h.num_classes = 90

But for coco isn't it 80 or 81?

**Comment by mingxingtan** [comment]
Hi @b03505036 

Please see the discussion here: https://stackoverflow.com/questions/50665110/tensorflow-models-uses-coco-90-class-ids-although-coco-has-only-80-categories

the original coco paper mentions 90 classes, so we use the maximum id of 90. However, in the released dataset, there are only 80 classes, leaving some of the ids have no images.

**Comment by mfoglio** [comment]
Does that mean that some category id will never be output from the model? E.g. if 68 is missing from https://github.com/xuannianz/EfficientDet/blob/master/coco_90.json so can I expect the EfficientDet model never to return 68?
