### ISSUE TITLE
How to predict efficientdet?

### ISSUE THREAD

**Issue by zmqp111** [google/automl#831]
Hi. 

I training own my dataset using efficientdet.

Model save using tf.keras.callbacks.ModelCheckpoint(), I get XXXX.tf weight files.

But I try to predict, have some get error

1.  for predict using keras/inspector.py
     **tensorflow.python.framework.errors_impl.FailedPreconditionError: saved_model; Is a directory**

2. using model.load_weights() and model.predict(img)
    I want get (nums, boxes, score, classes), but I have get only 2 outputs.

How can i predict own my dataset?

**Comment by Steve-2040** [comment]
You can have a look at this https://github.com/google/automl/issues/753#issuecomment-689353891 and https://github.com/google/automl/issues/813#issuecomment-707053728 for the saved_model it may be helpful.

**Comment by Nicerova7** [comment]
You can consider use the oficial tutorial https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb.

To train your own dataset (in tfrecords)

`!python main.py --mode=train_and_eval \
    --training_file_pattern={train_tf} \
    --validation_file_pattern={test_tf} \
    --model_name={MODEL} \
    --model_dir={output} \
    --ckpt={MODEL} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=3361  \
    --num_examples_per_epoch=7650  --num_epochs=1  \
    --hparams="num_classes=13,moving_average_decay=0,mixed_precision=true"`

Where train_tf and test_tf are routes to your tfrecords, MODEL is the version of your efficientdet model (for example efficientdet-d0), ckpt is the route to your checkpoints (You can use https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-d0.tar.gz ) . Remeber change your --hparams according to your dataset.

To save your model:

`saved_model_dir = 'savedmodel'
!rm -rf {saved_model_dir}
!python model_inspect.py --runmode=saved_model --model_name={MODEL} \
  --ckpt_path={ckpt_path} --saved_model_dir={saved_model_dir} \
  --hparams='config.yaml'`

Where your results will be in saved_model_dir , remember select your config.yaml route if when you were training putted 'moving_average_decay=0'. 

Finally,

`serve_image_out = 'serve_image_out'
!mkdir {serve_image_out}

!python model_inspect.py --runmode=saved_model_infer \
  --saved_model_dir={saved_model_dir} \
  --model_name={MODEL}  --input_image=testdata/test_img.jpg  \
  --output_image_dir={serve_image_out} \
  --min_score_thresh={min_score_thresh}  --max_boxes_to_draw={max_boxes_to_draw}`

Where testdata/test_image.jpg is the image route for your test (inference) process...
Some other variables for the above code:

min_score_thresh = 0.35
max_boxes_to_draw = 200

**Comment by oscaraen** [comment]
> Hi.
> 
> I training own my dataset using efficientdet.
> 
> Model save using tf.keras.callbacks.ModelCheckpoint(), I get XXXX.tf weight files.
> 
> But I try to predict, have some get error
> 
>     1. for predict using keras/inspector.py
>        **tensorflow.python.framework.errors_impl.FailedPreconditionError: saved_model; Is a directory**
> 
>     2. using model.load_weights() and model.predict(img)
>        I want get (nums, boxes, score, classes), but I have get only 2 outputs.
> 
> 
> How can i predict own my dataset?

Hello, I have a little question, I'm new on this and I don't know how to add keras callbacks to the main.py script (for training in custom data). How can I add callbacks? Thanks a lot
