### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ankit980** [google/automl#836]
I am writing code in python selenium for the conftest.py file but getting an error please help!! 

import pytest
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
driver= None

def pytest_addoption(parser):
    parser.addoption (
            "--browser_name",action="store",default='chrome'
    )

@pytest.fixture(scope="class")
def setup(request):
    global driver
    browser_name = request.config.getoption("browser_name")
    if browser_name == "Chrome":
        driver = webdriver.Chrome(executable_path="E://ankit//chromedriver.exe")
    elif browser_name == "Firefox":
        driver = webdriver.Firefox(executable_path="C://Users//Ankit//Downloads//geckodriver.exe")
    elif browser_name == "Ie":
        driver = webdriver.Ie(executable_path="C://Users//Ankit//Downloads//IEDriverServer.exe")
    driver.get("https://rahulshettyacademy.com/angularpractice/")
    driver.maximize_window()
    request.cls.driver=driver
    yield
    driver.close()

**Comment by srini-pro** [comment]
?
