### ISSUE TITLE
Visualize random images from dataloader

### ISSUE THREAD

**Issue by kartik4949** [google/automl#838]
Lot of people are having issue and are skeptical if the tfrecords created are correct or data labelling is correct 
Im developing a feature in dataloader which visualizes random 'n' number of images before training or just for testing dataloader!
@mingxingtan @fsx950223 thoughts?

**Comment by fsx950223** [comment]
https://github.com/sulc/tfrecord-viewer

**Comment by kartik4949** [comment]
@fsx950223 so cant we add this or something like this in our repository!

**Comment by Steve-2040** [comment]
Sounds like a good idea. I think it will be helpful if the output-sample-diagnostic-images also include augmented images? So, this will need to be done while training? Not sure if this can be done for GPU and TPU training.

**Comment by kartik4949** [comment]
@Steve-2040 yes will make a flag which can be invoked to diagnose training images

**Comment by Steve-2040** [comment]
I think this can be helpful. If you can specify a diagnostics path and folder (directory) to save 1 in n samples. It can be a guessing game to know what images are actually used for training.

**Comment by kartik4949** [comment]
Exactly 
Will store some n sample images with rois or masks before actuall training starts and user can confirm the images and continue with training

**Comment by fsx950223** [comment]
> I think this can be helpful. If you can specify a diagnostics path and folder (directory) to save 1 in n samples. It can be a guessing game to know what images are actually used for training.

Why don't you use ```img_summary_steps```?

**Comment by kartik4949** [comment]
@fsx950223 in tensorboard ...
Yeah that can be a option too but i didnt see any image step in tensorboard

**Comment by Steve-2040** [comment]
@fsx950223 Thanks for mentioning that. I was not aware of img_summary_steps Does that output the visual images including augmentation?
@kartik4949 I am thinking even if it starts outputting images while training, the user can verify these images after training started and then decide to continue or restart training.

**Comment by kartik4949** [comment]
use this #865
