### ISSUE TITLE
How can I see the log or tensor_board for the loss value?

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#84]
hi, thx for your code

I want to check the value of loss. What should I do?

**Comment by getter-boy** [comment]
I'm a beginner of GIT. I've browsed some git content out of curiosity. I'm sorry to disturb you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WonTaeYeon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 上午10:14
收件人:&nbsp;"google/automl"<automl@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[google/automl] How can I see the log or tensor_board for the loss value? (#84)





 
hi, thx for your code
 
I want to check the value of loss. What should I do?

**Comment by guruzen** [comment]
During your training you should see a logs directory. You should start your tensorboard pointing to this logs directory 
tensorboard --logdir <yourdirectory>/logs

**Comment by mingxingtan** [comment]
Thanks @guruzen for providing the instructions.
