### ISSUE TITLE
Where is checkpoint saved?

### ISSUE THREAD

**Issue by toilahung** [google/automl#841]
Hello everyone, I started finetuning for my custom dataset and the terminal said `Saving checkpoints for 0 into /tmp/model_dir/efficientdet-d0-finetune/model.ckpt. ` however when I check the `/tmp/model_dir/efficientdet-d0-finetune/` I didn't see any file.
Where did the checkpoint go? Thank you for your time.

**Comment by jms0923** [comment]
/tmp/ from root
do cd /tmp/model_dir/ then you can see checkpoints

**Comment by toilahung** [comment]
I check and during training there really no file inside the folder, even the folder not exists. Is it created after training?
