### ISSUE TITLE
How to reset global_step

### ISSUE THREAD

**Issue by SiBensberg** [google/automl#842]
I want to load a pretrained model of myself to continue training with other parts of the network freezed. A bit similiar to #796 
But the Training always starts at the step the loaded model finished. 
My Idea is to simply reset the 'global_step' tensor in the saved Checkpoint. But how to do this?

**Comment by matankley** [comment]
Hey, have you found a solution for resetting the global step ?

**Comment by SiBensberg** [comment]
My idea was to load the checkpoint into a model and reset the param. Then save it again. But I did not found the time for it. As soon as I found a solution I will post it here :)

**Comment by MiJiw** [comment]
I'm also interested in this to transfer knowledge from large custom dataset to small custom dataset.

@mingxingtan Could you please share how you prepared the pretrained checkpoints in the README? Thank you.

**Comment by mingxingtan** [comment]
Hi, could you paste your command line?

**Comment by kevinkvothe** [comment]
https://github.com/google/automl/issues/796#issuecomment-746727076
