### ISSUE TITLE
TypeError during quantization aware training

### ISSUE THREAD

**Issue by emmagarvey32911** [google/automl#849]
I'm trying to train an efficientdet-d0 Keras model using quantization aware training.  I have updated my config.yaml file to include the following line: 

**model_optimizations: {quantize: 1}**

and have updated line 97 in /keras/train.py script from `config.override(FLAGS.hparams)` to `config.override(FLAGS.hparams, allow_new_keys=True)`

From the[ /keras/model_optimization.py](https://github.com/google/automl/blob/master/efficientdet/keras/model_optimization.py) code I can see that it requires a dictionary argument with the key "quantize" but I'm unsure what the value of the dictionary pair should be.

In other words, what should X be?  - **model_optimizations: {quantize: X}**

As it stands, I get the following error when I try to train the model with the current config file:

Traceback (most recent call last):
  File "/home/emma/I2L/tfnightly/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/emma/I2L/tfnightly/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/emma/automl/efficientdet/keras/train.py", line 214, in main
    model_optimization.set_config(params['model_optimizations'])
  File "/home/emma/automl/efficientdet/keras/model_optimization.py", line 38, in set_config
    quantize, **configs[key])
TypeError: type object argument after ** must be a mapping, not str

I understand that its looking for a mapped value of some sort but I'm not exactly sure how to implement this in the config file.

**Comment by fsx950223** [comment]
model_optimizations: {'quantize': {}}
