### ISSUE TITLE
Release keras model

### ISSUE THREAD

**Issue by fsx950223** [google/automl#850]
I could get SOTA performance on the latest codebase.
Is it time to release keras model?
@mingxingtan

**Comment by mingxingtan** [comment]
Agreed. I think it is time to make keras models as default:

1. Update README and Tutorial to use keras code and models in default.
2. Clean up the top level files: (1) If they are required by keras models, then move to keras folder;  (2) I can move all other files to a "legacy" subfolder.

What do you think? @fsx950223

**Comment by fsx950223** [comment]
I agree.

**Comment by fsx950223** [comment]
> Agreed. I think it is time to make keras models as default:
> 
> 1. Update README and Tutorial to use keras code and models in default.
> 2. Clean up the top level files: (1) If they are required by keras models, then move to keras folder;  (2) I can move all other files to a "legacy" subfolder.
> 
> What do you think? @fsx950223

Please check Keras TPU process too.
