### ISSUE TITLE
Training issue with grad_checkpoint=true

### ISSUE THREAD

**Issue by kumaradi08** [google/automl#852]
**Error:** TypeError: Input 'y' of 'Mul' Op has type float16 that does not match type float32 of argument 'x'.

ValueError: Tensor conversion requested dtype float16 for Tensor with dtype float32: <tf.Tensor 'gradients/fpn_cells/cell_6/IdentityN_grad/fnode4/resample_2_8_9/max_pooling2d_30/MaxPool:0' shape=(2, 64, 64, 224) dtype=float32>

Issue while training Pascal VOC 2012 from ImageNet checkpoint for Backbone.

**Command:** python main.py --mode=train_and_eval --training_file_pattern=tfrecord/pascal-00000-of-00100.tfrecord --validation_file_pattern=tfrecord/pascal-00000-of-00100.tfrecord --model_name=efficientdet-d4 --model_dir=/tmp/model_dir/efficientdet-d4-scratch --backbone_ckpt=efficientnet-b5 --train_batch_size=2 --eval_batch_size=4 --eval_samples=56 --num_examples_per_epoch=56  --num_epochs=1  --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true,grad_checkpoint=true"

**Comment by DarekGit** [comment]
have you tried mixed_precision=false?
