### ISSUE TITLE
Can EfficientDet train customized dataset?

### ISSUE THREAD

**Issue by YangZhang-mizzou** [google/automl#86]
Hello! How can I train my dataset(coco format) using efficientdet? I cannot find where to define train dir. Thank you!

**Comment by YangZhang-mizzou** [comment]
get Failed precondition: new_bird/train; Is a directory when I try to put dir into training_file_pattern

**Comment by guruzen** [comment]
I think the tfrecord for training images need to be generated first before you give file pattern as train*

Download coco training data set and then generate the tfrecord in "tfrecord" folder

PYTHONPATH=".:$PYTHONPATH"  python3 dataset/create_coco_tfrecord.py \
    --image_dir=train2017 \
    --caption_annotations_file=annotations/captions_train2017.json \
    --output_file_prefix=tfrecord/train \
    --num_shards=32

Now ./tfrecord/train* will be available.

Next is to start training

python3 main.py --training_file_pattern=./tfrecord/train* \
--model_name=$MODEL \
--model_dir=/tmp/$MODEL \
--hparams="use_bfloat16=false" --use_tpu=False

Guess this solves your problem

**Comment by YangZhang-mizzou** [comment]
Thank you!
