### ISSUE TITLE
max_instances_per_image greater than 100 dosen't change output tensor

### ISSUE THREAD

**Issue by rm98kido** [google/automl#862]
Hi,

It dosen't matter what i try, the network dosen't detect more than 100 objects. the predicted output tensor size dosen't change. I tried to find the problem in the source, but coulnd't find anything so far. May im wrong with my hparams, execution?

and thanks for your great work, this net performs outstanding

```
python main.py --mode=train \
--training_file_pattern=tfrecord/train/extreme_example1-*-of-00100.tfrecord \
--validation_file_pattern=tfrecord/valid/extreme_example1-*-of-00100.tfrecord \
--model_name=efficientdet-d0 \
--model_dir=/tmp/model_dir/efficientdet-d0-extreme_example1  \
--backbone_ckpt=efficientnet-b0 \
--train_batch_size=10 \
--eval_batch_size=10 --eval_samples=1  \
--num_examples_per_epoch=7000  --num_epochs=150  \
--hparams="num_classes=2, image_size='536x352', mixed_precision=true, max_instances_per_image=500"

python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
--ckpt_path=/tmp/model_dir/efficientdet-d0-extreme_example1 --saved_model_dir=savedmodelextreme1 --hparams="num_classes=2, image_size='3008x1960', mixed_precision=true, max_instances_per_image=500";

python model_inspect.py --runmode=saved_model_infer \
--saved_model_dir=savedmodelextreme1 \
--model_name=efficientdet-d0  --input_image=/home/robert/develop/percise-locate-classify/images/testdata-preprocessed/*.jpg  \
--hparams="num_classes=2, image_size='3008x1960', mixed_precision=true, max_instances_per_image=500" \
--output_image_dir=serve_image_out_extreme1 \
--min_score_thresh=-0.1  --max_boxes_to_draw=500
```

**Comment by rm98kido** [comment]
My Bad, there was one space to much between --min_score_thresh=-0.1  --max_boxes_to_draw=500 so it didn't got the argument sorry for wasting anyone's time :D

**Comment by CMangoDH** [comment]
Should set max_boxes_to_draw parameter when run model_inspect.py on mode 'saved_model', if not do that, saved model output type is (-1, 100, 7), even set max_boxes_to_draw parameter on mode 'saved_model_infer' can not draw more than 100 boxes on image.
modify shell command:
`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
--ckpt_path=/tmp/model_dir/efficientdet-d0-extreme_example1 --saved_model_dir=savedmodelextreme1 --max_boxes_to_draw=500 --hparams="num_classes=2, image_size='3008x1960', mixed_precision=true, max_instances_per_image=500";`
after saved model inspect the type:
`saved_model_cli show --dir ./savedmodel --all`
output like below
`MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image_arrays:0'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, -1, -1, -1)
        name: image_arrays:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detections:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 500, 7)
        name: detections:0
  Method name is: tensorflow/serving/predict`
by the way, parameter 'max_instances_per_image' is for training, it means the max number of target object on  image. If this parameter not big enough, you will fail when training.
