### ISSUE TITLE
EfficientDet TF1

### ISSUE THREAD

**Issue by SukyoungCho** [google/automl#869]
Is a model on this repo only compatible with TF2? (https://github.com/google/automl/tree/master/efficientdet)

I am currently looking for an EfficientDet model which can be exported into a `tflite `file with `uint8` quantization to deploy it on a board using EdgeTPU compile. I wonder if there is an EfficientDet which can be quantized into uint8 format and then EdgeTPU compiled.

Also, it would be nice if you could tell me if EfficientDet cannot be implemented on TF1 Object Detection API. And, if so, how i could add a backbone of EfficientDet into TF1 Object Detection API and train it

**Comment by mingxingtan** [comment]
TFLite support is added  https://github.com/google/automl/tree/master/efficientdet/keras#3-export-savedmodel-frozen-graph-tensort-models-or-tflite
