### ISSUE TITLE
How can i run model_inspect.py for video?

### ISSUE THREAD

**Issue by levanpon98** [google/automl#87]
Hello!!, How can I run model_inspect.py for video, I can not find any command for this?

**Comment by mingxingtan** [comment]
Hi @levanpon98 You might want to use our inferernce.py utility:

https://github.com/google/automl/blob/552d0facd14f4fe9205a67fb13ecb5690a4d1c94/efficientdet/inference.py#L265

You probably can try to export a saved_model and do inference.

**Comment by levanpon98** [comment]
Thank @mingxingtan. I have another question
```
cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
```
I create a stream, and then I predict object in each frame but I got some error, how can i solve it

**Comment by jens25** [comment]
@levanpon98 I created a small script for inference from video stream, maybe this will help you:
https://gist.github.com/jens25/31e2faf9d3c16ee17f879872d28a1124
Place it inside the efficientdet folder and change the number in cv2.VideoCapture to the video device you want to use.

**Comment by levanpon98** [comment]
@jens25 thank you very much, you saved me
