### ISSUE TITLE
the question about the coco image sizes

### ISSUE THREAD

**Issue by liufengwei520** [google/automl#879]
the coco size is about 640,why  the input-size of your D7 version is 1536 ?Does this has some advance?

**Comment by Ted678Wu** [comment]
if I understand correctly, when you resize the image from small to big, it will enlarge the small object, which could be helpful for detection.

**Comment by mingxingtan** [comment]
@Ted678Wu is right.   D7 use large images to improve detection accuracy, but using large images is not a desirable solution as it significantly increases computational cost. However, it is generally a difficult (but good) research question: how to detect small objects.
