### ISSUE TITLE
Today the model detects less object

### ISSUE THREAD

**Issue by wadewangpower** [google/automl#89]
Yesterday, i run the script with previous pretained ckpt and source code(seems created on 3/16)on the test image which its result is the same as demo, but today i update the Pretrained EfficientDet Checkpoints( created on 3/27)and source code, and rerun the script, the result shows there is less objects are detected. min_score_thresh both equals 0.2, max_boxes_to_draw both equals 100. Why? 
![1](https://user-images.githubusercontent.com/43233772/77843773-fe324680-71d2-11ea-8c41-e627f7499aeb.jpg)
above image inferenced by driver.serve_images()
![0](https://user-images.githubusercontent.com/43233772/77843923-574eaa00-71d4-11ea-98b2-54913bc69d87.jpg)
above image inferenced by driver.inference()
![demo](https://user-images.githubusercontent.com/43233772/77843843-86185080-71d3-11ea-8386-5ab03acfcc76.jpg)
above image is demo image

**Comment by fsx950223** [comment]
Could you try it on colab with following params 
```
min_score_thresh = 0.4  #@param
max_boxes_to_draw = 200  #@param
line_thickness = 4  #@param
```
?

**Comment by mmzmagic** [comment]
i found this last day ,it not the checkpoint cause. same model ,same checkpoit ,same check picture.
use
python model_inspect.py --runmode=infer --model_name=efficientdet-d0  --ckpt_path=efficientdet-d0 --input_image=a3.jpg --output_image_dir=tmp  --line_thickness=1 --max_boxes_to_draw=1000 --min_score_thresh=0.2

resb image  object is less：

![0](https://user-images.githubusercontent.com/8248263/77845719-9a644980-71e3-11ea-8c66-387111d36790.jpg)

but use  driver.inference() is well.

![a5](https://user-images.githubusercontent.com/8248263/77845779-19598200-71e4-11ea-9e8a-484861c28061.jpg)

**Comment by guruzen** [comment]
Do anyone have an idea why it differs when we run manually vs running in colab?

**Comment by fsx950223** [comment]
> i found this last day ,it not the checkpoint cause. same model ,same checkpoit ,same check picture.
> use
> python model_inspect.py --runmode=infer --model_name=efficientdet-d0 --ckpt_path=efficientdet-d0 --input_image=a3.jpg --output_image_dir=tmp --line_thickness=1 --max_boxes_to_draw=1000 --min_score_thresh=0.2
> 
> resb image object is less：
> 
> ![0](https://user-images.githubusercontent.com/8248263/77845882-b87e7980-71e4-11ea-950b-a5985b17e97a.jpg)
> 
> but use driver.inference() is well.
> 
> ![a5](https://user-images.githubusercontent.com/8248263/77845779-19598200-71e4-11ea-9e8a-484861c28061.jpg)

Please change input_image_size to 1920, Thanks

**Comment by guruzen** [comment]
Just as i suspected. Thanks @fsx950223 . Works perfect now..

**Comment by mmzmagic** [comment]
thanks  resb,  i  was redownload  the pic form 
https://user-images.githubusercontent.com/11736571/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png
rename to a5.png and use command:
python model_inspect.py --runmode=infer --model_name=efficientdet-d0  --ckpt_path=efficientdet-d0 --input_image=a5.png --output_image_dir=tmp  --line_thickness=4 --max_boxes_to_draw=1000 --min_score_thresh=0.2
 
but the result image object less same
![0](https://user-images.githubusercontent.com/8248263/77846813-465d6300-71eb-11ea-8983-19fee4538b65.jpg)

**Comment by guruzen** [comment]
add --input_image_size=1920 to your command.

**Comment by mmzmagic** [comment]
@fsx950223   @guruzen    Thanks ! Works perfect now..

**Comment by wadewangpower** [comment]
> Could you try it on colab with following params
> 
> ```
> min_score_thresh = 0.4  #@param
> max_boxes_to_draw = 200  #@param
> line_thickness = 4  #@param
> ```
> 
> ?
> I got result
> ![image](https://user-images.githubusercontent.com/17592563/77845465-c54d9e00-71e1-11ea-8e50-ee92c8bb10d4.png)

yeah, if i set the parameters : min_score_thresh = 0.4  and max_boxes_to_draw = 200, the result is same to you and same to demo, but at beginning i also run the colab with default param (0.2 & 100), the result is there are only persons are detected shown as below : 
![Snipaste_2020-03-29_19-16-24](https://user-images.githubusercontent.com/43233772/77848349-a0aff100-71f6-11ea-90d5-e0cba559553f.png)
It's weird, isn't it ? Maybe the source code has changed ?

**Comment by fsx950223** [comment]
> > Could you try it on colab with following params
> > ```
> > min_score_thresh = 0.4  #@param
> > max_boxes_to_draw = 200  #@param
> > line_thickness = 4  #@param
> > ```
> > 
> > 
> > ?
> > I got result
> > ![image](https://user-images.githubusercontent.com/17592563/77845465-c54d9e00-71e1-11ea-8e50-ee92c8bb10d4.png)
> 
> yeah, if i set the parameters : min_score_thresh = 0.4 and max_boxes_to_draw = 200, the result is same to you and same to demo, but at beginning i also run the colab with default param (0.2 & 100), the result is there are only persons are detected shown as below :
> ![Snipaste_2020-03-29_19-16-24](https://user-images.githubusercontent.com/43233772/77848349-a0aff100-71f6-11ea-90d5-e0cba559553f.png)
> It's weird, isn't it ? Maybe the source code has changed ?

Maybe something wrong with TensorFlow implementation, I will check it tomorrow.

**Comment by wadewangpower** [comment]
Afterwards, i followed @mmzmagic and @fsx950223 's advice, the result is much normal, and i tried  some comparison with different params:
--min_score_thresh=**0.4** --max_boxes_to_draw=**500** --input_image_size=**1920**
![045001920](https://user-images.githubusercontent.com/43233772/77851155-0e194d00-720a-11ea-8694-1d48b6cd454f.jpg)

--min_score_thresh=**0.2** --max_boxes_to_draw=**500** --input_image_size=**1920**
![025001920](https://user-images.githubusercontent.com/43233772/77851164-13769780-720a-11ea-80eb-6c7f0f5a6858.jpg)

--min_score_thresh=**0.2** --max_boxes_to_draw=**500**   **NO**--input_image_size
![02500](https://user-images.githubusercontent.com/43233772/77851171-18d3e200-720a-11ea-865b-3eecc8fee923.jpg)

**I found : 1. inference result is sensitive to input_image_size, if we didn't declare it in command line, the result is worse.
2. the actual max boxes seems to be less than declared as 500.
By the way, the total running time is more than 1 minute, isn't it a little long ?**

**Comment by guruzen** [comment]
@wadewangpower Yes. it is a little sensitive to the input image size. efficient-d0's default is 512. I am not quite sure if you resize your image to 512 (d0) would give you similar results. But you can try.

And, btw your run for 1 minute includes the time it look to run the entire program. In inference.py, there is a session.run(detection_batch) or something. First run would take a long time. To know the inference time, call "session.run(detection_batch) second time.

In this image, i have called the run() 10 times and am measuring the time taken for the 11th time. You can reduce tat 10 to 2.
![IMG-20200329-WA0022](https://user-images.githubusercontent.com/15829083/77851387-90981180-71f6-11ea-8055-b2fc2dd1cc56.jpeg)

**Comment by wadewangpower** [comment]
> @wadewangpower Yes. it is a little sensitive to the input image size. efficient-d0's default is 512. I am not quite sure if you resize your image to 512 (d0) would give you similar results. But you can try.
> 
> And, btw your run for 1 minute includes the time it look to run the entire program. In inference.py, there is a session.run(detection_batch) or something. First run would take a long time. To know the inference time, call "session.run(detection_batch) second time.
> 
> In this image, i have called the run() 10 times and am measuring the time taken for the 11th time. You can reduce tat 10 to 2.
> ![IMG-20200329-WA0022](https://user-images.githubusercontent.com/15829083/77851387-90981180-71f6-11ea-8055-b2fc2dd1cc56.jpeg)

i writed it like this :
![Snipaste_2020-03-29_23-03-20](https://user-images.githubusercontent.com/43233772/77852522-b54db280-7211-11ea-8781-c6ea90b008e9.png)
and the result is `Inference time:20942.58203125`, does it mean the inference is about  20.942 seconds?

**Comment by guruzen** [comment]
No. Put back the for loop where you let it run once or twice. After that the measurement should be taken.

**Comment by wadewangpower** [comment]
> No. Put back the for loop where you let it run once or twice. After that the measurement should be taken.
Ya,  i just now noticed this point....   i haved uncommented the for loop, the result turns out `Inference time:912.582763671875`, emm, it looks like much normal ! Thank you !

**Comment by mingxingtan** [comment]
Thanks for pointing out the issue.  It was introduced by a PR for supporting savedmodel.

I have reverted the change in https://github.com/google/automl/commit/0918e401bfbdb433d283e7ca02caf31e9d313173.  With this fix, it works well as expected.

However, this is a temporary fix (and it doesn't support savedmodel), @fsx950223 has a further PR: https://github.com/google/automl/pull/95.  We will verify whether that would work later.

**Comment by wadewangpower** [comment]
> Thanks for pointing out the issue. It was introduced by a PR for supporting savedmodel.
> 
> I have reverted the change in [0918e40](https://github.com/google/automl/commit/0918e401bfbdb433d283e7ca02caf31e9d313173). With this fix, it works well as expected.
> 
> However, this is a temporary fix (and it doesn't support savedmodel), @fsx950223 has a further PR: #95. We will verify whether that would work later.

OK, i got it, thanks !
