### ISSUE TITLE
Is it possible to generate tflite int8 using model_inspect.py?

### ISSUE THREAD

**Issue by drahmad89** [google/automl#894]

**Comment by keesschollaart81** [comment]
Take a look at #11

**Comment by mingxingtan** [comment]
yes, the latest script can export int8 tflite files.

**Comment by drahmad89** [comment]
> yes, the latest script can export int8 tflite files.

Where can I find this parameter? I am checking model_inspect and found it only possible for the tensorRT

**Comment by judahkshitij** [comment]
@drahmad89 Did you ever find out the answer to your question as to whether model_inspect can generate int8 tflite or not? I checked latest model_inspect in master and did not see int8 for tflite. I also tried to export a d1 model to tflite and tried to compile using edgetpu_compiler, but compiler said model not quantized. So I guess perhaps int8 tflite is still not produced by model_inspect.py?
