### ISSUE TITLE
batch inference with saved model not working

### ISSUE THREAD

**Issue by soothingni** [google/automl#896]
V100-32G / Ubuntu 16.04 / CUDA 10.1

hi, thanks for a great repository!

I've been struggling for days to make batch inference work with saved model and would greatly appreciate some help with this.

The problem is that regardless of the batch size, the model **only returns detections for the first image**.

After checking out the model with saved_model_cli, I found out that the output dimension is fixed as (1, 100, 7). Below is the cli log.

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image_arrays:0'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, -1, -1, -1)
        name: image_arrays:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detections:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100, 7)
        name: detections:0
  Method name is: tensorflow/serving/predict
```

I followed the command provided in README to export the model. Below is the code I'm using for inference.

```
import os
import numpy as np
from PIL import Image
import tensorflow as tf

import inference

batch_size = 4
model_name = 'efficientdet-d7'
ckpt_path = 'ckpts/efficientdet-d7-finetune/archive'
saved_model_dir = 'saved_models/efficientdet-d7-finetune'

 # 1. Load model
driver = inference.ServingDriver(
    model_name,
    ckpt_path,
    batch_size=batch_size)
driver.load(saved_model_dir)

all_files = list(tf.io.gfile.glob( 'images/*.jpg'))
# print('all_files=', all_files)
 num_batches = (len(all_files) + batch_size - 1) // batch_size

# 2. Prediction
for i in range(num_batches):
    batch_files = all_files[i * batch_size:(i + 1) * batch_size]
    images = [Image.open(f) for f in batch_files]
    raw_images = [np.array(m) for m in images]

    size_before_pad = len(raw_images)
    if size_before_pad < batch_size:
        padding_size = batch_size - size_before_pad
        raw_images += [np.zeros_like(raw_images[0])] * padding_size
        detections_bs = driver.batch_inference(raw_images)
        print(detections_bs)
        print(len(detections_bs))
```

The last print function returns 1. And when I `print(detections_bs[0].shape)` it returns (1, 100, 7).

I would greatly appreciate some help with making batch inference work without having to train the model all over again. 

I've been looking at the first answer on [this stackoverflow query](https://stackoverflow.com/questions/59142040/tensorflow-2-0-how-to-change-the-output-signature-while-using-tf-saved-model), but am not sure how to implement this in my case, or if it is a valid option for my situation.

Thanks!

**Comment by fsx950223** [comment]
How do you export saved model?

**Comment by soothingni** [comment]
I followed the guideline in README.md.

```
!python model_inspect.py —runmode=saved_model \
  —model_name=efficientdet-d7 \
  —ckpt_path=ckpts/efficientdet-d7-finetune/archive/ \
  —hparams=d7-finetune.yaml \
  —saved_model_dir=saved_models/efficientdet-d7-finetune/ \
  —tensorrt=FP32
```

The content of `d7-finetune.yaml` is as follows.

```
num_classes: 2
var_freeze_expr: ‘{efficientnet|fpn_cells|resample_p6}’
label_map: {1: myobject}
use_keras_model: False
grad_checkpoint: True
```

Thanks!

**Comment by fsx950223** [comment]
> I followed the guideline in README.md.
> 
> ```
> !python model_inspect.py —runmode=saved_model \
>   —model_name=efficientdet-d7 \
>   —ckpt_path=ckpts/efficientdet-d7-finetune/archive/ \
>   —hparams=d7-finetune.yaml \
>   —saved_model_dir=saved_models/efficientdet-d7-finetune/ \
>   —tensorrt=FP32
> ```
> 
> The content of `d7-finetune.yaml` is as follows.
> 
> ```
> num_classes: 2
> var_freeze_expr: ‘{efficientnet|fpn_cells|resample_p6}’
> label_map: {1: myobject}
> use_keras_model: False
> grad_checkpoint: True
> ```
> 
> Thanks!

You should set batch_size=4 when you export saved model.

**Comment by soothingni** [comment]
Wow, never knew that.. I will definitely try that and will follow up. Thanks!

Does this mean that I have to export different models for different batch sizes? If so, it would be great if dynamic batch sizes can be integrated into the current source. (i.e. so that the output size in the saved model be (-1, 100, 7))

**Comment by juliangrosshauser** [comment]
You get a dynamic batch size by setting the first input dimension to `None`. Looks like that's possible by passing `--batch_size=0` to `model_inspect.py`: https://github.com/google/automl/blob/master/efficientdet/model_inspect.py#L104-L105

**Comment by soothingni** [comment]
> > I followed the guideline in README.md.
> > ```
> > !python model_inspect.py —runmode=saved_model \
> >   —model_name=efficientdet-d7 \
> >   —ckpt_path=ckpts/efficientdet-d7-finetune/archive/ \
> >   —hparams=d7-finetune.yaml \
> >   —saved_model_dir=saved_models/efficientdet-d7-finetune/ \
> >   —tensorrt=FP32
> > ```
> > 
> > 
> > The content of `d7-finetune.yaml` is as follows.
> > ```
> > num_classes: 2
> > var_freeze_expr: ‘{efficientnet|fpn_cells|resample_p6}’
> > label_map: {1: myobject}
> > use_keras_model: False
> > grad_checkpoint: True
> > ```
> > 
> > 
> > Thanks!
> 
> You should set batch_size=4 when you export saved model.

This worked! But FPS for batch inference(batch_size=4) seems to get worse compared to single image inference.

I used identical commands to export both models except for the last argument(--batch_size), and carried out the comparison for TRT FP16 models.

This is the command I used to export models.
- batch 1
```
! python model_inspect.py --runmode=saved_model \
--model_name=efficientdet-d7 \
--ckpt_path=ckpts/d7-finetune/archive \  
--hparams= d7-finetune.yaml \ 
--saved_model_dir=saved_models/efficientdet-d7-finetune-batch4 \
--tensorrt=FP16
```

- batch 4
```
! python model_inspect.py --runmode=saved_model \
--model_name=efficientdet-d7 \
--ckpt_path=ckpts/d7-finetune/archive \  
--hparams= d7-finetune.yaml \ 
--saved_model_dir=saved_models/efficientdet-d7-finetune-batch4 \
--tensorrt=FP16   --batch_size=4
```

This is the inference time log for each model.
- batch 1
```
--- batch prediction 7.662666320800781 seconds ---
--- batch prediction 0.12525105476379395 seconds ---
--- batch prediction 0.1230916976928711 seconds ---
--- batch prediction 0.11724495887756348 seconds ---
--- batch prediction 0.11823844909667969 seconds ---
--- batch prediction 0.11724591255187988 seconds ---
--- batch prediction 0.11847043037414551 seconds ---
--- batch prediction 0.11723732948303223 seconds ---
--- batch prediction 0.1189577579498291 seconds ---
...

```

- batch 4
```
--- batch prediction 9.26768708229065 seconds ---
--- batch prediction 0.5602936744689941 seconds ---
--- batch prediction 0.5482332706451416 seconds ---
--- batch prediction 0.5416345596313477 seconds ---
--- batch prediction 0.5343294143676758 seconds ---
--- batch prediction 0.5336945056915283 seconds ---
--- batch prediction 0.5245718955993652 seconds ---
--- batch prediction 0.5314595699310303 seconds ---
--- batch prediction 0.5324974060058594 seconds ---
--- batch prediction 0.5305490493774414 seconds ---
--- batch prediction 0.5256021022796631 seconds ---
--- batch prediction 0.5334055423736572 seconds ---
...
```

I was hoping that batch inference would improve inference speed, but apparently am having trouble seeing such results. Any idea why?

Thanks, again!

**Comment by soothingni** [comment]
> You get a dynamic batch size by setting the first input dimension to `None`. Looks like that's possible by passing `--batch_size=0` to `model_inspect.py`: https://github.com/google/automl/blob/master/efficientdet/model_inspect.py#L104-L105

Hi,

I was thinking the same thing, but assigning 0 to `--batch_size` returns the following error...

```
Traceback (most recent call last):
  File "../automl/efficientdet/model_inspect.py", line 520, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 150, in export_saved_model
    driver.build()
  File "/home/ubuntu/automl/efficientdet/inference.py", line 438, in build
    detections = det_post_process(params, class_outputs, box_outputs, scales)
  File "/home/ubuntu/automl/efficientdet/inference.py", line 236, in det_post_process
    params, cls_outputs, box_outputs, scales)
  File "/home/ubuntu/automl/efficientdet/keras/postprocess.py", line 267, in postprocess_global
    single_batch_fn, [boxes, scores, classes])
  File "/home/ubuntu/automl/efficientdet/keras/postprocess.py", line 46, in batch_map_fn
    return tf.vectorized_map(map_fn, inputs, *args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 407, in vectorized_map
    return pfor(loop_fn, batch_size)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 198, in pfor
    outputs = f()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 183, in f
    return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 269, in _pfor_impl
    outputs.append(converter.convert(loop_fn_output))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1284, in convert
    output = self._convert_helper(y)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1464, in _convert_helper
    (y_op.type, y_op, converted_inputs))
ValueError: No converter defined for NonMaxSuppressionV5
name: "loop_body/NonMaxSuppressionV5"
op: "NonMaxSuppressionV5"
input: "loop_body/GatherV2"
input: "loop_body/GatherV2_1"
input: "loop_body/NonMaxSuppressionV5/max_output_size"
input: "loop_body/NonMaxSuppressionV5/iou_threshold"
input: "loop_body/NonMaxSuppressionV5/score_threshold"
input: "loop_body/NonMaxSuppressionV5/soft_nms_sigma"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "pad_to_max_output_size"
  value {
    b: true
  }
}

inputs: [WrappedTensor(t=<tf.Tensor 'loop_body/GatherV2/pfor/GatherV2:0' shape=(None, None, 4) dtype=float32>, is_stacked=True, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/GatherV2_1/pfor/GatherV2:0' shape=(None, None) dtype=float32>, is_stacked=True, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/max_output_size:0' shape=() dtype=int32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/iou_threshold:0' shape=() dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/score_threshold:0' shape=()dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/soft_nms_sigma:0' shape=() dtype=float32>, is_stacked=False, is_sparse_stacked=False)].
Either add a converter or set --op_conversion_fallback_to_while_loop=True, which may run slower
```

**Comment by soothingni** [comment]
> > You get a dynamic batch size by setting the first input dimension to `None`. Looks like that's possible by passing `--batch_size=0` to `model_inspect.py`: https://github.com/google/automl/blob/master/efficientdet/model_inspect.py#L104-L105
> 
> Hi,
> 
> I was thinking the same thing, but assigning 0 to `--batch_size` returns the following error...
> 
> ```
> Traceback (most recent call last):
>   File "../automl/efficientdet/model_inspect.py", line 520, in <module>
>     app.run(main)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 303, in run
>     _run_main(main, args)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "model_inspect.py", line 513, in main
>     trace_filename=FLAGS.trace_filename)
>   File "model_inspect.py", line 462, in run_model
>     self.export_saved_model(**config_dict)
>   File "model_inspect.py", line 150, in export_saved_model
>     driver.build()
>   File "/home/ubuntu/automl/efficientdet/inference.py", line 438, in build
>     detections = det_post_process(params, class_outputs, box_outputs, scales)
>   File "/home/ubuntu/automl/efficientdet/inference.py", line 236, in det_post_process
>     params, cls_outputs, box_outputs, scales)
>   File "/home/ubuntu/automl/efficientdet/keras/postprocess.py", line 267, in postprocess_global
>     single_batch_fn, [boxes, scores, classes])
>   File "/home/ubuntu/automl/efficientdet/keras/postprocess.py", line 46, in batch_map_fn
>     return tf.vectorized_map(map_fn, inputs, *args)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 407, in vectorized_map
>     return pfor(loop_fn, batch_size)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 198, in pfor
>     outputs = f()
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 183, in f
>     return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 269, in _pfor_impl
>     outputs.append(converter.convert(loop_fn_output))
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1284, in convert
>     output = self._convert_helper(y)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1464, in _convert_helper
>     (y_op.type, y_op, converted_inputs))
> ValueError: No converter defined for NonMaxSuppressionV5
> name: "loop_body/NonMaxSuppressionV5"
> op: "NonMaxSuppressionV5"
> input: "loop_body/GatherV2"
> input: "loop_body/GatherV2_1"
> input: "loop_body/NonMaxSuppressionV5/max_output_size"
> input: "loop_body/NonMaxSuppressionV5/iou_threshold"
> input: "loop_body/NonMaxSuppressionV5/score_threshold"
> input: "loop_body/NonMaxSuppressionV5/soft_nms_sigma"
> attr {
>   key: "T"
>   value {
>     type: DT_FLOAT
>   }
> }
> attr {
>   key: "pad_to_max_output_size"
>   value {
>     b: true
>   }
> }
> 
> inputs: [WrappedTensor(t=<tf.Tensor 'loop_body/GatherV2/pfor/GatherV2:0' shape=(None, None, 4) dtype=float32>, is_stacked=True, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/GatherV2_1/pfor/GatherV2:0' shape=(None, None) dtype=float32>, is_stacked=True, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/max_output_size:0' shape=() dtype=int32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/iou_threshold:0' shape=() dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/score_threshold:0' shape=()dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/NonMaxSuppressionV5/soft_nms_sigma:0' shape=() dtype=float32>, is_stacked=False, is_sparse_stacked=False)].
> Either add a converter or set --op_conversion_fallback_to_while_loop=True, which may run slower
> ```

Follow up: Reinstalling tensorflow==2.3.1 made this error go away.

Succeeded in  exporting a dynamic batch model!

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image_arrays:0'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, -1, -1, -1)
        name: image_arrays:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detections:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 100, 7)
        name: detections:0
  Method name is: tensorflow/serving/predict
```

Thanks !!

**Comment by yptheangel** [comment]
@soothingni does the total inference time improve when doing batch inference? on my end i dont see any, comparing between batch size 4 against batch size 1, saved_model with (-1,100,7) output dim as well
