### ISSUE TITLE
The output features of BiFPN Layer

### ISSUE THREAD

**Issue by kevin20080525** [google/automl#9]
According to figure 3 of the BiFPN Layer in the paper, we take the last feature for each resolution as output.
Does it lose a break statement after line 533 in efficientdet_arch.py?
https://github.com/google/automl/blob/6dfc360b1a78d2d973b0d126acc76b1897ea9cc8/efficientdet/efficientdet_arch.py#L533

**Comment by mingxingtan** [comment]
Thank a lot for pointing out this issue. Fixed now.
