### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.

### ISSUE THREAD

**Issue by YangZhang-mizzou** [google/automl#90]
get this error when training customized dataset:
![image](https://user-images.githubusercontent.com/47132186/77843985-d4900580-7167-11ea-93d3-55b9bad0eed1.png)

**Comment by YangZhang-mizzou** [comment]
Anyone who got a similar error before?

**Comment by guruzen** [comment]
Can you send the entire logs pls?

**Comment by WonTaeYeon** [comment]
Delete all the files in the model storage directory folder and try running it again.

**Comment by YangZhang-mizzou** [comment]
Tried but still failed @WonTaeYeon

**Comment by YangZhang-mizzou** [comment]
[records.txt](https://github.com/google/automl/files/4399119/records.txt)
Here is the entire logs

**Comment by Guzaiwang** [comment]
> [records.txt](https://github.com/google/automl/files/4399119/records.txt)
> Here is the entire logs

I met the same issue, and I have not solved it until now.

**Comment by mingxingtan** [comment]
Looks like there are some issues with your input files. How did you generate the tfrecord files?

Notably, you should use our [create_coco_tfrecord](https://github.com/google/automl/blob/master/efficientdet/dataset/create_coco_tfrecord.py) tool, not the tensorflow models tools (that tool is a little out-dated).

see examples here: https://github.com/google/automl/tree/master/efficientdet#4-eval-on-coco-2017-val

**Comment by Guzaiwang** [comment]
> Looks like there are some issues with your input files. How did you generate the tfrecord files?
> 
> Notably, you should use our [create_coco_tfrecord](https://github.com/google/automl/blob/master/efficientdet/dataset/create_coco_tfrecord.py) tool, not the tensorflow models tools (that tool is a little out-dated).
> 
> see examples here: https://github.com/google/automl/tree/master/efficientdet#4-eval-on-coco-2017-val

Thanks for your tutorials about how to generate the tfrecord. Meanwhile, your example just show how to generate the evaluation tfrecord. I use the provided create_coco_tfrecord code to create the training tfrecord on my own dataset, the same error still occurs.

**Comment by YangZhang-mizzou** [comment]
> > Looks like there are some issues with your input files. How did you generate the tfrecord files?
> > Notably, you should use our [create_coco_tfrecord](https://github.com/google/automl/blob/master/efficientdet/dataset/create_coco_tfrecord.py) tool, not the tensorflow models tools (that tool is a little out-dated).
> > see examples here: https://github.com/google/automl/tree/master/efficientdet#4-eval-on-coco-2017-val
> 
> Thanks for your tutorials about how to generate the tfrecord. Meanwhile, your example just show how to generate the evaluation tfrecord. I use the provided create_coco_tfrecord code to create the training tfrecord on my own dataset, the same error still occurs.

**Comment by YangZhang-mizzou** [comment]
> Looks like there are some issues with your input files. How did you generate the tfrecord files?
> 
> Notably, you should use our [create_coco_tfrecord](https://github.com/google/automl/blob/master/efficientdet/dataset/create_coco_tfrecord.py) tool, not the tensorflow models tools (that tool is a little out-dated).
> 
> see examples here: https://github.com/google/automl/tree/master/efficientdet#4-eval-on-coco-2017-val

Thank you for your reply. Yes I think it is a input file problem. I use create_coco_tfrecord code with this command:


> Looks like there are some issues with your input files. How did you generate the tfrecord files?
> 
> Notably, you should use our [create_coco_tfrecord](https://github.com/google/automl/blob/master/efficientdet/dataset/create_coco_tfrecord.py) tool, not the tensorflow models tools (that tool is a little out-dated).
> 
> see examples here: https://github.com/google/automl/tree/master/efficientdet#4-eval-on-coco-2017-val

Thank you for your reply! I used your create_coco_tfrecord tool but still met this problem. It is my command and logs
[text.txt](https://github.com/google/automl/files/4415977/text.txt)
And my images are 512*512 png files. Here is my json file:
[train.zip](https://github.com/google/automl/files/4416030/train.zip)
Thank you!

**Comment by mingxingtan** [comment]
Hi @YangZhang-mizzou, for customized dataset, you might want to try create_pascaal_tfrecord.py to create the tfrecord and the eval json file.

Since it is a little similar to https://github.com/google/automl/issues/94 (a pinned issue), I am going to close this but keep #94 open. Feel free to add your comments there if you still have problems. Thanks!
