### ISSUE TITLE
ask for more information about loss when training on COCO 2017

### ISSUE THREAD

**Issue by Alex220284** [google/automl#91]
Hello, I have run the training process on COCO 2017 based on efficientdet-d0, and get the loss curve as following. However, when I use the training model to infer demo pic, nothing is plotted. I notice that the bbox score is too low(about 0.0002). So I wonder something wrong in my training.

<img width="810" alt="截屏2020-03-29下午5 02 46" src="https://user-images.githubusercontent.com/34477371/77845324-9edb3300-71e0-11ea-918c-7bfe21819875.png">

**Comment by guruzen** [comment]
I just started the training on GPU with a very small learning rate. With the default LR, it was failing with NaN. I am failing to see the logs directory generated. Will wait for sometime.

Where does your logs directory exists for tensorboard to look for?

**Comment by Alex220284** [comment]
> I just started the training on GPU with a very small learning rate. With the default LR, it was failing with NaN. I am failing to see the logs directory generated. Will wait for sometime.
> 
> Where does your logs directory exists for tensorboard to look for?

In the model_dir

**Comment by Alex220284** [comment]
> Hello, I have run the training process on COCO 2017 based on efficientdet-d0, and get the loss curve as following. However, when I use the training model to infer demo pic, nothing is plotted. I notice that the bbox score is too low(about 0.0002). So I wonder something wrong in my training.
> 
> <img alt="截屏2020-03-29下午5 02 46" width="810" src="https://user-images.githubusercontent.com/34477371/77845324-9edb3300-71e0-11ea-918c-7bfe21819875.png">

Why l2 loss so large?

**Comment by dkoguciuk** [comment]
@Alex220284, I believe you've managed to solve your training problem and closed the issue - that's great. Would you be kind enough to share your solution?

**Comment by Alex220284** [comment]
> @Alex220284, I believe you've managed to solve your training problem and closed the issue - that's great. Would you be kind enough to share your solution?

I have made a mistake on creating the training tfrecord by setting the param "caption_annotations_file" to "captions_train2017.json". In fact, Since I rectify the command to set param "object_annotations_file" to "instances_train2017.json", all things go as expected. Hope this is helpful to you.

**Comment by debabicz** [comment]
And what are your hyperparameters? My training just won't converge even with quite small learning rate.

**Comment by elesun2018** [comment]
when i run train code, meet a problem as follows:
/efficientdet# python main.py --training_file_pattern=tfrecord/train* --model_name=$MODEL --model_dir=model/$MODEL --hparams="use_bfloat16=false" --use_tpu=False

tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
 I decrease the learning rate from 0.08---> 0.01, and the same error. Thanks.
