### ISSUE TITLE
Dataloader/TFRecord Problem with TF2.4 update

### ISSUE THREAD

**Issue by cnmckee** [google/automl#914]
Hello,
Trying to inspect my tfrecords for finetuning on VOC with:

python inspect_tfrecords.py --file_pattern tfrecord/train/*.tfrecord --model_name efficientdet-d0 --samples 10 --save_samples_dir outputs/tfrecord_visuals/ --hparams voc_config.yaml

Keep running into this error. This means I can't train the model either.

I1229 19:02:58.827041 139923141277504 dataloader.py:92] target_size = (512, 512), output_size = (512, 512)
I1229 19:02:58.979506 139923141277504 dataloader.py:92] target_size = (512, 512), output_size = (512, 512)
E1229 19:03:00.998958 139923141277504 inspect_tfrecords.py:126] indices[15] = [15] does not index into param shape [15,4]
         [[{{node parser/cond_3/then/_30/parser/cond_3/GatherNd_3}}]]

My tfrecords worked fine before pulling the tf2.4 updates and upgrading tensorflow to 2.4. Can you point me as to what might be wrong? I used create_pascal_tfrecord.py to create the tfrecord files.

**Comment by kartik4949** [comment]
@cnmckee before tf2.4 could you inspect your tfrecords fine? with same script i mean?

**Comment by cnmckee** [comment]
Yes, that is correct. Just confirmed.

**Comment by fsx950223** [comment]
I revert some changes and you could pull the latest code and have a try.

**Comment by kartik4949** [comment]
closing as the new revert would solve it.

**Comment by fsx950223** [comment]
It's fixed in the latest codebase.
