### ISSUE TITLE
Questions about pretrained efficientdet

### ISSUE THREAD

**Issue by handsomefengfeng** [google/automl#92]
The paper mentioned that the EfficientDet-D6 is 50.9M.

I've downloaded from the pretrained.ckpt, but to find the model is 390M.

Could you please give any reasons？

**Comment by mingxingtan** [comment]
Hi @handsomefengfeng 

Yes, what the paper mentions is #parameters. Each parameter is 8 bytes (4 bytes float value + 4 byte moving_average_var float value), so the file size is about 50.8 * 8  ~= 400M

If you want to reduce the ckpt file size, you can do: (1) strip out all moving_average_vars, it would reduce the size to about 200M; (2) you can also quantize all variables to 8 bits, then the ckpt file size would be about 50M.
