### ISSUE TITLE
memory leak when training with keras/train.py

### ISSUE THREAD

**Issue by Net-Mist** [google/automl#923]
Hi ! 

Thanks a lot for all the work you did in this repo ! It is very useful
I'm training a model on Pascal-VOC dataset with the default settings using keras/train.py and I observed that there is a large memory leak: The memory increases by 2.7GB at the end of every validation step, leading the program to be killed after a few numbers of epoch.

This is the command I'm running in keras directory on master branch :

```bash
PYTHONPATH=../:$PYTHONPATH python train.py --mode traineval \
--train_file_pattern=/tfrecord/*.tfrecord \
--val_file_pattern=/tfrecord/*.tfrecord \
--model_name=efficientdet-d0 \
--model_dir=/experiments/default_voc  \
--batch_size=8 \
--eval_samples=1024 \
--num_examples_per_epoch=5717 --num_epochs=300  \
--hparams=../voc_config.yaml
```
and this is the voc_config.yaml file :

```yaml
num_classes: 21
label_map: {1: aeroplane, 2: bicycle, 3: bird, 4: boat, 5: bottle, 6: bus, 7: car, 8: cat, 9: chair, 10: cow, 11: diningtable, 12: dog, 13: horse, 14: motorbike, 15: person, 16: pottedplant, 17: sheep, 18: sofa, 19: train, 20: tvmonitor}
```

Is it a known bug ? Is there anything we can do to solve this issue ?

If it helps, I discover that settings validation_data=None in the model.fit call and removing the COCOCallback callback was needed to stop the memory leak.

**Comment by fsx950223** [comment]
I test the code on VOC dataset, there is no such memory leak when I train with keras/train.py, please install tensorflow2.4

**Comment by Net-Mist** [comment]
Hi ! Thanks a lot for your quick answer,

Installing tcmalloc (`apt-get install -y google-perftools`) and adding `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4` before my python command solved the bug, indeed

FYI, I am running tensorflow 2.4, more precisely the official docker image (`tensorflow/tensorflow:2.4.0-gpu`), and the only other packages I installed with pip are the one from the requirements.txt (+ tensorflow_hub that seems to be needed)
