### ISSUE TITLE
Training script differences

### ISSUE THREAD

**Issue by ngaloppo** [google/automl#928]
What are the main differences between training with `main.py --mode=train` vs `keras/train.py`? Why does the former generate `box_net/box-predict/pointwise_kernel` nodes, while the latter does not? 

The OpenVINO model optimizer relies on those node names to apply certain optimizations before converting to OpenVINO IR. 

Which training script is recommended? (both seem to be using the Keras model, since `use_keras_model` is `True` by default.

**Comment by fsx950223** [comment]
In Keras, the variable's name is ```box_net/box-predict/separable_conv2d/ReadVariableOp_1/resource```.

**Comment by fsx950223** [comment]
You should use following script to export frozen graph.
```python
import tensorflow as tf
import hparams_config
from keras import efficientdet_keras

config = hparams_config.get_efficientdet_config('efficientdet-d0')
config.override('./voc.yaml')

with tf.compat.v1.Session() as sess:
  images = tf.compat.v1.placeholder(tf.uint8, (None, None, None, 3), name='images')
  model = efficientdet_keras.EfficientDetModel(config=config)
  model.load_weights('/media/fangsixie/data/download/efficientdet-d0')
  outputs = model(images)
  output_names = [output.op.name for output in outputs]
  sess.run(tf.compat.v1.global_variables_initializer())
  graphdef = tf.compat.v1.graph_util.convert_variables_to_constants(
    sess, sess.graph_def, output_names)
tf.io.write_graph(graphdef, './test_frozen', 'frozen.pbtxt')
```

**Comment by ngaloppo** [comment]
> You should use following script to export frozen graph.

Why this script and not `model_inspect.py`?

**Comment by ngaloppo** [comment]
Which training script is recommended?

**Comment by fsx950223** [comment]
You could choose anyone which you like.

**Comment by ngaloppo** [comment]
> You could choose anyone which you like.

Is there a benefit to `main.py` vs. `keras/train.py`?

**Comment by mingxingtan** [comment]
keras/train.py is recommended in general (for CPUs/GPUs). keras models give you a lot of flexibility, like multi-gpus and so on.
main.py is a legacy script for TPUs, and I hope to migrate it to keras/train even for TPUs in future.
