### ISSUE TITLE
How to force saved_model to be float 16 

### ISSUE THREAD

**Issue by fitoule** [google/automl#936]
How to force saved_model to be float 16 ?
I tried 
--hparams="num_classes=2,image_size=1024,mixed_precision=True"
or 
--tensorrt=FP16

but it has no effect, generated model is exactly the same as default 32 bits

**Comment by mingxingtan** [comment]
mixed_precision means "weights are in fp32, but computes are in fp16".
If you set weights to be float16, it may affect accuracy. But if you really want to do it, you can disable mixed_precision (by commenting out those code), and set the inputs as float16, then all variables will be created as fp16.
