### ISSUE TITLE
How to train on VOC or custom dataset?

### ISSUE THREAD

**Issue by cyx6666** [google/automl#94]

**Comment by cyx6666** [comment]
I want to train efficientdet on PASCAL VOC 2012,what should i do?
Can I directly convert the XML format to json format for training?

**Comment by wangtianlong1994** [comment]
No, you need to convert it to TFrecord

**Comment by cyx6666** [comment]
> No, you need to convert it to TFrecord
Hi!
I trained a model on VOC,of course it has been conveted to tfrecord.But i dont know how to eval my dataset.
I read [https://github.com/google/automl/blob/master/efficientdet/README.md](url) that running eval `$ python main.py --mode=eval  \
    --model_name=${MODEL}  --model_dir=${CKPT_PATH}  \
    --validation_file_pattern=tfrecord/val*  \
    --val_json_file=annotations/instances_val2017.json  \
    --hparams="use_bfloat16=false" --use_tpu=False` must specify val_json_file,but my dataset is a xml format,so i don't have a json file.
What should i do?
Thanks

**Comment by cyx6666** [comment]
> No, you need to convert it to TFrecord

Hi!
I trained a model on VOC,of course it has been conveted to tfrecord.But i dont know how to eval my dataset.
I read https://github.com/google/automl/blob/master/efficientdet/README.md that running eval $ python main.py --mode=eval \ --model_name=${MODEL} --model_dir=${CKPT_PATH} \ --validation_file_pattern=tfrecord/val* \ --val_json_file=annotations/instances_val2017.json \ --hparams="use_bfloat16=false" --use_tpu=False must specify val_json_file,but my dataset is a xml format,so i don't have a json file.
What should i do?
Thanks

**Comment by wangtianlong1994** [comment]
My situation is the same as yours. I get XML by converting it to COCO, then tfrecord. But now I can't use the converted JSON for Eval, so I can't give you good advice. @cyx6666

**Comment by qtw1998** [comment]
> My situation is the same as yours. I get XML by converting it to COCO, then tfrecord. But now I can't use the converted JSON for Eval, so I can't give you good advice. @cyx6666
`CUDA_VISIBLE_DEVICE=6 python main.py --training_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/train.tfrecord --model_name=efficientdet-d1 --ckpt=/cluster/home/qiaotianwei/automl/efficientdet/efficientdet-d1 --hparams="use_bfloat16=false" --use_tpu=False --train_batch_size 4 --model_dir=/tmp/efficientdet/efficientdet-d1 --mode='train' --validation_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/val.tfrecord `


I'm using the command
I'm gonna train bdd100k(which has been made into tfrecord), ckpt I use the unzipped file
is it right ? thx

**Comment by wangtianlong1994** [comment]
> > 我的情况和你一样。我将XML转换为COCO，然后转换为tfrecord。但是现在我无法将转换后的JSON用于Eval，因此无法给您很好的建议。@ cyx6666
> > `CUDA_VISIBLE_DEVICE=6 python main.py --training_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/train.tfrecord --model_name=efficientdet-d1 --ckpt=/cluster/home/qiaotianwei/automl/efficientdet/efficientdet-d1 --hparams="use_bfloat16=false" --use_tpu=False --train_batch_size 4 --model_dir=/tmp/efficientdet/efficientdet-d1 --mode='train' --validation_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/val.tfrecord `
> 
> 我正在使用将
> 要训​​练的bdd100k（已被制成tfrecord）的命令，请问我使用解压缩的文件
> 对吗？谢谢

是这样的 不过我现在出现了一个问题 
只要指定了--validation_file_pattern后就会报错 
NameError: name 'unicode' is not defined
训练是正常的 测试就不行了

**Comment by mingxingtan** [comment]
I updated README and tutorial to show how to convert pascal data to COCO format and use them in train/eval. Feel free to let me know if you have further questions.

**Comment by qtw1998** [comment]
> > > 我的情况和你一样。我将XML转换为COCO，然后转换为tfrecord。但是现在我无法将转换后的JSON用于Eval，因此无法给您很好的建议。@ cyx6666
> > > `CUDA_VISIBLE_DEVICE=6 python main.py --training_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/train.tfrecord --model_name=efficientdet-d1 --ckpt=/cluster/home/qiaotianwei/automl/efficientdet/efficientdet-d1 --hparams="use_bfloat16=false" --use_tpu=False --train_batch_size 4 --model_dir=/tmp/efficientdet/efficientdet-d1 --mode='train' --validation_file_pattern=/cluster/home/qiaotianwei/automl/bdd100k/val.tfrecord `
> > 
> > 
> > 我正在使用将
> > 要训​​练的bdd100k（已被制成tfrecord）的命令，请问我使用解压缩的文件
> > 对吗？谢谢
> 
> 是这样的 不过我现在出现了一个问题
> 只要指定了--validation_file_pattern后就会报错
> NameError: name 'unicode' is not defined
> 训练是正常的 测试就不行了

老哥你解决了吗？
![image](https://user-images.githubusercontent.com/34357479/78654341-f66f5200-78f6-11ea-9420-c1310098aa03.png)
我报的这个错。。。。 Unicode那个已经解决了

**Comment by mingxingtan** [comment]
@qtw1998 This error means your dataset has problems. My previous code has some bugs, could retry the latest create_pascal_tfrecord.py script to convert your data to tfrecords?

**Comment by qtw1998** [comment]
> @qtw1998 This error means your dataset has problems. My previous code has some bugs, could retry the latest create_pascal_tfrecord.py script to convert your data to tfrecords?

use your latest version of create_pascal_tfrecord.py no use, still -1
lotta people have the problems waiting your method to solve
![image](https://user-images.githubusercontent.com/34357479/78746432-69310980-7999-11ea-8ff3-27cd109123fc.png)

**Comment by mingxingtan** [comment]
https://github.com/google/automl/commit/39bbf8d273eef1b5ec24e5ecaae907f1435313fc should have fixed the AP=-1 issue.

**Comment by shenxiaofei715** [comment]
我自己研究的一下如何训练自己的数据请看
   https://github.com/shenxiaofei715/efficientdet.git

**Comment by cyx6666** [comment]
> I updated README and tutorial to show how to convert pascal data to COCO format and use them in train/eval. Feel free to let me know if you have further questions.

Thanks for your code!I'll try it

**Comment by fitoule** [comment]
Still not working in mode without the JSON file. 
Without any JSON eval is working and give me results, but except for AP it is ever 1 or -1

**Comment by mingxingtan** [comment]
Training on VOC should be fine.  The json file for eval is not required anymore.
