### ISSUE TITLE
Suggestion for requirements change - opencv-python-headless

### ISSUE THREAD

**Issue by hankster** [google/automl#944]
When installing this package the requirements loaded opencv-python-headless and removed a previously installed opencv-python. This caused all my cv2 programs that used the display to crash.

Suggest changing the requirements to "_opencv-python_ **or** _opencv-python-headless_"

The instructions from opencv suggest one or the other of these packages be present, but not both.

**Comment by mingxingtan** [comment]
Hmm, I don't see any opencv-python or opencv-python-headless. Is it caused by others?
