### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[8,640,640,144] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

### ISSUE THREAD

**Issue by ankur47** [google/automl#946]
Hi

I am using efficientdet-5 model to train coco [datasets](https://cloud.google.com/tpu/docs/coco-setup) which stores in gcs bucket .

These are the environment variables and way of executing python module:
***ENV***
`file_pattern = "train-*-of-00256.tfrecord"`
  `images_per_epoch = 14592`
  `MODEL_DIR_BACKBONE="gs://{BUCKET_NAME}/saved_model_bcbn-scratch" `
  `MODEL = efficientdet-5`

***PYTHON***
`python main.py --mode=train_and_eval 
    --train_file_pattern=gs://BUCKET_NAME/{file_pattern} 
    --val_file_pattern=gs://BUCKET_NAME/{file_pattern} 
    --model_name={MODEL} 
    --model_dir={saved_model_dir} 
    --ckpt={MODEL} 
    --train_batch_size=8 
    --eval_batch_size=8 --eval_samples={images_per_epoch}  
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=1  
    --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true"`

Please help me to find out whether this error is either due to limited machine size or might be some wrong arguments

***Machine Configuration***

`Machine type : n1-standard-4 (4 vCPUs, 15 GB RAM)`
`Boot disk: 100 GB disk`
`Data disk:100 GB disk`
`Environment: : TensorFlow 2.4.1 `
`GPU: None`

Please find attached screenshot as well for reference

<img width="989" alt="Screenshot 2021-02-14 at 5 31 44 AM" src="https://user-images.githubusercontent.com/49708001/107864818-1318d680-6e86-11eb-9b59-af38e7acb06d.png">

**Comment by ameyparanjape** [comment]
As the error say, the execution is running `OOM (Out Of Memory)`, try reducing the batch size to get around this, alternatively you can use a GPU or TPU

**Comment by darouwan** [comment]
> As the error say, the execution is running `OOM (Out Of Memory)`, try reducing the `batch size` to get around this, alternatively you can use a GPU or TPU

Can I know where I can set the batch size for efficietnet?
