### ISSUE TITLE
Coco Labels

### ISSUE THREAD

**Issue by Mypathissional** [google/automl#949]
It seems that the pre-trained models given in the repository have 90 classes,
but the label map given https://github.com/google/automl/blob/master/efficientdet/g3doc/coco_ids.yaml contains only 81 labels(including the background).
As far as I understand COCO-2017 also contains 80 categories. So, it seems that the rest 10 categories were not optimized during the training process, is it correct?

Would be grateful for any help,
Maria

**Comment by thiemoToadi** [comment]
So what amount of labels was correct?
