### ISSUE TITLE
TF CPU vs TF GPU Performance

### ISSUE THREAD

**Issue by moaljazaery** [google/automl#952]
I am training D2 model. I found out that training on GPU with (batch size=16 and grad_checkpoint=true) achieving slightly worse accuracy (-3%) than training on CPU (batch_size= 16 and grad_checkpoint= false).
Without grad_checkpoint, tf GPU has out of memory issue.

I am not sure if grad_checkpoint is causing this issue, or it's a CPU VS GPU implementation.

Any thoughts?

**Comment by mingxingtan** [comment]
This is strange. It would be great if you have some simple reproducible example; otherwise, it is hard to figure out the reason.
