### ISSUE TITLE
Bad hardware status. Queue is closed 

### ISSUE THREAD

**Issue by ankur47** [google/automl#955]
Hi 
I have implemented different models like efficientdet-d1,efficientdet-d4 and it was successfully running but when I tried with efficientdet-d5, getting an error like **bad hardware status queue is closed**. The dataset used is open_image_v4 of size 513.8GB with a TPU machine of type v2-32. I believe efficientdet-d5 is much larger and costs more memory.Please suggest me what type of TPU size and batch size should consider to run this model successfully.

Command:
`python main.py --tpu=TPU_NAME --train_file_pattern=gs://train_path/*.tfrecord --model_dir=gs://model_dir --strategy=tpu --model_name=efficientdet-d5 --train_batch_size=64  --num_epochs=1 --hparams="num_classes=601,moving_average_decay=0" --num_examples_per_epoch=1740000`

**Comment by mingxingtan** [comment]
you have a lot of classes (601) and batch size 64 might be too big.  Maybe you can try smaller batch size? (or reduce the training image size)

**Comment by ankur47** [comment]
Thanks @mingxingtan It is working now.
