### ISSUE TITLE
The test speed of D6 on coco val2017 is very slow

### ISSUE THREAD

**Issue by PKUbahuangliuhe** [google/automl#96]
About 1.6fps. Is it ok?

**Comment by mingxingtan** [comment]
Does it include post-processing?  I am currently using a slow version nms, which can be significantly improved.

**Comment by mingxingtan** [comment]
You can use  `python model_inspect.py  --runmode=bm  --model_name=efficientdet-d6` to benchmark model latency.

**Comment by mingxingtan** [comment]
This issue is similar to https://github.com/google/automl/issues/97

I am going to close this issue for now and keeps https://github.com/google/automl/issues/97 open.
