### ISSUE TITLE
[TPU] Google Colab training - COCO evaluation error - Custom dataset

### ISSUE THREAD

**Issue by ameyparanjape** [google/automl#961]
Hello, I am curious to train/finetune the `efficientDet-D1` on Google Colab TPU. I have all my data (200k+ images) converted into tfrecord and verified with [inspect_tfrecords.py](https://github.com/google/automl/blob/master/efficientdet/dataset/inspect_tfrecords.py), tfrecord look alright. While training on colab TPU, after epoch 1, I keep running into this:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

No OpKernel was registered to support Op 'PyFunc' used by node coco_metric/PyFunc (defined at /content/gdrive/My Drive/automl/efficientdet/coco_metric.py:233)  with these attrs: [Tin=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", Tout=[], _xla_inferred_shapes=[]]
Registered devices: [CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[coco_metric/PyFunc]]

Errors may have originated from an input operation.
Input Source operations connected to node coco_metric/PyFunc:
 detnections (defined at /content/gdrive/My Drive/automl/efficientdet/det_model_fn.py:467)	
 concat_3 (defined at /usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:2313)

```

Here is my command that I use to run the training:

`!python main.py --mode=train_and_eval 
--train_file_pattern=GS_PATH_TO_TRAIN_TFRECORDS 
--val_file_pattern=GS_PATH_TO_VAL_TFRECORDS 
-model_dir=GS_PATH_TO_MODEL_DIR 
--hparams=GS_PATH_TO_YAML 
--num_epochs=200 
--train_batch_size=128 
--eval_batch_size=64 
--eval_samples=1024 
--num_examples_per_epoch=56064 
--ckpt=GS_PATH_TO_TRAIN_CKPT 
--strategy=tpu`

Has anyone been able to train on colab TPU? Am I missing something. I did check that `Pycocotools` is installed, still the error.

**Comment by mingxingtan** [comment]
Hi @ameyparanjape   Unfortunately, the default eval doesn't run well on Colab TPU.  You can possibly start two jobs: one for train with TPU, and one for eval with CPU/GPU.  I will chat with TF folks, and hopefully Colab TPU will support eval in future.

**Comment by ameyparanjape** [comment]
Hi @mingxingtan thank you for your response. do you mind throwing some more light on how to start 2 jobs on Colab TPU as you said? I have never worked with TPUs before, so have very limited knowledge, thanks!

**Comment by ameyparanjape** [comment]
I was able to get 2 parallel jobs running, one for train(tpu) and other for eval(gpu). Thanks!

Note - make sure to pass the same --hparams, if using any custom parameters.

**Comment by mloenow** [comment]
@mingxingtan Will this be improved in the near future? I tried patching hparams_config.py for overwriting eval_on_tpu, but it did not make any difference. Not even sure if that's a viable direction at all?

@ameyparanjape How did you manage to get two parallel jobs running?
