### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Ronald-Kray** [google/automl#967]
import numpy as np
      File "C:\Users\ha485\.conda\envs\'Official_EfficientDet'\lib\site-packages\numpy\__init__.py", line 124, in <module>
        from numpy.__config__ import show as show_config
      File "C:\Users\ha485\.conda\envs\'Official_EfficientDet'\lib\site-packages\numpy\__config__.py", line 18
        blas_mkl_info={'libraries': ['mkl_rt'], 'library_dirs': ['C:/Users/ha485/.conda/envs/'Official_EfficientDet'\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'includ
e_dirs': ['C:/Users/ha485/.conda/envs/'Official_EfficientDet'\\Library\\include']}
                                                                                                                  ^
    SyntaxError: invalid syntax
    ----------------------------------------

I can run code an error as invalid syntax.
Is there anyone to help with this?

**Comment by ameyparanjape** [comment]
Did you make sure to install the required packages before getting started? If not, please follow the teadme and install the requirements using `pip install -r requirements.txt`

**Comment by Ronald-Kray** [comment]
after command **pip install -r requirements.txt**
I have got the following errors.



('Official2') C:\Users\ha485\PycharmProjects\pythonProject1\efficientdet>pip install -r requirements.txt
Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI (from -r requirements.txt (line 14))
  Cloning https://github.com/cocodataset/cocoapi.git to c:\users\ha485\appdata\local\temp\pip-req-build-4hddywis
  Running command git clone -q https://github.com/cocodataset/cocoapi.git 'C:\Users\ha485\AppData\Local\Temp\pip-req-build-4hddywis'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ha485\.conda\envs\'"'"'Official2'"'"'\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ha485\\AppData\\Local\\Temp\\pip-req-build-4hddywis\\PythonAPI\
\setup.py'"'"'; __file__='"'"'C:\\Users\\ha485\\AppData\\Local\\Temp\\pip-req-build-4hddywis\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'
"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ha485\AppData\Local\Temp\pip-pip-egg-info-v6_k95h9'
         cwd: C:\Users\ha485\AppData\Local\Temp\pip-req-build-4hddywis\PythonAPI
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ha485\AppData\Local\Temp\pip-req-build-4hddywis\PythonAPI\setup.py", line 2, in <module>
        import numpy as np
      File "C:\Users\ha485\.conda\envs\'Official2'\lib\site-packages\numpy\__init__.py", line 124, in <module>
        from numpy.__config__ import show as show_config
      File "C:\Users\ha485\.conda\envs\'Official2'\lib\site-packages\numpy\__config__.py", line 18
        blas_mkl_info={'libraries': ['mkl_rt'], 'library_dirs': ['C:/Users/ha485/.conda/envs/'Official2'\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['C
:/Users/ha485/.conda/envs/'Official2'\\Library\\include']}
                                                                                                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by juliangrosshauser** [comment]
`pip install -r requirements.txt` only succeeds if you've already installed NumPy. That's why there's this [`install_deps.sh` script](https://github.com/google/automl/blob/master/efficientdet/install_deps.sh) in the repo that installs dependencies from the `requirements.txt` file line by line. That works because the `numpy>=1.19.4` line is above `git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI`.

@Ronald-Kray To install the dependencies I assume you need to do this:

```
pip install numpy
pip install -r requirements.txt
```

If this doesn't work, or you simply want to make your life easier, you can replace `git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI` with `pycocotools` in `requirements.txt`. That's the same dependency, but you don't have to build it yourself. This gets rid of all kinds of problems, like the one you ran into.
