### ISSUE TITLE
Can I get current trianing epoch and estimate trianing time?

### ISSUE THREAD

**Issue by qWildManp** [google/automl#969]

**Comment by qWildManp** [comment]
I'm using EfficientDet on trianing my custom dataset in VOC format. I followed the tutorial to start training,but I cannot visualize current epoch and trianing time estimation on training log. Is there any method can help me to visualize them? and How?
Here is my training command:

 python main.py \
--mode=train_and_eval \
--train_file_pattern=tfrecord/*.tfrecord \
--val_file_pattern=tfrecord/*.tfrecord \
--val_json_file=tfrecord/json_pascal.json \
--model_name=efficientdet-d6 \
--model_dir=tmp/efficientdet-d6  \
--ckpt=efficientdet-d6  \
--train_batch_size=2 \
--eval_batch_size=1 \
--eval_samples=512 \
--num_epochs=100 \
--hparams=./config.yaml

**Comment by mingxingtan** [comment]
You can look into your tensorboard, and it will show the current epoch, such as this one: https://tensorboard.dev/experiment/4IzZoQyAQLSManQfwaHyyQ/#scalars  (search for "train_epochs")
