### ISSUE TITLE
det_post_process is very slow

### ISSUE THREAD

**Issue by monghimng** [google/automl#97]
Thank you for sharing this codebase. I am looking to try this on a real time application. Using `model_inspect.py` and with `runmode=infer`, I was able to run inference and generate great results. However, as I log the runtime, I realized the speed for even the smallest model is quite slow:

feedforward takes around 20ms
post-processing (specifically the function `det_post_process`)takes 200ms

NMS takes the bulk of the time. I further noticed the benchmark mode in model inspect.py is able to reproduce numbers similar to the paper, but it actually ignores the post-processing. Is this an issue of the approach, or is this the implementation of the post processing?

Thanks!

**Comment by KaqiKaqi** [comment]
Hello. I measured the runtime of efficientdet-0 with runmode=infer, feedforward takes around 100ms. Could you please tell me more details about how you log the runtime and what's your gpu and tensorflow version?

Thanks

**Comment by monghimng** [comment]
@KaqiKaqi  See their response in #96 . I used their `model_inspect.py` with `runmode=bm`(benchmark) to log and reproduce their runtime. I used Titan X and TF 1.1.0 Hope this helps.

**Comment by marcosthiago** [comment]
Here i also got around 200ms with Titan Xp using ServingDriver `inference.py`, TF 2.1.0, 4~7fps. 
```
model_name = 'efficientdet-d0'
ckpt_path = 'efficientdet-d0'

def initialize():
    global model_name
    global ckpt_path
    global driver
    tf.reset_default_graph()
    tf.compat.v1.disable_eager_execution()
    driver = inference.ServingDriver(model_name, ckpt_path)
    driver.build()
    print("       EfficientDet loaded!")

def efficientdet_process_image(carmen_image):
    global model_name
    global ckpt_path
    global driver
    
    image = Image.fromarray(carmen_image)
    raw_images = []
    raw_images.append(np.array(image))
    start_time = current_milli_time()
    sess = driver.sess
    detections = sess.run('detections:0', {'image_arrays:0': raw_images})
    print('total_process=', (current_milli_time() - start_time))
    predret = np.array(detections[0][:,1:7], dtype=np.float)
    return predret
```

**Comment by KaqiKaqi** [comment]
> @KaqiKaqi See their response in #96 . I used their `model_inspect.py` with `runmode=bm`(benchmark) to log and reproduce their runtime. I used Titan X and TF 1.1.0 Hope this helps.

Thanks!

**Comment by Jilliansea** [comment]
Hello, @monghimng  I have test the code in [https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb](url), it's totally  inference time is also too big, does there any means to deal with the high time consume of detection post process, for post processing is also one part of detection?

**Comment by varghesealex90** [comment]
Sorry for the noob question. How do I get the time taken for forward pass, post-processing? I tried setting runmode=bm

backbone+fpn+box params/flops = 3.880067M, 35.604035962B
2020-04-07 08:56:37.259050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-07 08:56:38.397691: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Warm up: 0 11.7864s
Warm up: 1 6.0249s
Warm up: 2 0.1730s
Warm up: 3 0.1714s
Warm up: 4 0.1686s
Start benchmark runs total=20

**Comment by KaqiKaqi** [comment]
@varghesealex90 In inference.InferenceDriver.inference() I add some lines to record time:

```
  def inference(self,
                image_path_pattern: Text,
                output_dir: Text,
                **kwargs):
    """Read and preprocess input images.

    Args:
      image_path_pattern: Image file pattern such as /tmp/img*.jpg
      output_dir: the directory for output images. Output images will be named
        as 0.jpg, 1.jpg, ....
      **kwargs: extra parameters for for vistualization, such as
        min_score_thresh, max_boxes_to_draw, and line_thickness.

    Returns:
      Annotated image.
    """
    unique_pattern = os.path.splitext(os.path.basename(image_path_pattern))[0]
    params = copy.deepcopy(self.params)
    with tf.Session() as sess:
      # Buid inputs and preprocessing.
      raw_images, images, scales = build_inputs(
          image_path_pattern, params['image_size'])

      # Build model.
      class_outputs, box_outputs = build_model(
          self.model_name, images, **self.params)
      # for postprocessing.
      params.update(dict(batch_size=len(raw_images), disable_pyfun=False))
      restore_ckpt(sess, self.ckpt_path, enable_ema=True, export_ckpt=None)
      np.save('processed_img_ID', sess.run(images)[0])
      np.save('processed_scale_ID', sess.run(scales)[0])

      for ct in range(20):
        start_time = time.time()
        forward_res = sess.run([class_outputs, box_outputs])
        print("elapse-{}: ".format(ct), time.time() - start_time)

      with open("forward_res_ID.pkl", 'wb') as f:
          pickle.dump(forward_res, f)

      # Build postprocessing.
      with open('params_ID.pkl', 'wb') as f:
        pickle.dump(params, f)
      detections_batch = det_post_process(
          params, class_outputs, box_outputs, scales)

      outputs_np = sess.run(detections_batch)
      np.save("img_pred_res_ID", outputs_np[0])

      # Visualize results.
      for i, output_np in enumerate(outputs_np):
        # output_np has format [image_id, y, x, height, width, score, class]
        boxes = output_np[:, 1:5]
        classes = output_np[:, 6].astype(int)
        scores = output_np[:, 5]

        # This is not needed if disable_pyfun=True
        # convert [x, y, width, height] to [ymin, xmin, ymax, xmax]
        # TODO(tanmingxing): make this convertion more efficient.
        boxes[:, [0, 1, 2, 3]] = boxes[:, [1, 0, 3, 2]]

        boxes[:, 2:4] += boxes[:, 0:2]
        img = visualize_image(raw_images[i], boxes, classes, scores,
                              self.label_id_mapping, **kwargs)
        output_image_path = os.path.join(output_dir, unique_pattern + "_" + str(i) + '.jpg')
        Image.fromarray(img).save(output_image_path)
        logging.info('writing file to %s', output_image_path)

      return outputs_np
```

If you want to record the total time include post-processing , you can calculate the elapse time after `outputs_np = sess.run(detections_batch)`.

**Comment by varghesealex90** [comment]
Is EfficientDet supposed to run faster on TPUs than on GPU. I have NVIDIA-P100, I get fps as 8 FPS. Just the forward pass (POST PROCESSING is not included)
Is this because the support of depthwise convolution is not optimized as on TPUs or CPUs

**Comment by mingxingtan** [comment]
@varghesealex90 
8 FPS is much slower than expected. Which model and what image size are you using?  Do you construct tf graph for every session run?

**Comment by varghesealex90** [comment]
Hello @mingxingtan thanks for point that 8FPS is for 1920. When I change to 512, the FPS is 58.

elapse-0:  4.829689264297485
elapse-1:  0.708155632019043
elapse-2:  0.027691364288330078
elapse-3:  0.028492212295532227
elapse-4:  0.02188706398010254
elapse-5:  0.02613973617553711
elapse-6:  0.025372982025146484
elapse-7:  0.028477907180786133
elapse-8:  0.01793360710144043
elapse-9:  0.024994611740112305
elapse-10:  0.02590656280517578
elapse-11:  0.02544856071472168
elapse-12:  0.0260469913482666
elapse-13:  0.027614593505859375
elapse-14:  0.030781984329223633
elapse-15:  0.026781797409057617
elapse-16:  0.017867088317871094
elapse-17:  0.02035832405090332
elapse-18:  0.028326988220214844

For computing FPS, I just did 1/0.017.

**Comment by mingxingtan** [comment]
Great. About 20ms per image is reasonable.
I have also realized that some images are highly non-square. I will add support to allow non-square images soon.

**Comment by varghesealex90** [comment]
FYI, I just ran inference on the same image through yolov3. The output was generated in 19ms. It would ideal if pre-processing, forward pass and post-processing can be done in the 20 ms

**Comment by mingxingtan** [comment]
Yeah, it definitely needs to be optimized on GPU.  Is Yolo also in TF?  If so, could you help generate the trace file for both Yolo and efficientdet? 

Also, could you try different batch size (e.g. 1, 8) on both GPU and CPU? Thanks!

**Comment by varghesealex90** [comment]
No, I ran the official  implementation of darknet. I have never succeeded in training YOLO based networks on other repos. Ultralytics is one exception.

**Comment by varghesealex90** [comment]
I just modified the inferene.py to check the time taken to complete postprocess for 20 cycles.

ppelapse-0:  2.798837661743164
ppelapse-1:  0.13190007209777832
ppelapse-2:  0.11826610565185547
ppelapse-3:  0.1282057762145996
ppelapse-4:  0.13190031051635742
ppelapse-5:  0.13325095176696777
ppelapse-6:  0.1320052146911621
ppelapse-7:  0.13550591468811035
ppelapse-8:  0.1325514316558838
ppelapse-9:  0.12121200561523438
ppelapse-10:  0.12723398208618164
ppelapse-11:  0.11819028854370117
ppelapse-12:  0.13127446174621582
ppelapse-13:  0.1328573226928711
ppelapse-14:  0.1380608081817627
ppelapse-15:  0.1274576187133789
ppelapse-16:  0.12819337844848633
ppelapse-17:  0.12376713752746582
ppelapse-18:  0.12864255905151367
ppelapse-19:  0.12111902236938477


The forward pass is approx, the fps is close to 59, while the FPS for postprocessing is approx=9.

**Comment by mingxingtan** [comment]
Looks like we really need a fast post-processing for real applications. I will prioritize this.

**Comment by mingxingtan** [comment]
Please check out the latest code, README and tutorial. Now the end-to-end D0 latency is 24ms, which is reasonable. (We will try to further speed it up with tensorRT, but I think it is reasonable now, and I am going to close this issue).
