### ISSUE TITLE
efficientNetV2 release date

### ISSUE THREAD

**Issue by sergiev** [google/automl#972]
Hello, could you please provide us the estimated time to release? I'm currently working on thesis about scene text recognition and looking forward to expand backbones' family with your work.
Thanks in advance!

**Comment by d-li14** [comment]
@sergiev A PyTorch implementation is preliminarily provided here https://github.com/d-li14/efficientnetv2.pytorch

**Comment by amaarora** [comment]
@mingxingtan Is there a tentative date for code release please? :)

**Comment by Avinash279939** [comment]
Hi  @mingxingtan  waiting for the code release please..

**Comment by Roopesh-Bharatwaj-K-R** [comment]
Hi @mingxingtan , yeah awaiting for the code release, when it will be released. Thanks !

**Comment by KelvinYang0320** [comment]
Hello, @mingxingtan I am looking forward to your codes. Thank you!
