### ISSUE TITLE
inspect_tfrecords.py ; NotImplementedError: Cannot convert a symbolic Tensor (parser/strided_slice_16:0) to a numpy array.

### ISSUE THREAD

**Issue by partus** [google/automl#975]
## When Inspecting the dataset

`PYTHONPATH=".:$PYTHONPATH" python dataset/inspect_tfrecords.py \  
  --save_samples_dir ./log \
  --file_pattern ./ds/train-00000-of-00032.tfrecord`
## With Versions
![image](https://user-images.githubusercontent.com/1966996/114686075-7f4b7580-9d23-11eb-870c-a121d1910109.png)
## Results in 

`I0414 13:08:00.631590 140387902510912 dataloader.py:84] target_size = (512, 512), output_size = (512, 512)
E0414 13:08:00.743673 140387902510912 inspect_tfrecords.py:126] in user code:

    /home/user/snap/moda/automl/efficientdet/dataloader.py:442 None  *
        anchor_labeler, params)
    /home/user/snap/moda/automl/efficientdet/dataloader.py:338 dataset_parser  **
        num_positives) = anchor_labeler.label_anchors(boxes, classes)
    /home/user/snap/moda/automl/efficientdet/keras/anchors.py:237 label_anchors
        cls_targets, _, box_targets, _, matches = self._target_assigner.assign(
    /home/user/snap/moda/automl/efficientdet/object_detection/target_assigner.py:144 assign
        groundtruth_weights = tf.ones([num_gt_boxes], dtype=tf.float32)
    /usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py:3120 ones
        output = _constant_if_small(one, shape, dtype, name)
    /usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py:2804 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:5 prod
        
    /usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3030 prod
        return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
    /usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py:87 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /usr/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:852 __array__
        raise NotImplementedError(

    NotImplementedError: Cannot convert a symbolic Tensor (parser/strided_slice_16:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
`

**Comment by kartik4949** [comment]
works fine with numpy version 1.19

**Comment by kartik4949** [comment]
pip install numpy==1.19.5

**Comment by partus** [comment]
The same issue with other scripts , e.g. training.
Works with downgraded versions as mentioned by @kartik4949
