### ISSUE TITLE
Train efficientdet lite models on custom data

### ISSUE THREAD

**Issue by ameyparanjape** [google/automl#978]
What hyperparameters/configs need to be changed to enable training on efficientdet-lite models? Could not find any notes/ docs related to this. Any help would be appreciated!

**Comment by davideCremona** [comment]
Also I'm interested into this

**Comment by mingxingtan** [comment]
All training hyperparamters are written in the python code, so you should just need to change the model_name.
BTW, efficientdet-lite model checkpoints are also listed in README page: https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints

**Comment by mingxingtan** [comment]
For custom data, you may need to play with augmentation (scale_jittering) and LR (lower LR is preferred for finetuning).
