### ISSUE TITLE
Could it produce json format box result?

### ISSUE THREAD

**Issue by b03505036** [google/automl#98]
Could it produce json format box result?
If it can, could anyone give some examples?

**Comment by mingxingtan** [comment]
Are you talking about eval on something like test-dev set? If so, yes, you can run this command line to generate json files:

```
python main.py --mode=eval --model_name=$M  \
    --model_dir=/tmp/efficientdet/$M  \
    --validation_file_pattern=/tfrecord/test-dev-*.tfrecord  \
    --eval_samples=20288    --val_json_file=''"  \
    --testdev_dir=/tmp/test-dev-out/  \
    --hparams="use_bfloat16=false" --use_tpu=False --master='local' --logtostderr
```

**Comment by mingxingtan** [comment]
It would output the json file under testdev_dir

**Comment by cyx6666** [comment]
> Are you talking about eval on something like test-dev set? If so, yes, you can run this command line to generate json files:
> 
> ```
> python main.py --mode=eval --model_name=$M  \
>     --model_dir=/tmp/efficientdet/$M  \
>     --validation_file_pattern=/tfrecord/test-dev-*.tfrecord  \
>     --eval_samples=20288    --val_json_file=''"  \
>     --testdev_dir=/tmp/test-dev-out/  \
>     --hparams="use_bfloat16=false" --use_tpu=False --master='local' --logtostderr
> ```

Hi!
I used this command,but why i stopped at `Waiting for new checkpoint at /tmp/efficientdet/efficientdet-d4`？

**Comment by mingxingtan** [comment]
@cyx6666 you need to download the model checkout and unzip the checkpoint in the corresponding folder. For your case, you need to run:

```
$ cd /tmp/efficientdet/
$ wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/${MODEL}.tar.gz
$ tar zxf ${MODEL}.tar.gz
```
