### ISSUE TITLE
autoaugment : Invalid argument: output dimensions must be positive

### ISSUE THREAD

**Issue by thelinuxmaniac** [google/automl#982]
When the bounding box augmentation is computed, is there a check that discards the augmented bounding box if the bounding box falls beyond the image boundaries? I see the [_INVALID_BOX](https://github.com/google/automl/blob/89d7b375c93edec308220bf0f240d3b336ed6d59/efficientdet/aug/autoaugment.py#L34) property but I am unable to understand what this means?

My dataset contains some bounding boxes that are at the edge of image boundary and I suspect that the augmentation operation may be generating new bounding boxes that fall beyond the image boundary thereby causing the following `Invalid argument: output dimensions must be positive` error after the first step:

```
2021-05-04 18:52:06.617938: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-05-04 18:52:07.249895: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
INFO:tensorflow:loss = 37415.76, step = 0
I0504 19:05:10.706079 140685338785600 basic_session_run_hooks.py:262] loss = 37415.76, step = 0
INFO:tensorflow:box_loss = 0.0090180095, cls_loss = 37415.207, det_loss = 37415.656, step = 0
I0504 19:05:10.708910 140685338785600 basic_session_run_hooks.py:262] box_loss = 0.0090180095, cls_loss = 37415.207, det_loss = 37415.656, step = 0
Traceback (most recent call last):
  File "/data/adutta/dep/efficientdet/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/data/adutta/dep/efficientdet/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/data/adutta/dep/efficientdet/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_10/then/_83/cond/then/_341/cond/else/_639/while/body/_1031/cond/then/_1358/PartitionedCall/translate/transform/ImageProjectiveTransformV3}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_10/then/_83/cond/then/_341/cond/else/_639/while/body/_1031/cond/then/_1358/PartitionedCall/translate/transform/ImageProjectiveTransformV3}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_12185]]
0 successful operations.
0 derived errors ignored.
```

Here are additonal details about by envrionment:
CUDA Version: 11.1
OS: CentOS Linux release 7.9.2009 (Core)
EfficientDet Code Version: f036f3cee588fee9ad93d01e8dc3db901eb95a85
Tensorflow version: 2.4.1
Python version: Python 3.6.8

I would be grateful for any help and pointers to resolve this issue.

**Comment by kartik4949** [comment]
Hi,
Try inspecting your data with edge case via the inspection script that creates augmentations also

**Comment by thelinuxmaniac** [comment]
This is indeed very useful suggestion. I will try this out.
