### ISSUE TITLE
How to mask Segmentation from Image?

### ISSUE THREAD

**Issue by 7eta** [google/automl#983]
Hi. I used Mask-RCNN but too slow drawing segmentation.
so, I hope to change backbone Resnet101(mask rcnn) to EfficientDet
can you help me? or How to draw segmentation from Image.

**Comment by kartik4949** [comment]
Hi, 
1. EfficientNet is the backbone you are looking!
2. You can use mask head with efficientDet itself.
Refer https://github.com/google/automl/blob/2dbfb7984c20c24d856b96b54498799ed1b270cb/efficientdet/keras/segmentation.py
demo!
Thanks
