### ISSUE TITLE
efficientdet-lite pretrained ckpts?

### ISSUE THREAD

**Issue by klappec-bsci** [google/automl#984]
efficientdet-lite 0-4 are supported but I see no ckpt files available for them?

**Comment by mingxingtan** [comment]
checkpoints are added to README

**Comment by ameyparanjape** [comment]
@mingxingtan do you please mind providing the link to where in README these checkpoints are added? I looked through and could not find any, thank you!

**Comment by mingxingtan** [comment]
They are at the end of https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints
