### ISSUE TITLE
Convert coco data to tfrecord. Is this normal?Finished writing, skipped 26715 annotations.

### ISSUE THREAD

**Issue by honghande** [google/automl#99]
I only have 3998 datasets:
2020-03-30 10:38:18.559246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-30 10:38:18.571657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
I0330 10:38:21.221017 139868669736768 create_coco_tfrecord.py:286] writing to output path: tfrecrod_gstrain/train
I0330 10:38:22.631008 139868669736768 create_coco_tfrecord.py:216] Building bounding box index.
I0330 10:38:22.648128 139868669736768 create_coco_tfrecord.py:227] 0 images are missing bboxes.
I0330 10:38:22.884846 139868669736768 create_coco_tfrecord.py:324] On image 0 of 3998
I0330 10:38:24.368228 139868669736768 create_coco_tfrecord.py:324] On image 100 of 3998
I0330 10:38:27.518310 139868669736768 create_coco_tfrecord.py:324] On image 200 of 3998
I0330 10:38:29.349867 139868669736768 create_coco_tfrecord.py:324] On image 300 of 3998
I0330 10:38:30.973467 139868669736768 create_coco_tfrecord.py:324] On image 400 of 3998
I0330 10:38:32.126321 139868669736768 create_coco_tfrecord.py:324] On image 500 of 3998
I0330 10:38:33.460024 139868669736768 create_coco_tfrecord.py:324] On image 600 of 3998
I0330 10:38:35.038667 139868669736768 create_coco_tfrecord.py:324] On image 700 of 3998
I0330 10:38:37.093992 139868669736768 create_coco_tfrecord.py:324] On image 800 of 3998
I0330 10:38:38.265533 139868669736768 create_coco_tfrecord.py:324] On image 900 of 3998
I0330 10:38:40.014778 139868669736768 create_coco_tfrecord.py:324] On image 1000 of 3998
I0330 10:38:42.395982 139868669736768 create_coco_tfrecord.py:324] On image 1100 of 3998
I0330 10:38:43.311361 139868669736768 create_coco_tfrecord.py:324] On image 1200 of 3998
I0330 10:38:43.352942 139868669736768 create_coco_tfrecord.py:324] On image 1300 of 3998
I0330 10:38:44.219722 139868669736768 create_coco_tfrecord.py:324] On image 1400 of 3998
I0330 10:38:45.788143 139868669736768 create_coco_tfrecord.py:324] On image 1500 of 3998
I0330 10:38:47.393148 139868669736768 create_coco_tfrecord.py:324] On image 1600 of 3998
I0330 10:38:48.622148 139868669736768 create_coco_tfrecord.py:324] On image 1700 of 3998
I0330 10:38:49.200231 139868669736768 create_coco_tfrecord.py:324] On image 1800 of 3998
I0330 10:38:49.236066 139868669736768 create_coco_tfrecord.py:324] On image 1900 of 3998
I0330 10:38:49.713481 139868669736768 create_coco_tfrecord.py:324] On image 2000 of 3998
I0330 10:38:50.270777 139868669736768 create_coco_tfrecord.py:324] On image 2100 of 3998
I0330 10:38:51.389310 139868669736768 create_coco_tfrecord.py:324] On image 2200 of 3998
I0330 10:38:52.831865 139868669736768 create_coco_tfrecord.py:324] On image 2300 of 3998
I0330 10:38:53.790164 139868669736768 create_coco_tfrecord.py:324] On image 2400 of 3998
I0330 10:38:55.204479 139868669736768 create_coco_tfrecord.py:324] On image 2500 of 3998
I0330 10:38:55.494044 139868669736768 create_coco_tfrecord.py:324] On image 2600 of 3998
I0330 10:38:55.841624 139868669736768 create_coco_tfrecord.py:324] On image 2700 of 3998
I0330 10:38:56.696906 139868669736768 create_coco_tfrecord.py:324] On image 2800 of 3998
I0330 10:38:58.173091 139868669736768 create_coco_tfrecord.py:324] On image 2900 of 3998
I0330 10:38:59.055014 139868669736768 create_coco_tfrecord.py:324] On image 3000 of 3998
I0330 10:39:00.474417 139868669736768 create_coco_tfrecord.py:324] On image 3100 of 3998
I0330 10:39:01.295021 139868669736768 create_coco_tfrecord.py:324] On image 3200 of 3998
I0330 10:39:01.324279 139868669736768 create_coco_tfrecord.py:324] On image 3300 of 3998
I0330 10:39:01.347605 139868669736768 create_coco_tfrecord.py:324] On image 3400 of 3998
I0330 10:39:02.920136 139868669736768 create_coco_tfrecord.py:324] On image 3500 of 3998
I0330 10:39:03.652120 139868669736768 create_coco_tfrecord.py:324] On image 3600 of 3998
I0330 10:39:05.853588 139868669736768 create_coco_tfrecord.py:324] On image 3700 of 3998
I0330 10:39:06.524794 139868669736768 create_coco_tfrecord.py:324] On image 3800 of 3998
I0330 10:39:07.689178 139868669736768 create_coco_tfrecord.py:324] On image 3900 of 3998
I0330 10:39:10.138620 139868669736768 create_coco_tfrecord.py:336] Finished writing, skipped 26715 annotations.
PYTHONPATH=".:$PYTHONPATH"  python dataset/create_coco_tfrecord.py \
>     --image_dir=/data/internet/AI/dataset/gs/train2017 \
>     --object_annotations_file=/data/internet/AI/dataset/gs/instances_train2017.json \
>     --output_file_prefix=tfrecrod_gstrain/train \
>     --num_shards=32

**Comment by honghande** [comment]
I cleaned up the data, and it's still a problem：
I0331 15:59:52.820962 140481332815680 create_coco_tfrecord.py:216] Building bounding box index.
I0331 15:59:52.826234 140481332815680 create_coco_tfrecord.py:227] 0 images are missing bboxes.
I0331 15:59:52.855790 140481332815680 create_coco_tfrecord.py:324] On image 0 of 3249
I0331 15:59:52.937189 140481332815680 create_coco_tfrecord.py:324] On image 100 of 3249
I0331 15:59:52.994156 140481332815680 create_coco_tfrecord.py:324] On image 200 of 3249
I0331 15:59:53.115836 140481332815680 create_coco_tfrecord.py:324] On image 300 of 3249
I0331 15:59:53.185956 140481332815680 create_coco_tfrecord.py:324] On image 400 of 3249
I0331 15:59:53.283538 140481332815680 create_coco_tfrecord.py:324] On image 500 of 3249
I0331 15:59:53.383302 140481332815680 create_coco_tfrecord.py:324] On image 600 of 3249
I0331 15:59:53.447691 140481332815680 create_coco_tfrecord.py:324] On image 700 of 3249
I0331 15:59:53.502670 140481332815680 create_coco_tfrecord.py:324] On image 800 of 3249
I0331 15:59:53.535154 140481332815680 create_coco_tfrecord.py:324] On image 900 of 3249
I0331 15:59:53.560399 140481332815680 create_coco_tfrecord.py:324] On image 1000 of 3249
I0331 15:59:53.587440 140481332815680 create_coco_tfrecord.py:324] On image 1100 of 3249
I0331 15:59:53.614601 140481332815680 create_coco_tfrecord.py:324] On image 1200 of 3249
I0331 15:59:53.646209 140481332815680 create_coco_tfrecord.py:324] On image 1300 of 3249
I0331 15:59:53.677660 140481332815680 create_coco_tfrecord.py:324] On image 1400 of 3249
I0331 15:59:53.708530 140481332815680 create_coco_tfrecord.py:324] On image 1500 of 3249
I0331 15:59:53.737294 140481332815680 create_coco_tfrecord.py:324] On image 1600 of 3249
I0331 15:59:53.769800 140481332815680 create_coco_tfrecord.py:324] On image 1700 of 3249
I0331 15:59:53.798534 140481332815680 create_coco_tfrecord.py:324] On image 1800 of 3249
I0331 15:59:53.823927 140481332815680 create_coco_tfrecord.py:324] On image 1900 of 3249
I0331 15:59:53.851339 140481332815680 create_coco_tfrecord.py:324] On image 2000 of 3249
I0331 15:59:53.880070 140481332815680 create_coco_tfrecord.py:324] On image 2100 of 3249
I0331 15:59:53.910533 140481332815680 create_coco_tfrecord.py:324] On image 2200 of 3249
I0331 15:59:53.941381 140481332815680 create_coco_tfrecord.py:324] On image 2300 of 3249
I0331 15:59:53.963444 140481332815680 create_coco_tfrecord.py:324] On image 2400 of 3249
I0331 15:59:53.989516 140481332815680 create_coco_tfrecord.py:324] On image 2500 of 3249
I0331 15:59:54.021537 140481332815680 create_coco_tfrecord.py:324] On image 2600 of 3249
I0331 15:59:54.043646 140481332815680 create_coco_tfrecord.py:324] On image 2700 of 3249
I0331 15:59:54.069465 140481332815680 create_coco_tfrecord.py:324] On image 2800 of 3249
I0331 15:59:54.101665 140481332815680 create_coco_tfrecord.py:324] On image 2900 of 3249
I0331 15:59:54.124540 140481332815680 create_coco_tfrecord.py:324] On image 3000 of 3249
I0331 15:59:54.154321 140481332815680 create_coco_tfrecord.py:324] On image 3100 of 3249
I0331 15:59:54.182120 140481332815680 create_coco_tfrecord.py:324] On image 3200 of 3249
I0331 15:59:54.263695 140481332815680 create_coco_tfrecord.py:336] Finished writing, skipped 1 annotations.

**Comment by mingxingtan** [comment]
It means there is one annotation is not valid. You can debug it by adding logs to these lines:

https://github.com/google/automl/blob/b4b74c42667b988c809ea463b842525bab4bba03/efficientdet/dataset/create_coco_tfrecord.py#L145
https://github.com/google/automl/blob/b4b74c42667b988c809ea463b842525bab4bba03/efficientdet/dataset/create_coco_tfrecord.py#L148

**Comment by honghande** [comment]
OK, it's settled, thank you, but I have this situation:
https://github.com/google/automl/issues/68#issuecomment-607003904

**Comment by mingxingtan** [comment]
cool. Let's close this issue, and keep #68.
