### ISSUE TITLE
How to use the checkpoints?

### ISSUE THREAD

**Issue by awsaf49** [google/automl#997]
Can seem to understand how to load the checkpoints as they are neither in **h5** nor **ckpt** format.

**Comment by BishmoyPaul** [comment]
I think you can load them using `checkpoint.restore(tf.train.latest_checkpoint(checkpoint_directory))`, where you make a checkpoint object and load them using this code

**Comment by mingxingtan** [comment]
yes, you can also  take a look at the infer.py

**Comment by awsaf49** [comment]
> 
> 
> yes, you can also take a look at the infer.py

I get this error, `AssertionError: Some objects had attributes which were not restored:` when I try to load weights using **infer.py**

**Comment by ivanlen** [comment]
I get the same error as @awsaf49
