### ISSUE TITLE
Number of Channels in Stage 6 of small

### ISSUE THREAD

**Issue by seermer** [google/automl#999]
Hi, I noticed that in the paper, stage 6 of EfficientNetV2-s has 272 filters(channels), but this implementation uses 256, anyone know why? or am I using/understanding the code incorrectly? Thanks.

![image](https://user-images.githubusercontent.com/49250812/118386379-a7433700-b649-11eb-9e57-c44485a8623b.png)
![image](https://user-images.githubusercontent.com/49250812/118386401-d6f23f00-b649-11eb-8080-5bae6143a71a.png)

**Comment by mingxingtan** [comment]
Hi @seermer , please use the code as the source of truth.  We made a few simple changes to the networks after releasing the paper.  For this case, it is because 256 is more friendly to hardware than 272 (they have the same accuracy).
I will update the paper soon.
